using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Es = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · sin paquete de idioma",
        ["Engine_OneLanguage"] = "Windows OCR · 1 idioma",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} idiomas",
        ["Engine_OnDevice"] = "{0} · en el dispositivo",

        ["Preview_Placeholder"] = "Arrastre una imagen aquí, o use Archivo, Captura o Portapapeles abajo",
        ["Btn_CopyImage"] = "Copiar",
        ["Tip_CopyImage"] = "Copiar la imagen al portapapeles",
        ["Btn_SaveImage"] = "Guardar",
        ["Tip_SaveImage"] = "Guardar la imagen como…",
        ["Btn_FitToWindow"] = "Ajustar",
        ["Tip_FitToWindow"] = "Ajustar el zoom a la ventana",
        ["Tip_ActualSize"] = "Tamaño real en píxeles",
        ["Tip_PdfPrev"] = "Página anterior",
        ["Tip_PdfNext"] = "Página siguiente",
        ["Action_Open"] = "Abrir enlace",
        ["Action_Mail"] = "Escribir a",
        ["Action_Call"] = "Llamar a",
        ["Action_Search"] = "Buscar en la web",

        ["Voice_Placeholder"] = "Voz",
        ["Tip_Voice"] = "Voz usada para la lectura",
        ["Tip_Speak"] = "Leer el texto en voz alta",
        ["Tip_StopSpeak"] = "Detener la lectura",
        ["Tip_CopyText"] = "Copiar el texto (Ctrl+Mayús+C)",
        ["Btn_RemoveLineBreaks"] = "Sin saltos",
        ["Tip_RemoveLineBreaks"] = "Unir los saltos de línea en párrafos",
        ["Btn_RemoveSpaces"] = "Sin espacios",
        ["Tip_RemoveSpaces"] = "Quitar todos los espacios, para chino, japonés y coreano",
        ["Result_Placeholder"] = "El texto reconocido aparece aquí y se puede editar.",

        ["Btn_OpenFile"] = "Archivo",
        ["Tip_OpenFile"] = "Abrir un archivo de imagen (Ctrl+O)",
        ["Btn_Capture"] = "Captura",
        ["Tip_Capture"] = "Seleccionar una zona de la pantalla y reconocerla ({0}). Ctrl+Mayús+R para toda la pantalla.",
        ["Hotkey_Unavailable"] = "sin atajo: otra aplicación ocupa los dos",
        ["Btn_Paste"] = "Portapapeles",
        ["Tip_Paste"] = "Cargar una imagen o texto del portapapeles (Ctrl+V)",
        ["Btn_History"] = "Historial",
        ["Tip_History"] = "Resultados recientes",
        ["History_Empty"] = "Todavía no se ha reconocido nada.",
        ["History_EmptyPreview"] = "(vacío)",
        ["Tip_Settings"] = "Opciones",
        ["Settings_Header"] = "Opciones",
        ["Setting_UiLanguage"] = "Idioma de la aplicación",
        ["Lang_SystemDefault"] = "Idioma del sistema",
        ["Setting_RepairNumbers"] = "Corregir l e I dentro de los números",
        ["Setting_RepairNumbers_Desc"] = "Los motores leen v1.6.5 como vl.6.5 con frecuencia. Activado, una l o una I solo se convierte en 1 donde hay un separador y un dígito a su lado, de modo que html5 e IPv6 quedan intactos. Desactivado, se conserva exactamente la lectura del motor.",
        ["Setting_WatchClipboard"] = "Leer las imágenes que copio",
        ["Setting_WatchClipboard_Desc"] = "Haz una captura con Win+Shift+S y Glyfo la lee al momento y deja el texto en el portapapeles en lugar de la imagen, así el siguiente pegado es el texto. Solo se leen imágenes, nunca el texto copiado, y no se envía nada a ninguna parte: todo ocurre en este dispositivo.",
        ["Common_On"] = "Activado",
        ["Common_Off"] = "Desactivado",
        ["Lang_Placeholder"] = "Idioma",
        ["Tip_OcrLanguage"] = "Idioma de reconocimiento, según los paquetes de idioma instalados en Windows",
        ["Btn_Translate"] = "Traducir",
        ["Tip_Translate"] = "Traducir en este dispositivo: no se envía nada por la red",
        ["Btn_Barcode"] = "Códigos",
        ["Tip_Barcode"] = "Leer los códigos QR y de barras de la imagen",
        ["Btn_Recognize"] = "Reconocer",
        ["Tip_Recognize"] = "Reconocer el texto de la imagen (F5)",

        ["Option_AutoAi"] = "Automático (Windows AI)",
        ["Option_AutoMulti"] = "Automático (multilingüe · más lento)",

        ["Status_Loaded"] = "Se cargó {0}.",
        ["Status_OpenFailed"] = "No se pudo abrir la imagen: {0}",
        ["Status_ClipboardText"] = "Se cargó texto del portapapeles.",
        ["Status_ClipboardEmpty"] = "El portapapeles no contiene ninguna imagen ni texto.",
        ["Status_ClipboardFailed"] = "No se pudo leer el portapapeles: {0}",
        ["Status_DropFailed"] = "No se pudo usar lo que se arrastró: {0}",
        ["Status_ImageCopied"] = "Imagen copiada al portapapeles.",
        ["Status_ImageCopyFailed"] = "No se pudo copiar la imagen: {0}",
        ["Status_ImageSaved"] = "Imagen guardada como {0}.",
        ["Status_ImageSaveFailed"] = "No se pudo guardar la imagen: {0}",
        ["Status_Recognizing"] = "Reconociendo…",
        ["Status_NoText"] = "{0} no encontró texto en esta imagen.",
        ["Status_Done"] = "Listo ({0}).",
        ["Status_DoneConfidence"] = "Listo ({0}) · confianza media {1} %.",
        ["Status_RecognizeFailed"] = "El reconocimiento falló: {0}",
        ["Status_Scanning"] = "Buscando códigos QR y de barras…",
        ["Status_NoBarcode"] = "No hay ningún código QR ni de barras en esta imagen.",
        ["Status_BarcodeOne"] = "Se encontró un código {0}.",
        ["Status_BarcodeMany"] = "Se encontraron {0} códigos.",
        ["Status_ScanFailed"] = "La búsqueda falló: {0}",
        ["Status_PdfFailed"] = "no se pudo leer este PDF: puede estar protegido con contraseña o dañado",
        ["Status_LaunchFailed"] = "Windows no encontró con qué abrir eso.",
        ["Status_NothingToTranslate"] = "No hay texto que traducir.",
        ["Status_Translating"] = "Traduciendo al {0} en este dispositivo…",
        ["Status_Translated"] = "Traducido al {0}, en este dispositivo y sin acceso a la red.",
        ["Status_TranslateFailed"] = "La traducción falló: {0}",
        ["Status_NothingToCopy"] = "No hay texto que copiar.",
        ["Status_TextCopied"] = "Texto copiado al portapapeles.",
        ["Status_CopyFailed"] = "No se pudo copiar el texto: {0}",
        ["Status_NothingToSpeak"] = "No hay texto que leer.",
        ["Status_SpeakFailed"] = "No se pudo leer el texto: {0}",
        ["Status_HistoryLoaded"] = "Mostrando el resultado de {0}.",
        ["Status_NeedImage"] = "Cargue primero una imagen.",
        ["Status_CaptureFailed"] = "La captura de pantalla falló: {0}",
        ["Status_StartupBlockedByUser"] = "Windows tiene desactivado el inicio automático de Glyfo. Vuelva a activarlo en el Administrador de tareas, en Aplicaciones de inicio.",
        ["Status_StartupBlockedByPolicy"] = "Su organización no permite que las aplicaciones se inicien con Windows.",
        ["Status_LanguagePackMissing"] = "Windows no tiene ningún paquete de idioma OCR instalado, así que no hay con qué reconocer. Agregue el idioma que necesite en Hora e idioma y luego Idioma y región.",
        ["Btn_OpenLanguageSettings"] = "Abrir la configuración de idioma",

        ["Tray_Open"] = "Abrir Glyfo",
        ["Tray_CaptureRegion"] = "Capturar una zona",
        ["Tray_CaptureFullScreen"] = "Capturar toda la pantalla",
        ["Tray_Exit"] = "Salir",
        ["Tray_Tooltip"] = "Glyfo: pulsa {0} para capturar una zona",
        ["Toast_StartupTitle"] = "Glyfo está en marcha",
        ["Toast_StartupBody"] = "Pulsa {0} para seleccionar una zona de la pantalla y leer el texto que contiene. Ctrl+Mayús+R captura toda la pantalla.",
        ["Toast_DontRemind"] = "No volver a avisar",
        ["Toast_MinimizedTitle"] = "Glyfo sigue en marcha",
        ["Toast_MinimizedBody"] = "Pulsa {0} cuando quieras para capturar y reconocer. Para cerrarlo del todo, haz clic con el botón derecho en su icono del área de notificación y elige Salir.",
        ["Toast_ExitApp"] = "Salir de Glyfo",
        ["Toast_ResultTitle"] = "Texto reconocido",
        ["Toast_ResultCopied"] = "Copiado al portapapeles.",
        ["Toast_OpenWindow"] = "Abrir la ventana",
        ["Toast_NoTextTitle"] = "No se encontró texto",
        ["Toast_NoTextBody"] = "En esa zona no había nada legible como texto.",
        ["Toast_FailedTitle"] = "El reconocimiento falló",
        ["Toast_HotkeyUnavailableTitle"] = "El atajo de captura está ocupado",
        ["Toast_HotkeyUnavailableBody"] = "Otra aplicación ya lo tiene, así que la captura de pantalla solo está disponible desde la ventana y desde el icono del área de notificación.",
        ["Setting_CloseToTray"] = "Seguir en marcha al cerrar la ventana",
        ["Setting_CloseToTray_Desc"] = "Cuando está activado, cerrar la ventana deja Glyfo en marcha para que el atajo de captura siga funcionando, y su icono permanece en el área de notificación, donde Salir lo cierra del todo. Cuando está desactivado, cerrar la ventana termina la aplicación.",
        ["Setting_Startup"] = "Iniciar con Windows",
        ["Setting_Startup_Desc"] = "Cuando esta opción está activada, Glyfo se inicia con Windows y pasa directamente al área de notificación sin abrir ninguna ventana, de modo que el atajo de captura funciona desde que inicia sesión.",

        ["Source_Clipboard"] = "la imagen del portapapeles",
        ["Source_Dropped"] = "la imagen arrastrada",
        ["Source_Shared"] = "la imagen compartida",
        ["Source_FullScreen"] = "Pantalla completa",
        ["Source_Region"] = "Zona de la pantalla",
        ["Source_Codes"] = "{0} (códigos)",

        ["FileType_Image"] = "Imagen {0}",

        ["Region_Hint"] = "Arrastre para seleccionar una zona　·　Esc o clic derecho para cancelar",

        ["Err_NoLanguagePack"] = "Windows no tiene instalado el paquete de idioma OCR para este idioma. Agregue uno en Hora e idioma y luego Idioma y región.",
        ["Err_TextTooLong"] = "El texto es demasiado largo para el modelo local. Traduzca un fragmento más corto.",
        ["Err_ModelDeclined"] = "El modelo local se negó a traducir este texto.",
        ["Err_TranslationFailed"] = "La traducción local no devolvió ningún resultado.",
        ["Btn_About"] = "Acerca de Glyfo",
        ["About_Title"] = "Acerca de Glyfo",
        ["About_Version"] = "Versión {0}",
        ["About_Tagline"] = "Lee el texto de cualquier imagen, en este dispositivo. No se envía nada por la red.",
        ["About_Rate"] = "Valorar Glyfo",
        ["About_WhatsNew"] = "Novedades",
        ["About_Source"] = "Código fuente en GitHub",
        ["About_Privacy"] = "Directiva de privacidad",
        ["Common_Close"] = "Cerrar",
        ["News_Title"] = "Novedades",
        ["News_120_1"] = "Haz una captura con Win+Shift+S y Glyfo la lee por ti y deja el texto en el portapapeles. Está desactivado hasta que lo actives en Opciones.",
        ["News_120_2"] = "Los PDF se abren como las imágenes, página a página.",
        ["News_120_3"] = "Los enlaces, correos y teléfonos que aparecen en el texto reciben un botón debajo.",
        ["News_110_1"] = "Una página «Acerca de» con la versión y enlaces al código fuente y a la directiva de privacidad.",
        ["News_110_2"] = "Puedes valorar Glyfo sin salir de la ventana.",
        ["News_110_3"] = "Estas notas, que aparecen una vez con cada versión nueva.",
        ["News_110_4"] = "La captura ahora también ofrece la pantalla completa y oculta la ventana antes, así Glyfo nunca sale en la imagen.",
        ["Rate_Title"] = "¿Te está sirviendo Glyfo?",
        ["Rate_Body"] = "Una valoración en la Store es lo que permite que otros lo encuentren. Solo lleva un momento.",
        ["Rate_Action"] = "Valorar",
        ["Rate_Later"] = "Ahora no",
    };
}
