using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Fi = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windowsin tekstintunnistus · ei kielipakettia",
        ["Engine_OneLanguage"] = "Windowsin tekstintunnistus · 1 kieli",
        ["Engine_ManyLanguages"] = "Windowsin tekstintunnistus · {0} kieltä",
        ["Engine_OnDevice"] = "{0} · laitteessa",

        ["Preview_Placeholder"] = "Pudota kuva tähän tai käytä alla olevia painikkeita Tiedosto, Kaappaus tai Leikepöytä",
        ["Btn_CopyImage"] = "Kopioi",
        ["Tip_CopyImage"] = "Kopioi kuva leikepöydälle",
        ["Btn_SaveImage"] = "Tallenna",
        ["Tip_SaveImage"] = "Tallenna kuva nimellä…",
        ["Btn_FitToWindow"] = "Sovita",
        ["Tip_FitToWindow"] = "Sovita zoomaus ikkunaan",
        ["Tip_ActualSize"] = "Todellinen pikselikoko",
        ["Tip_PdfPrev"] = "Edellinen sivu",
        ["Tip_PdfNext"] = "Seuraava sivu",
        ["Tip_PdfAll"] = "Lue kaikki sivut",
        ["Action_Open"] = "Avaa linkki",
        ["Action_Mail"] = "Kirjoita osoitteeseen",
        ["Action_Call"] = "Soita numeroon",
        ["Action_Search"] = "Hae verkosta",

        ["Voice_Placeholder"] = "Ääni",
        ["Tip_Voice"] = "Ääneen lukemiseen käytettävä ääni",
        ["Tip_Speak"] = "Lue teksti ääneen",
        ["Tip_StopSpeak"] = "Lopeta lukeminen",
        ["Tip_CopyText"] = "Kopioi teksti (Ctrl+Vaihto+C)",
        ["Tip_SaveText"] = "Tallenna teksti tiedostoon (Ctrl+S)",
        ["Btn_RemoveLineBreaks"] = "Yhdistä rivit",
        ["Tip_RemoveLineBreaks"] = "Yhdistä kovat rivinvaihdot takaisin kappaleiksi",
        ["Btn_RemoveSpaces"] = "Ei välilyöntejä",
        ["Tip_RemoveSpaces"] = "Poista kaikki välilyönnit — kiinaa, japania ja koreaa varten",
        ["Result_Placeholder"] = "Tunnistettu teksti näkyy tässä, ja sitä voi muokata.",

        ["Btn_OpenFile"] = "Tiedosto",
        ["Tip_OpenFile"] = "Avaa kuvatiedosto (Ctrl+O)",
        ["Btn_Capture"] = "Kaappaus",
        ["Tip_Capture"] = "Valitse näytöltä alue ja tunnista se ({0}). Koko näyttö: Ctrl+Vaihto+R.",
        ["Hotkey_Unavailable"] = "ei pikanäppäintä — toinen sovellus on varannut molemmat",
        ["Btn_Paste"] = "Leikepöytä",
        ["Tip_Paste"] = "Lataa kuva tai teksti leikepöydältä (Ctrl+V)",
        ["Btn_History"] = "Historia",
        ["Tip_History"] = "Viimeisimmät tulokset",
        ["History_Empty"] = "Mitään ei ole vielä tunnistettu.",
        ["History_EmptyPreview"] = "(tyhjä)",
        ["History_SearchPlaceholder"] = "Hae tuloksista",
        ["History_NoMatch"] = "Mikään tulos ei vastaa hakua.",
        ["History_Off"] = "Historia on poistettu käytöstä asetuksissa.",
        ["History_Clear"] = "Tyhjennä historia",
        ["History_CopyItem"] = "Kopioi tämä teksti",
        ["History_DeleteItem"] = "Poista tämä merkintä",
        ["Tip_Settings"] = "Asetukset",
        ["Settings_Header"] = "Asetukset",
        ["Setting_UiLanguage"] = "Sovelluksen kieli",
        ["Lang_SystemDefault"] = "Järjestelmän oletus",
        ["Setting_RepairNumbers"] = "Korjaa l ja I lukujen sisällä",
        ["Setting_RepairNumbers_Desc"] = "Tunnistimet lukevat säännöllisesti merkkijonon v1.6.5 muodossa vl.6.5. Kun tämä on käytössä, l tai I muuttuu ykköseksi vain siellä, missä vieressä on erotin ja numero, joten html5 ja IPv6 jäävät rauhaan. Kun tämä ei ole käytössä, moottorin lukema säilyy täsmälleen sellaisena kuin se tuli.",
        ["Setting_WatchClipboard"] = "Lue kopioimani kuvat",
        ["Setting_WatchClipboard_Desc"] = "Ota kuvakaappaus näppäimillä Win+Shift+S, niin Glyfo lukee sen heti ja panee tekstin leikepöydälle kuvan tilalle, joten seuraava liittäminen tuottaa tekstin. Vain kuvia luetaan, ei koskaan kopioitua tekstiä, eikä mitään lähetetä minnekään — kaikki tapahtuu tässä laitteessa.",
        ["Setting_KeepHistory"] = "Säilytä historia istuntojen välillä",
        ["Setting_KeepHistory_Desc"] = "Säilyttää 200 viimeisintä tulosta, joten ne ovat tallella uudelleenkäynnistyksen jälkeenkin. Vain teksti tallennetaan, ei koskaan kuvia, tiedostoon joka kuuluu Glyfolle tällä laitteella. Tämän poistaminen käytöstä poistaa tiedoston ja tyhjentää luettelon heti.",
        ["Common_On"] = "Käytössä",
        ["Common_Off"] = "Ei käytössä",
        ["Lang_Placeholder"] = "Kieli",
        ["Tip_OcrLanguage"] = "Tunnistuskieli Windowsiin asennetuista kielipaketeista",
        ["Btn_Translate"] = "Käännä",
        ["Tip_Translate"] = "Käännä tässä laitteessa — mitään ei lähetetä verkon yli",
        ["Btn_Barcode"] = "Koodit",
        ["Tip_Barcode"] = "Lue kuvan QR-koodit ja viivakoodit",
        ["Btn_Recognize"] = "Tunnista",
        ["Tip_Recognize"] = "Tunnista kuvan teksti (F5)",

        ["Option_AutoAi"] = "Automaattinen (Windows AI)",
        ["Option_AutoMulti"] = "Automaattinen (monikielinen · hitaampi)",

        ["Status_Loaded"] = "{0} ladattu.",
        ["Status_OpenFailed"] = "Kuvaa ei voitu avata: {0}",
        ["Status_ClipboardText"] = "Teksti ladattu leikepöydältä.",
        ["Status_ClipboardEmpty"] = "Leikepöydällä ei ole kuvaa eikä tekstiä.",
        ["Status_ClipboardFailed"] = "Leikepöytää ei voitu lukea: {0}",
        ["Status_DropFailed"] = "Pudotettua kohdetta ei voitu käyttää: {0}",
        ["Status_ImageCopied"] = "Kuva kopioitu leikepöydälle.",
        ["Status_ImageCopyFailed"] = "Kuvaa ei voitu kopioida: {0}",
        ["Status_ImageSaved"] = "Kuva tallennettu nimellä {0}.",
        ["Status_ImageSaveFailed"] = "Kuvaa ei voitu tallentaa: {0}",
        ["Status_Recognizing"] = "Tunnistetaan…",
        ["Status_NoText"] = "{0} ei löytänyt tästä kuvasta tekstiä.",
        ["Status_Done"] = "Valmis ({0}).",
        ["Status_DoneConfidence"] = "Valmis ({0}) · keskimääräinen varmuus {1} %.",
        ["Status_RecognizeFailed"] = "Tunnistus epäonnistui: {0}",
        ["Status_Scanning"] = "Etsitään QR-koodeja ja viivakoodeja…",
        ["Status_NoBarcode"] = "Tästä kuvasta ei löytynyt QR-koodia eikä viivakoodia.",
        ["Status_BarcodeOne"] = "Löytyi yksi {0}-koodi.",
        ["Status_BarcodeMany"] = "Löytyi {0} koodia.",
        ["Status_ScanFailed"] = "Haku epäonnistui: {0}",
        ["Status_PdfFailed"] = "tätä PDF-tiedostoa ei voitu lukea — se voi olla salasanasuojattu tai vioittunut",
        ["Status_LaunchFailed"] = "Windows ei löytänyt mitään, jolla sen voisi avata.",
        ["Status_NothingToTranslate"] = "Käännettävää tekstiä ei ole.",
        ["Status_Translating"] = "Käännetään kielelle {0} tässä laitteessa…",
        ["Status_Translated"] = "Käännetty kielelle {0} — tässä laitteessa, ilman verkkoyhteyttä.",
        ["Status_TranslateFailed"] = "Käännös epäonnistui: {0}",
        ["Status_NothingToCopy"] = "Kopioitavaa tekstiä ei ole.",
        ["Status_NothingToSave"] = "Tallennettavaa tekstiä ei ole.",
        ["Status_TextSaved"] = "Teksti tallennettiin nimellä {0}.",
        ["Status_TextSaveFailed"] = "Tekstiä ei voitu tallentaa: {0}",
        ["Status_TextCopied"] = "Teksti kopioitu leikepöydälle.",
        ["Status_CopyFailed"] = "Tekstiä ei voitu kopioida: {0}",
        ["Status_NothingToSpeak"] = "Ääneen luettavaa tekstiä ei ole.",
        ["Status_SpeakFailed"] = "Tekstiä ei voitu lukea ääneen: {0}",
        ["Status_HistoryLoaded"] = "Näytetään tulos ajalta {0}.",
        ["Status_HistoryCleared"] = "Historia tyhjennetty.",
        ["Status_NeedImage"] = "Lataa ensin kuva.",
        ["Status_CaptureFailed"] = "Näytön kaappaus epäonnistui: {0}",
        ["Status_StartupBlockedByUser"] = "Windows on poistanut Glyfo:n automaattisen käynnistyksen käytöstä. Ota se takaisin käyttöön Tehtävienhallinnan Käynnistyssovellukset-välilehdellä.",
        ["Status_StartupBlockedByPolicy"] = "Organisaatiosi ei salli sovellusten käynnistyä Windowsin mukana.",
        ["Status_LanguagePackMissing"] = "Windowsiin ei ole asennettu yhtään tekstintunnistuksen kielipakettia, joten tunnistukseen ei ole mitään välinettä. Lisää tarvitsemasi kieli kohdasta Aika ja kieli ja sitten Kieli ja alue.",
        ["Btn_OpenLanguageSettings"] = "Avaa kieliasetukset",

        ["Tray_Open"] = "Avaa Glyfo",
        ["Tray_CaptureRegion"] = "Kaappaa alue",
        ["Tray_CaptureFullScreen"] = "Kaappaa koko näyttö",
        ["Tray_Exit"] = "Lopeta",
        ["Tray_Tooltip"] = "Glyfo — kaappaa alue painamalla {0}",
        ["Toast_StartupTitle"] = "Glyfo on käynnissä",
        ["Toast_StartupBody"] = "Valitse näytöltä alue ja lue sen teksti painamalla {0}. Koko näyttö: Ctrl+Vaihto+R.",
        ["Toast_DontRemind"] = "Älä muistuta enää",
        ["Toast_MinimizedTitle"] = "Glyfo on yhä käynnissä",
        ["Toast_MinimizedBody"] = "Voit kaapata ja tunnistaa milloin tahansa painamalla {0}. Sulje ohjelma kokonaan napsauttamalla sen kuvaketta ilmaisinalueella hiiren kakkospainikkeella ja valitsemalla Lopeta.",
        ["Toast_ExitApp"] = "Lopeta Glyfo",
        ["Toast_ResultTitle"] = "Teksti tunnistettu",
        ["Toast_ResultCopied"] = "Kopioitu leikepöydälle.",
        ["Toast_OpenWindow"] = "Avaa ikkuna",
        ["Toast_NoTextTitle"] = "Tekstiä ei löytynyt",
        ["Toast_NoTextBody"] = "Alueelta ei löytynyt mitään tekstinä luettavaa.",
        ["Toast_FailedTitle"] = "Tunnistus epäonnistui",
        ["Toast_HotkeyUnavailableTitle"] = "Pikanäppäin on varattu",
        ["Toast_HotkeyUnavailableBody"] = "Toinen sovellus on jo varannut sen, joten näytön kaappaus onnistuu vain ikkunasta ja ilmaisinalueen kuvakkeesta.",
        ["Setting_CloseToTray"] = "Jatka taustalla, kun ikkuna suljetaan",
        ["Setting_CloseToTray_Desc"] = "Kun tämä on käytössä, Glyfo jää käyntiin ikkunan sulkemisen jälkeen, jolloin pikanäppäin toimii yhä, ja kuvake jää ilmaisinalueelle, jossa Lopeta sulkee ohjelman kokonaan. Kun asetus ei ole käytössä, ikkunan sulkeminen lopettaa sovelluksen.",
        ["Setting_Startup"] = "Käynnistä Windowsin mukana",
        ["Setting_Startup_Desc"] = "Kun tämä on käytössä, Glyfo käynnistyy Windowsin mukana ja siirtyy suoraan ilmoitusalueelle avaamatta ikkunaa, joten kaappauksen pikanäppäin toimii heti kirjautumisesta lähtien.",

        ["Source_Clipboard"] = "leikepöydän kuva",
        ["Source_Dropped"] = "pudotettu kuva",
        ["Source_Shared"] = "jaettu kuva",
        ["Source_FullScreen"] = "Koko näyttö",
        ["Source_Region"] = "Näytön alue",
        ["Source_Codes"] = "{0} (koodit)",
        ["Source_Batch"] = "{0} tiedostoa",
        ["Source_PdfAll"] = "{0}, kaikki sivut",

        ["FileType_Image"] = "{0}-kuva",
        ["FileType_Text"] = "Pelkkä teksti",
        ["FileType_Markdown"] = "Markdown",
        ["Batch_Title"] = "Luetaan useita tiedostoja",
        ["Batch_Progress"] = "{0} / {1}",
        ["Batch_DoneAll"] = "Luettu {0}.",
        ["Batch_Cancelled"] = "Pysäytetty kohdassa {0} / {1}.",
        ["Batch_ItemFailed"] = "Ei voitu lukea: {0}",
        ["Batch_ItemEmpty"] = "(ei tekstiä)",
        ["Batch_Save"] = "Tallenna…",
        ["Batch_CopyAll"] = "Kopioi kaikki",
        ["Batch_Separate"] = "Tallenna jokainen kohde omaksi tiedostokseen",
        ["Batch_SavedFolder"] = "Tallennettiin {0} tiedostoa kansioon {1}.",
        ["Batch_TooLongForBox"] = "Luettiin {0} kohdetta. Teksti on liian pitkä näytettäväksi tässä — se on tallentamassasi tiedostossa.",

        ["Region_Hint"] = "Valitse alue vetämällä　·　Esc tai hiiren oikea painike peruuttaa",

        ["Err_NoLanguagePack"] = "Windowsiin ei ole asennettu tämän kielen tekstintunnistuksen kielipakettia. Lisää sellainen kohdasta Aika ja kieli ja sitten Kieli ja alue.",
        ["Err_TextTooLong"] = "Teksti on liian pitkä laitteessa toimivalle mallille. Käännä pienempi osa.",
        ["Err_ModelDeclined"] = "Laitteessa toimiva malli kieltäytyi kääntämästä tätä tekstiä.",
        ["Err_TranslationFailed"] = "Laitteessa tehty käännös ei tuottanut tulosta.",
        ["Btn_About"] = "Tietoja Glyfosta",
        ["About_Title"] = "Tietoja Glyfosta",
        ["About_Version"] = "Versio {0}",
        ["About_Tagline"] = "Lukee tekstin mistä tahansa kuvasta, tällä laitteella. Mitään ei lähetetä verkkoon.",
        ["About_Rate"] = "Arvioi Glyfo",
        ["About_WhatsNew"] = "Uutta",
        ["About_Source"] = "Lähdekoodi GitHubissa",
        ["About_Privacy"] = "Tietosuojakäytäntö",
        ["Common_Close"] = "Sulje",
        ["Common_Cancel"] = "Peruuta",
        ["News_Title"] = "Uutta",
        ["News_130_1"] = "Historia säilyy nyt uudelleenkäynnistyksen yli, ja sille on hakukenttä. Vain teksti säilytetään — asetuksista sen voi tyhjentää tai poistaa käytöstä.",
        ["News_130_2"] = "Ctrl+S tallentaa tunnistetun tekstin pelkkänä tekstinä tai Markdown-tiedostona.",
        ["News_130_3"] = "Avaa tai pudota useita tiedostoja kerralla tai lue koko PDF, ja tallenna kaikki yhteen tiedostoon tai yksi kohde per tiedosto.",
        ["News_120_1"] = "Ota kuvakaappaus näppäimillä Win+Shift+S, niin Glyfo lukee sen puolestasi ja jättää tekstin leikepöydälle. Pois päältä, kunnes otat sen käyttöön asetuksista.",
        ["News_120_2"] = "PDF-tiedostot avautuvat nyt kuvien tavoin, sivu kerrallaan.",
        ["News_120_3"] = "Tekstistä löytyvät linkit, sähköpostiosoitteet ja puhelinnumerot saavat painikkeen sen alle.",
        ["News_110_1"] = "Tietoja-sivu, jossa näkyy versio sekä linkit lähdekoodiin ja tietosuojakäytäntöön.",
        ["News_110_2"] = "Voit arvioida Glyfon poistumatta ikkunasta.",
        ["News_110_3"] = "Nämä tiedot, jotka näytetään kerran jokaisen uuden version yhteydessä.",
        ["News_110_4"] = "Kaappaus tarjoaa nyt myös koko näytön ja piilottaa ikkunan ensin, joten Glyfo ei enää jää kuvaan.",
        ["Rate_Title"] = "Onko Glyfosta ollut hyötyä?",
        ["Rate_Body"] = "Storen arvio on se, jonka avulla muut löytävät sovelluksen. Siihen menee hetki.",
        ["Rate_Action"] = "Arvioi",
        ["Rate_Later"] = "Ei nyt",
    };
}
