using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Fa = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "‏OCR ویندوز · بدون بستهٔ زبان",
        ["Engine_OneLanguage"] = "‏OCR ویندوز · ۱ زبان",
        ["Engine_ManyLanguages"] = "‏OCR ویندوز · {0} زبان",
        ["Engine_OnDevice"] = "{0} · روی دستگاه",

        ["Preview_Placeholder"] = "تصویری را اینجا رها کنید، یا از پرونده، تصویربرداری از صفحه یا کلیپ‌بورد در پایین استفاده کنید",
        ["Btn_CopyImage"] = "رونوشت",
        ["Tip_CopyImage"] = "رونوشت تصویر در کلیپ‌بورد",
        ["Btn_SaveImage"] = "ذخیره",
        ["Tip_SaveImage"] = "ذخیرهٔ تصویر با نام…",
        ["Btn_FitToWindow"] = "اندازهٔ پنجره",
        ["Tip_FitToWindow"] = "بزرگ‌نمایی به‌اندازه‌ای که در پنجره جا شود",
        ["Tip_ActualSize"] = "اندازهٔ واقعی به پیکسل",

        ["Voice_Placeholder"] = "صدا",
        ["Tip_Voice"] = "صدایی که برای خواندن به کار می‌رود",
        ["Tip_Speak"] = "متن را بلند بخوان",
        ["Tip_StopSpeak"] = "توقف خواندن",
        ["Tip_CopyText"] = "رونوشت متن (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "پیوند سطرها",
        ["Tip_RemoveLineBreaks"] = "پیوند دوبارهٔ شکست سطرها به شکل بند",
        ["Btn_RemoveSpaces"] = "بدون فاصله",
        ["Tip_RemoveSpaces"] = "حذف همهٔ فاصله‌ها — برای چینی، ژاپنی و کره‌ای",
        ["Result_Placeholder"] = "متن بازشناخته‌شده اینجا نمایان می‌شود و می‌توان آن را ویرایش کرد.",

        ["Btn_OpenFile"] = "پرونده",
        ["Tip_OpenFile"] = "گشودن یک پروندهٔ تصویری (Ctrl+O)",
        ["Btn_Capture"] = "تصویربرداری",
        ["Tip_Capture"] = "بخشی از صفحه را برگزینید و آن را بازشناسید ({0}). برای تمام صفحه Ctrl+Shift+R را بزنید.",
        ["Hotkey_Unavailable"] = "میان‌بری در دسترس نیست — برنامهٔ دیگری هر دو را گرفته است",
        ["Btn_Paste"] = "کلیپ‌بورد",
        ["Tip_Paste"] = "گرفتن تصویر یا متن از کلیپ‌بورد (Ctrl+V)",
        ["Btn_History"] = "تاریخچه",
        ["Tip_History"] = "نتیجه‌های اخیر",
        ["History_Empty"] = "هنوز چیزی بازشناسی نشده است.",
        ["History_EmptyPreview"] = "(خالی)",
        ["Tip_Settings"] = "گزینه‌ها",
        ["Settings_Header"] = "گزینه‌ها",
        ["Setting_UiLanguage"] = "زبان برنامه",
        ["Lang_SystemDefault"] = "پیش‌فرض سیستم",
        ["Setting_RepairNumbers"] = "اصلاح l و I درون عددها",
        ["Setting_RepairNumbers_Desc"] = "موتورهای بازشناسی بارها v1.6.5 را vl.6.5 می‌خوانند. با روشن بودن این گزینه، حرف l یا I تنها جایی به ۱ بدل می‌شود که در کنارش جداکننده و رقم باشد، پس html5 و IPv6 دست‌نخورده می‌مانند. با خاموش بودنش، خوانش موتور دقیقاً همان‌گونه که آمده نگه داشته می‌شود.",
        ["Common_On"] = "روشن",
        ["Common_Off"] = "خاموش",
        ["Lang_Placeholder"] = "زبان",
        ["Tip_OcrLanguage"] = "زبان بازشناسی، از میان بسته‌های زبانی نصب‌شده در ویندوز",
        ["Btn_Translate"] = "ترجمه",
        ["Tip_Translate"] = "ترجمه روی همین دستگاه — چیزی از شبکه فرستاده نمی‌شود",
        ["Btn_Barcode"] = "کدها",
        ["Tip_Barcode"] = "خواندن کدهای QR و بارکدهای درون تصویر",
        ["Btn_Recognize"] = "بازشناسی",
        ["Tip_Recognize"] = "بازشناسی متن درون تصویر (F5)",

        ["Option_AutoAi"] = "خودکار (Windows AI)",
        ["Option_AutoMulti"] = "خودکار (چندزبانه · کندتر)",

        ["Status_Loaded"] = "{0} بارگذاری شد.",
        ["Status_OpenFailed"] = "تصویر گشوده نشد: {0}",
        ["Status_ClipboardText"] = "متن از کلیپ‌بورد گرفته شد.",
        ["Status_ClipboardEmpty"] = "کلیپ‌بورد نه تصویری دارد و نه متنی.",
        ["Status_ClipboardFailed"] = "کلیپ‌بورد خوانده نشد: {0}",
        ["Status_DropFailed"] = "آنچه رها شد به کار نیامد: {0}",
        ["Status_ImageCopied"] = "تصویر در کلیپ‌بورد رونوشت شد.",
        ["Status_ImageCopyFailed"] = "تصویر رونوشت نشد: {0}",
        ["Status_ImageSaved"] = "تصویر با نام {0} ذخیره شد.",
        ["Status_ImageSaveFailed"] = "تصویر ذخیره نشد: {0}",
        ["Status_Recognizing"] = "در حال بازشناسی…",
        ["Status_NoText"] = "{0} در این تصویر متنی نیافت.",
        ["Status_Done"] = "انجام شد ({0}).",
        ["Status_DoneConfidence"] = "انجام شد ({0}) · اطمینان میانگین {1}٪.",
        ["Status_RecognizeFailed"] = "بازشناسی ناکام ماند: {0}",
        ["Status_Scanning"] = "در جست‌وجوی کدهای QR و بارکد…",
        ["Status_NoBarcode"] = "در این تصویر کد QR یا بارکدی یافت نشد.",
        ["Status_BarcodeOne"] = "یک کد {0} یافت شد.",
        ["Status_BarcodeMany"] = "{0} کد یافت شد.",
        ["Status_ScanFailed"] = "جست‌وجو ناکام ماند: {0}",
        ["Status_NothingToTranslate"] = "متنی برای ترجمه نیست.",
        ["Status_Translating"] = "در حال ترجمه به {0} روی همین دستگاه…",
        ["Status_Translated"] = "به {0} ترجمه شد، روی همین دستگاه، بدون دسترسی به شبکه.",
        ["Status_TranslateFailed"] = "ترجمه ناکام ماند: {0}",
        ["Status_NothingToCopy"] = "متنی برای رونوشت نیست.",
        ["Status_TextCopied"] = "متن در کلیپ‌بورد رونوشت شد.",
        ["Status_CopyFailed"] = "متن رونوشت نشد: {0}",
        ["Status_NothingToSpeak"] = "متنی برای خواندن نیست.",
        ["Status_SpeakFailed"] = "متن خوانده نشد: {0}",
        ["Status_HistoryLoaded"] = "نمایش نتیجهٔ {0}.",
        ["Status_NeedImage"] = "نخست تصویری بارگذاری کنید.",
        ["Status_CaptureFailed"] = "تصویربرداری از صفحه ناکام ماند: {0}",
        ["Status_StartupBlockedByUser"] = "ویندوز راه‌اندازی خودکار Glyfo را خاموش کرده است. آن را دوباره از مدیر وظیفه، در بخش برنامه‌های راه‌اندازی، روشن کنید.",
        ["Status_StartupBlockedByPolicy"] = "سازمان شما اجازه نمی‌دهد برنامه‌ها همراه با ویندوز اجرا شوند.",
        ["Status_LanguagePackMissing"] = "در ویندوز هیچ بستهٔ زبانی برای OCR نصب نیست، پس چیزی برای بازشناسی در کار نیست. زبان موردنیازتان را از زمان و زبان و سپس زبان و منطقه بیفزایید.",
        ["Btn_OpenLanguageSettings"] = "گشودن تنظیمات زبان",

        ["Tray_Open"] = "گشودن Glyfo",
        ["Tray_CaptureRegion"] = "گرفتن یک ناحیه",
        ["Tray_CaptureFullScreen"] = "گرفتن تمام صفحه",
        ["Tray_Exit"] = "خروج",
        ["Tray_Tooltip"] = "‏Glyfo — برای گرفتن یک ناحیه {0} را بزنید",
        ["Toast_StartupTitle"] = "‏Glyfo در حال اجراست",
        ["Toast_StartupBody"] = "برای برگزیدن بخشی از صفحه و خواندن متن آن {0} را بزنید. Ctrl+Shift+R تمام صفحه را می‌گیرد.",
        ["Toast_DontRemind"] = "دیگر یادآوری نکن",
        ["Toast_MinimizedTitle"] = "‏Glyfo هنوز در حال اجراست",
        ["Toast_MinimizedBody"] = "هر وقت خواستید {0} را بزنید تا تصویر گرفته و متن آن بازشناسی شود. برای بستن کامل، روی نماد آن در ناحیهٔ اعلان راست‌کلیک کنید و خروج را برگزینید.",
        ["Toast_ExitApp"] = "خروج از Glyfo",
        ["Toast_ResultTitle"] = "متن بازشناسی شد",
        ["Toast_ResultCopied"] = "در کلیپ‌بورد رونوشت شد.",
        ["Toast_OpenWindow"] = "گشودن پنجره",
        ["Toast_NoTextTitle"] = "متنی یافت نشد",
        ["Toast_NoTextBody"] = "در آن ناحیه چیزی که به‌عنوان متن خوانده شود وجود نداشت.",
        ["Toast_FailedTitle"] = "بازشناسی ناموفق بود",
        ["Toast_HotkeyUnavailableTitle"] = "میان‌بر گرفتن تصویر اشغال است",
        ["Toast_HotkeyUnavailableBody"] = "برنامهٔ دیگری آن را گرفته است، بنابراین گرفتن تصویر صفحه تنها از پنجره و از نماد ناحیهٔ اعلان ممکن است.",
        ["Setting_CloseToTray"] = "ادامهٔ اجرا هنگام بستن پنجره",
        ["Setting_CloseToTray_Desc"] = "با روشن بودن این گزینه، بستن پنجره Glyfo را در حال اجرا نگه می‌دارد تا میان‌بر گرفتن تصویر کار کند و نماد آن در ناحیهٔ اعلان بماند؛ در آنجا گزینهٔ خروج آن را به‌کلی می‌بندد. با خاموش بودن آن، بستن پنجره برنامه را پایان می‌دهد.",
        ["Setting_Startup"] = "اجرا همراه با ویندوز",
        ["Setting_Startup_Desc"] = "با روشن بودن این گزینه، Glyfo همراه با ویندوز اجرا می‌شود و بدون باز کردن پنجره مستقیم به ناحیهٔ اعلان می‌رود؛ بنابراین میان‌بر گرفتن تصویر از همان لحظهٔ ورود کار می‌کند.",

        ["Source_Clipboard"] = "تصویر کلیپ‌بورد",
        ["Source_Dropped"] = "تصویر رهاشده",
        ["Source_Shared"] = "تصویر هم‌رسانی‌شده",
        ["Source_FullScreen"] = "تمام صفحه",
        ["Source_Region"] = "بخشی از صفحه",
        ["Source_Codes"] = "{0} (کدها)",

        ["FileType_Image"] = "تصویر {0}",

        ["Region_Hint"] = "برای گزینش یک ناحیه بکشید　·　‏Esc یا کلیک راست برای لغو",

        ["Err_NoLanguagePack"] = "در ویندوز برای این زبان بستهٔ زبانی OCR نصب نیست. یکی را از زمان و زبان و سپس زبان و منطقه بیفزایید.",
        ["Err_TextTooLong"] = "متن برای مدل روی دستگاه بلندتر از آن است که جا شود. بخش کوچک‌تری را ترجمه کنید.",
        ["Err_ModelDeclined"] = "مدل روی دستگاه از ترجمهٔ این متن سر باز زد.",
        ["Err_TranslationFailed"] = "ترجمهٔ روی دستگاه نتیجه‌ای نداد.",
        ["Btn_About"] = "درباره Glyfo",
        ["About_Title"] = "درباره Glyfo",
        ["About_Version"] = "نسخه {0}",
        ["About_Tagline"] = "متن هر تصویری را روی همین دستگاه می‌خواند. چیزی از طریق شبکه ارسال نمی‌شود.",
        ["About_Rate"] = "امتیاز دادن به Glyfo",
        ["About_WhatsNew"] = "تازه‌ها",
        ["About_Source"] = "کد منبع در GitHub",
        ["About_Privacy"] = "سیاست حریم خصوصی",
        ["Common_Close"] = "بستن",
        ["News_Title"] = "تازه‌ها",
        ["News_110_1"] = "صفحهٔ درباره، شامل نسخه و پیوندهای کد منبع و سیاست حریم خصوصی.",
        ["News_110_2"] = "می‌توانید بدون خارج شدن از پنجره به Glyfo امتیاز بدهید.",
        ["News_110_3"] = "همین یادداشت‌ها، که با هر نسخهٔ تازه یک بار نمایش داده می‌شوند.",
        ["News_110_4"] = "گرفتن تصویر اکنون تمام صفحه را هم دربر می‌گیرد و ابتدا پنجره را پنهان می‌کند تا Glyfo در تصویر نیفتد.",
        ["Rate_Title"] = "Glyfo به کارتان می‌آید؟",
        ["Rate_Body"] = "امتیاز در Store همان چیزی است که باعث می‌شود دیگران برنامه را پیدا کنند. فقط یک لحظه طول می‌کشد.",
        ["Rate_Action"] = "امتیاز بدهید",
        ["Rate_Later"] = "الان نه",
    };
}
