using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Id = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR Windows · tanpa paket bahasa",
        ["Engine_OneLanguage"] = "OCR Windows · 1 bahasa",
        ["Engine_ManyLanguages"] = "OCR Windows · {0} bahasa",
        ["Engine_OnDevice"] = "{0} · di perangkat",

        ["Preview_Placeholder"] = "Jatuhkan gambar di sini, atau gunakan Berkas, Tangkapan, atau Papan klip di bawah",
        ["Btn_CopyImage"] = "Salin",
        ["Tip_CopyImage"] = "Salin gambar ke papan klip",
        ["Btn_SaveImage"] = "Simpan",
        ["Tip_SaveImage"] = "Simpan gambar sebagai…",
        ["Btn_FitToWindow"] = "Paskan",
        ["Tip_FitToWindow"] = "Perbesar agar pas dengan jendela",
        ["Tip_ActualSize"] = "Ukuran piksel sebenarnya",
        ["Tip_PdfPrev"] = "Halaman sebelumnya",
        ["Tip_PdfNext"] = "Halaman berikutnya",
        ["Tip_PdfAll"] = "Baca semua halaman",
        ["Action_Open"] = "Buka tautan",
        ["Action_Mail"] = "Kirim surel ke",
        ["Action_Call"] = "Telepon",
        ["Action_Search"] = "Cari di web",

        ["Voice_Placeholder"] = "Suara",
        ["Tip_Voice"] = "Suara yang dipakai untuk membacakan",
        ["Tip_Speak"] = "Bacakan teksnya",
        ["Tip_StopSpeak"] = "Hentikan pembacaan",
        ["Tip_CopyText"] = "Salin teks (Ctrl+Shift+C)",
        ["Tip_SaveText"] = "Simpan teks ke berkas (Ctrl+S)",
        ["Btn_RemoveLineBreaks"] = "Gabung baris",
        ["Tip_RemoveLineBreaks"] = "Gabungkan kembali pemutus baris menjadi paragraf",
        ["Btn_RemoveSpaces"] = "Tanpa spasi",
        ["Tip_RemoveSpaces"] = "Hapus semua spasi — untuk bahasa Tionghoa, Jepang, dan Korea",
        ["Result_Placeholder"] = "Teks hasil pengenalan muncul di sini dan dapat disunting.",

        ["Btn_OpenFile"] = "Berkas",
        ["Tip_OpenFile"] = "Buka berkas gambar (Ctrl+O)",
        ["Btn_Capture"] = "Tangkapan",
        ["Tip_Capture"] = "Pilih sebagian layar lalu kenali ({0}). Tekan Ctrl+Shift+R untuk seluruh layar.",
        ["Hotkey_Unavailable"] = "tanpa pintasan — keduanya sudah dipakai aplikasi lain",
        ["Btn_Paste"] = "Papan klip",
        ["Tip_Paste"] = "Muat gambar atau teks dari papan klip (Ctrl+V)",
        ["Btn_History"] = "Riwayat",
        ["Tip_History"] = "Hasil terbaru",
        ["History_Empty"] = "Belum ada yang dikenali.",
        ["History_EmptyPreview"] = "(kosong)",
        ["History_SearchPlaceholder"] = "Cari di hasil",
        ["History_NoMatch"] = "Tidak ada hasil yang cocok.",
        ["History_Off"] = "Riwayat dimatikan di Opsi.",
        ["History_Clear"] = "Bersihkan riwayat",
        ["History_CopyItem"] = "Salin teks ini",
        ["History_DeleteItem"] = "Hapus entri ini",
        ["Tip_Settings"] = "Opsi",
        ["Settings_Header"] = "Opsi",
        ["Setting_UiLanguage"] = "Bahasa aplikasi",
        ["Lang_SystemDefault"] = "Bawaan sistem",
        ["Setting_RepairNumbers"] = "Perbaiki l dan I di dalam angka",
        ["Setting_RepairNumbers_Desc"] = "Mesin pengenal kerap membaca v1.6.5 sebagai vl.6.5. Jika opsi ini aktif, huruf l atau I hanya menjadi angka 1 di tempat yang bersebelahan dengan pemisah dan angka, sehingga html5 dan IPv6 tetap utuh. Jika nonaktif, bacaan mesin dipertahankan persis seperti aslinya.",
        ["Setting_WatchClipboard"] = "Baca gambar yang saya salin",
        ["Setting_WatchClipboard_Desc"] = "Ambil tangkapan layar dengan Win+Shift+S dan Glyfo langsung membacanya, lalu menaruh teksnya di papan klip menggantikan gambar, sehingga tempelan berikutnya berupa teks. Hanya gambar yang dibaca, tidak pernah teks yang disalin, dan tidak ada yang dikirim ke mana pun — semuanya terjadi di perangkat ini.",
        ["Setting_KeepHistory"] = "Simpan riwayat antar sesi",
        ["Setting_KeepHistory_Desc"] = "Menyimpan 200 hasil terakhir sehingga tetap ada setelah dimulai ulang. Hanya teks yang disimpan, tidak pernah gambar, dalam berkas milik Glyfo di perangkat ini. Mematikannya akan menghapus berkas itu dan mengosongkan daftar seketika.",
        ["Common_On"] = "Aktif",
        ["Common_Off"] = "Nonaktif",
        ["Lang_Placeholder"] = "Bahasa",
        ["Tip_OcrLanguage"] = "Bahasa pengenalan, dari paket bahasa yang terpasang di Windows",
        ["Btn_Translate"] = "Terjemahkan",
        ["Tip_Translate"] = "Terjemahkan di perangkat ini — tidak ada yang dikirim lewat jaringan",
        ["Btn_Barcode"] = "Kode",
        ["Tip_Barcode"] = "Baca kode QR dan kode batang dalam gambar",
        ["Btn_Recognize"] = "Kenali",
        ["Tip_Recognize"] = "Kenali teks dalam gambar (F5)",

        ["Option_AutoAi"] = "Otomatis (Windows AI)",
        ["Option_AutoMulti"] = "Otomatis (banyak bahasa · lebih lambat)",

        ["Status_Loaded"] = "{0} dimuat.",
        ["Status_OpenFailed"] = "Gambar tidak dapat dibuka: {0}",
        ["Status_ClipboardText"] = "Teks dimuat dari papan klip.",
        ["Status_ClipboardEmpty"] = "Papan klip tidak berisi gambar maupun teks.",
        ["Status_ClipboardFailed"] = "Papan klip tidak dapat dibaca: {0}",
        ["Status_DropFailed"] = "Isi yang dijatuhkan tidak dapat dipakai: {0}",
        ["Status_ImageCopied"] = "Gambar disalin ke papan klip.",
        ["Status_ImageCopyFailed"] = "Gambar tidak dapat disalin: {0}",
        ["Status_ImageSaved"] = "Gambar disimpan sebagai {0}.",
        ["Status_ImageSaveFailed"] = "Gambar tidak dapat disimpan: {0}",
        ["Status_Recognizing"] = "Mengenali…",
        ["Status_NoText"] = "{0} tidak menemukan teks pada gambar ini.",
        ["Status_Done"] = "Selesai ({0}).",
        ["Status_DoneConfidence"] = "Selesai ({0}) · keyakinan rata-rata {1}%.",
        ["Status_RecognizeFailed"] = "Pengenalan gagal: {0}",
        ["Status_Scanning"] = "Mencari kode QR dan kode batang…",
        ["Status_NoBarcode"] = "Tidak ada kode QR atau kode batang pada gambar ini.",
        ["Status_BarcodeOne"] = "Menemukan satu kode {0}.",
        ["Status_BarcodeMany"] = "Menemukan {0} kode.",
        ["Status_ScanFailed"] = "Pemindaian gagal: {0}",
        ["Status_PdfFailed"] = "PDF ini tidak dapat dibaca — mungkin dilindungi kata sandi atau rusak",
        ["Status_LaunchFailed"] = "Windows tidak menemukan apa pun untuk membukanya.",
        ["Status_NothingToTranslate"] = "Tidak ada teks untuk diterjemahkan.",
        ["Status_Translating"] = "Menerjemahkan ke bahasa {0} di perangkat ini…",
        ["Status_Translated"] = "Diterjemahkan ke bahasa {0}, di perangkat ini, tanpa akses jaringan.",
        ["Status_TranslateFailed"] = "Penerjemahan gagal: {0}",
        ["Status_NothingToCopy"] = "Tidak ada teks untuk disalin.",
        ["Status_NothingToSave"] = "Tidak ada teks untuk disimpan.",
        ["Status_TextSaved"] = "Teks disimpan sebagai {0}.",
        ["Status_TextSaveFailed"] = "Teks tidak dapat disimpan: {0}",
        ["Status_TextCopied"] = "Teks disalin ke papan klip.",
        ["Status_CopyFailed"] = "Teks tidak dapat disalin: {0}",
        ["Status_NothingToSpeak"] = "Tidak ada teks untuk dibacakan.",
        ["Status_SpeakFailed"] = "Teks tidak dapat dibacakan: {0}",
        ["Status_HistoryLoaded"] = "Menampilkan hasil dari {0}.",
        ["Status_HistoryCleared"] = "Riwayat dibersihkan.",
        ["Status_NeedImage"] = "Muat gambar terlebih dahulu.",
        ["Status_CaptureFailed"] = "Penangkapan layar gagal: {0}",
        ["Status_StartupBlockedByUser"] = "Windows menonaktifkan mulai otomatis untuk Glyfo. Aktifkan kembali di Pengelola Tugas pada Aplikasi Pengaktifan.",
        ["Status_StartupBlockedByPolicy"] = "Organisasi Anda tidak mengizinkan aplikasi dimulai bersama Windows.",
        ["Status_LanguagePackMissing"] = "Windows tidak memiliki paket bahasa OCR yang terpasang, jadi tidak ada yang bisa dipakai untuk mengenali. Tambahkan bahasa yang Anda perlukan di Waktu & bahasa, lalu Bahasa & wilayah.",
        ["Btn_OpenLanguageSettings"] = "Buka pengaturan bahasa",

        ["Tray_Open"] = "Buka Glyfo",
        ["Tray_CaptureRegion"] = "Tangkap sebuah area",
        ["Tray_CaptureFullScreen"] = "Tangkap seluruh layar",
        ["Tray_Exit"] = "Keluar",
        ["Tray_Tooltip"] = "Glyfo — tekan {0} untuk menangkap sebuah area",
        ["Toast_StartupTitle"] = "Glyfo sedang berjalan",
        ["Toast_StartupBody"] = "Tekan {0} untuk memilih sebagian layar dan membaca teks di dalamnya. Ctrl+Shift+R menangkap seluruh layar.",
        ["Toast_DontRemind"] = "Jangan ingatkan lagi",
        ["Toast_MinimizedTitle"] = "Glyfo masih berjalan",
        ["Toast_MinimizedBody"] = "Tekan {0} kapan saja untuk menangkap dan mengenali teks. Untuk menutupnya sepenuhnya, klik kanan ikonnya di area notifikasi lalu pilih Keluar.",
        ["Toast_ExitApp"] = "Keluar dari Glyfo",
        ["Toast_ResultTitle"] = "Teks dikenali",
        ["Toast_ResultCopied"] = "Disalin ke papan klip.",
        ["Toast_OpenWindow"] = "Buka jendela",
        ["Toast_NoTextTitle"] = "Teks tidak ditemukan",
        ["Toast_NoTextBody"] = "Tidak ada yang bisa dibaca sebagai teks di area itu.",
        ["Toast_FailedTitle"] = "Pengenalan gagal",
        ["Toast_HotkeyUnavailableTitle"] = "Pintasan tangkapan sedang dipakai",
        ["Toast_HotkeyUnavailableBody"] = "Aplikasi lain sudah memakainya, jadi tangkapan layar hanya bisa dilakukan dari jendela dan dari ikon di area notifikasi.",
        ["Setting_CloseToTray"] = "Tetap berjalan saat jendela ditutup",
        ["Setting_CloseToTray_Desc"] = "Bila aktif, menutup jendela membiarkan Glyfo tetap berjalan sehingga pintasan tangkapan masih berfungsi, dan ikonnya tetap di area notifikasi, tempat Keluar menutupnya sepenuhnya. Bila nonaktif, menutup jendela mengakhiri aplikasi.",
        ["Setting_Startup"] = "Mulai bersama Windows",
        ["Setting_Startup_Desc"] = "Saat aktif, Glyfo dimulai bersama Windows dan langsung masuk ke area notifikasi tanpa membuka jendela, sehingga pintasan tangkapan berfungsi sejak Anda masuk.",

        ["Source_Clipboard"] = "gambar dari papan klip",
        ["Source_Dropped"] = "gambar yang dijatuhkan",
        ["Source_Shared"] = "gambar yang dibagikan",
        ["Source_FullScreen"] = "Layar penuh",
        ["Source_Region"] = "Bagian layar",
        ["Source_Codes"] = "{0} (kode)",
        ["Source_Batch"] = "{0} berkas",
        ["Source_PdfAll"] = "{0}, semua halaman",

        ["FileType_Image"] = "Gambar {0}",
        ["FileType_Text"] = "Teks biasa",
        ["FileType_Markdown"] = "Markdown",
        ["Batch_Title"] = "Membaca beberapa berkas",
        ["Batch_Progress"] = "{0} dari {1}",
        ["Batch_DoneAll"] = "{0} dibaca.",
        ["Batch_Cancelled"] = "Dihentikan setelah {0} dari {1}.",
        ["Batch_ItemFailed"] = "Tidak dapat dibaca: {0}",
        ["Batch_ItemEmpty"] = "(tidak ada teks)",
        ["Batch_Save"] = "Simpan…",
        ["Batch_CopyAll"] = "Salin semua",
        ["Batch_Separate"] = "Simpan setiap item sebagai berkas tersendiri",
        ["Batch_SavedFolder"] = "{0} berkas disimpan ke {1}.",
        ["Batch_TooLongForBox"] = "{0} item dibaca. Teksnya terlalu panjang untuk ditampilkan di sini — ada di berkas yang baru Anda simpan.",

        ["Region_Hint"] = "Seret untuk memilih area　·　Esc atau klik kanan untuk membatalkan",

        ["Err_NoLanguagePack"] = "Windows tidak memiliki paket bahasa OCR untuk bahasa ini. Tambahkan satu di Waktu & bahasa, lalu Bahasa & wilayah.",
        ["Err_TextTooLong"] = "Teksnya terlalu panjang untuk model di perangkat. Terjemahkan bagian yang lebih pendek.",
        ["Err_ModelDeclined"] = "Model di perangkat menolak menerjemahkan teks ini.",
        ["Err_TranslationFailed"] = "Penerjemahan di perangkat tidak menghasilkan apa pun.",
        ["Btn_About"] = "Tentang Glyfo",
        ["About_Title"] = "Tentang Glyfo",
        ["About_Version"] = "Versi {0}",
        ["About_Tagline"] = "Membaca teks pada gambar apa pun, di perangkat ini. Tidak ada yang dikirim melalui jaringan.",
        ["About_Rate"] = "Beri rating Glyfo",
        ["About_WhatsNew"] = "Yang baru",
        ["About_Source"] = "Kode sumber di GitHub",
        ["About_Privacy"] = "Kebijakan privasi",
        ["Common_Close"] = "Tutup",
        ["Common_Cancel"] = "Batal",
        ["News_Title"] = "Yang baru",
        ["News_130_1"] = "Riwayat kini bertahan setelah dimulai ulang, dan ada kotak pencarian untuknya. Hanya teks yang disimpan — di Opsi riwayat bisa dikosongkan atau dimatikan.",
        ["News_130_2"] = "Ctrl+S menyimpan teks hasil pengenalan sebagai berkas teks biasa atau Markdown.",
        ["News_130_3"] = "Buka atau seret beberapa berkas sekaligus, atau baca satu PDF penuh, lalu simpan semuanya sebagai satu berkas atau satu berkas per item.",
        ["News_120_1"] = "Ambil tangkapan layar dengan Win+Shift+S dan Glyfo membacanya untuk Anda, lalu meninggalkan teksnya di papan klip. Mati sampai Anda menyalakannya di Opsi.",
        ["News_120_2"] = "PDF kini terbuka seperti gambar, satu halaman setiap kali.",
        ["News_120_3"] = "Tautan, alamat surel, dan nomor telepon yang ditemukan dalam teks mendapat tombol di bawahnya.",
        ["News_110_1"] = "Halaman Tentang, berisi versi serta tautan ke kode sumber dan kebijakan privasi.",
        ["News_110_2"] = "Anda dapat memberi rating Glyfo tanpa meninggalkan jendela.",
        ["News_110_3"] = "Catatan ini, yang muncul sekali setiap kali ada versi baru.",
        ["News_110_4"] = "Tangkapan kini juga menawarkan seluruh layar dan menyembunyikan jendela lebih dulu, jadi Glyfo tidak pernah ikut terekam.",
        ["Rate_Title"] = "Apakah Glyfo membantu?",
        ["Rate_Body"] = "Rating di Store adalah cara orang lain menemukan aplikasi ini. Hanya perlu sebentar.",
        ["Rate_Action"] = "Beri rating",
        ["Rate_Later"] = "Nanti saja",
    };
}
