using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Th = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR ของ Windows · ไม่มีชุดภาษา",
        ["Engine_OneLanguage"] = "OCR ของ Windows · 1 ภาษา",
        ["Engine_ManyLanguages"] = "OCR ของ Windows · {0} ภาษา",
        ["Engine_OnDevice"] = "{0} · บนอุปกรณ์",

        ["Preview_Placeholder"] = "ลากรูปมาวางที่นี่ หรือใช้ปุ่มไฟล์ จับภาพ หรือคลิปบอร์ดด้านล่าง",
        ["Btn_CopyImage"] = "คัดลอก",
        ["Tip_CopyImage"] = "คัดลอกรูปไปยังคลิปบอร์ด",
        ["Btn_SaveImage"] = "บันทึก",
        ["Tip_SaveImage"] = "บันทึกรูปเป็น…",
        ["Btn_FitToWindow"] = "พอดีหน้าต่าง",
        ["Tip_FitToWindow"] = "ย่อขยายให้พอดีกับหน้าต่าง",
        ["Tip_ActualSize"] = "ขนาดพิกเซลจริง",

        ["Voice_Placeholder"] = "เสียง",
        ["Tip_Voice"] = "เสียงที่ใช้อ่านออกเสียง",
        ["Tip_Speak"] = "อ่านข้อความออกเสียง",
        ["Tip_StopSpeak"] = "หยุดอ่าน",
        ["Tip_CopyText"] = "คัดลอกข้อความ (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "รวมบรรทัด",
        ["Tip_RemoveLineBreaks"] = "รวมการขึ้นบรรทัดใหม่ให้กลับเป็นย่อหน้า",
        ["Btn_RemoveSpaces"] = "ไม่มีช่องว่าง",
        ["Tip_RemoveSpaces"] = "ลบช่องว่างทั้งหมด — สำหรับภาษาจีน ญี่ปุ่น และเกาหลี",
        ["Result_Placeholder"] = "ข้อความที่อ่านได้จะปรากฏที่นี่และแก้ไขได้",

        ["Btn_OpenFile"] = "ไฟล์",
        ["Tip_OpenFile"] = "เปิดไฟล์รูปภาพ (Ctrl+O)",
        ["Btn_Capture"] = "จับภาพ",
        ["Tip_Capture"] = "เลือกพื้นที่บนหน้าจอแล้วอ่านข้อความ ({0}) กด Ctrl+Shift+R เพื่อจับทั้งหน้าจอ",
        ["Hotkey_Unavailable"] = "ไม่มีปุ่มลัด — แอปอื่นใช้ทั้งสองปุ่มไปแล้ว",
        ["Btn_Paste"] = "คลิปบอร์ด",
        ["Tip_Paste"] = "โหลดรูปหรือข้อความจากคลิปบอร์ด (Ctrl+V)",
        ["Btn_History"] = "ประวัติ",
        ["Tip_History"] = "ผลลัพธ์ล่าสุด",
        ["History_Empty"] = "ยังไม่ได้อ่านอะไรเลย",
        ["History_EmptyPreview"] = "(ว่าง)",
        ["Tip_Settings"] = "ตัวเลือก",
        ["Settings_Header"] = "ตัวเลือก",
        ["Setting_UiLanguage"] = "ภาษาของแอป",
        ["Lang_SystemDefault"] = "ค่าเริ่มต้นของระบบ",
        ["Setting_RepairNumbers"] = "แก้ l และ I ที่อยู่ในตัวเลข",
        ["Setting_RepairNumbers_Desc"] = "ตัวอ่านข้อความมักอ่าน v1.6.5 เป็น vl.6.5 เมื่อเปิดตัวเลือกนี้ ตัว l หรือ I จะกลายเป็นเลข 1 เฉพาะตรงที่มีตัวคั่นและตัวเลขอยู่ติดกันเท่านั้น html5 และ IPv6 จึงไม่ถูกแตะต้อง เมื่อปิด ผลที่เครื่องอ่านได้จะคงไว้ตรงตามเดิมทุกประการ",
        ["Common_On"] = "เปิด",
        ["Common_Off"] = "ปิด",
        ["Lang_Placeholder"] = "ภาษา",
        ["Tip_OcrLanguage"] = "ภาษาที่ใช้อ่าน จากชุดภาษาที่ติดตั้งไว้ใน Windows",
        ["Btn_Translate"] = "แปล",
        ["Tip_Translate"] = "แปลบนอุปกรณ์นี้ — ไม่มีการส่งอะไรผ่านเครือข่าย",
        ["Btn_Barcode"] = "รหัส",
        ["Tip_Barcode"] = "อ่านคิวอาร์โค้ดและบาร์โค้ดในรูป",
        ["Btn_Recognize"] = "อ่านข้อความ",
        ["Tip_Recognize"] = "อ่านข้อความในรูป (F5)",

        ["Option_AutoAi"] = "อัตโนมัติ (Windows AI)",
        ["Option_AutoMulti"] = "อัตโนมัติ (หลายภาษา · ช้ากว่า)",

        ["Status_Loaded"] = "โหลด{0}แล้ว",
        ["Status_OpenFailed"] = "เปิดรูปไม่ได้: {0}",
        ["Status_ClipboardText"] = "โหลดข้อความจากคลิปบอร์ดแล้ว",
        ["Status_ClipboardEmpty"] = "คลิปบอร์ดไม่มีทั้งรูปและข้อความ",
        ["Status_ClipboardFailed"] = "อ่านคลิปบอร์ดไม่ได้: {0}",
        ["Status_DropFailed"] = "ใช้สิ่งที่ลากมาวางไม่ได้: {0}",
        ["Status_ImageCopied"] = "คัดลอกรูปไปยังคลิปบอร์ดแล้ว",
        ["Status_ImageCopyFailed"] = "คัดลอกรูปไม่ได้: {0}",
        ["Status_ImageSaved"] = "บันทึกรูปเป็น {0} แล้ว",
        ["Status_ImageSaveFailed"] = "บันทึกรูปไม่ได้: {0}",
        ["Status_Recognizing"] = "กำลังอ่าน…",
        ["Status_NoText"] = "{0} ไม่พบข้อความในรูปนี้",
        ["Status_Done"] = "เสร็จแล้ว ({0})",
        ["Status_DoneConfidence"] = "เสร็จแล้ว ({0}) · ความมั่นใจเฉลี่ย {1}%",
        ["Status_RecognizeFailed"] = "อ่านข้อความไม่สำเร็จ: {0}",
        ["Status_Scanning"] = "กำลังค้นหาคิวอาร์โค้ดและบาร์โค้ด…",
        ["Status_NoBarcode"] = "ไม่พบคิวอาร์โค้ดหรือบาร์โค้ดในรูปนี้",
        ["Status_BarcodeOne"] = "พบรหัส {0} หนึ่งรายการ",
        ["Status_BarcodeMany"] = "พบรหัส {0} รายการ",
        ["Status_ScanFailed"] = "สแกนไม่สำเร็จ: {0}",
        ["Status_NothingToTranslate"] = "ไม่มีข้อความให้แปล",
        ["Status_Translating"] = "กำลังแปลเป็น{0}บนอุปกรณ์นี้…",
        ["Status_Translated"] = "แปลเป็น{0}แล้ว บนอุปกรณ์นี้ โดยไม่ใช้เครือข่าย",
        ["Status_TranslateFailed"] = "แปลไม่สำเร็จ: {0}",
        ["Status_NothingToCopy"] = "ไม่มีข้อความให้คัดลอก",
        ["Status_TextCopied"] = "คัดลอกข้อความไปยังคลิปบอร์ดแล้ว",
        ["Status_CopyFailed"] = "คัดลอกข้อความไม่ได้: {0}",
        ["Status_NothingToSpeak"] = "ไม่มีข้อความให้อ่าน",
        ["Status_SpeakFailed"] = "อ่านข้อความออกเสียงไม่ได้: {0}",
        ["Status_HistoryLoaded"] = "กำลังแสดงผลลัพธ์จาก {0}",
        ["Status_NeedImage"] = "โหลดรูปก่อน",
        ["Status_CaptureFailed"] = "จับภาพหน้าจอไม่สำเร็จ: {0}",
        ["Status_StartupBlockedByUser"] = "Windows ปิดการเริ่มทำงานอัตโนมัติของ Glyfo ไว้ เปิดอีกครั้งได้ในตัวจัดการงาน ที่แอปเริ่มต้นระบบ",
        ["Status_StartupBlockedByPolicy"] = "องค์กรของคุณไม่อนุญาตให้แอปเริ่มทำงานพร้อม Windows",
        ["Status_LanguagePackMissing"] = "Windows ยังไม่ได้ติดตั้งชุดภาษาสำหรับ OCR จึงไม่มีอะไรให้ใช้อ่านข้อความ เพิ่มภาษาที่ต้องการได้ที่ เวลาและภาษา แล้วไปที่ ภาษาและภูมิภาค",
        ["Btn_OpenLanguageSettings"] = "เปิดการตั้งค่าภาษา",

        ["Tray_Open"] = "เปิด Glyfo",
        ["Tray_CaptureRegion"] = "จับภาพพื้นที่",
        ["Tray_CaptureFullScreen"] = "จับภาพทั้งหน้าจอ",
        ["Tray_Exit"] = "ออก",
        ["Tray_Tooltip"] = "Glyfo — กด {0} เพื่อจับภาพพื้นที่",
        ["Toast_StartupTitle"] = "Glyfo กำลังทำงาน",
        ["Toast_StartupBody"] = "กด {0} เพื่อเลือกพื้นที่บนหน้าจอแล้วอ่านข้อความในนั้น กด Ctrl+Shift+R เพื่อจับทั้งหน้าจอ",
        ["Toast_DontRemind"] = "ไม่ต้องเตือนอีก",
        ["Toast_MinimizedTitle"] = "Glyfo ยังทำงานอยู่",
        ["Toast_MinimizedBody"] = "กด {0} เมื่อใดก็ได้เพื่อจับภาพและอ่านข้อความ หากต้องการปิดจริง ๆ ให้คลิกขวาที่ไอคอนในพื้นที่แจ้งเตือนแล้วเลือกออก",
        ["Toast_ExitApp"] = "ออกจาก Glyfo",
        ["Toast_ResultTitle"] = "อ่านข้อความได้แล้ว",
        ["Toast_ResultCopied"] = "คัดลอกไปยังคลิปบอร์ดแล้ว",
        ["Toast_OpenWindow"] = "เปิดหน้าต่าง",
        ["Toast_NoTextTitle"] = "ไม่พบข้อความ",
        ["Toast_NoTextBody"] = "ในพื้นที่นั้นไม่มีสิ่งใดที่อ่านเป็นข้อความได้",
        ["Toast_FailedTitle"] = "อ่านข้อความไม่สำเร็จ",
        ["Toast_HotkeyUnavailableTitle"] = "ปุ่มลัดสำหรับจับภาพถูกใช้อยู่",
        ["Toast_HotkeyUnavailableBody"] = "แอปอื่นใช้ปุ่มลัดนี้อยู่แล้ว จึงจับภาพหน้าจอได้จากหน้าต่างและไอคอนในพื้นที่แจ้งเตือนเท่านั้น",
        ["Setting_CloseToTray"] = "ทำงานต่อเมื่อปิดหน้าต่าง",
        ["Setting_CloseToTray_Desc"] = "เมื่อเปิดตัวเลือกนี้ การปิดหน้าต่างจะไม่ปิด Glyfo ปุ่มลัดจับภาพจึงยังใช้ได้ และไอคอนจะอยู่ในพื้นที่แจ้งเตือน ซึ่งเลือกออกได้เพื่อปิดโปรแกรมจริง ๆ เมื่อปิดตัวเลือกนี้ การปิดหน้าต่างจะเป็นการออกจากแอป",
        ["Setting_Startup"] = "เริ่มทำงานพร้อม Windows",
        ["Setting_Startup_Desc"] = "เมื่อเปิดตัวเลือกนี้ Glyfo จะเริ่มทำงานพร้อม Windows และเข้าสู่พื้นที่แจ้งเตือนโดยตรงโดยไม่เปิดหน้าต่าง ทำให้ใช้แป้นพิมพ์ลัดจับภาพได้ทันทีที่ลงชื่อเข้าใช้",

        ["Source_Clipboard"] = "รูปจากคลิปบอร์ด",
        ["Source_Dropped"] = "รูปที่ลากมาวาง",
        ["Source_Shared"] = "รูปภาพที่แชร์",
        ["Source_FullScreen"] = "เต็มหน้าจอ",
        ["Source_Region"] = "พื้นที่บนหน้าจอ",
        ["Source_Codes"] = "{0} (รหัส)",

        ["FileType_Image"] = "รูป {0}",

        ["Region_Hint"] = "ลากเพื่อเลือกพื้นที่　·　Esc หรือคลิกขวาเพื่อยกเลิก",

        ["Err_NoLanguagePack"] = "Windows ยังไม่ได้ติดตั้งชุดภาษาสำหรับ OCR ของภาษานี้ เพิ่มได้ที่ เวลาและภาษา แล้วไปที่ ภาษาและภูมิภาค",
        ["Err_TextTooLong"] = "ข้อความยาวเกินกว่าที่โมเดลบนอุปกรณ์จะรับไหว ลองแปลส่วนที่สั้นลง",
        ["Err_ModelDeclined"] = "โมเดลบนอุปกรณ์ปฏิเสธที่จะแปลข้อความนี้",
        ["Err_TranslationFailed"] = "การแปลบนอุปกรณ์ไม่ได้ผลลัพธ์ใด ๆ",
    };
}
