using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> It = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR di Windows · nessun language pack",
        ["Engine_OneLanguage"] = "OCR di Windows · 1 lingua",
        ["Engine_ManyLanguages"] = "OCR di Windows · {0} lingue",
        ["Engine_OnDevice"] = "{0} · sul dispositivo",

        ["Preview_Placeholder"] = "Trascina qui un'immagine, oppure usa File, Cattura o Appunti qui sotto",
        ["Btn_CopyImage"] = "Copia",
        ["Tip_CopyImage"] = "Copia l'immagine negli appunti",
        ["Btn_SaveImage"] = "Salva",
        ["Tip_SaveImage"] = "Salva l'immagine con nome…",
        ["Btn_FitToWindow"] = "Adatta",
        ["Tip_FitToWindow"] = "Adatta lo zoom alla finestra",
        ["Tip_ActualSize"] = "Dimensione reale in pixel",

        ["Voice_Placeholder"] = "Voce",
        ["Tip_Voice"] = "Voce usata per la lettura ad alta voce",
        ["Tip_Speak"] = "Leggi il testo ad alta voce",
        ["Tip_StopSpeak"] = "Interrompi la lettura",
        ["Tip_CopyText"] = "Copia il testo (Ctrl+Maiusc+C)",
        ["Btn_RemoveLineBreaks"] = "Unisci righe",
        ["Tip_RemoveLineBreaks"] = "Riunisci le interruzioni di riga in paragrafi",
        ["Btn_RemoveSpaces"] = "Senza spazi",
        ["Tip_RemoveSpaces"] = "Rimuovi tutti gli spazi, per cinese, giapponese e coreano",
        ["Result_Placeholder"] = "Il testo riconosciuto compare qui e può essere modificato.",

        ["Btn_OpenFile"] = "File",
        ["Tip_OpenFile"] = "Apri un file immagine (Ctrl+O)",
        ["Btn_Capture"] = "Cattura",
        ["Tip_Capture"] = "Seleziona un'area dello schermo e riconoscila ({0}). Premi Ctrl+Maiusc+R per l'intero schermo.",
        ["Hotkey_Unavailable"] = "nessuna scorciatoia — un'altra app le occupa entrambe",
        ["Btn_Paste"] = "Appunti",
        ["Tip_Paste"] = "Carica un'immagine o del testo dagli appunti (Ctrl+V)",
        ["Btn_History"] = "Cronologia",
        ["Tip_History"] = "Risultati recenti",
        ["History_Empty"] = "Non è ancora stato riconosciuto nulla.",
        ["History_EmptyPreview"] = "(vuoto)",
        ["Tip_Settings"] = "Opzioni",
        ["Settings_Header"] = "Opzioni",
        ["Setting_UiLanguage"] = "Lingua dell'app",
        ["Lang_SystemDefault"] = "Impostazione di sistema",
        ["Setting_RepairNumbers"] = "Correggi l e I dentro i numeri",
        ["Setting_RepairNumbers_Desc"] = "I motori di riconoscimento leggono spesso v1.6.5 come vl.6.5. Se l'opzione è attiva, una l o una I diventa 1 solo dove accanto si trovano un separatore e una cifra, così html5 e IPv6 restano intatti. Se è disattivata, la lettura del motore viene mantenuta esattamente com'è.",
        ["Common_On"] = "Attivo",
        ["Common_Off"] = "Non attivo",
        ["Lang_Placeholder"] = "Lingua",
        ["Tip_OcrLanguage"] = "Lingua di riconoscimento, tra i language pack installati in Windows",
        ["Btn_Translate"] = "Traduci",
        ["Tip_Translate"] = "Traduci su questo dispositivo — nulla viene inviato in rete",
        ["Btn_Barcode"] = "Codici",
        ["Tip_Barcode"] = "Leggi i codici QR e i codici a barre nell'immagine",
        ["Btn_Recognize"] = "Riconosci",
        ["Tip_Recognize"] = "Riconosci il testo nell'immagine (F5)",

        ["Option_AutoAi"] = "Automatico (Windows AI)",
        ["Option_AutoMulti"] = "Automatico (multilingua · più lento)",

        ["Status_Loaded"] = "{0} caricata.",
        ["Status_OpenFailed"] = "Impossibile aprire l'immagine: {0}",
        ["Status_ClipboardText"] = "Testo caricato dagli appunti.",
        ["Status_ClipboardEmpty"] = "Negli appunti non ci sono né immagini né testo.",
        ["Status_ClipboardFailed"] = "Impossibile leggere gli appunti: {0}",
        ["Status_DropFailed"] = "Impossibile usare l'elemento trascinato: {0}",
        ["Status_ImageCopied"] = "Immagine copiata negli appunti.",
        ["Status_ImageCopyFailed"] = "Impossibile copiare l'immagine: {0}",
        ["Status_ImageSaved"] = "Immagine salvata come {0}.",
        ["Status_ImageSaveFailed"] = "Impossibile salvare l'immagine: {0}",
        ["Status_Recognizing"] = "Riconoscimento in corso…",
        ["Status_NoText"] = "{0} non ha trovato testo in questa immagine.",
        ["Status_Done"] = "Fatto ({0}).",
        ["Status_DoneConfidence"] = "Fatto ({0}) · attendibilità media {1}%.",
        ["Status_RecognizeFailed"] = "Riconoscimento non riuscito: {0}",
        ["Status_Scanning"] = "Ricerca di codici QR e codici a barre…",
        ["Status_NoBarcode"] = "Nessun codice QR o a barre trovato in questa immagine.",
        ["Status_BarcodeOne"] = "Trovato un codice {0}.",
        ["Status_BarcodeMany"] = "Trovati {0} codici.",
        ["Status_ScanFailed"] = "Scansione non riuscita: {0}",
        ["Status_NothingToTranslate"] = "Non c'è testo da tradurre.",
        ["Status_Translating"] = "Traduzione in {0} su questo dispositivo…",
        ["Status_Translated"] = "Tradotto in {0}, su questo dispositivo, senza accesso alla rete.",
        ["Status_TranslateFailed"] = "Traduzione non riuscita: {0}",
        ["Status_NothingToCopy"] = "Non c'è testo da copiare.",
        ["Status_TextCopied"] = "Testo copiato negli appunti.",
        ["Status_CopyFailed"] = "Impossibile copiare il testo: {0}",
        ["Status_NothingToSpeak"] = "Non c'è testo da leggere ad alta voce.",
        ["Status_SpeakFailed"] = "Impossibile leggere il testo ad alta voce: {0}",
        ["Status_HistoryLoaded"] = "Viene mostrato il risultato di {0}.",
        ["Status_NeedImage"] = "Carica prima un'immagine.",
        ["Status_CaptureFailed"] = "Cattura dello schermo non riuscita: {0}",
        ["Status_StartupBlockedByUser"] = "Windows ha disattivato l’avvio automatico di Glyfo. Riattivalo in Gestione attività, nella scheda App di avvio.",
        ["Status_StartupBlockedByPolicy"] = "L’organizzazione non consente alle app di avviarsi con Windows.",
        ["Status_LanguagePackMissing"] = "In Windows non è installato alcun language pack per l'OCR, quindi non c'è nulla con cui riconoscere. Aggiungi la lingua che ti serve in Data/ora e lingua, poi Lingua e area geografica.",
        ["Btn_OpenLanguageSettings"] = "Apri le impostazioni della lingua",

        ["Tray_Open"] = "Apri Glyfo",
        ["Tray_CaptureRegion"] = "Cattura un'area",
        ["Tray_CaptureFullScreen"] = "Cattura tutto lo schermo",
        ["Tray_Exit"] = "Esci",
        ["Tray_Tooltip"] = "Glyfo — premi {0} per catturare un'area",
        ["Toast_StartupTitle"] = "Glyfo è in esecuzione",
        ["Toast_StartupBody"] = "Premi {0} per selezionare una parte dello schermo e leggerne il testo. Ctrl+Maiusc+R cattura l'intero schermo.",
        ["Toast_DontRemind"] = "Non ricordarmelo più",
        ["Toast_MinimizedTitle"] = "Glyfo è ancora in esecuzione",
        ["Toast_MinimizedBody"] = "Premi {0} in qualsiasi momento per catturare e riconoscere. Per chiuderlo del tutto, fai clic con il pulsante destro sulla sua icona nell'area di notifica e scegli Esci.",
        ["Toast_ExitApp"] = "Esci da Glyfo",
        ["Toast_ResultTitle"] = "Testo riconosciuto",
        ["Toast_ResultCopied"] = "Copiato negli appunti.",
        ["Toast_OpenWindow"] = "Apri la finestra",
        ["Toast_NoTextTitle"] = "Nessun testo trovato",
        ["Toast_NoTextBody"] = "In quell'area non c'era nulla di leggibile come testo.",
        ["Toast_FailedTitle"] = "Riconoscimento non riuscito",
        ["Toast_HotkeyUnavailableTitle"] = "La scorciatoia di cattura è occupata",
        ["Toast_HotkeyUnavailableBody"] = "Un'altra app la usa già, quindi la cattura dello schermo è disponibile solo dalla finestra e dall'icona nell'area di notifica.",
        ["Setting_CloseToTray"] = "Continua a funzionare alla chiusura della finestra",
        ["Setting_CloseToTray_Desc"] = "Quando è attivo, chiudere la finestra lascia Glyfo in esecuzione perché la scorciatoia di cattura continui a funzionare e la sua icona resta nell'area di notifica, dove Esci lo chiude definitivamente. Quando è disattivato, chiudere la finestra termina l'app.",
        ["Setting_Startup"] = "Avvia con Windows",
        ["Setting_Startup_Desc"] = "Se attivo, Glyfo si avvia con Windows e va direttamente nell’area di notifica senza aprire finestre, così la scorciatoia di cattura funziona già dall’accesso.",

        ["Source_Clipboard"] = "l'immagine dagli appunti",
        ["Source_Dropped"] = "l'immagine trascinata",
        ["Source_Shared"] = "l’immagine condivisa",
        ["Source_FullScreen"] = "Schermo intero",
        ["Source_Region"] = "Area dello schermo",
        ["Source_Codes"] = "{0} (codici)",

        ["FileType_Image"] = "Immagine {0}",

        ["Region_Hint"] = "Trascina per selezionare un'area　·　Esc o clic destro per annullare",

        ["Err_NoLanguagePack"] = "In Windows non è installato alcun language pack per l'OCR di questa lingua. Aggiungine uno in Data/ora e lingua, poi Lingua e area geografica.",
        ["Err_TextTooLong"] = "Il testo è troppo lungo per il modello locale. Traducine una parte più breve.",
        ["Err_ModelDeclined"] = "Il modello locale ha rifiutato di tradurre questo testo.",
        ["Err_TranslationFailed"] = "La traduzione locale non ha prodotto alcun risultato.",
        ["Btn_About"] = "Informazioni su Glyfo",
        ["About_Title"] = "Informazioni su Glyfo",
        ["About_Version"] = "Versione {0}",
        ["About_Tagline"] = "Legge il testo di qualsiasi immagine, su questo dispositivo. Nulla viene inviato in rete.",
        ["About_Rate"] = "Valuta Glyfo",
        ["About_WhatsNew"] = "Novità",
        ["About_Source"] = "Codice sorgente su GitHub",
        ["About_Privacy"] = "Informativa sulla privacy",
        ["Common_Close"] = "Chiudi",
        ["News_Title"] = "Novità",
        ["News_110_1"] = "Una pagina Informazioni, con la versione e i collegamenti al codice sorgente e all'informativa sulla privacy.",
        ["News_110_2"] = "Puoi valutare Glyfo senza uscire dalla finestra.",
        ["News_110_3"] = "Queste note, mostrate una volta a ogni nuova versione.",
        ["Rate_Title"] = "Glyfo ti sta tornando utile?",
        ["Rate_Body"] = "Una valutazione nello Store è ciò che permette agli altri di trovarlo. Ci vuole un attimo.",
        ["Rate_Action"] = "Valuta",
        ["Rate_Later"] = "Non ora",
    };
}
