using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Pt = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR do Windows · sem pacote de idioma",
        ["Engine_OneLanguage"] = "OCR do Windows · 1 idioma",
        ["Engine_ManyLanguages"] = "OCR do Windows · {0} idiomas",
        ["Engine_OnDevice"] = "{0} · no dispositivo",

        ["Preview_Placeholder"] = "Solte uma imagem aqui, ou use Arquivo, Captura ou Área de transferência abaixo",
        ["Btn_CopyImage"] = "Copiar",
        ["Tip_CopyImage"] = "Copiar a imagem para a área de transferência",
        ["Btn_SaveImage"] = "Salvar",
        ["Tip_SaveImage"] = "Salvar a imagem como…",
        ["Btn_FitToWindow"] = "Ajustar",
        ["Tip_FitToWindow"] = "Ajustar o zoom à janela",
        ["Tip_ActualSize"] = "Tamanho real em pixels",
        ["Tip_PdfPrev"] = "Página anterior",
        ["Tip_PdfNext"] = "Próxima página",
        ["Action_Open"] = "Abrir link",
        ["Action_Mail"] = "Escrever para",
        ["Action_Call"] = "Ligar para",
        ["Action_Search"] = "Pesquisar na web por",

        ["Voice_Placeholder"] = "Voz",
        ["Tip_Voice"] = "Voz usada na leitura em voz alta",
        ["Tip_Speak"] = "Ler o texto em voz alta",
        ["Tip_StopSpeak"] = "Parar a leitura",
        ["Tip_CopyText"] = "Copiar o texto (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Sem quebras",
        ["Tip_RemoveLineBreaks"] = "Juntar as quebras de linha de volta em parágrafos",
        ["Btn_RemoveSpaces"] = "Sem espaços",
        ["Tip_RemoveSpaces"] = "Remover todos os espaços, para chinês, japonês e coreano",
        ["Result_Placeholder"] = "O texto reconhecido aparece aqui e pode ser editado.",

        ["Btn_OpenFile"] = "Arquivo",
        ["Tip_OpenFile"] = "Abrir um arquivo de imagem (Ctrl+O)",
        ["Btn_Capture"] = "Captura",
        ["Tip_Capture"] = "Selecionar uma região da tela e reconhecê-la ({0}). Pressione Ctrl+Shift+R para a tela inteira.",
        ["Hotkey_Unavailable"] = "sem atalho — outro aplicativo ocupou os dois",
        ["Btn_Paste"] = "Área de transferência",
        ["Tip_Paste"] = "Carregar uma imagem ou texto da área de transferência (Ctrl+V)",
        ["Btn_History"] = "Histórico",
        ["Tip_History"] = "Resultados recentes",
        ["History_Empty"] = "Nada reconhecido ainda.",
        ["History_EmptyPreview"] = "(vazio)",
        ["Tip_Settings"] = "Opções",
        ["Settings_Header"] = "Opções",
        ["Setting_UiLanguage"] = "Idioma do aplicativo",
        ["Lang_SystemDefault"] = "Padrão do sistema",
        ["Setting_RepairNumbers"] = "Corrigir l e I dentro de números",
        ["Setting_RepairNumbers_Desc"] = "Os reconhecedores leem v1.6.5 como vl.6.5 com frequência. Com esta opção ativada, um l ou I vira 1 apenas onde há um separador e um dígito ao lado, então html5 e IPv6 ficam intactos. Desativada, a leitura do mecanismo é mantida exatamente como veio.",
        ["Setting_WatchClipboard"] = "Ler as imagens que eu copio",
        ["Setting_WatchClipboard_Desc"] = "Faça uma captura com Win+Shift+S e o Glyfo a lê na hora, colocando o texto na área de transferência no lugar da imagem, de modo que a próxima colagem seja o texto. Só imagens são lidas, nunca o texto copiado, e nada é enviado a lugar algum: tudo acontece neste dispositivo.",
        ["Common_On"] = "Ativado",
        ["Common_Off"] = "Desativado",
        ["Lang_Placeholder"] = "Idioma",
        ["Tip_OcrLanguage"] = "Idioma de reconhecimento, entre os pacotes de idioma instalados no Windows",
        ["Btn_Translate"] = "Traduzir",
        ["Tip_Translate"] = "Traduzir neste dispositivo — nada é enviado pela rede",
        ["Btn_Barcode"] = "Códigos",
        ["Tip_Barcode"] = "Ler códigos QR e códigos de barras na imagem",
        ["Btn_Recognize"] = "Reconhecer",
        ["Tip_Recognize"] = "Reconhecer o texto da imagem (F5)",

        ["Option_AutoAi"] = "Automático (Windows AI)",
        ["Option_AutoMulti"] = "Automático (vários idiomas · mais lento)",

        ["Status_Loaded"] = "{0} carregada.",
        ["Status_OpenFailed"] = "Não foi possível abrir a imagem: {0}",
        ["Status_ClipboardText"] = "Texto carregado da área de transferência.",
        ["Status_ClipboardEmpty"] = "A área de transferência não contém imagem nem texto.",
        ["Status_ClipboardFailed"] = "Não foi possível ler a área de transferência: {0}",
        ["Status_DropFailed"] = "Não foi possível usar o que foi solto: {0}",
        ["Status_ImageCopied"] = "Imagem copiada para a área de transferência.",
        ["Status_ImageCopyFailed"] = "Não foi possível copiar a imagem: {0}",
        ["Status_ImageSaved"] = "Imagem salva como {0}.",
        ["Status_ImageSaveFailed"] = "Não foi possível salvar a imagem: {0}",
        ["Status_Recognizing"] = "Reconhecendo…",
        ["Status_NoText"] = "{0} não encontrou texto nesta imagem.",
        ["Status_Done"] = "Concluído ({0}).",
        ["Status_DoneConfidence"] = "Concluído ({0}) · confiança média de {1}%.",
        ["Status_RecognizeFailed"] = "O reconhecimento falhou: {0}",
        ["Status_Scanning"] = "Procurando códigos QR e códigos de barras…",
        ["Status_NoBarcode"] = "Nenhum código QR ou de barras encontrado nesta imagem.",
        ["Status_BarcodeOne"] = "Um código {0} encontrado.",
        ["Status_BarcodeMany"] = "{0} códigos encontrados.",
        ["Status_ScanFailed"] = "A leitura falhou: {0}",
        ["Status_PdfFailed"] = "não foi possível ler este PDF: ele pode estar protegido por senha ou danificado",
        ["Status_LaunchFailed"] = "O Windows não encontrou nada para abrir isso.",
        ["Status_NothingToTranslate"] = "Não há texto para traduzir.",
        ["Status_Translating"] = "Traduzindo para {0} neste dispositivo…",
        ["Status_Translated"] = "Traduzido para {0}, neste dispositivo, sem acesso à rede.",
        ["Status_TranslateFailed"] = "A tradução falhou: {0}",
        ["Status_NothingToCopy"] = "Não há texto para copiar.",
        ["Status_TextCopied"] = "Texto copiado para a área de transferência.",
        ["Status_CopyFailed"] = "Não foi possível copiar o texto: {0}",
        ["Status_NothingToSpeak"] = "Não há texto para ler em voz alta.",
        ["Status_SpeakFailed"] = "Não foi possível ler o texto em voz alta: {0}",
        ["Status_HistoryLoaded"] = "Mostrando o resultado de {0}.",
        ["Status_NeedImage"] = "Carregue uma imagem primeiro.",
        ["Status_CaptureFailed"] = "A captura de tela falhou: {0}",
        ["Status_StartupBlockedByUser"] = "O Windows desativou a inicialização automática do Glyfo. Reative-a no Gerenciador de Tarefas, em Aplicativos de inicialização.",
        ["Status_StartupBlockedByPolicy"] = "Sua organização não permite que aplicativos sejam iniciados com o Windows.",
        ["Status_LanguagePackMissing"] = "O Windows não tem nenhum pacote de idioma de OCR instalado, então não há com o que reconhecer. Adicione o idioma que você precisa em Hora e idioma, depois Idioma e região.",
        ["Btn_OpenLanguageSettings"] = "Abrir as configurações de idioma",

        ["Tray_Open"] = "Abrir o Glyfo",
        ["Tray_CaptureRegion"] = "Capturar uma região",
        ["Tray_CaptureFullScreen"] = "Capturar a tela inteira",
        ["Tray_Exit"] = "Sair",
        ["Tray_Tooltip"] = "Glyfo — pressione {0} para capturar uma região",
        ["Toast_StartupTitle"] = "O Glyfo está em execução",
        ["Toast_StartupBody"] = "Pressione {0} para selecionar uma parte da tela e ler o texto nela. Ctrl+Shift+R captura a tela inteira.",
        ["Toast_DontRemind"] = "Não avisar de novo",
        ["Toast_MinimizedTitle"] = "O Glyfo continua em execução",
        ["Toast_MinimizedBody"] = "Pressione {0} a qualquer momento para capturar e reconhecer. Para fechá-lo de vez, clique com o botão direito no ícone dele na área de notificação e escolha Sair.",
        ["Toast_ExitApp"] = "Sair do Glyfo",
        ["Toast_ResultTitle"] = "Texto reconhecido",
        ["Toast_ResultCopied"] = "Copiado para a área de transferência.",
        ["Toast_OpenWindow"] = "Abrir a janela",
        ["Toast_NoTextTitle"] = "Nenhum texto encontrado",
        ["Toast_NoTextBody"] = "Não havia nada legível como texto nessa região.",
        ["Toast_FailedTitle"] = "Falha no reconhecimento",
        ["Toast_HotkeyUnavailableTitle"] = "O atalho de captura está ocupado",
        ["Toast_HotkeyUnavailableBody"] = "Outro aplicativo já o ocupa, então a captura de tela só está disponível pela janela e pelo ícone na área de notificação.",
        ["Setting_CloseToTray"] = "Continuar em execução ao fechar a janela",
        ["Setting_CloseToTray_Desc"] = "Quando isto está ativado, fechar a janela deixa o Glyfo em execução para que o atalho de captura continue funcionando, e o ícone dele permanece na área de notificação, onde Sair o fecha de vez. Quando está desativado, fechar a janela encerra o aplicativo.",
        ["Setting_Startup"] = "Iniciar com o Windows",
        ["Setting_Startup_Desc"] = "Quando ativado, o Glyfo inicia com o Windows e vai direto para a área de notificação, sem abrir janela, de modo que o atalho de captura funciona desde o login.",

        ["Source_Clipboard"] = "a imagem da área de transferência",
        ["Source_Dropped"] = "a imagem solta",
        ["Source_Shared"] = "a imagem compartilhada",
        ["Source_FullScreen"] = "Tela inteira",
        ["Source_Region"] = "Região da tela",
        ["Source_Codes"] = "{0} (códigos)",

        ["FileType_Image"] = "Imagem {0}",

        ["Region_Hint"] = "Arraste para selecionar uma área　·　Esc ou clique com o botão direito para cancelar",

        ["Err_NoLanguagePack"] = "O Windows não tem pacote de idioma de OCR instalado para este idioma. Adicione um em Hora e idioma, depois Idioma e região.",
        ["Err_TextTooLong"] = "O texto é longo demais para o modelo local. Traduza um trecho menor.",
        ["Err_ModelDeclined"] = "O modelo local recusou-se a traduzir este texto.",
        ["Err_TranslationFailed"] = "A tradução local não produziu resultado.",
        ["Btn_About"] = "Sobre o Glyfo",
        ["About_Title"] = "Sobre o Glyfo",
        ["About_Version"] = "Versão {0}",
        ["About_Tagline"] = "Lê o texto de qualquer imagem, neste dispositivo. Nada é enviado pela rede.",
        ["About_Rate"] = "Avaliar o Glyfo",
        ["About_WhatsNew"] = "Novidades",
        ["About_Source"] = "Código-fonte no GitHub",
        ["About_Privacy"] = "Política de privacidade",
        ["Common_Close"] = "Fechar",
        ["News_Title"] = "Novidades",
        ["News_120_1"] = "Faça uma captura com Win+Shift+S e o Glyfo a lê para você, deixando o texto na área de transferência. Fica desligado até você ativá-lo nas opções.",
        ["News_120_2"] = "Os PDFs agora abrem como imagens, uma página por vez.",
        ["News_120_3"] = "Links, endereços de e-mail e telefones encontrados no texto ganham um botão abaixo dele.",
        ["News_110_1"] = "Uma página Sobre, com a versão e links para o código-fonte e a política de privacidade.",
        ["News_110_2"] = "Você pode avaliar o Glyfo sem sair da janela.",
        ["News_110_3"] = "Estas notas, mostradas uma vez a cada versão nova.",
        ["News_110_4"] = "A captura agora também oferece a tela inteira e esconde a janela antes, para o Glyfo nunca aparecer na imagem.",
        ["Rate_Title"] = "O Glyfo está sendo útil?",
        ["Rate_Body"] = "Uma avaliação na Store é o que faz outras pessoas encontrarem o aplicativo. Leva só um instante.",
        ["Rate_Action"] = "Avaliar",
        ["Rate_Later"] = "Agora não",
    };
}
