using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> ZhHans = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · 未安装语言包",
        ["Engine_OneLanguage"] = "Windows OCR · 1 种语言",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} 种语言",
        ["Engine_OnDevice"] = "{0} · 本地运行",

        ["Preview_Placeholder"] = "把图片拖到这里，或使用下方的文件、截图、剪贴板",
        ["Btn_CopyImage"] = "复制",
        ["Tip_CopyImage"] = "复制图片到剪贴板",
        ["Btn_SaveImage"] = "保存",
        ["Tip_SaveImage"] = "图片另存为…",
        ["Btn_FitToWindow"] = "自适应",
        ["Tip_FitToWindow"] = "缩放到适合窗口",
        ["Tip_ActualSize"] = "实际像素大小",

        ["Voice_Placeholder"] = "语音",
        ["Tip_Voice"] = "朗读所用的语音",
        ["Tip_Speak"] = "朗读文本",
        ["Tip_StopSpeak"] = "停止朗读",
        ["Tip_CopyText"] = "复制文本（Ctrl+Shift+C）",
        ["Btn_RemoveLineBreaks"] = "去换行",
        ["Tip_RemoveLineBreaks"] = "把硬换行合并回段落",
        ["Btn_RemoveSpaces"] = "去空格",
        ["Tip_RemoveSpaces"] = "删除所有空格，适用于中日韩文本",
        ["Result_Placeholder"] = "识别出的文本显示在这里，可以直接编辑。",

        ["Btn_OpenFile"] = "文件",
        ["Tip_OpenFile"] = "打开图片文件（Ctrl+O）",
        ["Btn_Capture"] = "截图",
        ["Tip_Capture"] = "框选屏幕区域并识别（{0}）。按 Ctrl+Shift+R 截取整个屏幕。",
        ["Hotkey_Unavailable"] = "无快捷键，两个组合都被其他程序占用",
        ["Btn_Paste"] = "剪贴板",
        ["Tip_Paste"] = "从剪贴板载入图片或文本（Ctrl+V）",
        ["Btn_History"] = "历史",
        ["Tip_History"] = "最近的识别结果",
        ["History_Empty"] = "还没有识别记录。",
        ["History_EmptyPreview"] = "（空）",
        ["Tip_Settings"] = "选项",
        ["Settings_Header"] = "选项",
        ["Setting_UiLanguage"] = "界面语言",
        ["Lang_SystemDefault"] = "跟随系统",
        ["Setting_RepairNumbers"] = "修正数字中的 l 和 I",
        ["Setting_RepairNumbers_Desc"] = "识别引擎经常把 v1.6.5 读成 vl.6.5。开启后，只有当 l 或 I 旁边同时有分隔符和数字时才会改成 1，因此 html5 和 IPv6 不受影响。关闭后完全保留引擎的原始读数。",
        ["Common_On"] = "开",
        ["Common_Off"] = "关",
        ["Lang_Placeholder"] = "语言",
        ["Tip_OcrLanguage"] = "识别语言，来自 Windows 已安装的语言包",
        ["Btn_Translate"] = "翻译",
        ["Tip_Translate"] = "在本机翻译，不经过网络",
        ["Btn_Barcode"] = "条码",
        ["Tip_Barcode"] = "识别图中的二维码和条形码",
        ["Btn_Recognize"] = "识别",
        ["Tip_Recognize"] = "识别图片中的文字（F5）",

        ["Option_AutoAi"] = "自动检测（Windows AI）",
        ["Option_AutoMulti"] = "自动检测（多语言 · 较慢）",

        ["Status_Loaded"] = "已载入{0}。",
        ["Status_OpenFailed"] = "无法打开图片：{0}",
        ["Status_ClipboardText"] = "已从剪贴板载入文本。",
        ["Status_ClipboardEmpty"] = "剪贴板中既没有图片也没有文本。",
        ["Status_ClipboardFailed"] = "无法读取剪贴板：{0}",
        ["Status_DropFailed"] = "无法使用拖入的内容：{0}",
        ["Status_ImageCopied"] = "图片已复制到剪贴板。",
        ["Status_ImageCopyFailed"] = "无法复制图片：{0}",
        ["Status_ImageSaved"] = "图片已保存为 {0}。",
        ["Status_ImageSaveFailed"] = "无法保存图片：{0}",
        ["Status_Recognizing"] = "正在识别…",
        ["Status_NoText"] = "{0} 没有在这张图片中找到文字。",
        ["Status_Done"] = "完成（{0}）。",
        ["Status_DoneConfidence"] = "完成（{0}）· 平均置信度 {1}%。",
        ["Status_RecognizeFailed"] = "识别失败：{0}",
        ["Status_Scanning"] = "正在查找二维码和条形码…",
        ["Status_NoBarcode"] = "这张图片中没有二维码或条形码。",
        ["Status_BarcodeOne"] = "找到 1 个 {0} 码。",
        ["Status_BarcodeMany"] = "找到 {0} 个码。",
        ["Status_ScanFailed"] = "扫描失败：{0}",
        ["Status_NothingToTranslate"] = "没有可翻译的文本。",
        ["Status_Translating"] = "正在本机翻译成{0}…",
        ["Status_Translated"] = "已在本机翻译成{0}，全程不联网。",
        ["Status_TranslateFailed"] = "翻译失败：{0}",
        ["Status_NothingToCopy"] = "没有可复制的文本。",
        ["Status_TextCopied"] = "文本已复制到剪贴板。",
        ["Status_CopyFailed"] = "无法复制文本：{0}",
        ["Status_NothingToSpeak"] = "没有可朗读的文本。",
        ["Status_SpeakFailed"] = "无法朗读：{0}",
        ["Status_HistoryLoaded"] = "正在显示 {0} 的识别结果。",
        ["Status_NeedImage"] = "请先载入一张图片。",
        ["Status_CaptureFailed"] = "屏幕截取失败：{0}",
        ["Status_StartupBlockedByUser"] = "Windows 已禁止 Glyfo 开机自启。请在任务管理器的启动应用中重新开启。",
        ["Status_StartupBlockedByPolicy"] = "你所在的组织不允许应用随 Windows 启动。",
        ["Status_LanguagePackMissing"] = "Windows 尚未安装任何 OCR 语言包，没有可用的识别语言。请在“时间和语言 → 语言和区域”中添加所需语言。",
        ["Btn_OpenLanguageSettings"] = "打开语言设置",

        ["Tray_Open"] = "打开 Glyfo",
        ["Tray_CaptureRegion"] = "截取区域",
        ["Tray_CaptureFullScreen"] = "截取整个屏幕",
        ["Tray_Exit"] = "退出",
        ["Tray_Tooltip"] = "Glyfo — 按 {0} 截取区域",
        ["Toast_StartupTitle"] = "Glyfo 正在运行",
        ["Toast_StartupBody"] = "按 {0} 框选屏幕区域并识别其中的文字；按 Ctrl+Shift+R 截取整个屏幕。",
        ["Toast_DontRemind"] = "不再提醒",
        ["Toast_MinimizedTitle"] = "Glyfo 仍在运行",
        ["Toast_MinimizedBody"] = "随时按 {0} 即可截图识别。要彻底退出，请右键单击通知区域的图标并选择“退出”。",
        ["Toast_ExitApp"] = "退出 Glyfo",
        ["Toast_ResultTitle"] = "识别完成",
        ["Toast_ResultCopied"] = "已复制到剪贴板。",
        ["Toast_OpenWindow"] = "打开窗口",
        ["Toast_NoTextTitle"] = "未发现文字",
        ["Toast_NoTextBody"] = "该区域中没有可以识别为文字的内容。",
        ["Toast_FailedTitle"] = "识别失败",
        ["Toast_HotkeyUnavailableTitle"] = "截图快捷键被占用",
        ["Toast_HotkeyUnavailableBody"] = "其他程序已经占用了它，因此只能从窗口或通知区域的图标发起截图。",
        ["Setting_CloseToTray"] = "关闭窗口后继续运行",
        ["Setting_CloseToTray_Desc"] = "开启后，关闭窗口不会退出 Glyfo，截图快捷键继续有效，图标留在通知区域，在那里选择“退出”才会彻底关闭；关闭此项后，关闭窗口即退出程序。",
        ["Setting_Startup"] = "开机自启",
        ["Setting_Startup_Desc"] = "开启后，Glyfo 随 Windows 一起启动，不显示窗口而直接进入通知区域，登录后截图快捷键立即可用。",

        ["Source_Clipboard"] = "剪贴板图片",
        ["Source_Dropped"] = "拖入的图片",
        ["Source_Shared"] = "共享的图片",
        ["Source_FullScreen"] = "整个屏幕",
        ["Source_Region"] = "屏幕区域",
        ["Source_Codes"] = "{0}（条码）",

        ["FileType_Image"] = "{0} 图片",

        ["Region_Hint"] = "拖动鼠标框选区域　·　Esc 或右键取消",

        ["Err_NoLanguagePack"] = "Windows 未安装该语言的 OCR 语言包。请在“时间和语言 → 语言和区域”中添加。",
        ["Err_TextTooLong"] = "文本超出了本地模型的处理长度，请分段翻译。",
        ["Err_ModelDeclined"] = "本地模型拒绝翻译这段文本。",
        ["Err_TranslationFailed"] = "本地翻译没有返回结果。",
    };
}
