using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Fil = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · walang language pack",
        ["Engine_OneLanguage"] = "Windows OCR · 1 wika",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} wika",
        ["Engine_OnDevice"] = "{0} · sa device",

        ["Preview_Placeholder"] = "Ihulog dito ang isang larawan, o gamitin ang File, Kuha, o Clipboard sa ibaba",
        ["Btn_CopyImage"] = "Kopyahin",
        ["Tip_CopyImage"] = "Kopyahin ang larawan sa clipboard",
        ["Btn_SaveImage"] = "I-save",
        ["Tip_SaveImage"] = "I-save ang larawan bilang…",
        ["Btn_FitToWindow"] = "Ikasya",
        ["Tip_FitToWindow"] = "I-zoom para kumasya sa window",
        ["Tip_ActualSize"] = "Aktuwal na laki sa pixel",
        ["Tip_PdfPrev"] = "Nakaraang pahina",
        ["Tip_PdfNext"] = "Susunod na pahina",
        ["Tip_PdfAll"] = "Basahin ang lahat ng pahina",
        ["Action_Open"] = "Buksan ang link",
        ["Action_Mail"] = "Sulatan si",
        ["Action_Call"] = "Tawagan ang",
        ["Action_Search"] = "Hanapin sa web ang",

        ["Voice_Placeholder"] = "Boses",
        ["Tip_Voice"] = "Boses na ginagamit sa pagbabasa nang malakas",
        ["Tip_Speak"] = "Basahin nang malakas ang teksto",
        ["Tip_StopSpeak"] = "Itigil ang pagbabasa",
        ["Tip_CopyText"] = "Kopyahin ang teksto (Ctrl+Shift+C)",
        ["Tip_SaveText"] = "I-save ang teksto sa isang file (Ctrl+S)",
        ["Btn_RemoveLineBreaks"] = "Pagdugtungin",
        ["Tip_RemoveLineBreaks"] = "Pagdugtungin muli ang mga hating linya bilang talata",
        ["Btn_RemoveSpaces"] = "Walang espasyo",
        ["Tip_RemoveSpaces"] = "Alisin ang lahat ng espasyo — para sa Tsino, Hapon at Koreano",
        ["Result_Placeholder"] = "Lilitaw dito ang nakilalang teksto at maaari itong i-edit.",

        ["Btn_OpenFile"] = "File",
        ["Tip_OpenFile"] = "Magbukas ng file ng larawan (Ctrl+O)",
        ["Btn_Capture"] = "Kuha",
        ["Tip_Capture"] = "Pumili ng bahagi ng screen at kilalanin ito ({0}). Pindutin ang Ctrl+Shift+R para sa buong screen.",
        ["Hotkey_Unavailable"] = "walang shortcut — kapwa nakuha na ng ibang app",
        ["Btn_Paste"] = "Clipboard",
        ["Tip_Paste"] = "Kunin ang larawan o teksto mula sa clipboard (Ctrl+V)",
        ["Btn_History"] = "Kasaysayan",
        ["Tip_History"] = "Mga kamakailang resulta",
        ["History_Empty"] = "Wala pang nakikilala.",
        ["History_EmptyPreview"] = "(walang laman)",
        ["History_SearchPlaceholder"] = "Maghanap sa mga resulta",
        ["History_NoMatch"] = "Walang resultang tumutugma.",
        ["History_Off"] = "Naka-off ang kasaysayan sa Mga Opsyon.",
        ["History_Clear"] = "I-clear ang kasaysayan",
        ["History_CopyItem"] = "Kopyahin ang tekstong ito",
        ["History_DeleteItem"] = "Tanggalin ang entry na ito",
        ["Tip_Settings"] = "Mga opsyon",
        ["Settings_Header"] = "Mga opsyon",
        ["Setting_UiLanguage"] = "Wika ng app",
        ["Lang_SystemDefault"] = "Default ng system",
        ["Setting_RepairNumbers"] = "Ayusin ang l at I sa loob ng mga numero",
        ["Setting_RepairNumbers_Desc"] = "Madalas basahin ng mga recognizer ang v1.6.5 bilang vl.6.5. Kapag naka-on ito, nagiging 1 lamang ang l o I kung may katabing pananda at digit, kaya hindi nagagalaw ang html5 at IPv6. Kapag naka-off, mananatili ang pagbasa ng makina nang eksakto kung paano ito dumating.",
        ["Setting_WatchClipboard"] = "Basahin ang mga larawang kinokopya ko",
        ["Setting_WatchClipboard_Desc"] = "Kumuha ng screenshot gamit ang Win+Shift+S at agad itong babasahin ng Glyfo, saka ilalagay ang teksto sa clipboard kapalit ng larawan, kaya teksto na ang susunod mong ipe-paste. Mga larawan lang ang binabasa, hindi kailanman ang kinopyang teksto, at walang ipinapadala kahit saan — lahat ay nangyayari sa device na ito.",
        ["Setting_KeepHistory"] = "Panatilihin ang kasaysayan sa pagitan ng mga session",
        ["Setting_KeepHistory_Desc"] = "Pinapanatili ang huling 200 resulta para naroon pa rin ang mga ito pagkatapos mag-restart. Ang teksto lang ang nakaimbak, hindi kailanman ang mga larawan, sa isang file na pag-aari ng Glyfo sa device na ito. Kapag ito ay ini-off, buburahin ang file na iyon at agad na mauubos ang listahan.",
        ["Common_On"] = "On",
        ["Common_Off"] = "Off",
        ["Lang_Placeholder"] = "Wika",
        ["Tip_OcrLanguage"] = "Wika ng pagkilala, mula sa mga language pack na naka-install sa Windows",
        ["Btn_Translate"] = "Isalin",
        ["Tip_Translate"] = "Isalin sa device na ito — walang ipinapadala sa network",
        ["Btn_Barcode"] = "Mga code",
        ["Tip_Barcode"] = "Basahin ang mga QR code at barcode sa larawan",
        ["Btn_Recognize"] = "Kilalanin",
        ["Tip_Recognize"] = "Kilalanin ang teksto sa larawan (F5)",

        ["Option_AutoAi"] = "Awtomatiko (Windows AI)",
        ["Option_AutoMulti"] = "Awtomatiko (maraming wika · mas mabagal)",

        ["Status_Loaded"] = "Na-load ang {0}.",
        ["Status_OpenFailed"] = "Hindi mabuksan ang larawan: {0}",
        ["Status_ClipboardText"] = "Na-load ang teksto mula sa clipboard.",
        ["Status_ClipboardEmpty"] = "Walang larawan ni teksto ang clipboard.",
        ["Status_ClipboardFailed"] = "Hindi mabasa ang clipboard: {0}",
        ["Status_DropFailed"] = "Hindi magamit ang inihulog: {0}",
        ["Status_ImageCopied"] = "Nakopya ang larawan sa clipboard.",
        ["Status_ImageCopyFailed"] = "Hindi makopya ang larawan: {0}",
        ["Status_ImageSaved"] = "Na-save ang larawan bilang {0}.",
        ["Status_ImageSaveFailed"] = "Hindi ma-save ang larawan: {0}",
        ["Status_Recognizing"] = "Kinikilala…",
        ["Status_NoText"] = "Walang natagpuang teksto ang {0} sa larawang ito.",
        ["Status_Done"] = "Tapos na ({0}).",
        ["Status_DoneConfidence"] = "Tapos na ({0}) · katiyakan sa karaniwan {1}%.",
        ["Status_RecognizeFailed"] = "Nabigo ang pagkilala: {0}",
        ["Status_Scanning"] = "Naghahanap ng mga QR code at barcode…",
        ["Status_NoBarcode"] = "Walang natagpuang QR code o barcode sa larawang ito.",
        ["Status_BarcodeOne"] = "May natagpuang isang {0} code.",
        ["Status_BarcodeMany"] = "May natagpuang {0} code.",
        ["Status_ScanFailed"] = "Nabigo ang paghahanap: {0}",
        ["Status_PdfFailed"] = "hindi nabasa ang PDF na ito — maaaring may password ito o sira",
        ["Status_LaunchFailed"] = "Walang nakitang pambukas ang Windows para diyan.",
        ["Status_NothingToTranslate"] = "Walang tekstong maisasalin.",
        ["Status_Translating"] = "Isinasalin sa {0} sa device na ito…",
        ["Status_Translated"] = "Naisalin sa {0}, sa device na ito, nang walang koneksyon sa network.",
        ["Status_TranslateFailed"] = "Nabigo ang pagsasalin: {0}",
        ["Status_NothingToCopy"] = "Walang tekstong makokopya.",
        ["Status_NothingToSave"] = "Walang tekstong mase-save.",
        ["Status_TextSaved"] = "Na-save ang teksto bilang {0}.",
        ["Status_TextSaveFailed"] = "Hindi na-save ang teksto: {0}",
        ["Status_TextCopied"] = "Nakopya ang teksto sa clipboard.",
        ["Status_CopyFailed"] = "Hindi makopya ang teksto: {0}",
        ["Status_NothingToSpeak"] = "Walang tekstong mababasa nang malakas.",
        ["Status_SpeakFailed"] = "Hindi mabasa nang malakas ang teksto: {0}",
        ["Status_HistoryLoaded"] = "Ipinapakita ang resulta mula {0}.",
        ["Status_HistoryCleared"] = "Na-clear ang kasaysayan.",
        ["Status_NeedImage"] = "Mag-load muna ng larawan.",
        ["Status_CaptureFailed"] = "Nabigo ang pagkuha ng screen: {0}",
        ["Status_StartupBlockedByUser"] = "Naka-off ng Windows ang pag-start ng Glyfo. I-on itong muli sa Task Manager, sa Startup apps.",
        ["Status_StartupBlockedByPolicy"] = "Hindi pinapayagan ng iyong organisasyon na mag-start ang mga app kasabay ng Windows.",
        ["Status_LanguagePackMissing"] = "Walang naka-install na OCR language pack sa Windows, kaya walang magagamit sa pagkilala. Idagdag ang wikang kailangan mo sa Oras at wika, saka Wika at rehiyon.",
        ["Btn_OpenLanguageSettings"] = "Buksan ang mga setting ng wika",

        ["Tray_Open"] = "Buksan ang Glyfo",
        ["Tray_CaptureRegion"] = "Kumuha ng bahagi",
        ["Tray_CaptureFullScreen"] = "Kunan ang buong screen",
        ["Tray_Exit"] = "Lumabas",
        ["Tray_Tooltip"] = "Glyfo — pindutin ang {0} para kumuha ng bahagi",
        ["Toast_StartupTitle"] = "Tumatakbo ang Glyfo",
        ["Toast_StartupBody"] = "Pindutin ang {0} para pumili ng bahagi ng screen at basahin ang teksto rito. Ang Ctrl+Shift+R ay kumukuha ng buong screen.",
        ["Toast_DontRemind"] = "Huwag nang ipaalala",
        ["Toast_MinimizedTitle"] = "Tumatakbo pa rin ang Glyfo",
        ["Toast_MinimizedBody"] = "Pindutin ang {0} anumang oras para kumuha at kilalanin ang teksto. Para isara ito nang tuluyan, i-right click ang icon nito sa notification area at piliin ang Lumabas.",
        ["Toast_ExitApp"] = "Lumabas sa Glyfo",
        ["Toast_ResultTitle"] = "Nakilala ang teksto",
        ["Toast_ResultCopied"] = "Nakopya sa clipboard.",
        ["Toast_OpenWindow"] = "Buksan ang window",
        ["Toast_NoTextTitle"] = "Walang natagpuang teksto",
        ["Toast_NoTextBody"] = "Walang mababasa bilang teksto sa bahaging iyon.",
        ["Toast_FailedTitle"] = "Nabigo ang pagkilala",
        ["Toast_HotkeyUnavailableTitle"] = "Ginagamit na ang shortcut sa pagkuha",
        ["Toast_HotkeyUnavailableBody"] = "Nauna nang kinuha ito ng ibang app, kaya sa window at sa icon sa notification area na lang maaaring kumuha ng screen.",
        ["Setting_CloseToTray"] = "Manatiling tumatakbo kapag isinara ang window",
        ["Setting_CloseToTray_Desc"] = "Kapag naka-on ito, patuloy na tumatakbo ang Glyfo kahit isara mo ang window, kaya gumagana pa rin ang shortcut sa pagkuha, at nananatili ang icon nito sa notification area kung saan tuluyan itong isinasara ng Lumabas. Kapag naka-off, ang pagsasara ng window ang nagtatapos sa app.",
        ["Setting_Startup"] = "Mag-start kasabay ng Windows",
        ["Setting_Startup_Desc"] = "Kapag naka-on ito, magsisimula ang Glyfo kasabay ng Windows at diretsong pupunta sa notification area nang hindi nagbubukas ng window, kaya gumagana na ang shortcut sa pagkuha mula sa sandaling mag-sign in ka.",

        ["Source_Clipboard"] = "larawan mula sa clipboard",
        ["Source_Dropped"] = "inihulog na larawan",
        ["Source_Shared"] = "ang ibinahaging larawan",
        ["Source_FullScreen"] = "Buong screen",
        ["Source_Region"] = "Bahagi ng screen",
        ["Source_Codes"] = "{0} (mga code)",
        ["Source_Batch"] = "{0} na file",
        ["Source_PdfAll"] = "{0}, lahat ng pahina",

        ["FileType_Image"] = "Larawang {0}",
        ["FileType_Text"] = "Payak na teksto",
        ["FileType_Markdown"] = "Markdown",
        ["Batch_Title"] = "Binabasa ang ilang file",
        ["Batch_Progress"] = "{0} sa {1}",
        ["Batch_DoneAll"] = "Nabasa ang {0}.",
        ["Batch_Cancelled"] = "Huminto pagkatapos ng {0} sa {1}.",
        ["Batch_ItemFailed"] = "Hindi mabasa: {0}",
        ["Batch_ItemEmpty"] = "(walang teksto)",
        ["Batch_Save"] = "I-save…",
        ["Batch_CopyAll"] = "Kopyahin lahat",
        ["Batch_Separate"] = "I-save ang bawat isa bilang sarili nitong file",
        ["Batch_SavedFolder"] = "Na-save ang {0} na file sa {1}.",
        ["Batch_TooLongForBox"] = "Nabasa ang {0} na item. Masyadong mahaba ang teksto para ipakita rito — nasa file na na-save mo ito.",

        ["Region_Hint"] = "Mag-drag para pumili ng bahagi　·　Esc o kanang pag-click para kanselahin",

        ["Err_NoLanguagePack"] = "Walang naka-install na OCR language pack ang Windows para sa wikang ito. Magdagdag ng isa sa Oras at wika, saka Wika at rehiyon.",
        ["Err_TextTooLong"] = "Masyadong mahaba ang teksto para sa modelong nasa device. Magsalin ng mas maikling bahagi.",
        ["Err_ModelDeclined"] = "Tumanggi ang modelong nasa device na isalin ang tekstong ito.",
        ["Err_TranslationFailed"] = "Walang naibigay na resulta ang pagsasalin sa device.",
        ["Btn_About"] = "Tungkol sa Glyfo",
        ["About_Title"] = "Tungkol sa Glyfo",
        ["About_Version"] = "Bersyon {0}",
        ["About_Tagline"] = "Binabasa ang teksto sa anumang larawan, dito mismo sa device. Walang ipinapadala sa network.",
        ["About_Rate"] = "I-rate ang Glyfo",
        ["About_WhatsNew"] = "Ano ang bago",
        ["About_Source"] = "Source code sa GitHub",
        ["About_Privacy"] = "Patakaran sa privacy",
        ["Common_Close"] = "Isara",
        ["Common_Cancel"] = "Kanselahin",
        ["News_Title"] = "Ano ang bago",
        ["News_130_1"] = "Nabubuhay na ngayon ang kasaysayan pagkatapos mag-restart, at may kahon na para hanapin ito. Teksto lang ang itinatago — sa Mga Opsyon maaari itong ubusin o i-off.",
        ["News_130_2"] = "Ini-save ng Ctrl+S ang nakilalang teksto bilang payak na teksto o Markdown na file.",
        ["News_130_3"] = "Magbukas o mag-drop ng ilang file nang sabay, o basahin ang buong PDF, at i-save ang lahat bilang isang file o isa bawat item.",
        ["News_120_1"] = "Kumuha ng screenshot gamit ang Win+Shift+S at babasahin ito ng Glyfo para sa iyo, saka iiwan ang teksto sa clipboard. Naka-off hanggang buksan mo ito sa Mga Opsyon.",
        ["News_120_2"] = "Nabubuksan na ang PDF gaya ng larawan, isang pahina sa bawat pagkakataon.",
        ["News_120_3"] = "Ang mga link, email address at numero ng telepono sa teksto ay binibigyan ng button sa ilalim nito.",
        ["News_110_1"] = "Isang pahinang Tungkol sa, kasama ang bersyon at mga link sa source code at patakaran sa privacy.",
        ["News_110_2"] = "Puwede mong i-rate ang Glyfo nang hindi umaalis sa window.",
        ["News_110_3"] = "Ang mga tala na ito, na lumalabas nang isang beses sa bawat bagong bersyon.",
        ["News_110_4"] = "Puwede nang kunin ang buong screen, at itinatago muna ang window kaya hindi na napapasama ang Glyfo sa larawan.",
        ["Rate_Title"] = "Nakakatulong ba ang Glyfo?",
        ["Rate_Body"] = "Ang rating sa Store ang paraan para makita ito ng iba. Sandali lang ito.",
        ["Rate_Action"] = "I-rate",
        ["Rate_Later"] = "Hindi muna",
    };
}
