using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Nb = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · ingen språkpakke",
        ["Engine_OneLanguage"] = "Windows OCR · 1 språk",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} språk",
        ["Engine_OnDevice"] = "{0} · på enheten",

        ["Preview_Placeholder"] = "Slipp et bilde her, eller bruk Fil, Skjermklipp eller Utklippstavle nedenfor",
        ["Btn_CopyImage"] = "Kopier",
        ["Tip_CopyImage"] = "Kopier bildet til utklippstavlen",
        ["Btn_SaveImage"] = "Lagre",
        ["Tip_SaveImage"] = "Lagre bildet som…",
        ["Btn_FitToWindow"] = "Tilpass",
        ["Tip_FitToWindow"] = "Zoom slik at bildet passer i vinduet",
        ["Tip_ActualSize"] = "Faktisk pikselstørrelse",

        ["Voice_Placeholder"] = "Stemme",
        ["Tip_Voice"] = "Stemmen som brukes til opplesing",
        ["Tip_Speak"] = "Les opp teksten",
        ["Tip_StopSpeak"] = "Stopp opplesingen",
        ["Tip_CopyText"] = "Kopier teksten (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Slå sammen",
        ["Tip_RemoveLineBreaks"] = "Slå harde linjeskift sammen til avsnitt igjen",
        ["Btn_RemoveSpaces"] = "Uten mellomrom",
        ["Tip_RemoveSpaces"] = "Fjern alle mellomrom — for kinesisk, japansk og koreansk",
        ["Result_Placeholder"] = "Den gjenkjente teksten vises her og kan redigeres.",

        ["Btn_OpenFile"] = "Fil",
        ["Tip_OpenFile"] = "Åpne en bildefil (Ctrl+O)",
        ["Btn_Capture"] = "Skjermklipp",
        ["Tip_Capture"] = "Merk et skjermområde og gjenkjenn det ({0}). Trykk Ctrl+Shift+R for hele skjermen.",
        ["Hotkey_Unavailable"] = "ingen hurtigtast — en annen app har tatt begge",
        ["Btn_Paste"] = "Utklippstavle",
        ["Tip_Paste"] = "Hent et bilde eller tekst fra utklippstavlen (Ctrl+V)",
        ["Btn_History"] = "Logg",
        ["Tip_History"] = "Nylige resultater",
        ["History_Empty"] = "Ingenting er gjenkjent ennå.",
        ["History_EmptyPreview"] = "(tom)",
        ["Tip_Settings"] = "Alternativer",
        ["Settings_Header"] = "Alternativer",
        ["Setting_UiLanguage"] = "Språk i appen",
        ["Lang_SystemDefault"] = "Systemstandard",
        ["Setting_RepairNumbers"] = "Rett l og I inni tall",
        ["Setting_RepairNumbers_Desc"] = "Gjenkjennere leser jevnlig v1.6.5 som vl.6.5. Når dette er på, blir en l eller I bare til 1 der det står et skilletegn og et siffer ved siden av, slik at html5 og IPv6 får være i fred. Når det er av, beholdes motorens lesning nøyaktig slik den kom.",
        ["Common_On"] = "På",
        ["Common_Off"] = "Av",
        ["Lang_Placeholder"] = "Språk",
        ["Tip_OcrLanguage"] = "Gjenkjenningsspråk, blant språkpakkene Windows har installert",
        ["Btn_Translate"] = "Oversett",
        ["Tip_Translate"] = "Oversett på denne enheten — ingenting sendes over nettverket",
        ["Btn_Barcode"] = "Koder",
        ["Tip_Barcode"] = "Les QR-koder og strekkoder i bildet",
        ["Btn_Recognize"] = "Gjenkjenn",
        ["Tip_Recognize"] = "Gjenkjenn teksten i bildet (F5)",

        ["Option_AutoAi"] = "Automatisk (Windows AI)",
        ["Option_AutoMulti"] = "Automatisk (flere språk · tregere)",

        ["Status_Loaded"] = "{0} lastet inn.",
        ["Status_OpenFailed"] = "Kunne ikke åpne bildet: {0}",
        ["Status_ClipboardText"] = "Tekst hentet fra utklippstavlen.",
        ["Status_ClipboardEmpty"] = "Utklippstavlen inneholder verken bilde eller tekst.",
        ["Status_ClipboardFailed"] = "Kunne ikke lese utklippstavlen: {0}",
        ["Status_DropFailed"] = "Kunne ikke bruke det som ble sluppet: {0}",
        ["Status_ImageCopied"] = "Bildet er kopiert til utklippstavlen.",
        ["Status_ImageCopyFailed"] = "Kunne ikke kopiere bildet: {0}",
        ["Status_ImageSaved"] = "Bildet er lagret som {0}.",
        ["Status_ImageSaveFailed"] = "Kunne ikke lagre bildet: {0}",
        ["Status_Recognizing"] = "Gjenkjenner…",
        ["Status_NoText"] = "{0} fant ingen tekst i dette bildet.",
        ["Status_Done"] = "Ferdig ({0}).",
        ["Status_DoneConfidence"] = "Ferdig ({0}) · gjennomsnittlig sikkerhet {1} %.",
        ["Status_RecognizeFailed"] = "Gjenkjenningen mislyktes: {0}",
        ["Status_Scanning"] = "Søker etter QR-koder og strekkoder…",
        ["Status_NoBarcode"] = "Fant ingen QR-kode eller strekkode i dette bildet.",
        ["Status_BarcodeOne"] = "Fant én {0}-kode.",
        ["Status_BarcodeMany"] = "Fant {0} koder.",
        ["Status_ScanFailed"] = "Søket mislyktes: {0}",
        ["Status_NothingToTranslate"] = "Det er ingen tekst å oversette.",
        ["Status_Translating"] = "Oversetter til {0} på denne enheten…",
        ["Status_Translated"] = "Oversatt til {0}, på denne enheten, uten nettverkstilgang.",
        ["Status_TranslateFailed"] = "Oversettelsen mislyktes: {0}",
        ["Status_NothingToCopy"] = "Det er ingen tekst å kopiere.",
        ["Status_TextCopied"] = "Teksten er kopiert til utklippstavlen.",
        ["Status_CopyFailed"] = "Kunne ikke kopiere teksten: {0}",
        ["Status_NothingToSpeak"] = "Det er ingen tekst å lese opp.",
        ["Status_SpeakFailed"] = "Kunne ikke lese opp teksten: {0}",
        ["Status_HistoryLoaded"] = "Viser resultatet fra {0}.",
        ["Status_NeedImage"] = "Last inn et bilde først.",
        ["Status_CaptureFailed"] = "Skjermbildet mislyktes: {0}",
        ["Status_StartupBlockedByUser"] = "Windows har slått av automatisk oppstart for Glyfo. Slå den på igjen i Oppgavebehandling under Oppstartsapper.",
        ["Status_StartupBlockedByPolicy"] = "Organisasjonen din tillater ikke at apper starter sammen med Windows.",
        ["Status_LanguagePackMissing"] = "Windows har ingen OCR-språkpakke installert, så det finnes ingenting å gjenkjenne med. Legg til språket du trenger under Tid og språk, deretter Språk og område.",
        ["Btn_OpenLanguageSettings"] = "Åpne språkinnstillingene",

        ["Tray_Open"] = "Åpne Glyfo",
        ["Tray_CaptureRegion"] = "Ta et område",
        ["Tray_CaptureFullScreen"] = "Ta hele skjermen",
        ["Tray_Exit"] = "Avslutt",
        ["Tray_Tooltip"] = "Glyfo — trykk {0} for å ta et område",
        ["Toast_StartupTitle"] = "Glyfo kjører",
        ["Toast_StartupBody"] = "Trykk {0} for å merke et område av skjermen og lese teksten i det. Ctrl+Shift+R tar hele skjermen.",
        ["Toast_DontRemind"] = "Ikke minn meg på det igjen",
        ["Toast_MinimizedTitle"] = "Glyfo kjører fortsatt",
        ["Toast_MinimizedBody"] = "Trykk {0} når som helst for å ta et bilde og gjenkjenne teksten. Høyreklikk ikonet i systemstatusfeltet og velg Avslutt for å lukke programmet helt.",
        ["Toast_ExitApp"] = "Avslutt Glyfo",
        ["Toast_ResultTitle"] = "Tekst gjenkjent",
        ["Toast_ResultCopied"] = "Kopiert til utklippstavlen.",
        ["Toast_OpenWindow"] = "Åpne vinduet",
        ["Toast_NoTextTitle"] = "Fant ingen tekst",
        ["Toast_NoTextBody"] = "Det var ingenting i det området som kunne leses som tekst.",
        ["Toast_FailedTitle"] = "Gjenkjenningen mislyktes",
        ["Toast_HotkeyUnavailableTitle"] = "Hurtigtasten er opptatt",
        ["Toast_HotkeyUnavailableBody"] = "En annen app har den allerede, så skjermbilder kan bare tas fra vinduet og fra ikonet i systemstatusfeltet.",
        ["Setting_CloseToTray"] = "Fortsett å kjøre når vinduet lukkes",
        ["Setting_CloseToTray_Desc"] = "Når dette er på, fortsetter Glyfo å kjøre etter at du lukker vinduet, slik at hurtigtasten fortsatt virker, og ikonet blir liggende i systemstatusfeltet, der Avslutt lukker programmet helt. Når det er av, avsluttes appen når vinduet lukkes.",
        ["Setting_Startup"] = "Start sammen med Windows",
        ["Setting_Startup_Desc"] = "Når dette er på, starter Glyfo sammen med Windows og går rett til varslingsområdet uten å åpne et vindu, slik at snarveien for skjermbilde virker fra du logger på.",

        ["Source_Clipboard"] = "bildet fra utklippstavlen",
        ["Source_Dropped"] = "bildet som ble sluppet",
        ["Source_Shared"] = "det delte bildet",
        ["Source_FullScreen"] = "Hele skjermen",
        ["Source_Region"] = "Skjermområde",
        ["Source_Codes"] = "{0} (koder)",

        ["FileType_Image"] = "{0}-bilde",

        ["Region_Hint"] = "Dra for å merke et område　·　Esc eller høyreklikk avbryter",

        ["Err_NoLanguagePack"] = "Windows har ingen OCR-språkpakke installert for dette språket. Legg til en under Tid og språk, deretter Språk og område.",
        ["Err_TextTooLong"] = "Teksten er for lang for modellen på enheten. Oversett en mindre del.",
        ["Err_ModelDeclined"] = "Modellen på enheten avslo å oversette denne teksten.",
        ["Err_TranslationFailed"] = "Oversettelsen på enheten ga ingen resultat.",
    };
}
