using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Ro = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR Windows · niciun pachet de limbă",
        ["Engine_OneLanguage"] = "OCR Windows · 1 limbă",
        ["Engine_ManyLanguages"] = "OCR Windows · {0} limbi",
        ["Engine_OnDevice"] = "{0} · pe dispozitiv",

        ["Preview_Placeholder"] = "Trage o imagine aici sau folosește Fișier, Captură ori Clipboard mai jos",
        ["Btn_CopyImage"] = "Copiază",
        ["Tip_CopyImage"] = "Copiază imaginea în clipboard",
        ["Btn_SaveImage"] = "Salvează",
        ["Tip_SaveImage"] = "Salvează imaginea ca…",
        ["Btn_FitToWindow"] = "Încadrează",
        ["Tip_FitToWindow"] = "Potrivește dimensiunea la fereastră",
        ["Tip_ActualSize"] = "Dimensiunea reală în pixeli",
        ["Tip_PdfPrev"] = "Pagina anterioară",
        ["Tip_PdfNext"] = "Pagina următoare",
        ["Tip_PdfAll"] = "Citește toate paginile",
        ["Action_Open"] = "Deschide linkul",
        ["Action_Mail"] = "Scrie la",
        ["Action_Call"] = "Sună la",
        ["Action_Search"] = "Caută pe web",

        ["Voice_Placeholder"] = "Voce",
        ["Tip_Voice"] = "Vocea folosită pentru citirea cu voce tare",
        ["Tip_Speak"] = "Citește textul cu voce tare",
        ["Tip_StopSpeak"] = "Oprește citirea",
        ["Tip_CopyText"] = "Copiază textul (Ctrl+Shift+C)",
        ["Tip_SaveText"] = "Salvează textul într-un fișier (Ctrl+S)",
        ["Btn_RemoveLineBreaks"] = "Fără rupturi",
        ["Tip_RemoveLineBreaks"] = "Unește la loc întreruperile de rând în paragrafe",
        ["Btn_RemoveSpaces"] = "Fără spații",
        ["Tip_RemoveSpaces"] = "Elimină toate spațiile — pentru chineză, japoneză și coreeană",
        ["Result_Placeholder"] = "Textul recunoscut apare aici și poate fi editat.",

        ["Btn_OpenFile"] = "Fișier",
        ["Tip_OpenFile"] = "Deschide un fișier imagine (Ctrl+O)",
        ["Btn_Capture"] = "Captură",
        ["Tip_Capture"] = "Selectează o zonă de pe ecran și recunoaște-o ({0}). Apasă Ctrl+Shift+R pentru tot ecranul.",
        ["Hotkey_Unavailable"] = "nicio scurtătură — altă aplicație le-a ocupat pe amândouă",
        ["Btn_Paste"] = "Clipboard",
        ["Tip_Paste"] = "Încarcă o imagine sau un text din clipboard (Ctrl+V)",
        ["Btn_History"] = "Istoric",
        ["Tip_History"] = "Rezultate recente",
        ["History_Empty"] = "Nu s-a recunoscut încă nimic.",
        ["History_EmptyPreview"] = "(gol)",
        ["History_SearchPlaceholder"] = "Caută în rezultate",
        ["History_NoMatch"] = "Niciun rezultat nu se potrivește.",
        ["History_Off"] = "Istoricul este dezactivat în opțiuni.",
        ["History_Clear"] = "Golește istoricul",
        ["History_CopyItem"] = "Copiază acest text",
        ["History_DeleteItem"] = "Șterge această intrare",
        ["Tip_Settings"] = "Opțiuni",
        ["Settings_Header"] = "Opțiuni",
        ["Setting_UiLanguage"] = "Limba aplicației",
        ["Lang_SystemDefault"] = "Implicit din sistem",
        ["Setting_RepairNumbers"] = "Corectează l și I din interiorul numerelor",
        ["Setting_RepairNumbers_Desc"] = "Motoarele de recunoaștere citesc frecvent v1.6.5 ca vl.6.5. Când opțiunea este activă, un l sau I devine 1 doar acolo unde alături se află un separator și o cifră, așa că html5 și IPv6 rămân neatinse. Când este dezactivată, citirea motorului se păstrează exact așa cum a venit.",
        ["Setting_WatchClipboard"] = "Citește imaginile pe care le copiez",
        ["Setting_WatchClipboard_Desc"] = "Fă o captură cu Win+Shift+S, iar Glyfo o citește imediat și pune textul în clipboard în locul imaginii, astfel încât următoarea lipire să fie textul. Se citesc doar imagini, niciodată textul copiat, și nimic nu este trimis nicăieri — totul se petrece pe acest dispozitiv.",
        ["Setting_KeepHistory"] = "Păstrează istoricul între sesiuni",
        ["Setting_KeepHistory_Desc"] = "Păstrează ultimele 200 de rezultate, ca să fie acolo și după o repornire. Se salvează doar textul, niciodată imaginile, într-un fișier care aparține de Glyfo pe acest dispozitiv. Dezactivarea șterge acel fișier și golește lista imediat.",
        ["Common_On"] = "Activat",
        ["Common_Off"] = "Dezactivat",
        ["Lang_Placeholder"] = "Limbă",
        ["Tip_OcrLanguage"] = "Limba de recunoaștere, dintre pachetele de limbă instalate în Windows",
        ["Btn_Translate"] = "Tradu",
        ["Tip_Translate"] = "Tradu pe acest dispozitiv — nu se trimite nimic prin rețea",
        ["Btn_Barcode"] = "Coduri",
        ["Tip_Barcode"] = "Citește codurile QR și codurile de bare din imagine",
        ["Btn_Recognize"] = "Recunoaște",
        ["Tip_Recognize"] = "Recunoaște textul din imagine (F5)",

        ["Option_AutoAi"] = "Automat (Windows AI)",
        ["Option_AutoMulti"] = "Automat (mai multe limbi · mai lent)",

        ["Status_Loaded"] = "{0} încărcată.",
        ["Status_OpenFailed"] = "Imaginea nu a putut fi deschisă: {0}",
        ["Status_ClipboardText"] = "Text încărcat din clipboard.",
        ["Status_ClipboardEmpty"] = "În clipboard nu se află nici imagine, nici text.",
        ["Status_ClipboardFailed"] = "Clipboardul nu a putut fi citit: {0}",
        ["Status_DropFailed"] = "Elementul tras nu a putut fi folosit: {0}",
        ["Status_ImageCopied"] = "Imagine copiată în clipboard.",
        ["Status_ImageCopyFailed"] = "Imaginea nu a putut fi copiată: {0}",
        ["Status_ImageSaved"] = "Imagine salvată ca {0}.",
        ["Status_ImageSaveFailed"] = "Imaginea nu a putut fi salvată: {0}",
        ["Status_Recognizing"] = "Se recunoaște…",
        ["Status_NoText"] = "{0} nu a găsit text în această imagine.",
        ["Status_Done"] = "Gata ({0}).",
        ["Status_DoneConfidence"] = "Gata ({0}) · încredere medie {1}%.",
        ["Status_RecognizeFailed"] = "Recunoașterea a eșuat: {0}",
        ["Status_Scanning"] = "Se caută coduri QR și coduri de bare…",
        ["Status_NoBarcode"] = "Niciun cod QR sau de bare găsit în această imagine.",
        ["Status_BarcodeOne"] = "S-a găsit un cod {0}.",
        ["Status_BarcodeMany"] = "S-au găsit {0} coduri.",
        ["Status_ScanFailed"] = "Scanarea a eșuat: {0}",
        ["Status_PdfFailed"] = "acest PDF nu a putut fi citit — poate fi protejat cu parolă sau deteriorat",
        ["Status_LaunchFailed"] = "Windows nu a găsit nimic cu care să deschidă asta.",
        ["Status_NothingToTranslate"] = "Nu există text de tradus.",
        ["Status_Translating"] = "Se traduce în {0} pe acest dispozitiv…",
        ["Status_Translated"] = "Tradus în {0}, pe acest dispozitiv, fără acces la rețea.",
        ["Status_TranslateFailed"] = "Traducerea a eșuat: {0}",
        ["Status_NothingToCopy"] = "Nu există text de copiat.",
        ["Status_NothingToSave"] = "Nu există text de salvat.",
        ["Status_TextSaved"] = "Text salvat ca {0}.",
        ["Status_TextSaveFailed"] = "Textul nu a putut fi salvat: {0}",
        ["Status_TextCopied"] = "Text copiat în clipboard.",
        ["Status_CopyFailed"] = "Textul nu a putut fi copiat: {0}",
        ["Status_NothingToSpeak"] = "Nu există text de citit cu voce tare.",
        ["Status_SpeakFailed"] = "Textul nu a putut fi citit cu voce tare: {0}",
        ["Status_HistoryLoaded"] = "Se afișează rezultatul de la {0}.",
        ["Status_HistoryCleared"] = "Istoric golit.",
        ["Status_NeedImage"] = "Încarcă mai întâi o imagine.",
        ["Status_CaptureFailed"] = "Captura de ecran a eșuat: {0}",
        ["Status_StartupBlockedByUser"] = "Windows a dezactivat pornirea automată a Glyfo. Reactivați-o în Manager de activități, la Aplicații de pornire.",
        ["Status_StartupBlockedByPolicy"] = "Organizația dvs. nu permite aplicațiilor să pornească odată cu Windows.",
        ["Status_LanguagePackMissing"] = "Windows nu are instalat niciun pachet de limbă pentru OCR, deci nu există cu ce să se facă recunoașterea. Adaugă limba de care ai nevoie din Oră și limbă, apoi Limbă și regiune.",
        ["Btn_OpenLanguageSettings"] = "Deschide setările de limbă",

        ["Tray_Open"] = "Deschide Glyfo",
        ["Tray_CaptureRegion"] = "Captează o zonă",
        ["Tray_CaptureFullScreen"] = "Captează tot ecranul",
        ["Tray_Exit"] = "Ieșire",
        ["Tray_Tooltip"] = "Glyfo — apasă {0} pentru a captura o zonă",
        ["Toast_StartupTitle"] = "Glyfo rulează",
        ["Toast_StartupBody"] = "Apasă {0} pentru a selecta o parte din ecran și a citi textul din ea. Ctrl+Shift+R capturează tot ecranul.",
        ["Toast_DontRemind"] = "Nu-mi mai aminti",
        ["Toast_MinimizedTitle"] = "Glyfo rulează în continuare",
        ["Toast_MinimizedBody"] = "Apasă {0} oricând pentru a captura și recunoaște. Ca să-l închizi de tot, dă clic dreapta pe pictograma lui din zona de notificare și alege Ieșire.",
        ["Toast_ExitApp"] = "Ieși din Glyfo",
        ["Toast_ResultTitle"] = "Text recunoscut",
        ["Toast_ResultCopied"] = "Copiat în clipboard.",
        ["Toast_OpenWindow"] = "Deschide fereastra",
        ["Toast_NoTextTitle"] = "Nu s-a găsit text",
        ["Toast_NoTextBody"] = "În zona aceea nu era nimic care să poată fi citit ca text.",
        ["Toast_FailedTitle"] = "Recunoașterea a eșuat",
        ["Toast_HotkeyUnavailableTitle"] = "Scurtătura de captură este ocupată",
        ["Toast_HotkeyUnavailableBody"] = "O altă aplicație o folosește deja, așa că ecranul poate fi capturat doar din fereastră și din pictograma din zona de notificare.",
        ["Setting_CloseToTray"] = "Continuă să ruleze la închiderea ferestrei",
        ["Setting_CloseToTray_Desc"] = "Când este activat, închiderea ferestrei lasă Glyfo pornit, astfel încât scurtătura de captură să funcționeze în continuare, iar pictograma rămâne în zona de notificare, unde Ieșire îl închide definitiv. Când este dezactivat, închiderea ferestrei oprește aplicația.",
        ["Setting_Startup"] = "Pornire odată cu Windows",
        ["Setting_Startup_Desc"] = "Când această opțiune este activată, Glyfo pornește odată cu Windows și trece direct în zona de notificare, fără să deschidă o fereastră, astfel încât comanda rapidă de captură funcționează din momentul conectării.",

        ["Source_Clipboard"] = "imaginea din clipboard",
        ["Source_Dropped"] = "imaginea trasă",
        ["Source_Shared"] = "imaginea partajată",
        ["Source_FullScreen"] = "Tot ecranul",
        ["Source_Region"] = "Zonă de pe ecran",
        ["Source_Codes"] = "{0} (coduri)",
        ["Source_Batch"] = "{0} fișiere",
        ["Source_PdfAll"] = "{0}, toate paginile",

        ["FileType_Image"] = "Imagine {0}",
        ["FileType_Text"] = "Text simplu",
        ["FileType_Markdown"] = "Markdown",
        ["Batch_Title"] = "Se citesc mai multe fișiere",
        ["Batch_Progress"] = "{0} din {1}",
        ["Batch_DoneAll"] = "Citite: {0}.",
        ["Batch_Cancelled"] = "Oprit după {0} din {1}.",
        ["Batch_ItemFailed"] = "Nu a putut fi citit: {0}",
        ["Batch_ItemEmpty"] = "(fără text)",
        ["Batch_Save"] = "Salvează…",
        ["Batch_CopyAll"] = "Copiază tot",
        ["Batch_Separate"] = "Salvează fiecare element în fișierul său",
        ["Batch_SavedFolder"] = "{0} fișiere salvate în {1}.",
        ["Batch_TooLongForBox"] = "Au fost citite {0} elemente. Textul este prea lung ca să fie afișat aici — se află în fișierul pe care l-ai salvat.",

        ["Region_Hint"] = "Trage pentru a selecta o zonă　·　Esc sau clic dreapta anulează",

        ["Err_NoLanguagePack"] = "Windows nu are instalat un pachet de limbă pentru OCR pentru această limbă. Adaugă unul din Oră și limbă, apoi Limbă și regiune.",
        ["Err_TextTooLong"] = "Textul este prea lung pentru modelul de pe dispozitiv. Tradu o porțiune mai mică.",
        ["Err_ModelDeclined"] = "Modelul de pe dispozitiv a refuzat să traducă acest text.",
        ["Err_TranslationFailed"] = "Traducerea pe dispozitiv nu a produs niciun rezultat.",
        ["Btn_About"] = "Despre Glyfo",
        ["About_Title"] = "Despre Glyfo",
        ["About_Version"] = "Versiunea {0}",
        ["About_Tagline"] = "Citește textul din orice imagine, pe acest dispozitiv. Nu se trimite nimic prin rețea.",
        ["About_Rate"] = "Evaluați Glyfo",
        ["About_WhatsNew"] = "Noutăți",
        ["About_Source"] = "Codul sursă pe GitHub",
        ["About_Privacy"] = "Politica de confidențialitate",
        ["Common_Close"] = "Închidere",
        ["Common_Cancel"] = "Anulare",
        ["News_Title"] = "Noutăți",
        ["News_130_1"] = "Istoricul supraviețuiește acum unei reporniri și are o casetă de căutare. Se păstrează doar textul — din opțiuni poate fi golit sau dezactivat.",
        ["News_130_2"] = "Ctrl+S salvează textul recunoscut ca fișier text simplu sau Markdown.",
        ["News_130_3"] = "Deschide sau trage mai multe fișiere odată ori citește un PDF întreg și salvează tot într-un singur fișier sau câte unul pentru fiecare element.",
        ["News_120_1"] = "Fă o captură cu Win+Shift+S, iar Glyfo o citește în locul tău și lasă textul în clipboard. Este dezactivat până îl activezi din opțiuni.",
        ["News_120_2"] = "Fișierele PDF se deschid acum ca imaginile, pagină cu pagină.",
        ["News_120_3"] = "Linkurile, adresele de e-mail și numerele de telefon găsite în text primesc un buton dedesubt.",
        ["News_110_1"] = "O pagină Despre, cu versiunea și linkuri către codul sursă și politica de confidențialitate.",
        ["News_110_2"] = "Puteți evalua Glyfo fără să părăsiți fereastra.",
        ["News_110_3"] = "Aceste note, afișate o dată la fiecare versiune nouă.",
        ["News_110_4"] = "Capturarea oferă acum și tot ecranul și ascunde mai întâi fereastra, așa că Glyfo nu mai apare în imagine.",
        ["Rate_Title"] = "Vă este de folos Glyfo?",
        ["Rate_Body"] = "O evaluare în Store este ceea ce îi ajută pe alții să găsească aplicația. Durează o clipă.",
        ["Rate_Action"] = "Evaluați",
        ["Rate_Later"] = "Nu acum",
    };
}
