using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Tr = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · dil paketi yok",
        ["Engine_OneLanguage"] = "Windows OCR · 1 dil",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} dil",
        ["Engine_OnDevice"] = "{0} · cihazda",

        ["Preview_Placeholder"] = "Buraya bir görüntü bırakın ya da aşağıdaki Dosya, Yakala veya Pano düğmelerini kullanın",
        ["Btn_CopyImage"] = "Kopyala",
        ["Tip_CopyImage"] = "Görüntüyü panoya kopyala",
        ["Btn_SaveImage"] = "Kaydet",
        ["Tip_SaveImage"] = "Görüntüyü farklı kaydet…",
        ["Btn_FitToWindow"] = "Sığdır",
        ["Tip_FitToWindow"] = "Pencereye sığacak şekilde yakınlaştır",
        ["Tip_ActualSize"] = "Gerçek piksel boyutu",
        ["Tip_PdfPrev"] = "Önceki sayfa",
        ["Tip_PdfNext"] = "Sonraki sayfa",
        ["Action_Open"] = "Bağlantıyı aç",
        ["Action_Mail"] = "Şuraya yaz",
        ["Action_Call"] = "Ara",
        ["Action_Search"] = "Web de ara",

        ["Voice_Placeholder"] = "Ses",
        ["Tip_Voice"] = "Sesli okuma için kullanılan ses",
        ["Tip_Speak"] = "Metni sesli oku",
        ["Tip_StopSpeak"] = "Okumayı durdur",
        ["Tip_CopyText"] = "Metni kopyala (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Satırları birleştir",
        ["Tip_RemoveLineBreaks"] = "Sert satır sonlarını yeniden paragraflara birleştir",
        ["Btn_RemoveSpaces"] = "Boşluksuz",
        ["Tip_RemoveSpaces"] = "Tüm boşlukları kaldır — Çince, Japonca ve Korece için",
        ["Result_Placeholder"] = "Tanınan metin burada görünür ve düzenlenebilir.",

        ["Btn_OpenFile"] = "Dosya",
        ["Tip_OpenFile"] = "Bir görüntü dosyası aç (Ctrl+O)",
        ["Btn_Capture"] = "Yakala",
        ["Tip_Capture"] = "Ekranda bir bölge seçip tanı ({0}). Ekranın tamamı için Ctrl+Shift+R tuşlarına basın.",
        ["Hotkey_Unavailable"] = "kısayol yok — ikisini de başka bir uygulama almış",
        ["Btn_Paste"] = "Pano",
        ["Tip_Paste"] = "Panodan bir görüntü veya metin yükle (Ctrl+V)",
        ["Btn_History"] = "Geçmiş",
        ["Tip_History"] = "Son sonuçlar",
        ["History_Empty"] = "Henüz hiçbir şey tanınmadı.",
        ["History_EmptyPreview"] = "(boş)",
        ["Tip_Settings"] = "Seçenekler",
        ["Settings_Header"] = "Seçenekler",
        ["Setting_UiLanguage"] = "Uygulama dili",
        ["Lang_SystemDefault"] = "Sistem varsayılanı",
        ["Setting_RepairNumbers"] = "Sayıların içindeki l ve I harflerini düzelt",
        ["Setting_RepairNumbers_Desc"] = "Tanıyıcılar v1.6.5 ifadesini sık sık vl.6.5 olarak okur. Bu seçenek açıkken bir l ya da I yalnızca yanında bir ayırıcı ve bir rakam varsa 1 olur; böylece html5 ve IPv6 olduğu gibi kalır. Kapalıyken motorun okuması geldiği haliyle korunur.",
        ["Setting_WatchClipboard"] = "Kopyaladığım resimleri oku",
        ["Setting_WatchClipboard_Desc"] = "Win+Shift+S ile ekran görüntüsü alın; Glyfo onu hemen okur ve resim yerine metni panoya koyar, böylece bir sonraki yapıştırma metin olur. Yalnızca resimler okunur, kopyalanan metin asla okunmaz ve hiçbir şey hiçbir yere gönderilmez — her şey bu cihazda olur.",
        ["Common_On"] = "Açık",
        ["Common_Off"] = "Kapalı",
        ["Lang_Placeholder"] = "Dil",
        ["Tip_OcrLanguage"] = "Tanıma dili — Windows'ta yüklü dil paketleri arasından",
        ["Btn_Translate"] = "Çevir",
        ["Tip_Translate"] = "Bu cihazda çevir — ağ üzerinden hiçbir şey gönderilmez",
        ["Btn_Barcode"] = "Kodlar",
        ["Tip_Barcode"] = "Görüntüdeki QR kodlarını ve barkodları oku",
        ["Btn_Recognize"] = "Tanı",
        ["Tip_Recognize"] = "Görüntüdeki metni tanı (F5)",

        ["Option_AutoAi"] = "Otomatik (Windows AI)",
        ["Option_AutoMulti"] = "Otomatik (çok dilli · daha yavaş)",

        ["Status_Loaded"] = "{0} yüklendi.",
        ["Status_OpenFailed"] = "Görüntü açılamadı: {0}",
        ["Status_ClipboardText"] = "Panodan metin yüklendi.",
        ["Status_ClipboardEmpty"] = "Panoda ne görüntü ne de metin var.",
        ["Status_ClipboardFailed"] = "Pano okunamadı: {0}",
        ["Status_DropFailed"] = "Bırakılan öğe kullanılamadı: {0}",
        ["Status_ImageCopied"] = "Görüntü panoya kopyalandı.",
        ["Status_ImageCopyFailed"] = "Görüntü kopyalanamadı: {0}",
        ["Status_ImageSaved"] = "Görüntü {0} olarak kaydedildi.",
        ["Status_ImageSaveFailed"] = "Görüntü kaydedilemedi: {0}",
        ["Status_Recognizing"] = "Tanınıyor…",
        ["Status_NoText"] = "{0} bu görüntüde metin bulamadı.",
        ["Status_Done"] = "Tamamlandı ({0}).",
        ["Status_DoneConfidence"] = "Tamamlandı ({0}) · ortalama güven %{1}.",
        ["Status_RecognizeFailed"] = "Tanıma başarısız oldu: {0}",
        ["Status_Scanning"] = "QR kodları ve barkodlar aranıyor…",
        ["Status_NoBarcode"] = "Bu görüntüde QR kodu veya barkod bulunamadı.",
        ["Status_BarcodeOne"] = "Bir {0} kodu bulundu.",
        ["Status_BarcodeMany"] = "{0} kod bulundu.",
        ["Status_ScanFailed"] = "Tarama başarısız oldu: {0}",
        ["Status_PdfFailed"] = "bu PDF okunamadı — parola korumalı ya da bozuk olabilir",
        ["Status_LaunchFailed"] = "Windows bunu açacak bir şey bulamadı.",
        ["Status_NothingToTranslate"] = "Çevrilecek metin yok.",
        ["Status_Translating"] = "Bu cihazda {0} diline çevriliyor…",
        ["Status_Translated"] = "{0} diline çevrildi — bu cihazda, ağ erişimi olmadan.",
        ["Status_TranslateFailed"] = "Çeviri başarısız oldu: {0}",
        ["Status_NothingToCopy"] = "Kopyalanacak metin yok.",
        ["Status_TextCopied"] = "Metin panoya kopyalandı.",
        ["Status_CopyFailed"] = "Metin kopyalanamadı: {0}",
        ["Status_NothingToSpeak"] = "Sesli okunacak metin yok.",
        ["Status_SpeakFailed"] = "Metin sesli okunamadı: {0}",
        ["Status_HistoryLoaded"] = "{0} tarihli sonuç gösteriliyor.",
        ["Status_NeedImage"] = "Önce bir görüntü yükleyin.",
        ["Status_CaptureFailed"] = "Ekran yakalama başarısız oldu: {0}",
        ["Status_StartupBlockedByUser"] = "Windows, Glyfo için başlangıçta çalıştırmayı kapattı. Görev Yöneticisi’ndeki Başlangıç uygulamaları bölümünden yeniden açın.",
        ["Status_StartupBlockedByPolicy"] = "Kuruluşunuz uygulamaların Windows ile birlikte başlatılmasına izin vermiyor.",
        ["Status_LanguagePackMissing"] = "Windows'ta yüklü bir OCR dil paketi yok, dolayısıyla tanıma yapılacak bir şey de yok. İhtiyacınız olan dili Saat ve dil, ardından Dil ve bölge altından ekleyin.",
        ["Btn_OpenLanguageSettings"] = "Dil ayarlarını aç",

        ["Tray_Open"] = "Glyfo'ı aç",
        ["Tray_CaptureRegion"] = "Bir bölge yakala",
        ["Tray_CaptureFullScreen"] = "Tüm ekranı yakala",
        ["Tray_Exit"] = "Çıkış",
        ["Tray_Tooltip"] = "Glyfo — bir bölge yakalamak için {0} tuşlarına basın",
        ["Toast_StartupTitle"] = "Glyfo çalışıyor",
        ["Toast_StartupBody"] = "Ekranın bir bölümünü seçip içindeki metni okumak için {0} tuşlarına basın. Ctrl+Shift+R tüm ekranı yakalar.",
        ["Toast_DontRemind"] = "Bir daha hatırlatma",
        ["Toast_MinimizedTitle"] = "Glyfo hâlâ çalışıyor",
        ["Toast_MinimizedBody"] = "Yakalayıp tanımak için istediğiniz zaman {0} tuşlarına basın. Tamamen kapatmak için bildirim alanındaki simgesine sağ tıklayıp Çıkış'ı seçin.",
        ["Toast_ExitApp"] = "Glyfo'dan çık",
        ["Toast_ResultTitle"] = "Metin tanındı",
        ["Toast_ResultCopied"] = "Panoya kopyalandı.",
        ["Toast_OpenWindow"] = "Pencereyi aç",
        ["Toast_NoTextTitle"] = "Metin bulunamadı",
        ["Toast_NoTextBody"] = "O bölgede metin olarak okunabilecek bir şey yoktu.",
        ["Toast_FailedTitle"] = "Tanıma başarısız oldu",
        ["Toast_HotkeyUnavailableTitle"] = "Yakalama kısayolu kullanımda",
        ["Toast_HotkeyUnavailableBody"] = "Başka bir uygulama onu almış durumda, bu yüzden ekran yakalama yalnızca pencereden ve bildirim alanındaki simgeden yapılabilir.",
        ["Setting_CloseToTray"] = "Pencere kapatılınca çalışmaya devam et",
        ["Setting_CloseToTray_Desc"] = "Bu açıkken pencereyi kapatmak Glyfo'ı çalışır durumda bırakır, böylece yakalama kısayolu çalışmaya devam eder ve simgesi bildirim alanında kalır; oradaki Çıkış uygulamayı tamamen kapatır. Kapalıyken pencereyi kapatmak uygulamayı sonlandırır.",
        ["Setting_Startup"] = "Windows ile birlikte başlat",
        ["Setting_Startup_Desc"] = "Bu seçenek açıkken Glyfo, Windows ile birlikte başlar ve pencere açmadan doğrudan bildirim alanına yerleşir; böylece yakalama kısayolu oturum açar açmaz çalışır.",

        ["Source_Clipboard"] = "panodaki görüntü",
        ["Source_Dropped"] = "bırakılan görüntü",
        ["Source_Shared"] = "paylaşılan görüntü",
        ["Source_FullScreen"] = "Tam ekran",
        ["Source_Region"] = "Ekran bölgesi",
        ["Source_Codes"] = "{0} (kodlar)",

        ["FileType_Image"] = "{0} görüntüsü",

        ["Region_Hint"] = "Bir alan seçmek için sürükleyin　·　İptal için Esc veya sağ tık",

        ["Err_NoLanguagePack"] = "Windows'ta bu dil için yüklü bir OCR dil paketi yok. Saat ve dil, ardından Dil ve bölge altından bir tane ekleyin.",
        ["Err_TextTooLong"] = "Metin, cihazdaki model için fazla uzun. Daha küçük bir bölümünü çevirin.",
        ["Err_ModelDeclined"] = "Cihazdaki model bu metni çevirmeyi reddetti.",
        ["Err_TranslationFailed"] = "Cihazdaki çeviri bir sonuç üretmedi.",
        ["Btn_About"] = "Glyfo hakkında",
        ["About_Title"] = "Glyfo hakkında",
        ["About_Version"] = "Sürüm {0}",
        ["About_Tagline"] = "Herhangi bir görüntüdeki metni bu cihazda okur. Ağ üzerinden hiçbir şey gönderilmez.",
        ["About_Rate"] = "Glyfo'yu değerlendir",
        ["About_WhatsNew"] = "Yenilikler",
        ["About_Source"] = "GitHub'daki kaynak kodu",
        ["About_Privacy"] = "Gizlilik ilkesi",
        ["Common_Close"] = "Kapat",
        ["News_Title"] = "Yenilikler",
        ["News_120_1"] = "Win+Shift+S ile ekran görüntüsü alın; Glyfo onu sizin için okur ve metni panoda bırakır. Seçeneklerden açana kadar kapalıdır.",
        ["News_120_2"] = "PDF dosyaları artık resimler gibi, sayfa sayfa açılıyor.",
        ["News_120_3"] = "Metinde bulunan bağlantılar, e-posta adresleri ve telefon numaraları altında bir düğme kazanır.",
        ["News_110_1"] = "Sürümü, kaynak kodu ve gizlilik ilkesi bağlantılarını içeren bir hakkında sayfası.",
        ["News_110_2"] = "Glyfo'yu pencereden çıkmadan değerlendirebilirsiniz.",
        ["News_110_3"] = "Yeni bir sürümü ilk açtığınızda görünen bu notlar.",
        ["News_110_4"] = "Yakalama artık tüm ekranı da sunuyor ve önce pencereyi gizliyor, böylece Glyfo görüntüye hiç girmiyor.",
        ["Rate_Title"] = "Glyfo işinizi görüyor mu?",
        ["Rate_Body"] = "Mağazadaki değerlendirmeler, başkalarının uygulamayı bulmasını sağlar. Yalnızca birkaç saniye sürer.",
        ["Rate_Action"] = "Değerlendir",
        ["Rate_Later"] = "Şimdi değil",
    };
}
