using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Bn = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · কোনো ভাষা প্যাক নেই",
        ["Engine_OneLanguage"] = "Windows OCR · ১টি ভাষা",
        ["Engine_ManyLanguages"] = "Windows OCR · {0}টি ভাষা",
        ["Engine_OnDevice"] = "{0} · ডিভাইসেই",

        ["Preview_Placeholder"] = "এখানে একটি ছবি ছেড়ে দিন, কিংবা নিচের ফাইল, স্ক্রিন কাটা বা ক্লিপবোর্ড ব্যবহার করুন",
        ["Btn_CopyImage"] = "কপি",
        ["Tip_CopyImage"] = "ছবিটি ক্লিপবোর্ডে কপি করুন",
        ["Btn_SaveImage"] = "সংরক্ষণ",
        ["Tip_SaveImage"] = "ছবিটি এভাবে সংরক্ষণ করুন…",
        ["Btn_FitToWindow"] = "মানানসই",
        ["Tip_FitToWindow"] = "উইন্ডোতে মানানসই করে জুম করুন",
        ["Tip_ActualSize"] = "প্রকৃত পিক্সেল আকার",

        ["Voice_Placeholder"] = "কণ্ঠ",
        ["Tip_Voice"] = "পড়ে শোনানোর জন্য যে কণ্ঠ ব্যবহার হবে",
        ["Tip_Speak"] = "লেখাটি পড়ে শোনান",
        ["Tip_StopSpeak"] = "পড়া থামান",
        ["Tip_CopyText"] = "লেখা কপি করুন (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "লাইন জোড়া",
        ["Tip_RemoveLineBreaks"] = "লাইন-বিরতিগুলো জুড়ে আবার অনুচ্ছেদ বানান",
        ["Btn_RemoveSpaces"] = "ফাঁকা বাদ",
        ["Tip_RemoveSpaces"] = "সব ফাঁকা জায়গা মুছে দিন — চীনা, জাপানি ও কোরীয় ভাষার জন্য",
        ["Result_Placeholder"] = "শনাক্ত হওয়া লেখা এখানে দেখা যাবে এবং সম্পাদনা করা যাবে।",

        ["Btn_OpenFile"] = "ফাইল",
        ["Tip_OpenFile"] = "একটি ছবির ফাইল খুলুন (Ctrl+O)",
        ["Btn_Capture"] = "স্ক্রিন কাটা",
        ["Tip_Capture"] = "পর্দার একটি অংশ বেছে নিয়ে শনাক্ত করুন ({0})। পুরো পর্দার জন্য Ctrl+Shift+R চাপুন।",
        ["Hotkey_Unavailable"] = "কোনো শর্টকাট নেই — দুটিই অন্য অ্যাপ দখল করে আছে",
        ["Btn_Paste"] = "ক্লিপবোর্ড",
        ["Tip_Paste"] = "ক্লিপবোর্ড থেকে ছবি বা লেখা নিন (Ctrl+V)",
        ["Btn_History"] = "ইতিহাস",
        ["Tip_History"] = "সাম্প্রতিক ফলাফল",
        ["History_Empty"] = "এখনো কিছু শনাক্ত করা হয়নি।",
        ["History_EmptyPreview"] = "(ফাঁকা)",
        ["Tip_Settings"] = "বিকল্প",
        ["Settings_Header"] = "বিকল্প",
        ["Setting_UiLanguage"] = "অ্যাপের ভাষা",
        ["Lang_SystemDefault"] = "সিস্টেমের ডিফল্ট",
        ["Setting_RepairNumbers"] = "সংখ্যার ভেতরের l ও I ঠিক করুন",
        ["Setting_RepairNumbers_Desc"] = "শনাক্তকারী ইঞ্জিন প্রায়ই v1.6.5 কে vl.6.5 হিসেবে পড়ে। এটি চালু থাকলে l বা I কেবল সেখানেই ১ হয়ে যায় যেখানে পাশে বিভাজক ও অঙ্ক থাকে, ফলে html5 আর IPv6 অক্ষত থাকে। বন্ধ থাকলে ইঞ্জিন যা পড়েছে ঠিক তা-ই অবিকল রাখা হয়।",
        ["Common_On"] = "চালু",
        ["Common_Off"] = "বন্ধ",
        ["Lang_Placeholder"] = "ভাষা",
        ["Tip_OcrLanguage"] = "শনাক্তকরণের ভাষা, Windows-এ ইনস্টল করা ভাষা প্যাক থেকে",
        ["Btn_Translate"] = "অনুবাদ",
        ["Tip_Translate"] = "এই ডিভাইসেই অনুবাদ করুন — নেটওয়ার্কে কিছুই পাঠানো হয় না",
        ["Btn_Barcode"] = "কোড",
        ["Tip_Barcode"] = "ছবির QR কোড ও বারকোড পড়ুন",
        ["Btn_Recognize"] = "শনাক্ত",
        ["Tip_Recognize"] = "ছবির লেখা শনাক্ত করুন (F5)",

        ["Option_AutoAi"] = "স্বয়ংক্রিয় (Windows AI)",
        ["Option_AutoMulti"] = "স্বয়ংক্রিয় (একাধিক ভাষা · ধীর)",

        ["Status_Loaded"] = "{0} লোড হয়েছে।",
        ["Status_OpenFailed"] = "ছবিটি খোলা গেল না: {0}",
        ["Status_ClipboardText"] = "ক্লিপবোর্ড থেকে লেখা নেওয়া হয়েছে।",
        ["Status_ClipboardEmpty"] = "ক্লিপবোর্ডে ছবিও নেই, লেখাও নেই।",
        ["Status_ClipboardFailed"] = "ক্লিপবোর্ড পড়া গেল না: {0}",
        ["Status_DropFailed"] = "ছেড়ে দেওয়া জিনিসটি কাজে লাগানো গেল না: {0}",
        ["Status_ImageCopied"] = "ছবিটি ক্লিপবোর্ডে কপি হয়েছে।",
        ["Status_ImageCopyFailed"] = "ছবিটি কপি করা গেল না: {0}",
        ["Status_ImageSaved"] = "ছবিটি {0} নামে সংরক্ষিত হয়েছে।",
        ["Status_ImageSaveFailed"] = "ছবিটি সংরক্ষণ করা গেল না: {0}",
        ["Status_Recognizing"] = "শনাক্ত করা হচ্ছে…",
        ["Status_NoText"] = "{0} এই ছবিতে কোনো লেখা পায়নি।",
        ["Status_Done"] = "সম্পন্ন ({0})।",
        ["Status_DoneConfidence"] = "সম্পন্ন ({0}) · গড় আস্থা {1}%।",
        ["Status_RecognizeFailed"] = "শনাক্তকরণ ব্যর্থ হলো: {0}",
        ["Status_Scanning"] = "QR কোড ও বারকোড খোঁজা হচ্ছে…",
        ["Status_NoBarcode"] = "এই ছবিতে কোনো QR কোড বা বারকোড পাওয়া যায়নি।",
        ["Status_BarcodeOne"] = "একটি {0} কোড পাওয়া গেছে।",
        ["Status_BarcodeMany"] = "{0}টি কোড পাওয়া গেছে।",
        ["Status_ScanFailed"] = "খোঁজা ব্যর্থ হলো: {0}",
        ["Status_NothingToTranslate"] = "অনুবাদ করার মতো কোনো লেখা নেই।",
        ["Status_Translating"] = "এই ডিভাইসেই {0} ভাষায় অনুবাদ করা হচ্ছে…",
        ["Status_Translated"] = "{0} ভাষায় অনুবাদ হয়েছে — এই ডিভাইসেই, নেটওয়ার্ক ছাড়াই।",
        ["Status_TranslateFailed"] = "অনুবাদ ব্যর্থ হলো: {0}",
        ["Status_NothingToCopy"] = "কপি করার মতো কোনো লেখা নেই।",
        ["Status_TextCopied"] = "লেখাটি ক্লিপবোর্ডে কপি হয়েছে।",
        ["Status_CopyFailed"] = "লেখাটি কপি করা গেল না: {0}",
        ["Status_NothingToSpeak"] = "পড়ে শোনানোর মতো কোনো লেখা নেই।",
        ["Status_SpeakFailed"] = "লেখাটি পড়ে শোনানো গেল না: {0}",
        ["Status_HistoryLoaded"] = "{0}-এর ফলাফল দেখানো হচ্ছে।",
        ["Status_NeedImage"] = "আগে একটি ছবি লোড করুন।",
        ["Status_CaptureFailed"] = "স্ক্রিন কাটা ব্যর্থ হলো: {0}",
        ["Status_StartupBlockedByUser"] = "Windows Glyfo-এর স্টার্টআপ বন্ধ করে রেখেছে। টাস্ক ম্যানেজারের স্টার্টআপ অ্যাপস থেকে এটি আবার চালু করুন।",
        ["Status_StartupBlockedByPolicy"] = "আপনার প্রতিষ্ঠান অ্যাপকে Windows-এর সঙ্গে চালু হতে দেয় না।",
        ["Status_LanguagePackMissing"] = "Windows-এ কোনো OCR ভাষা প্যাক ইনস্টল করা নেই, তাই শনাক্ত করার মতো কিছুই নেই। প্রয়োজনীয় ভাষাটি সময় ও ভাষা, তারপর ভাষা ও অঞ্চল থেকে যোগ করুন।",
        ["Btn_OpenLanguageSettings"] = "ভাষার সেটিংস খুলুন",

        ["Tray_Open"] = "Glyfo খুলুন",
        ["Tray_CaptureRegion"] = "একটি অংশ ধরুন",
        ["Tray_CaptureFullScreen"] = "পুরো পর্দা ধরুন",
        ["Tray_Exit"] = "প্রস্থান",
        ["Tray_Tooltip"] = "Glyfo — কোনো অংশ ধরতে {0} চাপুন",
        ["Toast_StartupTitle"] = "Glyfo চলছে",
        ["Toast_StartupBody"] = "পর্দার একটি অংশ বেছে নিয়ে তার লেখা পড়তে {0} চাপুন। পুরো পর্দার জন্য Ctrl+Shift+R চাপুন।",
        ["Toast_DontRemind"] = "আর মনে করিয়ে দেবেন না",
        ["Toast_MinimizedTitle"] = "Glyfo এখনও চলছে",
        ["Toast_MinimizedBody"] = "যেকোনো সময় {0} চেপে ছবি নিয়ে লেখা শনাক্ত করুন। পুরোপুরি বন্ধ করতে বিজ্ঞপ্তি এলাকায় এর আইকনে ডান ক্লিক করে প্রস্থান বেছে নিন।",
        ["Toast_ExitApp"] = "Glyfo থেকে প্রস্থান",
        ["Toast_ResultTitle"] = "লেখা শনাক্ত হয়েছে",
        ["Toast_ResultCopied"] = "ক্লিপবোর্ডে কপি হয়েছে।",
        ["Toast_OpenWindow"] = "উইন্ডো খুলুন",
        ["Toast_NoTextTitle"] = "কোনো লেখা পাওয়া যায়নি",
        ["Toast_NoTextBody"] = "ওই অংশে লেখা হিসেবে পড়ার মতো কিছু ছিল না।",
        ["Toast_FailedTitle"] = "শনাক্তকরণ ব্যর্থ হয়েছে",
        ["Toast_HotkeyUnavailableTitle"] = "ধরার শর্টকাটটি ব্যবহৃত হচ্ছে",
        ["Toast_HotkeyUnavailableBody"] = "অন্য একটি অ্যাপ আগেই এটি দখল করেছে, তাই পর্দা ধরা যাবে কেবল উইন্ডো থেকে ও বিজ্ঞপ্তি এলাকার আইকন থেকে।",
        ["Setting_CloseToTray"] = "উইন্ডো বন্ধ করলেও চলতে থাকুক",
        ["Setting_CloseToTray_Desc"] = "এটি চালু থাকলে উইন্ডো বন্ধ করার পরও Glyfo চলতে থাকে, ফলে ধরার শর্টকাট কাজ করে যায় এবং এর আইকন বিজ্ঞপ্তি এলাকায় থেকে যায়, যেখানে প্রস্থান বেছে নিলে এটি পুরোপুরি বন্ধ হয়। বন্ধ থাকলে উইন্ডো বন্ধ করলেই অ্যাপটি শেষ হয়ে যায়।",
        ["Setting_Startup"] = "Windows-এর সঙ্গে চালু হোক",
        ["Setting_Startup_Desc"] = "এটি চালু থাকলে Glyfo Windows-এর সঙ্গে চালু হয় এবং কোনও উইন্ডো না খুলে সরাসরি বিজ্ঞপ্তি এলাকায় চলে যায়, তাই সাইন ইন করার সঙ্গে সঙ্গেই ক্যাপচার শর্টকাট কাজ করে।",

        ["Source_Clipboard"] = "ক্লিপবোর্ডের ছবি",
        ["Source_Dropped"] = "ছেড়ে দেওয়া ছবি",
        ["Source_Shared"] = "শেয়ার করা ছবি",
        ["Source_FullScreen"] = "পুরো পর্দা",
        ["Source_Region"] = "পর্দার অংশ",
        ["Source_Codes"] = "{0} (কোড)",

        ["FileType_Image"] = "{0} ছবি",

        ["Region_Hint"] = "একটি অংশ বেছে নিতে টেনে আনুন　·　Esc বা ডান ক্লিকে বাতিল",

        ["Err_NoLanguagePack"] = "এই ভাষার জন্য Windows-এ কোনো OCR ভাষা প্যাক ইনস্টল করা নেই। সময় ও ভাষা, তারপর ভাষা ও অঞ্চল থেকে একটি যোগ করুন।",
        ["Err_TextTooLong"] = "ডিভাইসে চলা মডেলের জন্য লেখাটি বড্ড লম্বা। ছোট একটি অংশ অনুবাদ করুন।",
        ["Err_ModelDeclined"] = "ডিভাইসে চলা মডেলটি এই লেখা অনুবাদ করতে রাজি হয়নি।",
        ["Err_TranslationFailed"] = "ডিভাইসে করা অনুবাদ থেকে কোনো ফল আসেনি।",
        ["Btn_About"] = "Glyfo সম্পর্কে",
        ["About_Title"] = "Glyfo সম্পর্কে",
        ["About_Version"] = "সংস্করণ {0}",
        ["About_Tagline"] = "যেকোনো ছবির লেখা এই ডিভাইসেই পড়ে। নেটওয়ার্কে কিছুই পাঠানো হয় না।",
        ["About_Rate"] = "Glyfo-কে রেটিং দিন",
        ["About_WhatsNew"] = "নতুন কী আছে",
        ["About_Source"] = "GitHub-এ সোর্স কোড",
        ["About_Privacy"] = "গোপনীয়তা নীতি",
        ["Common_Close"] = "বন্ধ করুন",
        ["News_Title"] = "নতুন কী আছে",
        ["News_110_1"] = "একটি সম্পর্কে পাতা, যাতে সংস্করণ এবং সোর্স কোড ও গোপনীয়তা নীতির লিঙ্ক রয়েছে।",
        ["News_110_2"] = "উইন্ডো ছেড়ে না গিয়েই Glyfo-কে রেটিং দিতে পারবেন।",
        ["News_110_3"] = "এই নোটগুলো, যা প্রতিটি নতুন সংস্করণে একবার দেখানো হয়।",
        ["Rate_Title"] = "Glyfo কি কাজে লাগছে?",
        ["Rate_Body"] = "Store-এ দেওয়া রেটিং থেকেই অন্যরা অ্যাপটি খুঁজে পান। সময় লাগে সামান্যই।",
        ["Rate_Action"] = "রেটিং দিন",
        ["Rate_Later"] = "এখন নয়",
    };
}
