using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Ja = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · 言語パックなし",
        ["Engine_OneLanguage"] = "Windows OCR · 1 言語",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} 言語",
        ["Engine_OnDevice"] = "{0} · デバイス上で実行",

        ["Preview_Placeholder"] = "ここに画像をドロップするか、下のファイル・キャプチャ・クリップボードを使います",
        ["Btn_CopyImage"] = "コピー",
        ["Tip_CopyImage"] = "画像をクリップボードにコピー",
        ["Btn_SaveImage"] = "保存",
        ["Tip_SaveImage"] = "画像に名前を付けて保存…",
        ["Btn_FitToWindow"] = "全体表示",
        ["Tip_FitToWindow"] = "ウィンドウに合わせて拡大縮小",
        ["Tip_ActualSize"] = "実際のピクセルサイズ",

        ["Voice_Placeholder"] = "音声",
        ["Tip_Voice"] = "読み上げに使う音声",
        ["Tip_Speak"] = "テキストを読み上げる",
        ["Tip_StopSpeak"] = "読み上げを停止",
        ["Tip_CopyText"] = "テキストをコピー（Ctrl+Shift+C）",
        ["Btn_RemoveLineBreaks"] = "改行削除",
        ["Tip_RemoveLineBreaks"] = "強制改行を段落に戻す",
        ["Btn_RemoveSpaces"] = "空白削除",
        ["Tip_RemoveSpaces"] = "すべての空白を削除します。中国語・日本語・韓国語向け",
        ["Result_Placeholder"] = "認識されたテキストがここに表示され、編集できます。",

        ["Btn_OpenFile"] = "ファイル",
        ["Tip_OpenFile"] = "画像ファイルを開く（Ctrl+O）",
        ["Btn_Capture"] = "キャプチャ",
        ["Tip_Capture"] = "画面の範囲を選んで認識します（{0}）。Ctrl+Shift+R で画面全体。",
        ["Hotkey_Unavailable"] = "ショートカットなし。どちらも他のアプリが使用中です",
        ["Btn_Paste"] = "クリップボード",
        ["Tip_Paste"] = "クリップボードから画像またはテキストを読み込む（Ctrl+V）",
        ["Btn_History"] = "履歴",
        ["Tip_History"] = "最近の認識結果",
        ["History_Empty"] = "まだ認識結果がありません。",
        ["History_EmptyPreview"] = "（空）",
        ["Tip_Settings"] = "オプション",
        ["Settings_Header"] = "オプション",
        ["Setting_UiLanguage"] = "アプリの言語",
        ["Lang_SystemDefault"] = "システムに従う",
        ["Setting_RepairNumbers"] = "数字の中の l と I を修正",
        ["Setting_RepairNumbers_Desc"] = "認識エンジンは v1.6.5 を vl.6.5 と読むことがよくあります。オンにすると、l や I の隣に区切り記号と数字の両方がある場合にだけ 1 に変換するため、html5 や IPv6 はそのまま残ります。オフにすると、エンジンが返した読みをそのまま使います。",
        ["Common_On"] = "オン",
        ["Common_Off"] = "オフ",
        ["Lang_Placeholder"] = "言語",
        ["Tip_OcrLanguage"] = "認識言語。Windows にインストール済みの言語パックから選べます",
        ["Btn_Translate"] = "翻訳",
        ["Tip_Translate"] = "このデバイス上で翻訳します。ネットワークには何も送信しません",
        ["Btn_Barcode"] = "コード",
        ["Tip_Barcode"] = "画像の QR コードとバーコードを読み取る",
        ["Btn_Recognize"] = "認識",
        ["Tip_Recognize"] = "画像内のテキストを認識（F5）",

        ["Option_AutoAi"] = "自動判別（Windows AI）",
        ["Option_AutoMulti"] = "自動判別（多言語 · 低速）",

        ["Status_Loaded"] = "{0}を読み込みました。",
        ["Status_OpenFailed"] = "画像を開けませんでした：{0}",
        ["Status_ClipboardText"] = "クリップボードからテキストを読み込みました。",
        ["Status_ClipboardEmpty"] = "クリップボードに画像もテキストもありません。",
        ["Status_ClipboardFailed"] = "クリップボードを読み取れませんでした：{0}",
        ["Status_DropFailed"] = "ドロップされた内容を使えませんでした：{0}",
        ["Status_ImageCopied"] = "画像をクリップボードにコピーしました。",
        ["Status_ImageCopyFailed"] = "画像をコピーできませんでした：{0}",
        ["Status_ImageSaved"] = "画像を {0} として保存しました。",
        ["Status_ImageSaveFailed"] = "画像を保存できませんでした：{0}",
        ["Status_Recognizing"] = "認識しています…",
        ["Status_NoText"] = "{0} はこの画像からテキストを見つけられませんでした。",
        ["Status_Done"] = "完了（{0}）。",
        ["Status_DoneConfidence"] = "完了（{0}）· 平均信頼度 {1}%。",
        ["Status_RecognizeFailed"] = "認識に失敗しました：{0}",
        ["Status_Scanning"] = "QR コードとバーコードを探しています…",
        ["Status_NoBarcode"] = "この画像に QR コードやバーコードは見つかりませんでした。",
        ["Status_BarcodeOne"] = "{0} コードを 1 件見つけました。",
        ["Status_BarcodeMany"] = "コードを {0} 件見つけました。",
        ["Status_ScanFailed"] = "スキャンに失敗しました：{0}",
        ["Status_NothingToTranslate"] = "翻訳するテキストがありません。",
        ["Status_Translating"] = "このデバイス上で{0}に翻訳しています…",
        ["Status_Translated"] = "{0}に翻訳しました。すべてこのデバイス上で行われ、ネットワークは使いません。",
        ["Status_TranslateFailed"] = "翻訳に失敗しました：{0}",
        ["Status_NothingToCopy"] = "コピーするテキストがありません。",
        ["Status_TextCopied"] = "テキストをクリップボードにコピーしました。",
        ["Status_CopyFailed"] = "テキストをコピーできませんでした：{0}",
        ["Status_NothingToSpeak"] = "読み上げるテキストがありません。",
        ["Status_SpeakFailed"] = "読み上げられませんでした：{0}",
        ["Status_HistoryLoaded"] = "{0} の結果を表示しています。",
        ["Status_NeedImage"] = "先に画像を読み込んでください。",
        ["Status_CaptureFailed"] = "画面のキャプチャに失敗しました：{0}",
        ["Status_StartupBlockedByUser"] = "Windows で Glyfo のスタートアップが無効になっています。タスク マネージャーのスタートアップ アプリから有効にしてください。",
        ["Status_StartupBlockedByPolicy"] = "組織のポリシーにより、アプリを Windows と同時に起動できません。",
        ["Status_LanguagePackMissing"] = "Windows に OCR の言語パックが 1 つもインストールされていないため、認識できません。［時刻と言語］→［言語と地域］で必要な言語を追加してください。",
        ["Btn_OpenLanguageSettings"] = "言語設定を開く",

        ["Tray_Open"] = "Glyfo を開く",
        ["Tray_CaptureRegion"] = "範囲を取り込む",
        ["Tray_CaptureFullScreen"] = "画面全体を取り込む",
        ["Tray_Exit"] = "終了",
        ["Tray_Tooltip"] = "Glyfo — {0} で範囲を取り込みます",
        ["Toast_StartupTitle"] = "Glyfo は実行中です",
        ["Toast_StartupBody"] = "{0} を押すと画面の範囲を選んで文字を認識できます。Ctrl+Shift+R で画面全体を取り込みます。",
        ["Toast_DontRemind"] = "今後表示しない",
        ["Toast_MinimizedTitle"] = "Glyfo はまだ実行中です",
        ["Toast_MinimizedBody"] = "いつでも {0} で取り込みと認識ができます。完全に終了するには、通知領域のアイコンを右クリックして「終了」を選びます。",
        ["Toast_ExitApp"] = "Glyfo を終了",
        ["Toast_ResultTitle"] = "文字を認識しました",
        ["Toast_ResultCopied"] = "クリップボードにコピーしました。",
        ["Toast_OpenWindow"] = "ウィンドウを開く",
        ["Toast_NoTextTitle"] = "文字が見つかりません",
        ["Toast_NoTextBody"] = "その範囲には文字として読み取れるものがありませんでした。",
        ["Toast_FailedTitle"] = "認識に失敗しました",
        ["Toast_HotkeyUnavailableTitle"] = "取り込みのショートカットが使用中です",
        ["Toast_HotkeyUnavailableBody"] = "他のアプリが既に使用しているため、画面の取り込みはウィンドウと通知領域のアイコンからのみ行えます。",
        ["Setting_CloseToTray"] = "ウィンドウを閉じても実行を続ける",
        ["Setting_CloseToTray_Desc"] = "オンにすると、ウィンドウを閉じても Glyfo は実行を続け、取り込みのショートカットが使えるままになります。アイコンは通知領域に残り、そこで「終了」を選ぶと完全に終了します。オフにすると、ウィンドウを閉じた時点でアプリが終了します。",
        ["Setting_Startup"] = "Windows と同時に起動",
        ["Setting_Startup_Desc"] = "オンにすると、Glyfo は Windows と同時に起動し、ウィンドウを開かずに通知領域へ入ります。サインインした時点からキャプチャのショートカットが使えます。",

        ["Source_Clipboard"] = "クリップボードの画像",
        ["Source_Dropped"] = "ドロップされた画像",
        ["Source_Shared"] = "共有された画像",
        ["Source_FullScreen"] = "画面全体",
        ["Source_Region"] = "画面の範囲",
        ["Source_Codes"] = "{0}（コード）",

        ["FileType_Image"] = "{0} 画像",

        ["Region_Hint"] = "ドラッグして範囲を選択　·　Esc または右クリックで取り消し",

        ["Err_NoLanguagePack"] = "この言語の OCR 言語パックが Windows にインストールされていません。［時刻と言語］→［言語と地域］で追加してください。",
        ["Err_TextTooLong"] = "テキストがデバイス上のモデルには長すぎます。分けて翻訳してください。",
        ["Err_ModelDeclined"] = "デバイス上のモデルがこのテキストの翻訳を拒否しました。",
        ["Err_TranslationFailed"] = "デバイス上の翻訳から結果が返りませんでした。",
        ["Btn_About"] = "Glyfo について",
        ["About_Title"] = "Glyfo について",
        ["About_Version"] = "バージョン {0}",
        ["About_Tagline"] = "画像の中の文字をこの端末だけで読み取ります。ネットワークには何も送りません。",
        ["About_Rate"] = "Glyfo を評価",
        ["About_WhatsNew"] = "更新内容",
        ["About_Source"] = "GitHub のソースコード",
        ["About_Privacy"] = "プライバシー ポリシー",
        ["Common_Close"] = "閉じる",
        ["News_Title"] = "更新内容",
        ["News_110_1"] = "バージョン、ソースコード、プライバシー ポリシーをまとめた「Glyfo について」を追加しました。",
        ["News_110_2"] = "ストアに移動せず、ウィンドウの中でそのまま評価できるようになりました。",
        ["News_110_3"] = "新しいバージョンを初めて開いたときに、この更新内容を表示します。",
        ["News_110_4"] = "キャプチャに画面全体が加わりました。撮る前にウィンドウを隠すので、Glyfo が写り込むことはありません。",
        ["Rate_Title"] = "Glyfo は役に立っていますか",
        ["Rate_Body"] = "ストアの評価は、ほかの人がこのアプリを見つける手がかりになります。ほんの少しの手間です。",
        ["Rate_Action"] = "評価する",
        ["Rate_Later"] = "後で",
    };
}
