using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Vi = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR của Windows · chưa có gói ngôn ngữ",
        ["Engine_OneLanguage"] = "OCR của Windows · 1 ngôn ngữ",
        ["Engine_ManyLanguages"] = "OCR của Windows · {0} ngôn ngữ",
        ["Engine_OnDevice"] = "{0} · trên thiết bị",

        ["Preview_Placeholder"] = "Thả một ảnh vào đây, hoặc dùng Tệp, Chụp màn hình hay Bảng nhớ tạm ở bên dưới",
        ["Btn_CopyImage"] = "Sao chép",
        ["Tip_CopyImage"] = "Sao chép ảnh vào bảng nhớ tạm",
        ["Btn_SaveImage"] = "Lưu",
        ["Tip_SaveImage"] = "Lưu ảnh thành…",
        ["Btn_FitToWindow"] = "Vừa khung",
        ["Tip_FitToWindow"] = "Thu phóng cho vừa cửa sổ",
        ["Tip_ActualSize"] = "Kích thước điểm ảnh thật",
        ["Tip_PdfPrev"] = "Trang trước",
        ["Tip_PdfNext"] = "Trang sau",
        ["Action_Open"] = "Mở liên kết",
        ["Action_Mail"] = "Gửi thư tới",
        ["Action_Call"] = "Gọi",
        ["Action_Search"] = "Tìm trên web",

        ["Voice_Placeholder"] = "Giọng đọc",
        ["Tip_Voice"] = "Giọng dùng để đọc thành tiếng",
        ["Tip_Speak"] = "Đọc to văn bản",
        ["Tip_StopSpeak"] = "Dừng đọc",
        ["Tip_CopyText"] = "Sao chép văn bản (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Nối dòng",
        ["Tip_RemoveLineBreaks"] = "Nối các dấu xuống dòng cứng trở lại thành đoạn văn",
        ["Btn_RemoveSpaces"] = "Bỏ khoảng trắng",
        ["Tip_RemoveSpaces"] = "Xóa toàn bộ khoảng trắng — dành cho tiếng Trung, Nhật và Hàn",
        ["Result_Placeholder"] = "Văn bản nhận dạng được sẽ hiện ở đây và có thể chỉnh sửa.",

        ["Btn_OpenFile"] = "Tệp",
        ["Tip_OpenFile"] = "Mở một tệp ảnh (Ctrl+O)",
        ["Btn_Capture"] = "Chụp màn hình",
        ["Tip_Capture"] = "Chọn một vùng màn hình rồi nhận dạng ({0}). Nhấn Ctrl+Shift+R để lấy toàn màn hình.",
        ["Hotkey_Unavailable"] = "không có phím tắt — một ứng dụng khác đã chiếm cả hai",
        ["Btn_Paste"] = "Bảng nhớ tạm",
        ["Tip_Paste"] = "Nạp ảnh hoặc văn bản từ bảng nhớ tạm (Ctrl+V)",
        ["Btn_History"] = "Lịch sử",
        ["Tip_History"] = "Kết quả gần đây",
        ["History_Empty"] = "Chưa nhận dạng gì cả.",
        ["History_EmptyPreview"] = "(trống)",
        ["Tip_Settings"] = "Tùy chọn",
        ["Settings_Header"] = "Tùy chọn",
        ["Setting_UiLanguage"] = "Ngôn ngữ ứng dụng",
        ["Lang_SystemDefault"] = "Mặc định của hệ thống",
        ["Setting_RepairNumbers"] = "Sửa l và I nằm trong số",
        ["Setting_RepairNumbers_Desc"] = "Các bộ nhận dạng thường đọc v1.6.5 thành vl.6.5. Khi bật tùy chọn này, chữ l hoặc I chỉ đổi thành số 1 ở nơi có dấu phân cách và chữ số nằm kề bên, nên html5 và IPv6 vẫn nguyên vẹn. Khi tắt, kết quả đọc của bộ máy được giữ đúng như nó vốn có.",
        ["Setting_WatchClipboard"] = "Đọc ảnh tôi sao chép",
        ["Setting_WatchClipboard_Desc"] = "Chụp màn hình bằng Win+Shift+S và Glyfo đọc ngay, rồi đặt văn bản vào clipboard thay cho ảnh, nên lần dán tiếp theo sẽ là văn bản. Chỉ ảnh mới được đọc, không bao giờ đọc văn bản đã sao chép, và không có gì được gửi đi đâu — mọi thứ diễn ra trên thiết bị này.",
        ["Common_On"] = "Bật",
        ["Common_Off"] = "Tắt",
        ["Lang_Placeholder"] = "Ngôn ngữ",
        ["Tip_OcrLanguage"] = "Ngôn ngữ nhận dạng, lấy từ các gói ngôn ngữ đã cài trong Windows",
        ["Btn_Translate"] = "Dịch",
        ["Tip_Translate"] = "Dịch ngay trên thiết bị này — không có gì được gửi qua mạng",
        ["Btn_Barcode"] = "Mã",
        ["Tip_Barcode"] = "Đọc mã QR và mã vạch trong ảnh",
        ["Btn_Recognize"] = "Nhận dạng",
        ["Tip_Recognize"] = "Nhận dạng văn bản trong ảnh (F5)",

        ["Option_AutoAi"] = "Tự động (Windows AI)",
        ["Option_AutoMulti"] = "Tự động (nhiều ngôn ngữ · chậm hơn)",

        ["Status_Loaded"] = "Đã nạp {0}.",
        ["Status_OpenFailed"] = "Không mở được ảnh: {0}",
        ["Status_ClipboardText"] = "Đã nạp văn bản từ bảng nhớ tạm.",
        ["Status_ClipboardEmpty"] = "Bảng nhớ tạm không chứa ảnh lẫn văn bản.",
        ["Status_ClipboardFailed"] = "Không đọc được bảng nhớ tạm: {0}",
        ["Status_DropFailed"] = "Không dùng được nội dung vừa thả: {0}",
        ["Status_ImageCopied"] = "Đã sao chép ảnh vào bảng nhớ tạm.",
        ["Status_ImageCopyFailed"] = "Không sao chép được ảnh: {0}",
        ["Status_ImageSaved"] = "Đã lưu ảnh thành {0}.",
        ["Status_ImageSaveFailed"] = "Không lưu được ảnh: {0}",
        ["Status_Recognizing"] = "Đang nhận dạng…",
        ["Status_NoText"] = "{0} không tìm thấy văn bản nào trong ảnh này.",
        ["Status_Done"] = "Xong ({0}).",
        ["Status_DoneConfidence"] = "Xong ({0}) · độ tin cậy trung bình {1}%.",
        ["Status_RecognizeFailed"] = "Nhận dạng thất bại: {0}",
        ["Status_Scanning"] = "Đang tìm mã QR và mã vạch…",
        ["Status_NoBarcode"] = "Không tìm thấy mã QR hay mã vạch nào trong ảnh này.",
        ["Status_BarcodeOne"] = "Tìm thấy một mã {0}.",
        ["Status_BarcodeMany"] = "Tìm thấy {0} mã.",
        ["Status_ScanFailed"] = "Quét thất bại: {0}",
        ["Status_PdfFailed"] = "không đọc được tệp PDF này — có thể nó được bảo vệ bằng mật khẩu hoặc đã hỏng",
        ["Status_LaunchFailed"] = "Windows không tìm thấy gì để mở thứ đó.",
        ["Status_NothingToTranslate"] = "Không có văn bản để dịch.",
        ["Status_Translating"] = "Đang dịch sang {0} trên thiết bị này…",
        ["Status_Translated"] = "Đã dịch sang {0}, ngay trên thiết bị này, không cần mạng.",
        ["Status_TranslateFailed"] = "Dịch thất bại: {0}",
        ["Status_NothingToCopy"] = "Không có văn bản để sao chép.",
        ["Status_TextCopied"] = "Đã sao chép văn bản vào bảng nhớ tạm.",
        ["Status_CopyFailed"] = "Không sao chép được văn bản: {0}",
        ["Status_NothingToSpeak"] = "Không có văn bản để đọc.",
        ["Status_SpeakFailed"] = "Không đọc được văn bản: {0}",
        ["Status_HistoryLoaded"] = "Đang hiển thị kết quả lúc {0}.",
        ["Status_NeedImage"] = "Hãy nạp một ảnh trước đã.",
        ["Status_CaptureFailed"] = "Chụp màn hình thất bại: {0}",
        ["Status_StartupBlockedByUser"] = "Windows đã tắt khởi động cùng hệ thống cho Glyfo. Hãy bật lại trong Trình quản lý tác vụ, ở mục Ứng dụng khởi động.",
        ["Status_StartupBlockedByPolicy"] = "Tổ chức của bạn không cho phép ứng dụng khởi động cùng Windows.",
        ["Status_LanguagePackMissing"] = "Windows chưa cài gói ngôn ngữ OCR nào nên không có gì để nhận dạng. Hãy thêm ngôn ngữ bạn cần trong Thời gian và ngôn ngữ, rồi Ngôn ngữ và khu vực.",
        ["Btn_OpenLanguageSettings"] = "Mở cài đặt ngôn ngữ",

        ["Tray_Open"] = "Mở Glyfo",
        ["Tray_CaptureRegion"] = "Chụp một vùng",
        ["Tray_CaptureFullScreen"] = "Chụp toàn màn hình",
        ["Tray_Exit"] = "Thoát",
        ["Tray_Tooltip"] = "Glyfo — nhấn {0} để chụp một vùng",
        ["Toast_StartupTitle"] = "Glyfo đang chạy",
        ["Toast_StartupBody"] = "Nhấn {0} để chọn một vùng màn hình và đọc chữ trong đó. Ctrl+Shift+R lấy toàn màn hình.",
        ["Toast_DontRemind"] = "Không nhắc nữa",
        ["Toast_MinimizedTitle"] = "Glyfo vẫn đang chạy",
        ["Toast_MinimizedBody"] = "Nhấn {0} bất cứ lúc nào để chụp và nhận dạng. Để đóng hẳn, hãy bấm chuột phải vào biểu tượng của nó trong vùng thông báo rồi chọn Thoát.",
        ["Toast_ExitApp"] = "Thoát Glyfo",
        ["Toast_ResultTitle"] = "Đã nhận dạng chữ",
        ["Toast_ResultCopied"] = "Đã sao chép vào bảng nhớ tạm.",
        ["Toast_OpenWindow"] = "Mở cửa sổ",
        ["Toast_NoTextTitle"] = "Không tìm thấy chữ",
        ["Toast_NoTextBody"] = "Trong vùng đó không có gì đọc được thành chữ.",
        ["Toast_FailedTitle"] = "Nhận dạng thất bại",
        ["Toast_HotkeyUnavailableTitle"] = "Phím tắt chụp đang bị chiếm",
        ["Toast_HotkeyUnavailableBody"] = "Một ứng dụng khác đã giữ phím tắt này, nên chỉ có thể chụp màn hình từ cửa sổ và từ biểu tượng trong vùng thông báo.",
        ["Setting_CloseToTray"] = "Tiếp tục chạy khi đóng cửa sổ",
        ["Setting_CloseToTray_Desc"] = "Khi bật, đóng cửa sổ vẫn để Glyfo chạy để phím tắt chụp tiếp tục hoạt động, và biểu tượng của nó vẫn ở trong vùng thông báo, nơi lệnh Thoát sẽ đóng hẳn chương trình. Khi tắt, đóng cửa sổ là thoát ứng dụng.",
        ["Setting_Startup"] = "Khởi động cùng Windows",
        ["Setting_Startup_Desc"] = "Khi bật, Glyfo khởi động cùng Windows và vào thẳng khu vực thông báo mà không mở cửa sổ, nên phím tắt chụp màn hình dùng được ngay từ lúc bạn đăng nhập.",

        ["Source_Clipboard"] = "ảnh từ bảng nhớ tạm",
        ["Source_Dropped"] = "ảnh vừa thả vào",
        ["Source_Shared"] = "ảnh được chia sẻ",
        ["Source_FullScreen"] = "Toàn màn hình",
        ["Source_Region"] = "Vùng màn hình",
        ["Source_Codes"] = "{0} (mã)",

        ["FileType_Image"] = "Ảnh {0}",

        ["Region_Hint"] = "Kéo để chọn một vùng　·　Esc hoặc bấm chuột phải để hủy",

        ["Err_NoLanguagePack"] = "Windows chưa cài gói ngôn ngữ OCR cho ngôn ngữ này. Hãy thêm một gói trong Thời gian và ngôn ngữ, rồi Ngôn ngữ và khu vực.",
        ["Err_TextTooLong"] = "Văn bản quá dài đối với mô hình trên thiết bị. Hãy dịch một phần ngắn hơn.",
        ["Err_ModelDeclined"] = "Mô hình trên thiết bị đã từ chối dịch văn bản này.",
        ["Err_TranslationFailed"] = "Bản dịch trên thiết bị không trả về kết quả nào.",
        ["Btn_About"] = "Giới thiệu về Glyfo",
        ["About_Title"] = "Giới thiệu về Glyfo",
        ["About_Version"] = "Phiên bản {0}",
        ["About_Tagline"] = "Đọc chữ trong mọi hình ảnh, ngay trên thiết bị này. Không có gì được gửi qua mạng.",
        ["About_Rate"] = "Đánh giá Glyfo",
        ["About_WhatsNew"] = "Có gì mới",
        ["About_Source"] = "Mã nguồn trên GitHub",
        ["About_Privacy"] = "Chính sách quyền riêng tư",
        ["Common_Close"] = "Đóng",
        ["News_Title"] = "Có gì mới",
        ["News_120_1"] = "Chụp màn hình bằng Win+Shift+S và Glyfo đọc giúp bạn, để lại văn bản trong clipboard. Tính năng tắt cho tới khi bạn bật trong tùy chọn.",
        ["News_120_2"] = "Giờ đây có thể mở PDF như ảnh, từng trang một.",
        ["News_120_3"] = "Liên kết, địa chỉ e-mail và số điện thoại tìm thấy trong văn bản sẽ có nút ở bên dưới.",
        ["News_110_1"] = "Trang Giới thiệu, có số phiên bản cùng liên kết tới mã nguồn và chính sách quyền riêng tư.",
        ["News_110_2"] = "Bạn có thể đánh giá Glyfo mà không cần rời khỏi cửa sổ.",
        ["News_110_3"] = "Chính những ghi chú này, hiện một lần mỗi khi có phiên bản mới.",
        ["News_110_4"] = "Chụp giờ có thêm toàn màn hình, và cửa sổ được ẩn trước nên Glyfo không bao giờ lọt vào ảnh.",
        ["Rate_Title"] = "Glyfo có giúp được gì cho bạn không?",
        ["Rate_Body"] = "Đánh giá trên Store là cách để người khác tìm thấy ứng dụng. Chỉ mất một chút thời gian.",
        ["Rate_Action"] = "Đánh giá",
        ["Rate_Later"] = "Để sau",
    };
}
