using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Nl = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows-OCR · geen taalpakket",
        ["Engine_OneLanguage"] = "Windows-OCR · 1 taal",
        ["Engine_ManyLanguages"] = "Windows-OCR · {0} talen",
        ["Engine_OnDevice"] = "{0} · op het apparaat",

        ["Preview_Placeholder"] = "Sleep hier een afbeelding naartoe, of gebruik hieronder Bestand, Opname of Klembord",
        ["Btn_CopyImage"] = "Kopiëren",
        ["Tip_CopyImage"] = "De afbeelding naar het klembord kopiëren",
        ["Btn_SaveImage"] = "Opslaan",
        ["Tip_SaveImage"] = "Afbeelding opslaan als…",
        ["Btn_FitToWindow"] = "Passend",
        ["Tip_FitToWindow"] = "Inzoomen tot het venster past",
        ["Tip_ActualSize"] = "Werkelijke pixelgrootte",

        ["Voice_Placeholder"] = "Stem",
        ["Tip_Voice"] = "Stem waarmee wordt voorgelezen",
        ["Tip_Speak"] = "De tekst voorlezen",
        ["Tip_StopSpeak"] = "Voorlezen stoppen",
        ["Tip_CopyText"] = "De tekst kopiëren (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Geen einden",
        ["Tip_RemoveLineBreaks"] = "Harde regeleinden weer tot alinea's samenvoegen",
        ["Btn_RemoveSpaces"] = "Geen spaties",
        ["Tip_RemoveSpaces"] = "Alle spaties verwijderen, voor Chinees, Japans en Koreaans",
        ["Result_Placeholder"] = "De herkende tekst verschijnt hier en kan worden bewerkt.",

        ["Btn_OpenFile"] = "Bestand",
        ["Tip_OpenFile"] = "Een afbeeldingsbestand openen (Ctrl+O)",
        ["Btn_Capture"] = "Opname",
        ["Tip_Capture"] = "Een schermgebied selecteren en herkennen ({0}). Druk op Ctrl+Shift+R voor het hele scherm.",
        ["Hotkey_Unavailable"] = "geen sneltoets — een andere app heeft ze allebei bezet",
        ["Btn_Paste"] = "Klembord",
        ["Tip_Paste"] = "Een afbeelding of tekst van het klembord laden (Ctrl+V)",
        ["Btn_History"] = "Geschiedenis",
        ["Tip_History"] = "Recente resultaten",
        ["History_Empty"] = "Er is nog niets herkend.",
        ["History_EmptyPreview"] = "(leeg)",
        ["Tip_Settings"] = "Opties",
        ["Settings_Header"] = "Opties",
        ["Setting_UiLanguage"] = "Taal van de app",
        ["Lang_SystemDefault"] = "Systeemstandaard",
        ["Setting_RepairNumbers"] = "l en I in getallen corrigeren",
        ["Setting_RepairNumbers_Desc"] = "Herkenners lezen v1.6.5 geregeld als vl.6.5. Staat dit aan, dan wordt een l of I alleen een 1 waar er een scheidingsteken en een cijfer naast staan, zodat html5 en IPv6 met rust worden gelaten. Staat het uit, dan blijft de lezing van de engine precies zoals die binnenkwam.",
        ["Common_On"] = "Aan",
        ["Common_Off"] = "Uit",
        ["Lang_Placeholder"] = "Taal",
        ["Tip_OcrLanguage"] = "Herkenningstaal, uit de taalpakketten die Windows heeft geïnstalleerd",
        ["Btn_Translate"] = "Vertalen",
        ["Tip_Translate"] = "Op dit apparaat vertalen — er wordt niets over het netwerk verstuurd",
        ["Btn_Barcode"] = "Codes",
        ["Tip_Barcode"] = "QR-codes en streepjescodes in de afbeelding lezen",
        ["Btn_Recognize"] = "Herkennen",
        ["Tip_Recognize"] = "De tekst in de afbeelding herkennen (F5)",

        ["Option_AutoAi"] = "Automatisch (Windows AI)",
        ["Option_AutoMulti"] = "Automatisch (meertalig · trager)",

        ["Status_Loaded"] = "{0} geladen.",
        ["Status_OpenFailed"] = "De afbeelding kon niet worden geopend: {0}",
        ["Status_ClipboardText"] = "Tekst van het klembord geladen.",
        ["Status_ClipboardEmpty"] = "Op het klembord staat geen afbeelding en geen tekst.",
        ["Status_ClipboardFailed"] = "Het klembord kon niet worden gelezen: {0}",
        ["Status_DropFailed"] = "Het gesleepte item kon niet worden gebruikt: {0}",
        ["Status_ImageCopied"] = "Afbeelding naar het klembord gekopieerd.",
        ["Status_ImageCopyFailed"] = "De afbeelding kon niet worden gekopieerd: {0}",
        ["Status_ImageSaved"] = "Afbeelding opgeslagen als {0}.",
        ["Status_ImageSaveFailed"] = "De afbeelding kon niet worden opgeslagen: {0}",
        ["Status_Recognizing"] = "Bezig met herkennen…",
        ["Status_NoText"] = "{0} heeft geen tekst in deze afbeelding gevonden.",
        ["Status_Done"] = "Klaar ({0}).",
        ["Status_DoneConfidence"] = "Klaar ({0}) · gemiddelde betrouwbaarheid {1}%.",
        ["Status_RecognizeFailed"] = "De herkenning is mislukt: {0}",
        ["Status_Scanning"] = "Er wordt naar QR-codes en streepjescodes gezocht…",
        ["Status_NoBarcode"] = "Geen QR-code of streepjescode in deze afbeelding gevonden.",
        ["Status_BarcodeOne"] = "Eén {0}-code gevonden.",
        ["Status_BarcodeMany"] = "{0} codes gevonden.",
        ["Status_ScanFailed"] = "Het scannen is mislukt: {0}",
        ["Status_NothingToTranslate"] = "Er is geen tekst om te vertalen.",
        ["Status_Translating"] = "Bezig met vertalen naar het {0} op dit apparaat…",
        ["Status_Translated"] = "Vertaald naar het {0}, op dit apparaat, zonder netwerktoegang.",
        ["Status_TranslateFailed"] = "De vertaling is mislukt: {0}",
        ["Status_NothingToCopy"] = "Er is geen tekst om te kopiëren.",
        ["Status_TextCopied"] = "Tekst naar het klembord gekopieerd.",
        ["Status_CopyFailed"] = "De tekst kon niet worden gekopieerd: {0}",
        ["Status_NothingToSpeak"] = "Er is geen tekst om voor te lezen.",
        ["Status_SpeakFailed"] = "De tekst kon niet worden voorgelezen: {0}",
        ["Status_HistoryLoaded"] = "Het resultaat van {0} wordt getoond.",
        ["Status_NeedImage"] = "Laad eerst een afbeelding.",
        ["Status_CaptureFailed"] = "De schermopname is mislukt: {0}",
        ["Status_StartupBlockedByUser"] = "Windows heeft het automatisch starten van Glyfo uitgeschakeld. Zet het weer aan in Taakbeheer, bij Opstart-apps.",
        ["Status_StartupBlockedByPolicy"] = "Uw organisatie staat niet toe dat apps met Windows meestarten.",
        ["Status_LanguagePackMissing"] = "In Windows is geen OCR-taalpakket geïnstalleerd, dus er is niets om mee te herkennen. Voeg de taal die je nodig hebt toe bij Tijd en taal, dan Taal en regio.",
        ["Btn_OpenLanguageSettings"] = "Taalinstellingen openen",

        ["Tray_Open"] = "Glyfo openen",
        ["Tray_CaptureRegion"] = "Een gebied vastleggen",
        ["Tray_CaptureFullScreen"] = "Het hele scherm vastleggen",
        ["Tray_Exit"] = "Afsluiten",
        ["Tray_Tooltip"] = "Glyfo — druk op {0} om een gebied vast te leggen",
        ["Toast_StartupTitle"] = "Glyfo draait",
        ["Toast_StartupBody"] = "Druk op {0} om een deel van het scherm te selecteren en de tekst erin te lezen. Ctrl+Shift+R legt het hele scherm vast.",
        ["Toast_DontRemind"] = "Niet meer herinneren",
        ["Toast_MinimizedTitle"] = "Glyfo draait nog",
        ["Toast_MinimizedBody"] = "Druk wanneer u wilt op {0} om vast te leggen en te herkennen. Om het echt af te sluiten klikt u met de rechtermuisknop op het pictogram in het systeemvak en kiest u Afsluiten.",
        ["Toast_ExitApp"] = "Glyfo afsluiten",
        ["Toast_ResultTitle"] = "Tekst herkend",
        ["Toast_ResultCopied"] = "Naar het klembord gekopieerd.",
        ["Toast_OpenWindow"] = "Venster openen",
        ["Toast_NoTextTitle"] = "Geen tekst gevonden",
        ["Toast_NoTextBody"] = "In dat gebied was niets als tekst te lezen.",
        ["Toast_FailedTitle"] = "Herkenning mislukt",
        ["Toast_HotkeyUnavailableTitle"] = "De sneltoets is bezet",
        ["Toast_HotkeyUnavailableBody"] = "Een andere app heeft hem al, dus schermopname kan alleen vanuit het venster en vanaf het pictogram in het systeemvak.",
        ["Setting_CloseToTray"] = "Blijven draaien als het venster wordt gesloten",
        ["Setting_CloseToTray_Desc"] = "Als dit aanstaat, blijft Glyfo draaien nadat u het venster sluit, zodat de sneltoets blijft werken; het pictogram blijft in het systeemvak, waar Afsluiten het programma definitief sluit. Staat het uit, dan beëindigt het sluiten van het venster de app.",
        ["Setting_Startup"] = "Met Windows starten",
        ["Setting_Startup_Desc"] = "Als dit aanstaat, start Glyfo met Windows en gaat het meteen naar het systeemvak zonder een venster te openen, zodat de opnamesneltoets werkt vanaf het aanmelden.",

        ["Source_Clipboard"] = "de afbeelding van het klembord",
        ["Source_Dropped"] = "de gesleepte afbeelding",
        ["Source_Shared"] = "de gedeelde afbeelding",
        ["Source_FullScreen"] = "Volledig scherm",
        ["Source_Region"] = "Schermgebied",
        ["Source_Codes"] = "{0} (codes)",

        ["FileType_Image"] = "{0}-afbeelding",

        ["Region_Hint"] = "Sleep om een gebied te selecteren　·　Esc of rechtermuisknop annuleert",

        ["Err_NoLanguagePack"] = "In Windows is voor deze taal geen OCR-taalpakket geïnstalleerd. Voeg er een toe bij Tijd en taal, dan Taal en regio.",
        ["Err_TextTooLong"] = "De tekst is te lang voor het model op het apparaat. Vertaal een kleiner stuk.",
        ["Err_ModelDeclined"] = "Het model op het apparaat heeft geweigerd deze tekst te vertalen.",
        ["Err_TranslationFailed"] = "De vertaling op het apparaat heeft geen resultaat opgeleverd.",
    };
}
