using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Hi = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · कोई भाषा पैक नहीं",
        ["Engine_OneLanguage"] = "Windows OCR · 1 भाषा",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} भाषाएँ",
        ["Engine_OnDevice"] = "{0} · डिवाइस पर",

        ["Preview_Placeholder"] = "यहाँ कोई चित्र छोड़ें, या नीचे दिए फ़ाइल, स्क्रीन कैप्चर या क्लिपबोर्ड का उपयोग करें",
        ["Btn_CopyImage"] = "कॉपी करें",
        ["Tip_CopyImage"] = "चित्र को क्लिपबोर्ड पर कॉपी करें",
        ["Btn_SaveImage"] = "सहेजें",
        ["Tip_SaveImage"] = "चित्र इस रूप में सहेजें…",
        ["Btn_FitToWindow"] = "फ़िट करें",
        ["Tip_FitToWindow"] = "ज़ूम इतना करें कि चित्र विंडो में समा जाए",
        ["Tip_ActualSize"] = "वास्तविक पिक्सेल आकार",

        ["Voice_Placeholder"] = "आवाज़",
        ["Tip_Voice"] = "पढ़कर सुनाने के लिए इस्तेमाल होने वाली आवाज़",
        ["Tip_Speak"] = "पाठ को पढ़कर सुनाएँ",
        ["Tip_StopSpeak"] = "पढ़ना रोकें",
        ["Tip_CopyText"] = "पाठ कॉपी करें (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "पंक्तियाँ जोड़ें",
        ["Tip_RemoveLineBreaks"] = "पंक्ति विरामों को दोबारा अनुच्छेद में जोड़ें",
        ["Btn_RemoveSpaces"] = "रिक्तियाँ हटाएँ",
        ["Tip_RemoveSpaces"] = "सारी रिक्तियाँ हटा दें — चीनी, जापानी और कोरियाई के लिए",
        ["Result_Placeholder"] = "पहचाना गया पाठ यहाँ दिखेगा और उसे संपादित किया जा सकता है।",

        ["Btn_OpenFile"] = "फ़ाइल",
        ["Tip_OpenFile"] = "कोई चित्र फ़ाइल खोलें (Ctrl+O)",
        ["Btn_Capture"] = "स्क्रीन कैप्चर",
        ["Tip_Capture"] = "स्क्रीन का कोई हिस्सा चुनें और उसे पहचानें ({0})। पूरी स्क्रीन के लिए Ctrl+Shift+R दबाएँ।",
        ["Hotkey_Unavailable"] = "कोई शॉर्टकट नहीं — दोनों किसी दूसरे ऐप ने ले रखे हैं",
        ["Btn_Paste"] = "क्लिपबोर्ड",
        ["Tip_Paste"] = "क्लिपबोर्ड से चित्र या पाठ लें (Ctrl+V)",
        ["Btn_History"] = "इतिहास",
        ["Tip_History"] = "हाल के परिणाम",
        ["History_Empty"] = "अभी तक कुछ भी पहचाना नहीं गया।",
        ["History_EmptyPreview"] = "(खाली)",
        ["Tip_Settings"] = "विकल्प",
        ["Settings_Header"] = "विकल्प",
        ["Setting_UiLanguage"] = "ऐप की भाषा",
        ["Lang_SystemDefault"] = "सिस्टम की डिफ़ॉल्ट",
        ["Setting_RepairNumbers"] = "संख्याओं के भीतर l और I सुधारें",
        ["Setting_RepairNumbers_Desc"] = "पहचान इंजन अक्सर v1.6.5 को vl.6.5 पढ़ लेते हैं। यह चालू होने पर l या I सिर्फ़ वहीं 1 बनता है जहाँ बगल में विभाजक और अंक हों, इसलिए html5 और IPv6 ज्यों के त्यों रहते हैं। बंद होने पर इंजन ने जो पढ़ा है वही ठीक वैसा ही रखा जाता है।",
        ["Common_On"] = "चालू",
        ["Common_Off"] = "बंद",
        ["Lang_Placeholder"] = "भाषा",
        ["Tip_OcrLanguage"] = "पहचान की भाषा, Windows में स्थापित भाषा पैकों में से",
        ["Btn_Translate"] = "अनुवाद करें",
        ["Tip_Translate"] = "इसी डिवाइस पर अनुवाद करें — नेटवर्क पर कुछ नहीं भेजा जाता",
        ["Btn_Barcode"] = "कोड",
        ["Tip_Barcode"] = "चित्र में मौजूद QR कोड और बारकोड पढ़ें",
        ["Btn_Recognize"] = "पहचानें",
        ["Tip_Recognize"] = "चित्र में मौजूद पाठ पहचानें (F5)",

        ["Option_AutoAi"] = "स्वचालित (Windows AI)",
        ["Option_AutoMulti"] = "स्वचालित (कई भाषाएँ · धीमा)",

        ["Status_Loaded"] = "{0} लोड हो गया।",
        ["Status_OpenFailed"] = "चित्र खोला नहीं जा सका: {0}",
        ["Status_ClipboardText"] = "क्लिपबोर्ड से पाठ लिया गया।",
        ["Status_ClipboardEmpty"] = "क्लिपबोर्ड में न चित्र है न पाठ।",
        ["Status_ClipboardFailed"] = "क्लिपबोर्ड पढ़ा नहीं जा सका: {0}",
        ["Status_DropFailed"] = "छोड़ी गई वस्तु का उपयोग नहीं हो सका: {0}",
        ["Status_ImageCopied"] = "चित्र क्लिपबोर्ड पर कॉपी हो गया।",
        ["Status_ImageCopyFailed"] = "चित्र कॉपी नहीं हो सका: {0}",
        ["Status_ImageSaved"] = "चित्र {0} के रूप में सहेजा गया।",
        ["Status_ImageSaveFailed"] = "चित्र सहेजा नहीं जा सका: {0}",
        ["Status_Recognizing"] = "पहचाना जा रहा है…",
        ["Status_NoText"] = "{0} को इस चित्र में कोई पाठ नहीं मिला।",
        ["Status_Done"] = "पूरा हुआ ({0})।",
        ["Status_DoneConfidence"] = "पूरा हुआ ({0}) · औसत विश्वास {1}%।",
        ["Status_RecognizeFailed"] = "पहचान विफल रही: {0}",
        ["Status_Scanning"] = "QR कोड और बारकोड खोजे जा रहे हैं…",
        ["Status_NoBarcode"] = "इस चित्र में कोई QR कोड या बारकोड नहीं मिला।",
        ["Status_BarcodeOne"] = "एक {0} कोड मिला।",
        ["Status_BarcodeMany"] = "{0} कोड मिले।",
        ["Status_ScanFailed"] = "खोज विफल रही: {0}",
        ["Status_NothingToTranslate"] = "अनुवाद के लिए कोई पाठ नहीं है।",
        ["Status_Translating"] = "इसी डिवाइस पर {0} में अनुवाद हो रहा है…",
        ["Status_Translated"] = "{0} में अनुवाद हुआ — इसी डिवाइस पर, बिना नेटवर्क के।",
        ["Status_TranslateFailed"] = "अनुवाद विफल रहा: {0}",
        ["Status_NothingToCopy"] = "कॉपी करने के लिए कोई पाठ नहीं है।",
        ["Status_TextCopied"] = "पाठ क्लिपबोर्ड पर कॉपी हो गया।",
        ["Status_CopyFailed"] = "पाठ कॉपी नहीं हो सका: {0}",
        ["Status_NothingToSpeak"] = "पढ़कर सुनाने के लिए कोई पाठ नहीं है।",
        ["Status_SpeakFailed"] = "पाठ पढ़कर सुनाया नहीं जा सका: {0}",
        ["Status_HistoryLoaded"] = "{0} का परिणाम दिखाया जा रहा है।",
        ["Status_NeedImage"] = "पहले कोई चित्र लोड करें।",
        ["Status_CaptureFailed"] = "स्क्रीन कैप्चर विफल रहा: {0}",
        ["Status_StartupBlockedByUser"] = "Windows ने Glyfo का स्टार्टअप बंद कर रखा है। इसे कार्य प्रबंधक में स्टार्टअप ऐप्स के अंतर्गत फिर से चालू करें।",
        ["Status_StartupBlockedByPolicy"] = "आपका संगठन ऐप्स को Windows के साथ शुरू होने की अनुमति नहीं देता।",
        ["Status_LanguagePackMissing"] = "Windows में कोई OCR भाषा पैक स्थापित नहीं है, इसलिए पहचानने के लिए कुछ है ही नहीं। जो भाषा चाहिए उसे समय और भाषा में, फिर भाषा और क्षेत्र में जोड़ें।",
        ["Btn_OpenLanguageSettings"] = "भाषा सेटिंग खोलें",

        ["Tray_Open"] = "Glyfo खोलें",
        ["Tray_CaptureRegion"] = "कोई क्षेत्र कैप्चर करें",
        ["Tray_CaptureFullScreen"] = "पूरी स्क्रीन कैप्चर करें",
        ["Tray_Exit"] = "बाहर निकलें",
        ["Tray_Tooltip"] = "Glyfo — कोई क्षेत्र कैप्चर करने के लिए {0} दबाएँ",
        ["Toast_StartupTitle"] = "Glyfo चल रहा है",
        ["Toast_StartupBody"] = "स्क्रीन का कोई हिस्सा चुनकर उसका पाठ पढ़ने के लिए {0} दबाएँ। पूरी स्क्रीन के लिए Ctrl+Shift+R दबाएँ।",
        ["Toast_DontRemind"] = "फिर याद न दिलाएँ",
        ["Toast_MinimizedTitle"] = "Glyfo अब भी चल रहा है",
        ["Toast_MinimizedBody"] = "कैप्चर और पहचान के लिए कभी भी {0} दबाएँ। पूरी तरह बंद करने के लिए सूचना क्षेत्र में इसके आइकॉन पर दायाँ क्लिक करें और बाहर निकलें चुनें।",
        ["Toast_ExitApp"] = "Glyfo से बाहर निकलें",
        ["Toast_ResultTitle"] = "पाठ पहचाना गया",
        ["Toast_ResultCopied"] = "क्लिपबोर्ड पर कॉपी हो गया।",
        ["Toast_OpenWindow"] = "विंडो खोलें",
        ["Toast_NoTextTitle"] = "कोई पाठ नहीं मिला",
        ["Toast_NoTextBody"] = "उस क्षेत्र में पाठ के रूप में पढ़ने लायक कुछ नहीं था।",
        ["Toast_FailedTitle"] = "पहचान विफल रही",
        ["Toast_HotkeyUnavailableTitle"] = "कैप्चर शॉर्टकट व्यस्त है",
        ["Toast_HotkeyUnavailableBody"] = "इसे पहले ही कोई दूसरा ऐप ले चुका है, इसलिए स्क्रीन कैप्चर केवल विंडो से और सूचना क्षेत्र के आइकॉन से ही किया जा सकता है।",
        ["Setting_CloseToTray"] = "विंडो बंद करने पर चलता रहे",
        ["Setting_CloseToTray_Desc"] = "यह चालू होने पर विंडो बंद करने के बाद भी Glyfo चलता रहता है, जिससे कैप्चर शॉर्टकट काम करता रहता है और इसका आइकॉन सूचना क्षेत्र में बना रहता है, जहाँ बाहर निकलें चुनने पर यह पूरी तरह बंद होता है। बंद होने पर विंडो बंद करते ही ऐप समाप्त हो जाता है।",
        ["Setting_Startup"] = "Windows के साथ शुरू करें",
        ["Setting_Startup_Desc"] = "यह चालू होने पर Glyfo Windows के साथ शुरू होता है और बिना विंडो खोले सीधे सूचना क्षेत्र में चला जाता है, इसलिए साइन इन करते ही कैप्चर शॉर्टकट काम करने लगता है।",

        ["Source_Clipboard"] = "क्लिपबोर्ड का चित्र",
        ["Source_Dropped"] = "छोड़ा गया चित्र",
        ["Source_Shared"] = "साझा की गई छवि",
        ["Source_FullScreen"] = "पूरी स्क्रीन",
        ["Source_Region"] = "स्क्रीन का हिस्सा",
        ["Source_Codes"] = "{0} (कोड)",

        ["FileType_Image"] = "{0} चित्र",

        ["Region_Hint"] = "क्षेत्र चुनने के लिए खींचें　·　Esc या दायाँ क्लिक रद्द कर देता है",

        ["Err_NoLanguagePack"] = "इस भाषा के लिए Windows में कोई OCR भाषा पैक स्थापित नहीं है। एक पैक समय और भाषा में, फिर भाषा और क्षेत्र में जोड़ें।",
        ["Err_TextTooLong"] = "यह पाठ डिवाइस पर चलने वाले मॉडल के लिए बहुत लंबा है। कोई छोटा हिस्सा अनुवाद करें।",
        ["Err_ModelDeclined"] = "डिवाइस पर चलने वाले मॉडल ने इस पाठ का अनुवाद करने से इनकार कर दिया।",
        ["Err_TranslationFailed"] = "डिवाइस पर हुए अनुवाद से कोई परिणाम नहीं मिला।",
        ["Btn_About"] = "Glyfo के बारे में",
        ["About_Title"] = "Glyfo के बारे में",
        ["About_Version"] = "संस्करण {0}",
        ["About_Tagline"] = "किसी भी छवि का पाठ इसी डिवाइस पर पढ़ता है। नेटवर्क पर कुछ नहीं भेजा जाता।",
        ["About_Rate"] = "Glyfo को रेटिंग दें",
        ["About_WhatsNew"] = "नया क्या है",
        ["About_Source"] = "GitHub पर स्रोत कोड",
        ["About_Privacy"] = "गोपनीयता नीति",
        ["Common_Close"] = "बंद करें",
        ["News_Title"] = "नया क्या है",
        ["News_110_1"] = "एक बारे में पृष्ठ, जिसमें संस्करण तथा स्रोत कोड और गोपनीयता नीति के लिंक हैं।",
        ["News_110_2"] = "आप विंडो छोड़े बिना Glyfo को रेटिंग दे सकते हैं।",
        ["News_110_3"] = "ये नोट, जो हर नए संस्करण पर एक बार दिखते हैं।",
        ["News_110_4"] = "कैप्चर अब पूरी स्क्रीन भी लेता है और पहले विंडो छिपा देता है, इसलिए Glyfo कभी तस्वीर में नहीं आता।",
        ["Rate_Title"] = "क्या Glyfo आपके काम आ रहा है?",
        ["Rate_Body"] = "Store में दी गई रेटिंग से ही दूसरे लोग इस ऐप तक पहुँचते हैं। इसमें बस एक पल लगता है।",
        ["Rate_Action"] = "रेटिंग दें",
        ["Rate_Later"] = "अभी नहीं",
    };
}
