using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Ms = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR Windows · tiada pek bahasa",
        ["Engine_OneLanguage"] = "OCR Windows · 1 bahasa",
        ["Engine_ManyLanguages"] = "OCR Windows · {0} bahasa",
        ["Engine_OnDevice"] = "{0} · pada peranti",

        ["Preview_Placeholder"] = "Lepaskan imej di sini, atau gunakan Fail, Tangkapan atau Papan keratan di bawah",
        ["Btn_CopyImage"] = "Salin",
        ["Tip_CopyImage"] = "Salin imej ke papan keratan",
        ["Btn_SaveImage"] = "Simpan",
        ["Tip_SaveImage"] = "Simpan imej sebagai…",
        ["Btn_FitToWindow"] = "Muat",
        ["Tip_FitToWindow"] = "Zum supaya muat dalam tetingkap",
        ["Tip_ActualSize"] = "Saiz piksel sebenar",

        ["Voice_Placeholder"] = "Suara",
        ["Tip_Voice"] = "Suara yang digunakan untuk membaca",
        ["Tip_Speak"] = "Baca teks dengan kuat",
        ["Tip_StopSpeak"] = "Hentikan bacaan",
        ["Tip_CopyText"] = "Salin teks (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Cantum baris",
        ["Tip_RemoveLineBreaks"] = "Cantumkan semula pemisah baris menjadi perenggan",
        ["Btn_RemoveSpaces"] = "Tanpa ruang",
        ["Tip_RemoveSpaces"] = "Buang semua ruang — untuk bahasa Cina, Jepun dan Korea",
        ["Result_Placeholder"] = "Teks yang dikenali muncul di sini dan boleh disunting.",

        ["Btn_OpenFile"] = "Fail",
        ["Tip_OpenFile"] = "Buka fail imej (Ctrl+O)",
        ["Btn_Capture"] = "Tangkapan",
        ["Tip_Capture"] = "Pilih kawasan skrin dan kenali ({0}). Tekan Ctrl+Shift+R untuk seluruh skrin.",
        ["Hotkey_Unavailable"] = "tiada pintasan — kedua-duanya telah diambil oleh apl lain",
        ["Btn_Paste"] = "Papan keratan",
        ["Tip_Paste"] = "Muatkan imej atau teks daripada papan keratan (Ctrl+V)",
        ["Btn_History"] = "Sejarah",
        ["Tip_History"] = "Keputusan terkini",
        ["History_Empty"] = "Belum ada apa-apa yang dikenali.",
        ["History_EmptyPreview"] = "(kosong)",
        ["Tip_Settings"] = "Pilihan",
        ["Settings_Header"] = "Pilihan",
        ["Setting_UiLanguage"] = "Bahasa apl",
        ["Lang_SystemDefault"] = "Lalai sistem",
        ["Setting_RepairNumbers"] = "Betulkan l dan I di dalam nombor",
        ["Setting_RepairNumbers_Desc"] = "Enjin pengecaman kerap membaca v1.6.5 sebagai vl.6.5. Apabila pilihan ini dihidupkan, huruf l atau I hanya menjadi 1 di tempat yang bersebelahan dengan pemisah dan digit, jadi html5 dan IPv6 kekal seperti asal. Apabila dimatikan, bacaan enjin dikekalkan tepat sebagaimana ia diterima.",
        ["Common_On"] = "Hidup",
        ["Common_Off"] = "Mati",
        ["Lang_Placeholder"] = "Bahasa",
        ["Tip_OcrLanguage"] = "Bahasa pengecaman, daripada pek bahasa yang dipasang dalam Windows",
        ["Btn_Translate"] = "Terjemah",
        ["Tip_Translate"] = "Terjemah pada peranti ini — tiada apa-apa dihantar melalui rangkaian",
        ["Btn_Barcode"] = "Kod",
        ["Tip_Barcode"] = "Baca kod QR dan kod bar dalam imej",
        ["Btn_Recognize"] = "Kenali",
        ["Tip_Recognize"] = "Kenali teks dalam imej (F5)",

        ["Option_AutoAi"] = "Automatik (Windows AI)",
        ["Option_AutoMulti"] = "Automatik (berbilang bahasa · lebih perlahan)",

        ["Status_Loaded"] = "{0} dimuatkan.",
        ["Status_OpenFailed"] = "Imej tidak dapat dibuka: {0}",
        ["Status_ClipboardText"] = "Teks dimuatkan daripada papan keratan.",
        ["Status_ClipboardEmpty"] = "Papan keratan tidak mengandungi imej mahupun teks.",
        ["Status_ClipboardFailed"] = "Papan keratan tidak dapat dibaca: {0}",
        ["Status_DropFailed"] = "Kandungan yang dilepaskan tidak dapat digunakan: {0}",
        ["Status_ImageCopied"] = "Imej disalin ke papan keratan.",
        ["Status_ImageCopyFailed"] = "Imej tidak dapat disalin: {0}",
        ["Status_ImageSaved"] = "Imej disimpan sebagai {0}.",
        ["Status_ImageSaveFailed"] = "Imej tidak dapat disimpan: {0}",
        ["Status_Recognizing"] = "Sedang mengenali…",
        ["Status_NoText"] = "{0} tidak menemui sebarang teks dalam imej ini.",
        ["Status_Done"] = "Selesai ({0}).",
        ["Status_DoneConfidence"] = "Selesai ({0}) · keyakinan purata {1}%.",
        ["Status_RecognizeFailed"] = "Pengecaman gagal: {0}",
        ["Status_Scanning"] = "Mencari kod QR dan kod bar…",
        ["Status_NoBarcode"] = "Tiada kod QR atau kod bar ditemui dalam imej ini.",
        ["Status_BarcodeOne"] = "Menemui satu kod {0}.",
        ["Status_BarcodeMany"] = "Menemui {0} kod.",
        ["Status_ScanFailed"] = "Imbasan gagal: {0}",
        ["Status_NothingToTranslate"] = "Tiada teks untuk diterjemahkan.",
        ["Status_Translating"] = "Menterjemah ke bahasa {0} pada peranti ini…",
        ["Status_Translated"] = "Diterjemahkan ke bahasa {0}, pada peranti ini, tanpa akses rangkaian.",
        ["Status_TranslateFailed"] = "Terjemahan gagal: {0}",
        ["Status_NothingToCopy"] = "Tiada teks untuk disalin.",
        ["Status_TextCopied"] = "Teks disalin ke papan keratan.",
        ["Status_CopyFailed"] = "Teks tidak dapat disalin: {0}",
        ["Status_NothingToSpeak"] = "Tiada teks untuk dibaca.",
        ["Status_SpeakFailed"] = "Teks tidak dapat dibaca: {0}",
        ["Status_HistoryLoaded"] = "Memaparkan keputusan daripada {0}.",
        ["Status_NeedImage"] = "Muatkan imej dahulu.",
        ["Status_CaptureFailed"] = "Tangkapan skrin gagal: {0}",
        ["Status_StartupBlockedByUser"] = "Windows telah mematikan mula automatik bagi Glyfo. Hidupkannya semula dalam Pengurus Tugasan di bahagian Apl Permulaan.",
        ["Status_StartupBlockedByPolicy"] = "Organisasi anda tidak membenarkan apl dimulakan bersama Windows.",
        ["Status_LanguagePackMissing"] = "Windows tiada pek bahasa OCR yang dipasang, jadi tiada apa-apa untuk membuat pengecaman. Tambah bahasa yang anda perlukan di Masa & bahasa, kemudian Bahasa & rantau.",
        ["Btn_OpenLanguageSettings"] = "Buka tetapan bahasa",

        ["Tray_Open"] = "Buka Glyfo",
        ["Tray_CaptureRegion"] = "Tangkap satu kawasan",
        ["Tray_CaptureFullScreen"] = "Tangkap seluruh skrin",
        ["Tray_Exit"] = "Keluar",
        ["Tray_Tooltip"] = "Glyfo — tekan {0} untuk menangkap satu kawasan",
        ["Toast_StartupTitle"] = "Glyfo sedang berjalan",
        ["Toast_StartupBody"] = "Tekan {0} untuk memilih sebahagian skrin dan membaca teks di dalamnya. Ctrl+Shift+R menangkap seluruh skrin.",
        ["Toast_DontRemind"] = "Jangan ingatkan lagi",
        ["Toast_MinimizedTitle"] = "Glyfo masih berjalan",
        ["Toast_MinimizedBody"] = "Tekan {0} bila-bila masa untuk menangkap dan mengenali teks. Untuk menutupnya sepenuhnya, klik kanan ikonnya di kawasan pemberitahuan dan pilih Keluar.",
        ["Toast_ExitApp"] = "Keluar daripada Glyfo",
        ["Toast_ResultTitle"] = "Teks dikenali",
        ["Toast_ResultCopied"] = "Disalin ke papan keratan.",
        ["Toast_OpenWindow"] = "Buka tetingkap",
        ["Toast_NoTextTitle"] = "Teks tidak ditemui",
        ["Toast_NoTextBody"] = "Tiada apa-apa di kawasan itu yang boleh dibaca sebagai teks.",
        ["Toast_FailedTitle"] = "Pengecaman gagal",
        ["Toast_HotkeyUnavailableTitle"] = "Pintasan tangkapan sedang digunakan",
        ["Toast_HotkeyUnavailableBody"] = "Apl lain sudah menggunakannya, jadi tangkapan skrin hanya boleh dibuat dari tetingkap dan dari ikon di kawasan pemberitahuan.",
        ["Setting_CloseToTray"] = "Terus berjalan apabila tetingkap ditutup",
        ["Setting_CloseToTray_Desc"] = "Apabila ini dihidupkan, menutup tetingkap membiarkan Glyfo terus berjalan supaya pintasan tangkapan masih berfungsi, dan ikonnya kekal di kawasan pemberitahuan, tempat Keluar menutupnya sepenuhnya. Apabila dimatikan, menutup tetingkap menamatkan apl.",
        ["Setting_Startup"] = "Mula bersama Windows",
        ["Setting_Startup_Desc"] = "Apabila dihidupkan, Glyfo bermula bersama Windows dan terus masuk ke kawasan pemberitahuan tanpa membuka tetingkap, jadi pintasan tangkapan berfungsi sebaik sahaja anda log masuk.",

        ["Source_Clipboard"] = "imej daripada papan keratan",
        ["Source_Dropped"] = "imej yang dilepaskan",
        ["Source_Shared"] = "imej yang dikongsi",
        ["Source_FullScreen"] = "Skrin penuh",
        ["Source_Region"] = "Kawasan skrin",
        ["Source_Codes"] = "{0} (kod)",

        ["FileType_Image"] = "Imej {0}",

        ["Region_Hint"] = "Seret untuk memilih kawasan　·　Esc atau klik kanan untuk batal",

        ["Err_NoLanguagePack"] = "Windows tiada pek bahasa OCR yang dipasang untuk bahasa ini. Tambah satu di Masa & bahasa, kemudian Bahasa & rantau.",
        ["Err_TextTooLong"] = "Teks terlalu panjang untuk model pada peranti. Terjemah bahagian yang lebih kecil.",
        ["Err_ModelDeclined"] = "Model pada peranti enggan menterjemah teks ini.",
        ["Err_TranslationFailed"] = "Terjemahan pada peranti tidak menghasilkan apa-apa.",
        ["Btn_About"] = "Perihal Glyfo",
        ["About_Title"] = "Perihal Glyfo",
        ["About_Version"] = "Versi {0}",
        ["About_Tagline"] = "Membaca teks dalam mana-mana imej, pada peranti ini. Tiada apa-apa dihantar melalui rangkaian.",
        ["About_Rate"] = "Nilaikan Glyfo",
        ["About_WhatsNew"] = "Apa yang baharu",
        ["About_Source"] = "Kod sumber di GitHub",
        ["About_Privacy"] = "Dasar privasi",
        ["Common_Close"] = "Tutup",
        ["News_Title"] = "Apa yang baharu",
        ["News_110_1"] = "Halaman Perihal, dengan versi serta pautan ke kod sumber dan dasar privasi.",
        ["News_110_2"] = "Anda boleh menilai Glyfo tanpa meninggalkan tetingkap.",
        ["News_110_3"] = "Nota ini, yang dipaparkan sekali bagi setiap versi baharu.",
        ["News_110_4"] = "Tangkapan kini turut menawarkan keseluruhan skrin dan menyembunyikan tetingkap dahulu, jadi Glyfo tidak pernah masuk ke dalam gambar.",
        ["Rate_Title"] = "Adakah Glyfo membantu anda?",
        ["Rate_Body"] = "Penilaian di Store ialah cara orang lain menemui aplikasi ini. Ia hanya mengambil sekejap.",
        ["Rate_Action"] = "Nilaikan",
        ["Rate_Later"] = "Bukan sekarang",
    };
}
