using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Th = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR ของ Windows · ไม่มีชุดภาษา",
        ["Engine_OneLanguage"] = "OCR ของ Windows · 1 ภาษา",
        ["Engine_ManyLanguages"] = "OCR ของ Windows · {0} ภาษา",
        ["Engine_OnDevice"] = "{0} · บนอุปกรณ์",

        ["Preview_Placeholder"] = "ลากรูปมาวางที่นี่ หรือใช้ปุ่มไฟล์ จับภาพ หรือคลิปบอร์ดด้านล่าง",
        ["Btn_CopyImage"] = "คัดลอก",
        ["Tip_CopyImage"] = "คัดลอกรูปไปยังคลิปบอร์ด",
        ["Btn_SaveImage"] = "บันทึก",
        ["Tip_SaveImage"] = "บันทึกรูปเป็น…",
        ["Btn_FitToWindow"] = "พอดีหน้าต่าง",
        ["Tip_FitToWindow"] = "ย่อขยายให้พอดีกับหน้าต่าง",
        ["Tip_ActualSize"] = "ขนาดพิกเซลจริง",
        ["Tip_PdfPrev"] = "หน้าก่อนหน้า",
        ["Tip_PdfNext"] = "หน้าถัดไป",
        ["Tip_PdfAll"] = "อ่านทุกหน้า",
        ["Action_Open"] = "เปิดลิงก์",
        ["Action_Mail"] = "เขียนถึง",
        ["Action_Call"] = "โทรหา",
        ["Action_Search"] = "ค้นหาบนเว็บ",

        ["Voice_Placeholder"] = "เสียง",
        ["Tip_Voice"] = "เสียงที่ใช้อ่านออกเสียง",
        ["Tip_Speak"] = "อ่านข้อความออกเสียง",
        ["Tip_StopSpeak"] = "หยุดอ่าน",
        ["Tip_CopyText"] = "คัดลอกข้อความ (Ctrl+Shift+C)",
        ["Tip_SaveText"] = "บันทึกข้อความเป็นไฟล์ (Ctrl+S)",
        ["Btn_RemoveLineBreaks"] = "รวมบรรทัด",
        ["Tip_RemoveLineBreaks"] = "รวมการขึ้นบรรทัดใหม่ให้กลับเป็นย่อหน้า",
        ["Btn_RemoveSpaces"] = "ไม่มีช่องว่าง",
        ["Tip_RemoveSpaces"] = "ลบช่องว่างทั้งหมด — สำหรับภาษาจีน ญี่ปุ่น และเกาหลี",
        ["Result_Placeholder"] = "ข้อความที่อ่านได้จะปรากฏที่นี่และแก้ไขได้",

        ["Btn_OpenFile"] = "ไฟล์",
        ["Tip_OpenFile"] = "เปิดไฟล์รูปภาพ (Ctrl+O)",
        ["Btn_Capture"] = "จับภาพ",
        ["Tip_Capture"] = "เลือกพื้นที่บนหน้าจอแล้วอ่านข้อความ ({0}) กด Ctrl+Shift+R เพื่อจับทั้งหน้าจอ",
        ["Hotkey_Unavailable"] = "ไม่มีปุ่มลัด — แอปอื่นใช้ทั้งสองปุ่มไปแล้ว",
        ["Btn_Paste"] = "คลิปบอร์ด",
        ["Tip_Paste"] = "โหลดรูปหรือข้อความจากคลิปบอร์ด (Ctrl+V)",
        ["Btn_History"] = "ประวัติ",
        ["Tip_History"] = "ผลลัพธ์ล่าสุด",
        ["History_Empty"] = "ยังไม่ได้อ่านอะไรเลย",
        ["History_EmptyPreview"] = "(ว่าง)",
        ["History_SearchPlaceholder"] = "ค้นหาในผลลัพธ์",
        ["History_NoMatch"] = "ไม่มีผลลัพธ์ที่ตรงกัน",
        ["History_Off"] = "ปิดประวัติไว้ในตัวเลือก",
        ["History_Clear"] = "ล้างประวัติ",
        ["History_CopyItem"] = "คัดลอกข้อความนี้",
        ["History_DeleteItem"] = "ลบรายการนี้",
        ["Tip_Settings"] = "ตัวเลือก",
        ["Settings_Header"] = "ตัวเลือก",
        ["Setting_UiLanguage"] = "ภาษาของแอป",
        ["Lang_SystemDefault"] = "ค่าเริ่มต้นของระบบ",
        ["Setting_RepairNumbers"] = "แก้ l และ I ที่อยู่ในตัวเลข",
        ["Setting_RepairNumbers_Desc"] = "ตัวอ่านข้อความมักอ่าน v1.6.5 เป็น vl.6.5 เมื่อเปิดตัวเลือกนี้ ตัว l หรือ I จะกลายเป็นเลข 1 เฉพาะตรงที่มีตัวคั่นและตัวเลขอยู่ติดกันเท่านั้น html5 และ IPv6 จึงไม่ถูกแตะต้อง เมื่อปิด ผลที่เครื่องอ่านได้จะคงไว้ตรงตามเดิมทุกประการ",
        ["Setting_WatchClipboard"] = "อ่านรูปที่ฉันคัดลอก",
        ["Setting_WatchClipboard_Desc"] = "จับภาพหน้าจอด้วย Win+Shift+S แล้ว Glyfo จะอ่านทันที จากนั้นใส่ข้อความลงคลิปบอร์ดแทนรูป การวางครั้งถัดไปจึงได้ข้อความ อ่านเฉพาะรูปเท่านั้น ไม่เคยอ่านข้อความที่คัดลอก และไม่มีอะไรถูกส่งไปที่ใด ทุกอย่างเกิดขึ้นบนเครื่องนี้",
        ["Setting_KeepHistory"] = "เก็บประวัติข้ามเซสชัน",
        ["Setting_KeepHistory_Desc"] = "เก็บผลลัพธ์ล่าสุด 200 รายการ เพื่อให้ยังอยู่หลังเริ่มโปรแกรมใหม่ เก็บเฉพาะข้อความ ไม่เก็บรูปภาพ ไว้ในไฟล์ของ Glyfo บนอุปกรณ์นี้ การปิดตัวเลือกนี้จะลบไฟล์นั้นและล้างรายการทันที",
        ["Common_On"] = "เปิด",
        ["Common_Off"] = "ปิด",
        ["Lang_Placeholder"] = "ภาษา",
        ["Tip_OcrLanguage"] = "ภาษาที่ใช้อ่าน จากชุดภาษาที่ติดตั้งไว้ใน Windows",
        ["Btn_Translate"] = "แปล",
        ["Tip_Translate"] = "แปลบนอุปกรณ์นี้ — ไม่มีการส่งอะไรผ่านเครือข่าย",
        ["Btn_Barcode"] = "รหัส",
        ["Tip_Barcode"] = "อ่านคิวอาร์โค้ดและบาร์โค้ดในรูป",
        ["Btn_Recognize"] = "อ่านข้อความ",
        ["Tip_Recognize"] = "อ่านข้อความในรูป (F5)",

        ["Option_AutoAi"] = "อัตโนมัติ (Windows AI)",
        ["Option_AutoMulti"] = "อัตโนมัติ (หลายภาษา · ช้ากว่า)",

        ["Status_Loaded"] = "โหลด{0}แล้ว",
        ["Status_OpenFailed"] = "เปิดรูปไม่ได้: {0}",
        ["Status_ClipboardText"] = "โหลดข้อความจากคลิปบอร์ดแล้ว",
        ["Status_ClipboardEmpty"] = "คลิปบอร์ดไม่มีทั้งรูปและข้อความ",
        ["Status_ClipboardFailed"] = "อ่านคลิปบอร์ดไม่ได้: {0}",
        ["Status_DropFailed"] = "ใช้สิ่งที่ลากมาวางไม่ได้: {0}",
        ["Status_ImageCopied"] = "คัดลอกรูปไปยังคลิปบอร์ดแล้ว",
        ["Status_ImageCopyFailed"] = "คัดลอกรูปไม่ได้: {0}",
        ["Status_ImageSaved"] = "บันทึกรูปเป็น {0} แล้ว",
        ["Status_ImageSaveFailed"] = "บันทึกรูปไม่ได้: {0}",
        ["Status_Recognizing"] = "กำลังอ่าน…",
        ["Status_NoText"] = "{0} ไม่พบข้อความในรูปนี้",
        ["Status_Done"] = "เสร็จแล้ว ({0})",
        ["Status_DoneConfidence"] = "เสร็จแล้ว ({0}) · ความมั่นใจเฉลี่ย {1}%",
        ["Status_RecognizeFailed"] = "อ่านข้อความไม่สำเร็จ: {0}",
        ["Status_Scanning"] = "กำลังค้นหาคิวอาร์โค้ดและบาร์โค้ด…",
        ["Status_NoBarcode"] = "ไม่พบคิวอาร์โค้ดหรือบาร์โค้ดในรูปนี้",
        ["Status_BarcodeOne"] = "พบรหัส {0} หนึ่งรายการ",
        ["Status_BarcodeMany"] = "พบรหัส {0} รายการ",
        ["Status_ScanFailed"] = "สแกนไม่สำเร็จ: {0}",
        ["Status_PdfFailed"] = "อ่านไฟล์ PDF นี้ไม่ได้ อาจมีการป้องกันด้วยรหัสผ่านหรือเสียหาย",
        ["Status_LaunchFailed"] = "Windows ไม่มีอะไรที่จะเปิดสิ่งนี้ได้",
        ["Status_NothingToTranslate"] = "ไม่มีข้อความให้แปล",
        ["Status_Translating"] = "กำลังแปลเป็น{0}บนอุปกรณ์นี้…",
        ["Status_Translated"] = "แปลเป็น{0}แล้ว บนอุปกรณ์นี้ โดยไม่ใช้เครือข่าย",
        ["Status_TranslateFailed"] = "แปลไม่สำเร็จ: {0}",
        ["Status_NothingToCopy"] = "ไม่มีข้อความให้คัดลอก",
        ["Status_NothingToSave"] = "ไม่มีข้อความให้บันทึก",
        ["Status_TextSaved"] = "บันทึกข้อความเป็น {0} แล้ว",
        ["Status_TextSaveFailed"] = "บันทึกข้อความไม่ได้: {0}",
        ["Status_TextCopied"] = "คัดลอกข้อความไปยังคลิปบอร์ดแล้ว",
        ["Status_CopyFailed"] = "คัดลอกข้อความไม่ได้: {0}",
        ["Status_NothingToSpeak"] = "ไม่มีข้อความให้อ่าน",
        ["Status_SpeakFailed"] = "อ่านข้อความออกเสียงไม่ได้: {0}",
        ["Status_HistoryLoaded"] = "กำลังแสดงผลลัพธ์จาก {0}",
        ["Status_HistoryCleared"] = "ล้างประวัติแล้ว",
        ["Status_NeedImage"] = "โหลดรูปก่อน",
        ["Status_CaptureFailed"] = "จับภาพหน้าจอไม่สำเร็จ: {0}",
        ["Status_StartupBlockedByUser"] = "Windows ปิดการเริ่มทำงานอัตโนมัติของ Glyfo ไว้ เปิดอีกครั้งได้ในตัวจัดการงาน ที่แอปเริ่มต้นระบบ",
        ["Status_StartupBlockedByPolicy"] = "องค์กรของคุณไม่อนุญาตให้แอปเริ่มทำงานพร้อม Windows",
        ["Status_LanguagePackMissing"] = "Windows ยังไม่ได้ติดตั้งชุดภาษาสำหรับ OCR จึงไม่มีอะไรให้ใช้อ่านข้อความ เพิ่มภาษาที่ต้องการได้ที่ เวลาและภาษา แล้วไปที่ ภาษาและภูมิภาค",
        ["Btn_OpenLanguageSettings"] = "เปิดการตั้งค่าภาษา",

        ["Tray_Open"] = "เปิด Glyfo",
        ["Tray_CaptureRegion"] = "จับภาพพื้นที่",
        ["Tray_CaptureFullScreen"] = "จับภาพทั้งหน้าจอ",
        ["Tray_Exit"] = "ออก",
        ["Tray_Tooltip"] = "Glyfo — กด {0} เพื่อจับภาพพื้นที่",
        ["Toast_StartupTitle"] = "Glyfo กำลังทำงาน",
        ["Toast_StartupBody"] = "กด {0} เพื่อเลือกพื้นที่บนหน้าจอแล้วอ่านข้อความในนั้น กด Ctrl+Shift+R เพื่อจับทั้งหน้าจอ",
        ["Toast_DontRemind"] = "ไม่ต้องเตือนอีก",
        ["Toast_MinimizedTitle"] = "Glyfo ยังทำงานอยู่",
        ["Toast_MinimizedBody"] = "กด {0} เมื่อใดก็ได้เพื่อจับภาพและอ่านข้อความ หากต้องการปิดจริง ๆ ให้คลิกขวาที่ไอคอนในพื้นที่แจ้งเตือนแล้วเลือกออก",
        ["Toast_ExitApp"] = "ออกจาก Glyfo",
        ["Toast_ResultTitle"] = "อ่านข้อความได้แล้ว",
        ["Toast_ResultCopied"] = "คัดลอกไปยังคลิปบอร์ดแล้ว",
        ["Toast_OpenWindow"] = "เปิดหน้าต่าง",
        ["Toast_NoTextTitle"] = "ไม่พบข้อความ",
        ["Toast_NoTextBody"] = "ในพื้นที่นั้นไม่มีสิ่งใดที่อ่านเป็นข้อความได้",
        ["Toast_FailedTitle"] = "อ่านข้อความไม่สำเร็จ",
        ["Toast_HotkeyUnavailableTitle"] = "ปุ่มลัดสำหรับจับภาพถูกใช้อยู่",
        ["Toast_HotkeyUnavailableBody"] = "แอปอื่นใช้ปุ่มลัดนี้อยู่แล้ว จึงจับภาพหน้าจอได้จากหน้าต่างและไอคอนในพื้นที่แจ้งเตือนเท่านั้น",
        ["Setting_CloseToTray"] = "ทำงานต่อเมื่อปิดหน้าต่าง",
        ["Setting_CloseToTray_Desc"] = "เมื่อเปิดตัวเลือกนี้ การปิดหน้าต่างจะไม่ปิด Glyfo ปุ่มลัดจับภาพจึงยังใช้ได้ และไอคอนจะอยู่ในพื้นที่แจ้งเตือน ซึ่งเลือกออกได้เพื่อปิดโปรแกรมจริง ๆ เมื่อปิดตัวเลือกนี้ การปิดหน้าต่างจะเป็นการออกจากแอป",
        ["Setting_Startup"] = "เริ่มทำงานพร้อม Windows",
        ["Setting_Startup_Desc"] = "เมื่อเปิดตัวเลือกนี้ Glyfo จะเริ่มทำงานพร้อม Windows และเข้าสู่พื้นที่แจ้งเตือนโดยตรงโดยไม่เปิดหน้าต่าง ทำให้ใช้แป้นพิมพ์ลัดจับภาพได้ทันทีที่ลงชื่อเข้าใช้",

        ["Source_Clipboard"] = "รูปจากคลิปบอร์ด",
        ["Source_Dropped"] = "รูปที่ลากมาวาง",
        ["Source_Shared"] = "รูปภาพที่แชร์",
        ["Source_FullScreen"] = "เต็มหน้าจอ",
        ["Source_Region"] = "พื้นที่บนหน้าจอ",
        ["Source_Codes"] = "{0} (รหัส)",
        ["Source_Batch"] = "{0} ไฟล์",
        ["Source_PdfAll"] = "{0} ทุกหน้า",

        ["FileType_Image"] = "รูป {0}",
        ["FileType_Text"] = "ข้อความธรรมดา",
        ["FileType_Markdown"] = "Markdown",
        ["Batch_Title"] = "กำลังอ่านหลายไฟล์",
        ["Batch_Progress"] = "{0} จาก {1}",
        ["Batch_DoneAll"] = "อ่านแล้ว {0} รายการ",
        ["Batch_Cancelled"] = "หยุดหลังจาก {0} จาก {1}",
        ["Batch_ItemFailed"] = "อ่านไม่ได้: {0}",
        ["Batch_ItemEmpty"] = "(ไม่มีข้อความ)",
        ["Batch_Save"] = "บันทึก…",
        ["Batch_CopyAll"] = "คัดลอกทั้งหมด",
        ["Batch_Separate"] = "บันทึกแต่ละรายการเป็นไฟล์แยก",
        ["Batch_SavedFolder"] = "บันทึก {0} ไฟล์ไปที่ {1} แล้ว",
        ["Batch_TooLongForBox"] = "อ่านแล้ว {0} รายการ ข้อความยาวเกินกว่าจะแสดงที่นี่ — อยู่ในไฟล์ที่คุณเพิ่งบันทึก",

        ["Region_Hint"] = "ลากเพื่อเลือกพื้นที่　·　Esc หรือคลิกขวาเพื่อยกเลิก",

        ["Err_NoLanguagePack"] = "Windows ยังไม่ได้ติดตั้งชุดภาษาสำหรับ OCR ของภาษานี้ เพิ่มได้ที่ เวลาและภาษา แล้วไปที่ ภาษาและภูมิภาค",
        ["Err_TextTooLong"] = "ข้อความยาวเกินกว่าที่โมเดลบนอุปกรณ์จะรับไหว ลองแปลส่วนที่สั้นลง",
        ["Err_ModelDeclined"] = "โมเดลบนอุปกรณ์ปฏิเสธที่จะแปลข้อความนี้",
        ["Err_TranslationFailed"] = "การแปลบนอุปกรณ์ไม่ได้ผลลัพธ์ใด ๆ",
        ["Btn_About"] = "เกี่ยวกับ Glyfo",
        ["About_Title"] = "เกี่ยวกับ Glyfo",
        ["About_Version"] = "เวอร์ชัน {0}",
        ["About_Tagline"] = "อ่านข้อความในภาพใดก็ได้ บนเครื่องนี้ ไม่มีการส่งข้อมูลออกทางเครือข่าย",
        ["About_Rate"] = "ให้คะแนน Glyfo",
        ["About_WhatsNew"] = "มีอะไรใหม่",
        ["About_Source"] = "ซอร์สโค้ดบน GitHub",
        ["About_Privacy"] = "นโยบายความเป็นส่วนตัว",
        ["Common_Close"] = "ปิด",
        ["Common_Cancel"] = "ยกเลิก",
        ["News_Title"] = "มีอะไรใหม่",
        ["News_130_1"] = "ตอนนี้ประวัติอยู่ต่อได้แม้เริ่มโปรแกรมใหม่ และมีช่องค้นหาให้ด้วย เก็บเฉพาะข้อความ — ในตัวเลือกจะล้างหรือปิดก็ได้",
        ["News_130_2"] = "Ctrl+S บันทึกข้อความที่อ่านได้เป็นไฟล์ข้อความธรรมดาหรือ Markdown",
        ["News_130_3"] = "เปิดหรือลากหลายไฟล์พร้อมกัน หรืออ่าน PDF ทั้งเล่ม แล้วบันทึกทั้งหมดเป็นไฟล์เดียวหรือไฟล์ละรายการ",
        ["News_120_1"] = "จับภาพหน้าจอด้วย Win+Shift+S แล้ว Glyfo จะอ่านให้และทิ้งข้อความไว้ในคลิปบอร์ด ปิดอยู่จนกว่าคุณจะเปิดในตัวเลือก",
        ["News_120_2"] = "ตอนนี้เปิดไฟล์ PDF ได้เหมือนรูป ทีละหน้า",
        ["News_120_3"] = "ลิงก์ อีเมล และเบอร์โทรที่พบในข้อความจะมีปุ่มอยู่ด้านล่าง",
        ["News_110_1"] = "หน้าเกี่ยวกับ ที่มีหมายเลขเวอร์ชันและลิงก์ไปยังซอร์สโค้ดกับนโยบายความเป็นส่วนตัว",
        ["News_110_2"] = "ให้คะแนน Glyfo ได้จากในหน้าต่างเลย ไม่ต้องออกไปที่ Store",
        ["News_110_3"] = "บันทึกนี้ ที่จะแสดงครั้งเดียวทุกครั้งที่มีเวอร์ชันใหม่",
        ["News_110_4"] = "การจับภาพรองรับทั้งหน้าจอแล้ว และจะซ่อนหน้าต่างก่อน Glyfo จึงไม่ติดอยู่ในภาพ",
        ["Rate_Title"] = "Glyfo ช่วยงานคุณได้ไหม",
        ["Rate_Body"] = "คะแนนใน Store คือสิ่งที่ทำให้คนอื่นเจอแอปนี้ ใช้เวลาไม่นาน",
        ["Rate_Action"] = "ให้คะแนน",
        ["Rate_Later"] = "ไว้ก่อน",
    };
}
