using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Pl = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR systemu Windows · brak pakietu językowego",
        ["Engine_OneLanguage"] = "OCR systemu Windows · 1 język",
        ["Engine_ManyLanguages"] = "OCR systemu Windows · języki: {0}",
        ["Engine_OnDevice"] = "{0} · lokalnie na urządzeniu",

        ["Preview_Placeholder"] = "Upuść tutaj obraz albo użyj przycisków Plik, Zrzut lub Schowek poniżej",
        ["Btn_CopyImage"] = "Kopiuj",
        ["Tip_CopyImage"] = "Kopiuj obraz do schowka",
        ["Btn_SaveImage"] = "Zapisz",
        ["Tip_SaveImage"] = "Zapisz obraz jako…",
        ["Btn_FitToWindow"] = "Dopasuj",
        ["Tip_FitToWindow"] = "Dopasuj powiększenie do okna",
        ["Tip_ActualSize"] = "Rzeczywisty rozmiar w pikselach",

        ["Voice_Placeholder"] = "Głos",
        ["Tip_Voice"] = "Głos używany do czytania na głos",
        ["Tip_Speak"] = "Przeczytaj tekst na głos",
        ["Tip_StopSpeak"] = "Zatrzymaj czytanie",
        ["Tip_CopyText"] = "Kopiuj tekst (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Bez łamania",
        ["Tip_RemoveLineBreaks"] = "Scal twarde końce wierszy z powrotem w akapity",
        ["Btn_RemoveSpaces"] = "Bez spacji",
        ["Tip_RemoveSpaces"] = "Usuń wszystkie spacje — dla chińskiego, japońskiego i koreańskiego",
        ["Result_Placeholder"] = "Rozpoznany tekst pojawi się tutaj i można go edytować.",

        ["Btn_OpenFile"] = "Plik",
        ["Tip_OpenFile"] = "Otwórz plik obrazu (Ctrl+O)",
        ["Btn_Capture"] = "Zrzut",
        ["Tip_Capture"] = "Zaznacz obszar ekranu i rozpoznaj go ({0}). Naciśnij Ctrl+Shift+R, aby objąć cały ekran.",
        ["Hotkey_Unavailable"] = "brak skrótu — oba zajęła inna aplikacja",
        ["Btn_Paste"] = "Schowek",
        ["Tip_Paste"] = "Wczytaj obraz lub tekst ze schowka (Ctrl+V)",
        ["Btn_History"] = "Historia",
        ["Tip_History"] = "Ostatnie wyniki",
        ["History_Empty"] = "Nic jeszcze nie rozpoznano.",
        ["History_EmptyPreview"] = "(puste)",
        ["Tip_Settings"] = "Opcje",
        ["Settings_Header"] = "Opcje",
        ["Setting_UiLanguage"] = "Język aplikacji",
        ["Lang_SystemDefault"] = "Domyślny systemu",
        ["Setting_RepairNumbers"] = "Popraw l oraz I wewnątrz liczb",
        ["Setting_RepairNumbers_Desc"] = "Silniki rozpoznawania regularnie odczytują v1.6.5 jako vl.6.5. Gdy opcja jest włączona, l lub I zamienia się w 1 tylko tam, gdzie obok stoi separator i cyfra, więc html5 i IPv6 pozostają nietknięte. Gdy jest wyłączona, odczyt silnika zostaje zachowany dokładnie taki, jaki przyszedł.",
        ["Common_On"] = "Wł.",
        ["Common_Off"] = "Wył.",
        ["Lang_Placeholder"] = "Język",
        ["Tip_OcrLanguage"] = "Język rozpoznawania, spośród pakietów językowych zainstalowanych w systemie Windows",
        ["Btn_Translate"] = "Przetłumacz",
        ["Tip_Translate"] = "Tłumacz na tym urządzeniu — nic nie jest wysyłane przez sieć",
        ["Btn_Barcode"] = "Kody",
        ["Tip_Barcode"] = "Odczytaj kody QR i kody kreskowe z obrazu",
        ["Btn_Recognize"] = "Rozpoznaj",
        ["Tip_Recognize"] = "Rozpoznaj tekst na obrazie (F5)",

        ["Option_AutoAi"] = "Automatycznie (Windows AI)",
        ["Option_AutoMulti"] = "Automatycznie (wiele języków · wolniej)",

        ["Status_Loaded"] = "Wczytano: {0}.",
        ["Status_OpenFailed"] = "Nie udało się otworzyć obrazu: {0}",
        ["Status_ClipboardText"] = "Wczytano tekst ze schowka.",
        ["Status_ClipboardEmpty"] = "W schowku nie ma ani obrazu, ani tekstu.",
        ["Status_ClipboardFailed"] = "Nie udało się odczytać schowka: {0}",
        ["Status_DropFailed"] = "Nie udało się użyć upuszczonego elementu: {0}",
        ["Status_ImageCopied"] = "Obraz skopiowany do schowka.",
        ["Status_ImageCopyFailed"] = "Nie udało się skopiować obrazu: {0}",
        ["Status_ImageSaved"] = "Obraz zapisany jako {0}.",
        ["Status_ImageSaveFailed"] = "Nie udało się zapisać obrazu: {0}",
        ["Status_Recognizing"] = "Rozpoznawanie…",
        ["Status_NoText"] = "{0} nie znalazł tekstu na tym obrazie.",
        ["Status_Done"] = "Gotowe ({0}).",
        ["Status_DoneConfidence"] = "Gotowe ({0}) · średnia pewność {1}%.",
        ["Status_RecognizeFailed"] = "Rozpoznawanie nie powiodło się: {0}",
        ["Status_Scanning"] = "Trwa szukanie kodów QR i kodów kreskowych…",
        ["Status_NoBarcode"] = "Nie znaleziono na tym obrazie kodu QR ani kodu kreskowego.",
        ["Status_BarcodeOne"] = "Znaleziono jeden kod {0}.",
        ["Status_BarcodeMany"] = "Znaleziono kody: {0}.",
        ["Status_ScanFailed"] = "Skanowanie nie powiodło się: {0}",
        ["Status_NothingToTranslate"] = "Nie ma tekstu do przetłumaczenia.",
        ["Status_Translating"] = "Tłumaczenie na {0} na tym urządzeniu…",
        ["Status_Translated"] = "Przetłumaczono na {0}, na tym urządzeniu, bez dostępu do sieci.",
        ["Status_TranslateFailed"] = "Tłumaczenie nie powiodło się: {0}",
        ["Status_NothingToCopy"] = "Nie ma tekstu do skopiowania.",
        ["Status_TextCopied"] = "Tekst skopiowany do schowka.",
        ["Status_CopyFailed"] = "Nie udało się skopiować tekstu: {0}",
        ["Status_NothingToSpeak"] = "Nie ma tekstu do przeczytania na głos.",
        ["Status_SpeakFailed"] = "Nie udało się przeczytać tekstu na głos: {0}",
        ["Status_HistoryLoaded"] = "Pokazywany jest wynik z {0}.",
        ["Status_NeedImage"] = "Najpierw wczytaj obraz.",
        ["Status_CaptureFailed"] = "Przechwycenie ekranu nie powiodło się: {0}",
        ["Status_StartupBlockedByUser"] = "System Windows wyłączył automatyczne uruchamianie Glyfo. Włącz je ponownie w Menedżerze zadań, w sekcji Aplikacje startowe.",
        ["Status_StartupBlockedByPolicy"] = "Twoja organizacja nie zezwala aplikacjom na uruchamianie razem z systemem Windows.",
        ["Status_LanguagePackMissing"] = "W systemie Windows nie zainstalowano żadnego pakietu językowego OCR, więc nie ma czym rozpoznawać. Dodaj potrzebny język w sekcji Czas i język, a następnie Język i region.",
        ["Btn_OpenLanguageSettings"] = "Otwórz ustawienia języka",

        ["Tray_Open"] = "Otwórz Glyfo",
        ["Tray_CaptureRegion"] = "Przechwyć obszar",
        ["Tray_CaptureFullScreen"] = "Przechwyć cały ekran",
        ["Tray_Exit"] = "Zakończ",
        ["Tray_Tooltip"] = "Glyfo — naciśnij {0}, aby przechwycić obszar",
        ["Toast_StartupTitle"] = "Glyfo działa",
        ["Toast_StartupBody"] = "Naciśnij {0}, aby zaznaczyć fragment ekranu i odczytać z niego tekst. Ctrl+Shift+R obejmuje cały ekran.",
        ["Toast_DontRemind"] = "Nie przypominaj więcej",
        ["Toast_MinimizedTitle"] = "Glyfo nadal działa",
        ["Toast_MinimizedBody"] = "Naciśnij {0} w dowolnej chwili, aby przechwycić obraz i rozpoznać tekst. Aby zamknąć program na dobre, kliknij prawym przyciskiem jego ikonę w obszarze powiadomień i wybierz Zakończ.",
        ["Toast_ExitApp"] = "Zakończ Glyfo",
        ["Toast_ResultTitle"] = "Rozpoznano tekst",
        ["Toast_ResultCopied"] = "Skopiowano do schowka.",
        ["Toast_OpenWindow"] = "Otwórz okno",
        ["Toast_NoTextTitle"] = "Nie znaleziono tekstu",
        ["Toast_NoTextBody"] = "W tym obszarze nie było niczego, co dałoby się odczytać jako tekst.",
        ["Toast_FailedTitle"] = "Rozpoznawanie nie powiodło się",
        ["Toast_HotkeyUnavailableTitle"] = "Skrót przechwytywania jest zajęty",
        ["Toast_HotkeyUnavailableBody"] = "Zajęła go inna aplikacja, więc ekran można przechwycić tylko z okna i z ikony w obszarze powiadomień.",
        ["Setting_CloseToTray"] = "Działaj dalej po zamknięciu okna",
        ["Setting_CloseToTray_Desc"] = "Gdy ta opcja jest włączona, zamknięcie okna pozostawia Glyfo uruchomiony, więc skrót przechwytywania nadal działa, a ikona zostaje w obszarze powiadomień, gdzie polecenie Zakończ zamyka program na dobre. Gdy jest wyłączona, zamknięcie okna kończy działanie aplikacji.",
        ["Setting_Startup"] = "Uruchamiaj razem z systemem Windows",
        ["Setting_Startup_Desc"] = "Gdy ta opcja jest włączona, Glyfo uruchamia się razem z systemem Windows i od razu trafia do obszaru powiadomień, bez otwierania okna, dzięki czemu skrót przechwytywania działa zaraz po zalogowaniu.",

        ["Source_Clipboard"] = "obraz ze schowka",
        ["Source_Dropped"] = "upuszczony obraz",
        ["Source_Shared"] = "udostępniony obraz",
        ["Source_FullScreen"] = "Cały ekran",
        ["Source_Region"] = "Obszar ekranu",
        ["Source_Codes"] = "{0} (kody)",

        ["FileType_Image"] = "Obraz {0}",

        ["Region_Hint"] = "Przeciągnij, aby zaznaczyć obszar　·　Esc lub prawy przycisk myszy anuluje",

        ["Err_NoLanguagePack"] = "W systemie Windows nie zainstalowano pakietu językowego OCR dla tego języka. Dodaj go w sekcji Czas i język, a następnie Język i region.",
        ["Err_TextTooLong"] = "Tekst jest za długi dla modelu działającego na urządzeniu. Przetłumacz mniejszy fragment.",
        ["Err_ModelDeclined"] = "Model na urządzeniu odmówił przetłumaczenia tego tekstu.",
        ["Err_TranslationFailed"] = "Tłumaczenie na urządzeniu nie dało wyniku.",
    };
}
