using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Ar = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "‏OCR في Windows · لا توجد حزمة لغة",
        ["Engine_OneLanguage"] = "‏OCR في Windows · لغة واحدة",
        ["Engine_ManyLanguages"] = "‏OCR في Windows · {0} لغات",
        ["Engine_OnDevice"] = "{0} · على الجهاز",

        ["Preview_Placeholder"] = "أفلِت صورة هنا، أو استخدم ملف أو لقطة الشاشة أو الحافظة بالأسفل",
        ["Btn_CopyImage"] = "نسخ",
        ["Tip_CopyImage"] = "نسخ الصورة إلى الحافظة",
        ["Btn_SaveImage"] = "حفظ",
        ["Tip_SaveImage"] = "حفظ الصورة باسم…",
        ["Btn_FitToWindow"] = "ملاءمة",
        ["Tip_FitToWindow"] = "تكبير أو تصغير لملاءمة النافذة",
        ["Tip_ActualSize"] = "الحجم الحقيقي بالبكسل",

        ["Voice_Placeholder"] = "الصوت",
        ["Tip_Voice"] = "الصوت المستخدَم في القراءة بصوت عالٍ",
        ["Tip_Speak"] = "اقرأ النص بصوت عالٍ",
        ["Tip_StopSpeak"] = "إيقاف القراءة",
        ["Tip_CopyText"] = "نسخ النص (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "دمج الأسطر",
        ["Tip_RemoveLineBreaks"] = "دمج فواصل الأسطر لتعود فقرات",
        ["Btn_RemoveSpaces"] = "بلا مسافات",
        ["Tip_RemoveSpaces"] = "إزالة كل المسافات — للصينية واليابانية والكورية",
        ["Result_Placeholder"] = "يظهر النص المتعرَّف عليه هنا ويمكن تحريره.",

        ["Btn_OpenFile"] = "ملف",
        ["Tip_OpenFile"] = "فتح ملف صورة (Ctrl+O)",
        ["Btn_Capture"] = "لقطة شاشة",
        ["Tip_Capture"] = "حدِّد جزءًا من الشاشة وتعرَّف عليه ({0}). اضغط Ctrl+Shift+R لالتقاط الشاشة كاملة.",
        ["Hotkey_Unavailable"] = "لا يوجد اختصار — استحوذ تطبيق آخر على كليهما",
        ["Btn_Paste"] = "الحافظة",
        ["Tip_Paste"] = "جلب صورة أو نص من الحافظة (Ctrl+V)",
        ["Btn_History"] = "السجل",
        ["Tip_History"] = "النتائج الأخيرة",
        ["History_Empty"] = "لم يُتعرَّف على شيء بعد.",
        ["History_EmptyPreview"] = "(فارغ)",
        ["Tip_Settings"] = "الخيارات",
        ["Settings_Header"] = "الخيارات",
        ["Setting_UiLanguage"] = "لغة التطبيق",
        ["Lang_SystemDefault"] = "الافتراضي للنظام",
        ["Setting_RepairNumbers"] = "تصحيح l وI داخل الأرقام",
        ["Setting_RepairNumbers_Desc"] = "كثيرًا ما تقرأ محرّكات التعرّف v1.6.5 على أنها vl.6.5. عند تشغيل هذا الخيار، لا يتحوّل الحرف l أو I إلى الرقم 1 إلا حيث يجاوره فاصل ورقم، فتبقى html5 وIPv6 على حالها. وعند إيقافه، تُحفظ قراءة المحرّك تمامًا كما وردت.",
        ["Common_On"] = "تشغيل",
        ["Common_Off"] = "إيقاف",
        ["Lang_Placeholder"] = "اللغة",
        ["Tip_OcrLanguage"] = "لغة التعرّف، من حزم اللغات المثبَّتة في Windows",
        ["Btn_Translate"] = "ترجمة",
        ["Tip_Translate"] = "الترجمة على هذا الجهاز — لا يُرسَل أي شيء عبر الشبكة",
        ["Btn_Barcode"] = "الرموز",
        ["Tip_Barcode"] = "قراءة رموز QR والباركود في الصورة",
        ["Btn_Recognize"] = "تعرّف",
        ["Tip_Recognize"] = "التعرّف على النص في الصورة (F5)",

        ["Option_AutoAi"] = "تلقائي (Windows AI)",
        ["Option_AutoMulti"] = "تلقائي (لغات متعددة · أبطأ)",

        ["Status_Loaded"] = "تم تحميل {0}.",
        ["Status_OpenFailed"] = "تعذّر فتح الصورة: {0}",
        ["Status_ClipboardText"] = "تم جلب النص من الحافظة.",
        ["Status_ClipboardEmpty"] = "لا تحتوي الحافظة على صورة ولا نص.",
        ["Status_ClipboardFailed"] = "تعذّرت قراءة الحافظة: {0}",
        ["Status_DropFailed"] = "تعذّر استخدام ما تم إفلاته: {0}",
        ["Status_ImageCopied"] = "تم نسخ الصورة إلى الحافظة.",
        ["Status_ImageCopyFailed"] = "تعذّر نسخ الصورة: {0}",
        ["Status_ImageSaved"] = "تم حفظ الصورة باسم {0}.",
        ["Status_ImageSaveFailed"] = "تعذّر حفظ الصورة: {0}",
        ["Status_Recognizing"] = "جارٍ التعرّف…",
        ["Status_NoText"] = "لم يجد {0} أي نص في هذه الصورة.",
        ["Status_Done"] = "تم ({0}).",
        ["Status_DoneConfidence"] = "تم ({0}) · متوسط الثقة {1}%.",
        ["Status_RecognizeFailed"] = "فشل التعرّف: {0}",
        ["Status_Scanning"] = "جارٍ البحث عن رموز QR والباركود…",
        ["Status_NoBarcode"] = "لم يُعثر على رمز QR أو باركود في هذه الصورة.",
        ["Status_BarcodeOne"] = "تم العثور على رمز {0} واحد.",
        ["Status_BarcodeMany"] = "تم العثور على {0} رموز.",
        ["Status_ScanFailed"] = "فشل البحث: {0}",
        ["Status_NothingToTranslate"] = "لا يوجد نص لترجمته.",
        ["Status_Translating"] = "جارٍ الترجمة إلى {0} على هذا الجهاز…",
        ["Status_Translated"] = "تمت الترجمة إلى {0}، على هذا الجهاز، دون أي اتصال بالشبكة.",
        ["Status_TranslateFailed"] = "فشلت الترجمة: {0}",
        ["Status_NothingToCopy"] = "لا يوجد نص لنسخه.",
        ["Status_TextCopied"] = "تم نسخ النص إلى الحافظة.",
        ["Status_CopyFailed"] = "تعذّر نسخ النص: {0}",
        ["Status_NothingToSpeak"] = "لا يوجد نص لقراءته.",
        ["Status_SpeakFailed"] = "تعذّرت قراءة النص: {0}",
        ["Status_HistoryLoaded"] = "عرض النتيجة من {0}.",
        ["Status_NeedImage"] = "حمِّل صورة أولًا.",
        ["Status_CaptureFailed"] = "فشل التقاط الشاشة: {0}",
        ["Status_StartupBlockedByUser"] = "أوقف Windows تشغيل Glyfo عند بدء التشغيل. أعد تفعيله من إدارة المهام ضمن تطبيقات بدء التشغيل.",
        ["Status_StartupBlockedByPolicy"] = "لا تسمح مؤسستك بتشغيل التطبيقات مع بدء Windows.",
        ["Status_LanguagePackMissing"] = "لا توجد أي حزمة لغة للتعرّف الضوئي مثبَّتة في Windows، فلا شيء يمكن التعرّف به. أضف اللغة التي تحتاجها من الوقت واللغة، ثم اللغة والمنطقة.",
        ["Btn_OpenLanguageSettings"] = "فتح إعدادات اللغة",

        ["Tray_Open"] = "فتح Glyfo",
        ["Tray_CaptureRegion"] = "التقاط منطقة",
        ["Tray_CaptureFullScreen"] = "التقاط الشاشة كاملة",
        ["Tray_Exit"] = "خروج",
        ["Tray_Tooltip"] = "‏Glyfo — اضغط {0} لالتقاط منطقة",
        ["Toast_StartupTitle"] = "‏Glyfo قيد التشغيل",
        ["Toast_StartupBody"] = "اضغط {0} لتحديد جزء من الشاشة وقراءة النص فيه. Ctrl+Shift+R يلتقط الشاشة كاملة.",
        ["Toast_DontRemind"] = "عدم التذكير مرة أخرى",
        ["Toast_MinimizedTitle"] = "‏Glyfo لا يزال قيد التشغيل",
        ["Toast_MinimizedBody"] = "اضغط {0} في أي وقت للالتقاط والتعرّف. لإغلاقه نهائيًا، انقر بزر الفأرة الأيمن على أيقونته في منطقة الإعلام واختر خروج.",
        ["Toast_ExitApp"] = "إنهاء Glyfo",
        ["Toast_ResultTitle"] = "تم التعرّف على النص",
        ["Toast_ResultCopied"] = "تم نسخه إلى الحافظة.",
        ["Toast_OpenWindow"] = "فتح النافذة",
        ["Toast_NoTextTitle"] = "لم يُعثر على نص",
        ["Toast_NoTextBody"] = "لا يوجد في تلك المنطقة ما يمكن قراءته كنص.",
        ["Toast_FailedTitle"] = "فشل التعرّف",
        ["Toast_HotkeyUnavailableTitle"] = "اختصار الالتقاط مشغول",
        ["Toast_HotkeyUnavailableBody"] = "استحوذ عليه تطبيق آخر، لذا لا يمكن التقاط الشاشة إلا من النافذة ومن الأيقونة في منطقة الإعلام.",
        ["Setting_CloseToTray"] = "الاستمرار في العمل عند إغلاق النافذة",
        ["Setting_CloseToTray_Desc"] = "عند تفعيل هذا الخيار، يظل Glyfo يعمل بعد إغلاق النافذة فيبقى اختصار الالتقاط فعّالًا، وتبقى أيقونته في منطقة الإعلام حيث يؤدي اختيار خروج إلى إغلاقه نهائيًا. وعند إيقافه، يؤدي إغلاق النافذة إلى إنهاء التطبيق.",
        ["Setting_Startup"] = "التشغيل مع بدء Windows",
        ["Setting_Startup_Desc"] = "عند تفعيل هذا الخيار، يبدأ Glyfo مع Windows وينتقل مباشرةً إلى منطقة الإعلام دون فتح نافذة، فيصبح اختصار الالتقاط جاهزًا منذ لحظة تسجيل الدخول.",

        ["Source_Clipboard"] = "صورة الحافظة",
        ["Source_Dropped"] = "الصورة المُفلَتة",
        ["Source_Shared"] = "الصورة المُشارَكة",
        ["Source_FullScreen"] = "الشاشة كاملة",
        ["Source_Region"] = "جزء من الشاشة",
        ["Source_Codes"] = "{0} (رموز)",

        ["FileType_Image"] = "صورة {0}",

        ["Region_Hint"] = "اسحب لتحديد منطقة　·　‏Esc أو النقر بالزر الأيمن للإلغاء",

        ["Err_NoLanguagePack"] = "لا توجد حزمة لغة للتعرّف الضوئي مثبَّتة في Windows لهذه اللغة. أضف واحدة من الوقت واللغة، ثم اللغة والمنطقة.",
        ["Err_TextTooLong"] = "النص أطول مما يحتمله النموذج العامل على الجهاز. ترجِم جزءًا أصغر.",
        ["Err_ModelDeclined"] = "رفض النموذج العامل على الجهاز ترجمة هذا النص.",
        ["Err_TranslationFailed"] = "لم تسفر الترجمة على الجهاز عن أي نتيجة.",
        ["Btn_About"] = "حول Glyfo",
        ["About_Title"] = "حول Glyfo",
        ["About_Version"] = "الإصدار {0}",
        ["About_Tagline"] = "يقرأ النص في أي صورة على هذا الجهاز. لا يُرسَل أي شيء عبر الشبكة.",
        ["About_Rate"] = "تقييم Glyfo",
        ["About_WhatsNew"] = "ما الجديد",
        ["About_Source"] = "التعليمات البرمجية المصدرية على GitHub",
        ["About_Privacy"] = "سياسة الخصوصية",
        ["Common_Close"] = "إغلاق",
        ["News_Title"] = "ما الجديد",
        ["News_110_1"] = "صفحة حول التطبيق تعرض الإصدار وروابط التعليمات البرمجية المصدرية وسياسة الخصوصية.",
        ["News_110_2"] = "يمكنك تقييم Glyfo دون مغادرة النافذة.",
        ["News_110_3"] = "هذه الملاحظات، وتظهر مرة واحدة مع كل إصدار جديد.",
        ["Rate_Title"] = "هل يفيدك Glyfo؟",
        ["Rate_Body"] = "التقييم في المتجر هو ما يجعل الآخرين يعثرون على التطبيق. لن يستغرق سوى لحظة.",
        ["Rate_Action"] = "تقييم",
        ["Rate_Later"] = "ليس الآن",
    };
}
