using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> ZhHant = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · 未安裝語言套件",
        ["Engine_OneLanguage"] = "Windows OCR · 1 種語言",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} 種語言",
        ["Engine_OnDevice"] = "{0} · 本機執行",

        ["Preview_Placeholder"] = "把圖片拖曳到這裡，或使用下方的檔案、擷取、剪貼簿",
        ["Btn_CopyImage"] = "複製",
        ["Tip_CopyImage"] = "複製圖片到剪貼簿",
        ["Btn_SaveImage"] = "儲存",
        ["Tip_SaveImage"] = "圖片另存新檔…",
        ["Btn_FitToWindow"] = "自動調整",
        ["Tip_FitToWindow"] = "縮放至符合視窗",
        ["Tip_ActualSize"] = "實際像素大小",

        ["Voice_Placeholder"] = "語音",
        ["Tip_Voice"] = "朗讀所使用的語音",
        ["Tip_Speak"] = "朗讀文字",
        ["Tip_StopSpeak"] = "停止朗讀",
        ["Tip_CopyText"] = "複製文字（Ctrl+Shift+C）",
        ["Btn_RemoveLineBreaks"] = "去換行",
        ["Tip_RemoveLineBreaks"] = "把強制換行合併回段落",
        ["Btn_RemoveSpaces"] = "去空格",
        ["Tip_RemoveSpaces"] = "刪除所有空格，適用於中日韓文字",
        ["Result_Placeholder"] = "辨識出的文字會顯示在這裡，可以直接編輯。",

        ["Btn_OpenFile"] = "檔案",
        ["Tip_OpenFile"] = "開啟圖片檔（Ctrl+O）",
        ["Btn_Capture"] = "擷取",
        ["Tip_Capture"] = "框選螢幕區域並辨識（{0}）。按 Ctrl+Shift+R 擷取整個螢幕。",
        ["Hotkey_Unavailable"] = "沒有快速鍵，兩組都被其他程式占用",
        ["Btn_Paste"] = "剪貼簿",
        ["Tip_Paste"] = "從剪貼簿載入圖片或文字（Ctrl+V）",
        ["Btn_History"] = "歷程記錄",
        ["Tip_History"] = "最近的辨識結果",
        ["History_Empty"] = "還沒有辨識記錄。",
        ["History_EmptyPreview"] = "（空白）",
        ["Tip_Settings"] = "選項",
        ["Settings_Header"] = "選項",
        ["Setting_UiLanguage"] = "介面語言",
        ["Lang_SystemDefault"] = "跟隨系統",
        ["Setting_RepairNumbers"] = "修正數字中的 l 與 I",
        ["Setting_RepairNumbers_Desc"] = "辨識引擎經常把 v1.6.5 讀成 vl.6.5。開啟後，只有當 l 或 I 旁邊同時有分隔符號與數字時才會改成 1，因此 html5 與 IPv6 不受影響。關閉後完全保留引擎的原始讀數。",
        ["Common_On"] = "開",
        ["Common_Off"] = "關",
        ["Lang_Placeholder"] = "語言",
        ["Tip_OcrLanguage"] = "辨識語言，來自 Windows 已安裝的語言套件",
        ["Btn_Translate"] = "翻譯",
        ["Tip_Translate"] = "在本機翻譯，不經過網路",
        ["Btn_Barcode"] = "條碼",
        ["Tip_Barcode"] = "辨識圖中的 QR Code 與條碼",
        ["Btn_Recognize"] = "辨識",
        ["Tip_Recognize"] = "辨識圖片中的文字（F5）",

        ["Option_AutoAi"] = "自動偵測（Windows AI）",
        ["Option_AutoMulti"] = "自動偵測（多語言 · 較慢）",

        ["Status_Loaded"] = "已載入{0}。",
        ["Status_OpenFailed"] = "無法開啟圖片：{0}",
        ["Status_ClipboardText"] = "已從剪貼簿載入文字。",
        ["Status_ClipboardEmpty"] = "剪貼簿中既沒有圖片也沒有文字。",
        ["Status_ClipboardFailed"] = "無法讀取剪貼簿：{0}",
        ["Status_DropFailed"] = "無法使用拖入的內容：{0}",
        ["Status_ImageCopied"] = "圖片已複製到剪貼簿。",
        ["Status_ImageCopyFailed"] = "無法複製圖片：{0}",
        ["Status_ImageSaved"] = "圖片已儲存為 {0}。",
        ["Status_ImageSaveFailed"] = "無法儲存圖片：{0}",
        ["Status_Recognizing"] = "正在辨識…",
        ["Status_NoText"] = "{0} 沒有在這張圖片中找到文字。",
        ["Status_Done"] = "完成（{0}）。",
        ["Status_DoneConfidence"] = "完成（{0}）· 平均信賴度 {1}%。",
        ["Status_RecognizeFailed"] = "辨識失敗：{0}",
        ["Status_Scanning"] = "正在尋找 QR Code 與條碼…",
        ["Status_NoBarcode"] = "這張圖片中沒有 QR Code 或條碼。",
        ["Status_BarcodeOne"] = "找到 1 個 {0} 碼。",
        ["Status_BarcodeMany"] = "找到 {0} 個碼。",
        ["Status_ScanFailed"] = "掃描失敗：{0}",
        ["Status_NothingToTranslate"] = "沒有可翻譯的文字。",
        ["Status_Translating"] = "正在本機翻譯成{0}…",
        ["Status_Translated"] = "已在本機翻譯成{0}，全程不連網。",
        ["Status_TranslateFailed"] = "翻譯失敗：{0}",
        ["Status_NothingToCopy"] = "沒有可複製的文字。",
        ["Status_TextCopied"] = "文字已複製到剪貼簿。",
        ["Status_CopyFailed"] = "無法複製文字：{0}",
        ["Status_NothingToSpeak"] = "沒有可朗讀的文字。",
        ["Status_SpeakFailed"] = "無法朗讀：{0}",
        ["Status_HistoryLoaded"] = "正在顯示 {0} 的辨識結果。",
        ["Status_NeedImage"] = "請先載入一張圖片。",
        ["Status_CaptureFailed"] = "螢幕擷取失敗：{0}",
        ["Status_StartupBlockedByUser"] = "Windows 已停用 Glyfo 的開機自動啟動。請在工作管理員的啟動應用程式中重新啟用。",
        ["Status_StartupBlockedByPolicy"] = "貴組織不允許應用程式隨 Windows 啟動。",
        ["Status_LanguagePackMissing"] = "Windows 尚未安裝任何 OCR 語言套件，沒有可用的辨識語言。請在「時間與語言 → 語言與地區」中新增所需語言。",
        ["Btn_OpenLanguageSettings"] = "開啟語言設定",

        ["Tray_Open"] = "開啟 Glyfo",
        ["Tray_CaptureRegion"] = "擷取區域",
        ["Tray_CaptureFullScreen"] = "擷取整個螢幕",
        ["Tray_Exit"] = "結束",
        ["Tray_Tooltip"] = "Glyfo — 按 {0} 擷取區域",
        ["Toast_StartupTitle"] = "Glyfo 正在執行",
        ["Toast_StartupBody"] = "按 {0} 框選螢幕區域並辨識其中的文字；按 Ctrl+Shift+R 擷取整個螢幕。",
        ["Toast_DontRemind"] = "不再提醒",
        ["Toast_MinimizedTitle"] = "Glyfo 仍在執行",
        ["Toast_MinimizedBody"] = "隨時按 {0} 即可擷取並辨識。若要完全結束，請在通知區域的圖示上按右鍵並選擇「結束」。",
        ["Toast_ExitApp"] = "結束 Glyfo",
        ["Toast_ResultTitle"] = "辨識完成",
        ["Toast_ResultCopied"] = "已複製到剪貼簿。",
        ["Toast_OpenWindow"] = "開啟視窗",
        ["Toast_NoTextTitle"] = "找不到文字",
        ["Toast_NoTextBody"] = "該區域中沒有可辨識為文字的內容。",
        ["Toast_FailedTitle"] = "辨識失敗",
        ["Toast_HotkeyUnavailableTitle"] = "擷取快速鍵已被占用",
        ["Toast_HotkeyUnavailableBody"] = "其他程式已經占用它，因此只能從視窗或通知區域的圖示進行擷取。",
        ["Setting_CloseToTray"] = "關閉視窗後繼續執行",
        ["Setting_CloseToTray_Desc"] = "開啟後，關閉視窗不會結束 Glyfo，擷取快速鍵仍然有效，圖示會留在通知區域，在那裡選擇「結束」才會完全關閉；關閉此項後，關閉視窗即結束程式。",
        ["Setting_Startup"] = "開機自動啟動",
        ["Setting_Startup_Desc"] = "開啟後，Glyfo 會隨 Windows 一起啟動，不顯示視窗而直接進入通知區域，登入後截圖快速鍵立即可用。",

        ["Source_Clipboard"] = "剪貼簿圖片",
        ["Source_Dropped"] = "拖入的圖片",
        ["Source_Shared"] = "分享的圖片",
        ["Source_FullScreen"] = "整個螢幕",
        ["Source_Region"] = "螢幕區域",
        ["Source_Codes"] = "{0}（條碼）",

        ["FileType_Image"] = "{0} 圖片",

        ["Region_Hint"] = "拖曳滑鼠框選區域　·　Esc 或按右鍵取消",

        ["Err_NoLanguagePack"] = "Windows 未安裝該語言的 OCR 語言套件。請在「時間與語言 → 語言與地區」中新增。",
        ["Err_TextTooLong"] = "文字超出本機模型的處理長度，請分段翻譯。",
        ["Err_ModelDeclined"] = "本機模型拒絕翻譯這段文字。",
        ["Err_TranslationFailed"] = "本機翻譯沒有傳回結果。",
        ["Btn_About"] = "關於 Glyfo",
        ["About_Title"] = "關於 Glyfo",
        ["About_Version"] = "版本 {0}",
        ["About_Tagline"] = "在本機讀取圖片中的文字，全程不連網。",
        ["About_Rate"] = "為 Glyfo 評分",
        ["About_WhatsNew"] = "更新說明",
        ["About_Source"] = "GitHub 原始碼",
        ["About_Privacy"] = "隱私權原則",
        ["Common_Close"] = "關閉",
        ["News_Title"] = "更新說明",
        ["News_110_1"] = "新增「關於」頁面，可查看版本號、原始碼與隱私權原則。",
        ["News_110_2"] = "可以直接在視窗裡為 Glyfo 評分，不必跳到商店。",
        ["News_110_3"] = "每次更新到新版本，首次開啟時會顯示這份說明。",
        ["Rate_Title"] = "Glyfo 用起來還順手嗎？",
        ["Rate_Body"] = "商店裡的評分決定了別人能不能找到它，只需要幾秒鐘。",
        ["Rate_Action"] = "去評分",
        ["Rate_Later"] = "暫不",
    };
}
