using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Ko = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · 언어 팩 없음",
        ["Engine_OneLanguage"] = "Windows OCR · 1개 언어",
        ["Engine_ManyLanguages"] = "Windows OCR · {0}개 언어",
        ["Engine_OnDevice"] = "{0} · 장치에서 실행",

        ["Preview_Placeholder"] = "여기에 이미지를 끌어다 놓거나 아래의 파일, 캡처, 클립보드를 사용하세요",
        ["Btn_CopyImage"] = "복사",
        ["Tip_CopyImage"] = "이미지를 클립보드에 복사",
        ["Btn_SaveImage"] = "저장",
        ["Tip_SaveImage"] = "이미지를 다른 이름으로 저장…",
        ["Btn_FitToWindow"] = "창에 맞춤",
        ["Tip_FitToWindow"] = "창 크기에 맞게 확대·축소",
        ["Tip_ActualSize"] = "실제 픽셀 크기",
        ["Tip_PdfPrev"] = "이전 페이지",
        ["Tip_PdfNext"] = "다음 페이지",
        ["Action_Open"] = "링크 열기",
        ["Action_Mail"] = "메일 쓰기",
        ["Action_Call"] = "전화 걸기",
        ["Action_Search"] = "웹에서 검색",

        ["Voice_Placeholder"] = "음성",
        ["Tip_Voice"] = "읽어 줄 때 사용할 음성",
        ["Tip_Speak"] = "텍스트 읽어 주기",
        ["Tip_StopSpeak"] = "읽기 중지",
        ["Tip_CopyText"] = "텍스트 복사(Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "줄바꿈 제거",
        ["Tip_RemoveLineBreaks"] = "강제 줄바꿈을 문단으로 되돌립니다",
        ["Btn_RemoveSpaces"] = "공백 제거",
        ["Tip_RemoveSpaces"] = "모든 공백을 제거합니다. 한국어·중국어·일본어용",
        ["Result_Placeholder"] = "인식된 텍스트가 여기에 표시되며 직접 편집할 수 있습니다.",

        ["Btn_OpenFile"] = "파일",
        ["Tip_OpenFile"] = "이미지 파일 열기(Ctrl+O)",
        ["Btn_Capture"] = "캡처",
        ["Tip_Capture"] = "화면 영역을 선택해 인식합니다({0}). 전체 화면은 Ctrl+Shift+R.",
        ["Hotkey_Unavailable"] = "바로 가기 없음 — 두 조합 모두 다른 앱이 사용 중",
        ["Btn_Paste"] = "클립보드",
        ["Tip_Paste"] = "클립보드에서 이미지나 텍스트 가져오기(Ctrl+V)",
        ["Btn_History"] = "기록",
        ["Tip_History"] = "최근 인식 결과",
        ["History_Empty"] = "아직 인식한 내용이 없습니다.",
        ["History_EmptyPreview"] = "(비어 있음)",
        ["Tip_Settings"] = "옵션",
        ["Settings_Header"] = "옵션",
        ["Setting_UiLanguage"] = "앱 언어",
        ["Lang_SystemDefault"] = "시스템 설정 따르기",
        ["Setting_RepairNumbers"] = "숫자 안의 l과 I 교정",
        ["Setting_RepairNumbers_Desc"] = "인식 엔진은 v1.6.5를 vl.6.5로 읽는 일이 잦습니다. 켜면 l이나 I 옆에 구분 기호와 숫자가 함께 있을 때만 1로 바꾸므로 html5와 IPv6은 그대로 둡니다. 끄면 엔진이 읽은 그대로 유지합니다.",
        ["Setting_WatchClipboard"] = "복사한 그림 읽기",
        ["Setting_WatchClipboard_Desc"] = "Win+Shift+S로 화면을 캡처하면 Glyfo가 곧바로 읽어 그림 대신 텍스트를 클립보드에 넣으므로, 다음 붙여넣기는 텍스트가 됩니다. 그림만 읽고 복사한 텍스트는 읽지 않으며, 어디로도 전송하지 않습니다. 모든 과정이 이 기기 안에서 이루어집니다.",
        ["Common_On"] = "켬",
        ["Common_Off"] = "끔",
        ["Lang_Placeholder"] = "언어",
        ["Tip_OcrLanguage"] = "인식 언어입니다. Windows에 설치된 언어 팩에서 가져옵니다",
        ["Btn_Translate"] = "번역",
        ["Tip_Translate"] = "이 장치에서 번역합니다. 네트워크로 전송되는 내용은 없습니다",
        ["Btn_Barcode"] = "코드",
        ["Tip_Barcode"] = "이미지의 QR 코드와 바코드 읽기",
        ["Btn_Recognize"] = "인식",
        ["Tip_Recognize"] = "이미지의 텍스트를 인식(F5)",

        ["Option_AutoAi"] = "자동 감지(Windows AI)",
        ["Option_AutoMulti"] = "자동 감지(다국어 · 느림)",

        ["Status_Loaded"] = "{0}을(를) 가져왔습니다.",
        ["Status_OpenFailed"] = "이미지를 열 수 없습니다: {0}",
        ["Status_ClipboardText"] = "클립보드에서 텍스트를 가져왔습니다.",
        ["Status_ClipboardEmpty"] = "클립보드에 이미지도 텍스트도 없습니다.",
        ["Status_ClipboardFailed"] = "클립보드를 읽을 수 없습니다: {0}",
        ["Status_DropFailed"] = "끌어다 놓은 항목을 사용할 수 없습니다: {0}",
        ["Status_ImageCopied"] = "이미지를 클립보드에 복사했습니다.",
        ["Status_ImageCopyFailed"] = "이미지를 복사할 수 없습니다: {0}",
        ["Status_ImageSaved"] = "이미지를 {0}(으)로 저장했습니다.",
        ["Status_ImageSaveFailed"] = "이미지를 저장할 수 없습니다: {0}",
        ["Status_Recognizing"] = "인식하는 중…",
        ["Status_NoText"] = "{0}이(가) 이 이미지에서 텍스트를 찾지 못했습니다.",
        ["Status_Done"] = "완료({0}).",
        ["Status_DoneConfidence"] = "완료({0}) · 평균 신뢰도 {1}%.",
        ["Status_RecognizeFailed"] = "인식하지 못했습니다: {0}",
        ["Status_Scanning"] = "QR 코드와 바코드를 찾는 중…",
        ["Status_NoBarcode"] = "이 이미지에는 QR 코드나 바코드가 없습니다.",
        ["Status_BarcodeOne"] = "{0} 코드 1개를 찾았습니다.",
        ["Status_BarcodeMany"] = "코드 {0}개를 찾았습니다.",
        ["Status_ScanFailed"] = "검사에 실패했습니다: {0}",
        ["Status_PdfFailed"] = "이 PDF를 읽을 수 없습니다. 암호로 보호되어 있거나 손상되었을 수 있습니다",
        ["Status_LaunchFailed"] = "Windows에 이것을 열 수 있는 항목이 없습니다.",
        ["Status_NothingToTranslate"] = "번역할 텍스트가 없습니다.",
        ["Status_Translating"] = "이 장치에서 {0}(으)로 번역하는 중…",
        ["Status_Translated"] = "{0}(으)로 번역했습니다. 모두 이 장치에서 처리되었고 네트워크는 쓰지 않았습니다.",
        ["Status_TranslateFailed"] = "번역하지 못했습니다: {0}",
        ["Status_NothingToCopy"] = "복사할 텍스트가 없습니다.",
        ["Status_TextCopied"] = "텍스트를 클립보드에 복사했습니다.",
        ["Status_CopyFailed"] = "텍스트를 복사할 수 없습니다: {0}",
        ["Status_NothingToSpeak"] = "읽어 줄 텍스트가 없습니다.",
        ["Status_SpeakFailed"] = "읽어 줄 수 없습니다: {0}",
        ["Status_HistoryLoaded"] = "{0}의 결과를 표시하고 있습니다.",
        ["Status_NeedImage"] = "먼저 이미지를 가져오세요.",
        ["Status_CaptureFailed"] = "화면 캡처에 실패했습니다: {0}",
        ["Status_StartupBlockedByUser"] = "Windows에서 Glyfo의 시작 프로그램 등록이 해제되어 있습니다. 작업 관리자의 시작 앱에서 다시 켜세요.",
        ["Status_StartupBlockedByPolicy"] = "조직 정책에 따라 앱을 Windows 시작 시 실행할 수 없습니다.",
        ["Status_LanguagePackMissing"] = "Windows에 OCR 언어 팩이 하나도 설치되어 있지 않아 인식할 수 없습니다. [시간 및 언어] → [언어 및 지역]에서 필요한 언어를 추가하세요.",
        ["Btn_OpenLanguageSettings"] = "언어 설정 열기",

        ["Tray_Open"] = "Glyfo 열기",
        ["Tray_CaptureRegion"] = "영역 캡처",
        ["Tray_CaptureFullScreen"] = "전체 화면 캡처",
        ["Tray_Exit"] = "종료",
        ["Tray_Tooltip"] = "Glyfo — {0} 키로 영역을 캡처합니다",
        ["Toast_StartupTitle"] = "Glyfo 실행 중",
        ["Toast_StartupBody"] = "{0} 키를 누르면 화면 영역을 선택해 글자를 인식합니다. 전체 화면은 Ctrl+Shift+R.",
        ["Toast_DontRemind"] = "다시 알리지 않음",
        ["Toast_MinimizedTitle"] = "Glyfo가 계속 실행 중입니다",
        ["Toast_MinimizedBody"] = "언제든 {0} 키로 캡처하고 인식할 수 있습니다. 완전히 끝내려면 알림 영역의 아이콘을 마우스 오른쪽 단추로 클릭하고 [종료]를 선택하세요.",
        ["Toast_ExitApp"] = "Glyfo 종료",
        ["Toast_ResultTitle"] = "글자를 인식했습니다",
        ["Toast_ResultCopied"] = "클립보드에 복사했습니다.",
        ["Toast_OpenWindow"] = "창 열기",
        ["Toast_NoTextTitle"] = "글자를 찾지 못했습니다",
        ["Toast_NoTextBody"] = "그 영역에는 글자로 읽을 수 있는 것이 없었습니다.",
        ["Toast_FailedTitle"] = "인식에 실패했습니다",
        ["Toast_HotkeyUnavailableTitle"] = "캡처 바로 가기가 사용 중입니다",
        ["Toast_HotkeyUnavailableBody"] = "다른 앱이 이미 사용하고 있어 화면 캡처는 창과 알림 영역 아이콘에서만 할 수 있습니다.",
        ["Setting_CloseToTray"] = "창을 닫아도 계속 실행",
        ["Setting_CloseToTray_Desc"] = "켜면 창을 닫아도 Glyfo가 계속 실행되어 캡처 바로 가기를 쓸 수 있고, 아이콘은 알림 영역에 남아 그곳의 [종료]로 완전히 닫을 수 있습니다. 끄면 창을 닫을 때 앱이 종료됩니다.",
        ["Setting_Startup"] = "Windows 시작 시 실행",
        ["Setting_Startup_Desc"] = "켜면 Glyfo이 Windows와 함께 시작되어 창을 열지 않고 곧바로 알림 영역으로 들어갑니다. 로그인한 순간부터 캡처 단축키를 쓸 수 있습니다.",

        ["Source_Clipboard"] = "클립보드 이미지",
        ["Source_Dropped"] = "끌어다 놓은 이미지",
        ["Source_Shared"] = "공유된 이미지",
        ["Source_FullScreen"] = "전체 화면",
        ["Source_Region"] = "화면 영역",
        ["Source_Codes"] = "{0}(코드)",

        ["FileType_Image"] = "{0} 이미지",

        ["Region_Hint"] = "끌어서 영역을 선택　·　Esc 또는 마우스 오른쪽 단추로 취소",

        ["Err_NoLanguagePack"] = "이 언어의 OCR 언어 팩이 Windows에 설치되어 있지 않습니다. [시간 및 언어] → [언어 및 지역]에서 추가하세요.",
        ["Err_TextTooLong"] = "장치 내 모델이 처리하기에 텍스트가 너무 깁니다. 나누어 번역하세요.",
        ["Err_ModelDeclined"] = "장치 내 모델이 이 텍스트의 번역을 거부했습니다.",
        ["Err_TranslationFailed"] = "장치 내 번역이 결과를 반환하지 않았습니다.",
        ["Btn_About"] = "Glyfo 정보",
        ["About_Title"] = "Glyfo 정보",
        ["About_Version"] = "버전 {0}",
        ["About_Tagline"] = "이미지 속 글자를 이 기기에서만 읽습니다. 네트워크로 나가는 것은 없습니다.",
        ["About_Rate"] = "Glyfo 평가하기",
        ["About_WhatsNew"] = "새로운 기능",
        ["About_Source"] = "GitHub 소스 코드",
        ["About_Privacy"] = "개인정보처리방침",
        ["Common_Close"] = "닫기",
        ["News_Title"] = "새로운 기능",
        ["News_120_1"] = "Win+Shift+S로 화면을 캡처하면 Glyfo가 대신 읽어 텍스트를 클립보드에 남깁니다. 옵션에서 켜기 전까지는 꺼져 있습니다.",
        ["News_120_2"] = "이제 PDF도 그림처럼 한 페이지씩 열 수 있습니다.",
        ["News_120_3"] = "텍스트에서 찾은 링크, 메일 주소, 전화번호에는 아래에 단추가 생깁니다.",
        ["News_110_1"] = "버전, 소스 코드, 개인정보처리방침을 모아 놓은 정보 화면이 생겼습니다.",
        ["News_110_2"] = "스토어로 나가지 않고 창 안에서 바로 평가할 수 있습니다.",
        ["News_110_3"] = "새 버전을 처음 열 때 이 변경 내용을 한 번 보여 줍니다.",
        ["News_110_4"] = "캡처에 전체 화면이 추가되었습니다. 찍기 전에 창을 숨기므로 Glyfo가 화면에 담기지 않습니다.",
        ["Rate_Title"] = "Glyfo가 도움이 되고 있나요?",
        ["Rate_Body"] = "스토어 평가는 다른 사람이 이 앱을 찾는 유일한 방법입니다. 잠깐이면 됩니다.",
        ["Rate_Action"] = "평가하기",
        ["Rate_Later"] = "나중에",
    };
}
