using System;
using System.Collections.Generic;

namespace Glyfo.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Pl = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR systemu Windows · brak pakietu językowego",
        ["Engine_OneLanguage"] = "OCR systemu Windows · 1 język",
        ["Engine_ManyLanguages"] = "OCR systemu Windows · języki: {0}",
        ["Engine_OnDevice"] = "{0} · lokalnie na urządzeniu",

        ["Preview_Placeholder"] = "Upuść tutaj obraz albo użyj przycisków Plik, Zrzut lub Schowek poniżej",
        ["Btn_CopyImage"] = "Kopiuj",
        ["Tip_CopyImage"] = "Kopiuj obraz do schowka",
        ["Btn_SaveImage"] = "Zapisz",
        ["Tip_SaveImage"] = "Zapisz obraz jako…",
        ["Btn_FitToWindow"] = "Dopasuj",
        ["Tip_FitToWindow"] = "Dopasuj powiększenie do okna",
        ["Tip_ActualSize"] = "Rzeczywisty rozmiar w pikselach",
        ["Tip_PdfPrev"] = "Poprzednia strona",
        ["Tip_PdfNext"] = "Następna strona",
        ["Tip_PdfAll"] = "Odczytaj wszystkie strony",
        ["Action_Open"] = "Otwórz łącze",
        ["Action_Mail"] = "Napisz do",
        ["Action_Call"] = "Zadzwoń pod",
        ["Action_Search"] = "Szukaj w sieci",

        ["Voice_Placeholder"] = "Głos",
        ["Tip_Voice"] = "Głos używany do czytania na głos",
        ["Tip_Speak"] = "Przeczytaj tekst na głos",
        ["Tip_StopSpeak"] = "Zatrzymaj czytanie",
        ["Tip_CopyText"] = "Kopiuj tekst (Ctrl+Shift+C)",
        ["Tip_SaveText"] = "Zapisz tekst do pliku (Ctrl+S)",
        ["Btn_RemoveLineBreaks"] = "Bez łamania",
        ["Tip_RemoveLineBreaks"] = "Scal twarde końce wierszy z powrotem w akapity",
        ["Btn_RemoveSpaces"] = "Bez spacji",
        ["Tip_RemoveSpaces"] = "Usuń wszystkie spacje — dla chińskiego, japońskiego i koreańskiego",
        ["Result_Placeholder"] = "Rozpoznany tekst pojawi się tutaj i można go edytować.",

        ["Btn_OpenFile"] = "Plik",
        ["Tip_OpenFile"] = "Otwórz plik obrazu (Ctrl+O)",
        ["Btn_Capture"] = "Zrzut",
        ["Tip_Capture"] = "Zaznacz obszar ekranu i rozpoznaj go ({0}). Naciśnij Ctrl+Shift+R, aby objąć cały ekran.",
        ["Hotkey_Unavailable"] = "brak skrótu — oba zajęła inna aplikacja",
        ["Btn_Paste"] = "Schowek",
        ["Tip_Paste"] = "Wczytaj obraz lub tekst ze schowka (Ctrl+V)",
        ["Btn_History"] = "Historia",
        ["Tip_History"] = "Ostatnie wyniki",
        ["History_Empty"] = "Nic jeszcze nie rozpoznano.",
        ["History_EmptyPreview"] = "(puste)",
        ["History_SearchPlaceholder"] = "Szukaj w wynikach",
        ["History_NoMatch"] = "Żaden wynik nie pasuje.",
        ["History_Off"] = "Historia jest wyłączona w opcjach.",
        ["History_Clear"] = "Wyczyść historię",
        ["History_CopyItem"] = "Kopiuj ten tekst",
        ["History_DeleteItem"] = "Usuń ten wpis",
        ["Tip_Settings"] = "Opcje",
        ["Settings_Header"] = "Opcje",
        ["Setting_UiLanguage"] = "Język aplikacji",
        ["Lang_SystemDefault"] = "Domyślny systemu",
        ["Setting_RepairNumbers"] = "Popraw l oraz I wewnątrz liczb",
        ["Setting_RepairNumbers_Desc"] = "Silniki rozpoznawania regularnie odczytują v1.6.5 jako vl.6.5. Gdy opcja jest włączona, l lub I zamienia się w 1 tylko tam, gdzie obok stoi separator i cyfra, więc html5 i IPv6 pozostają nietknięte. Gdy jest wyłączona, odczyt silnika zostaje zachowany dokładnie taki, jaki przyszedł.",
        ["Setting_WatchClipboard"] = "Odczytuj kopiowane obrazy",
        ["Setting_WatchClipboard_Desc"] = "Zrób zrzut ekranu klawiszami Win+Shift+S, a Glyfo od razu go odczyta i umieści w schowku tekst zamiast obrazu, więc następne wklejenie da tekst. Odczytywane są tylko obrazy, nigdy skopiowany tekst, i nic nie jest nigdzie wysyłane — wszystko dzieje się na tym urządzeniu.",
        ["Setting_KeepHistory"] = "Zachowuj historię między sesjami",
        ["Setting_KeepHistory_Desc"] = "Zachowuje ostatnie 200 wyników, więc są dostępne także po ponownym uruchomieniu. Zapisywany jest tylko tekst, nigdy obrazy, w pliku należącym do Glyfo na tym urządzeniu. Wyłączenie tej opcji usuwa ten plik i od razu czyści listę.",
        ["Common_On"] = "Wł.",
        ["Common_Off"] = "Wył.",
        ["Lang_Placeholder"] = "Język",
        ["Tip_OcrLanguage"] = "Język rozpoznawania, spośród pakietów językowych zainstalowanych w systemie Windows",
        ["Btn_Translate"] = "Przetłumacz",
        ["Tip_Translate"] = "Tłumacz na tym urządzeniu — nic nie jest wysyłane przez sieć",
        ["Btn_Barcode"] = "Kody",
        ["Tip_Barcode"] = "Odczytaj kody QR i kody kreskowe z obrazu",
        ["Btn_Recognize"] = "Rozpoznaj",
        ["Tip_Recognize"] = "Rozpoznaj tekst na obrazie (F5)",

        ["Option_AutoAi"] = "Automatycznie (Windows AI)",
        ["Option_AutoMulti"] = "Automatycznie (wiele języków · wolniej)",

        ["Status_Loaded"] = "Wczytano: {0}.",
        ["Status_OpenFailed"] = "Nie udało się otworzyć obrazu: {0}",
        ["Status_ClipboardText"] = "Wczytano tekst ze schowka.",
        ["Status_ClipboardEmpty"] = "W schowku nie ma ani obrazu, ani tekstu.",
        ["Status_ClipboardFailed"] = "Nie udało się odczytać schowka: {0}",
        ["Status_DropFailed"] = "Nie udało się użyć upuszczonego elementu: {0}",
        ["Status_ImageCopied"] = "Obraz skopiowany do schowka.",
        ["Status_ImageCopyFailed"] = "Nie udało się skopiować obrazu: {0}",
        ["Status_ImageSaved"] = "Obraz zapisany jako {0}.",
        ["Status_ImageSaveFailed"] = "Nie udało się zapisać obrazu: {0}",
        ["Status_Recognizing"] = "Rozpoznawanie…",
        ["Status_NoText"] = "{0} nie znalazł tekstu na tym obrazie.",
        ["Status_Done"] = "Gotowe ({0}).",
        ["Status_DoneConfidence"] = "Gotowe ({0}) · średnia pewność {1}%.",
        ["Status_RecognizeFailed"] = "Rozpoznawanie nie powiodło się: {0}",
        ["Status_Scanning"] = "Trwa szukanie kodów QR i kodów kreskowych…",
        ["Status_NoBarcode"] = "Nie znaleziono na tym obrazie kodu QR ani kodu kreskowego.",
        ["Status_BarcodeOne"] = "Znaleziono jeden kod {0}.",
        ["Status_BarcodeMany"] = "Znaleziono kody: {0}.",
        ["Status_ScanFailed"] = "Skanowanie nie powiodło się: {0}",
        ["Status_PdfFailed"] = "nie udało się odczytać tego pliku PDF — może być chroniony hasłem lub uszkodzony",
        ["Status_LaunchFailed"] = "System Windows nie znalazł niczego, czym mógłby to otworzyć.",
        ["Status_NothingToTranslate"] = "Nie ma tekstu do przetłumaczenia.",
        ["Status_Translating"] = "Tłumaczenie na {0} na tym urządzeniu…",
        ["Status_Translated"] = "Przetłumaczono na {0}, na tym urządzeniu, bez dostępu do sieci.",
        ["Status_TranslateFailed"] = "Tłumaczenie nie powiodło się: {0}",
        ["Status_NothingToCopy"] = "Nie ma tekstu do skopiowania.",
        ["Status_NothingToSave"] = "Nie ma tekstu do zapisania.",
        ["Status_TextSaved"] = "Tekst zapisany jako {0}.",
        ["Status_TextSaveFailed"] = "Nie udało się zapisać tekstu: {0}",
        ["Status_TextCopied"] = "Tekst skopiowany do schowka.",
        ["Status_CopyFailed"] = "Nie udało się skopiować tekstu: {0}",
        ["Status_NothingToSpeak"] = "Nie ma tekstu do przeczytania na głos.",
        ["Status_SpeakFailed"] = "Nie udało się przeczytać tekstu na głos: {0}",
        ["Status_HistoryLoaded"] = "Pokazywany jest wynik z {0}.",
        ["Status_HistoryCleared"] = "Historia wyczyszczona.",
        ["Status_NeedImage"] = "Najpierw wczytaj obraz.",
        ["Status_CaptureFailed"] = "Przechwycenie ekranu nie powiodło się: {0}",
        ["Status_StartupBlockedByUser"] = "System Windows wyłączył automatyczne uruchamianie Glyfo. Włącz je ponownie w Menedżerze zadań, w sekcji Aplikacje startowe.",
        ["Status_StartupBlockedByPolicy"] = "Twoja organizacja nie zezwala aplikacjom na uruchamianie razem z systemem Windows.",
        ["Status_LanguagePackMissing"] = "W systemie Windows nie zainstalowano żadnego pakietu językowego OCR, więc nie ma czym rozpoznawać. Dodaj potrzebny język w sekcji Czas i język, a następnie Język i region.",
        ["Btn_OpenLanguageSettings"] = "Otwórz ustawienia języka",

        ["Tray_Open"] = "Otwórz Glyfo",
        ["Tray_CaptureRegion"] = "Przechwyć obszar",
        ["Tray_CaptureFullScreen"] = "Przechwyć cały ekran",
        ["Tray_Exit"] = "Zakończ",
        ["Tray_Tooltip"] = "Glyfo — naciśnij {0}, aby przechwycić obszar",
        ["Toast_StartupTitle"] = "Glyfo działa",
        ["Toast_StartupBody"] = "Naciśnij {0}, aby zaznaczyć fragment ekranu i odczytać z niego tekst. Ctrl+Shift+R obejmuje cały ekran.",
        ["Toast_DontRemind"] = "Nie przypominaj więcej",
        ["Toast_MinimizedTitle"] = "Glyfo nadal działa",
        ["Toast_MinimizedBody"] = "Naciśnij {0} w dowolnej chwili, aby przechwycić obraz i rozpoznać tekst. Aby zamknąć program na dobre, kliknij prawym przyciskiem jego ikonę w obszarze powiadomień i wybierz Zakończ.",
        ["Toast_ExitApp"] = "Zakończ Glyfo",
        ["Toast_ResultTitle"] = "Rozpoznano tekst",
        ["Toast_ResultCopied"] = "Skopiowano do schowka.",
        ["Toast_OpenWindow"] = "Otwórz okno",
        ["Toast_NoTextTitle"] = "Nie znaleziono tekstu",
        ["Toast_NoTextBody"] = "W tym obszarze nie było niczego, co dałoby się odczytać jako tekst.",
        ["Toast_FailedTitle"] = "Rozpoznawanie nie powiodło się",
        ["Toast_HotkeyUnavailableTitle"] = "Skrót przechwytywania jest zajęty",
        ["Toast_HotkeyUnavailableBody"] = "Zajęła go inna aplikacja, więc ekran można przechwycić tylko z okna i z ikony w obszarze powiadomień.",
        ["Setting_CloseToTray"] = "Działaj dalej po zamknięciu okna",
        ["Setting_CloseToTray_Desc"] = "Gdy ta opcja jest włączona, zamknięcie okna pozostawia Glyfo uruchomiony, więc skrót przechwytywania nadal działa, a ikona zostaje w obszarze powiadomień, gdzie polecenie Zakończ zamyka program na dobre. Gdy jest wyłączona, zamknięcie okna kończy działanie aplikacji.",
        ["Setting_Startup"] = "Uruchamiaj razem z systemem Windows",
        ["Setting_Startup_Desc"] = "Gdy ta opcja jest włączona, Glyfo uruchamia się razem z systemem Windows i od razu trafia do obszaru powiadomień, bez otwierania okna, dzięki czemu skrót przechwytywania działa zaraz po zalogowaniu.",

        ["Source_Clipboard"] = "obraz ze schowka",
        ["Source_Dropped"] = "upuszczony obraz",
        ["Source_Shared"] = "udostępniony obraz",
        ["Source_FullScreen"] = "Cały ekran",
        ["Source_Region"] = "Obszar ekranu",
        ["Source_Codes"] = "{0} (kody)",
        ["Source_Batch"] = "Pliki: {0}",
        ["Source_PdfAll"] = "{0}, wszystkie strony",

        ["FileType_Image"] = "Obraz {0}",
        ["FileType_Text"] = "Zwykły tekst",
        ["FileType_Markdown"] = "Markdown",
        ["Batch_Title"] = "Odczytywanie wielu plików",
        ["Batch_Progress"] = "{0} z {1}",
        ["Batch_DoneAll"] = "Odczytano: {0}.",
        ["Batch_Cancelled"] = "Zatrzymano po {0} z {1}.",
        ["Batch_ItemFailed"] = "Nie udało się odczytać: {0}",
        ["Batch_ItemEmpty"] = "(brak tekstu)",
        ["Batch_Save"] = "Zapisz…",
        ["Batch_CopyAll"] = "Kopiuj wszystko",
        ["Batch_Separate"] = "Zapisz każdą pozycję w osobnym pliku",
        ["Batch_SavedFolder"] = "Zapisano {0} plików w {1}.",
        ["Batch_TooLongForBox"] = "Odczytano {0} pozycji. Tekst jest za długi, aby go tu pokazać — jest w pliku, który zapisano.",

        ["Region_Hint"] = "Przeciągnij, aby zaznaczyć obszar　·　Esc lub prawy przycisk myszy anuluje",

        ["Err_NoLanguagePack"] = "W systemie Windows nie zainstalowano pakietu językowego OCR dla tego języka. Dodaj go w sekcji Czas i język, a następnie Język i region.",
        ["Err_TextTooLong"] = "Tekst jest za długi dla modelu działającego na urządzeniu. Przetłumacz mniejszy fragment.",
        ["Err_ModelDeclined"] = "Model na urządzeniu odmówił przetłumaczenia tego tekstu.",
        ["Err_TranslationFailed"] = "Tłumaczenie na urządzeniu nie dało wyniku.",
        ["Btn_About"] = "Glyfo — informacje",
        ["About_Title"] = "Glyfo — informacje",
        ["About_Version"] = "Wersja {0}",
        ["About_Tagline"] = "Odczytuje tekst z dowolnego obrazu, na tym urządzeniu. Nic nie jest wysyłane przez sieć.",
        ["About_Rate"] = "Oceń Glyfo",
        ["About_WhatsNew"] = "Co nowego",
        ["About_Source"] = "Kod źródłowy w serwisie GitHub",
        ["About_Privacy"] = "Zasady zachowania poufności informacji",
        ["Common_Close"] = "Zamknij",
        ["Common_Cancel"] = "Anuluj",
        ["News_Title"] = "Co nowego",
        ["News_130_1"] = "Historia przetrwa teraz ponowne uruchomienie i ma pole wyszukiwania. Zachowywany jest tylko tekst — w opcjach można ją wyczyścić lub wyłączyć.",
        ["News_130_2"] = "Ctrl+S zapisuje rozpoznany tekst jako plik zwykłego tekstu lub Markdown.",
        ["News_130_3"] = "Otwórz albo przeciągnij kilka plików naraz lub odczytaj cały PDF i zapisz całość w jednym pliku albo po jednym na pozycję.",
        ["News_120_1"] = "Zrób zrzut ekranu klawiszami Win+Shift+S, a Glyfo odczyta go za Ciebie i zostawi tekst w schowku. Funkcja jest wyłączona, dopóki nie włączysz jej w opcjach.",
        ["News_120_2"] = "Pliki PDF otwierają się teraz jak obrazy, strona po stronie.",
        ["News_120_3"] = "Znalezione w tekście łącza, adresy e-mail i numery telefonów dostają pod nim przycisk.",
        ["News_110_1"] = "Strona informacyjna z numerem wersji oraz linkami do kodu źródłowego i zasad zachowania poufności.",
        ["News_110_2"] = "Glyfo można ocenić bez wychodzenia z okna.",
        ["News_110_3"] = "Te informacje, pokazywane raz przy każdej nowej wersji.",
        ["News_110_4"] = "Przechwytywanie obejmuje teraz cały ekran i najpierw ukrywa okno, więc Glyfo nigdy nie trafia na zrzut.",
        ["Rate_Title"] = "Czy Glyfo się przydaje?",
        ["Rate_Body"] = "Ocena w Sklepie to sposób, w jaki inni znajdują tę aplikację. Zajmie to chwilę.",
        ["Rate_Action"] = "Oceń",
        ["Rate_Later"] = "Nie teraz",
    };
}
