using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Es = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · sin paquete de idioma",
        ["Engine_OneLanguage"] = "Windows OCR · 1 idioma",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} idiomas",
        ["Engine_OnDevice"] = "{0} · en el dispositivo",

        ["Preview_Placeholder"] = "Arrastre una imagen aquí, o use Archivo, Captura o Portapapeles abajo",
        ["Btn_CopyImage"] = "Copiar",
        ["Tip_CopyImage"] = "Copiar la imagen al portapapeles",
        ["Btn_SaveImage"] = "Guardar",
        ["Tip_SaveImage"] = "Guardar la imagen como…",
        ["Btn_FitToWindow"] = "Ajustar",
        ["Tip_FitToWindow"] = "Ajustar el zoom a la ventana",
        ["Tip_ActualSize"] = "Tamaño real en píxeles",

        ["Voice_Placeholder"] = "Voz",
        ["Tip_Voice"] = "Voz usada para la lectura",
        ["Tip_Speak"] = "Leer el texto en voz alta",
        ["Tip_StopSpeak"] = "Detener la lectura",
        ["Tip_CopyText"] = "Copiar el texto (Ctrl+Mayús+C)",
        ["Btn_RemoveLineBreaks"] = "Sin saltos",
        ["Tip_RemoveLineBreaks"] = "Unir los saltos de línea en párrafos",
        ["Btn_RemoveSpaces"] = "Sin espacios",
        ["Tip_RemoveSpaces"] = "Quitar todos los espacios, para chino, japonés y coreano",
        ["Result_Placeholder"] = "El texto reconocido aparece aquí y se puede editar.",

        ["Btn_OpenFile"] = "Archivo",
        ["Tip_OpenFile"] = "Abrir un archivo de imagen (Ctrl+O)",
        ["Btn_Capture"] = "Captura",
        ["Tip_Capture"] = "Seleccionar una zona de la pantalla y reconocerla ({0}). Ctrl+Mayús+R para toda la pantalla.",
        ["Hotkey_Unavailable"] = "sin atajo: otra aplicación ocupa los dos",
        ["Btn_Paste"] = "Portapapeles",
        ["Tip_Paste"] = "Cargar una imagen o texto del portapapeles (Ctrl+V)",
        ["Btn_History"] = "Historial",
        ["Tip_History"] = "Resultados recientes",
        ["History_Empty"] = "Todavía no se ha reconocido nada.",
        ["History_EmptyPreview"] = "(vacío)",
        ["Tip_Settings"] = "Opciones",
        ["Settings_Header"] = "Opciones",
        ["Setting_UiLanguage"] = "Idioma de la aplicación",
        ["Lang_SystemDefault"] = "Idioma del sistema",
        ["Setting_RepairNumbers"] = "Corregir l e I dentro de los números",
        ["Setting_RepairNumbers_Desc"] = "Los motores leen v1.6.5 como vl.6.5 con frecuencia. Activado, una l o una I solo se convierte en 1 donde hay un separador y un dígito a su lado, de modo que html5 e IPv6 quedan intactos. Desactivado, se conserva exactamente la lectura del motor.",
        ["Common_On"] = "Activado",
        ["Common_Off"] = "Desactivado",
        ["Lang_Placeholder"] = "Idioma",
        ["Tip_OcrLanguage"] = "Idioma de reconocimiento, según los paquetes de idioma instalados en Windows",
        ["Btn_Translate"] = "Traducir",
        ["Tip_Translate"] = "Traducir en este dispositivo: no se envía nada por la red",
        ["Btn_Barcode"] = "Códigos",
        ["Tip_Barcode"] = "Leer los códigos QR y de barras de la imagen",
        ["Btn_Recognize"] = "Reconocer",
        ["Tip_Recognize"] = "Reconocer el texto de la imagen (F5)",

        ["Option_AutoAi"] = "Automático (Windows AI)",
        ["Option_AutoMulti"] = "Automático (multilingüe · más lento)",

        ["Status_Loaded"] = "Se cargó {0}.",
        ["Status_OpenFailed"] = "No se pudo abrir la imagen: {0}",
        ["Status_ClipboardText"] = "Se cargó texto del portapapeles.",
        ["Status_ClipboardEmpty"] = "El portapapeles no contiene ninguna imagen ni texto.",
        ["Status_ClipboardFailed"] = "No se pudo leer el portapapeles: {0}",
        ["Status_DropFailed"] = "No se pudo usar lo que se arrastró: {0}",
        ["Status_ImageCopied"] = "Imagen copiada al portapapeles.",
        ["Status_ImageCopyFailed"] = "No se pudo copiar la imagen: {0}",
        ["Status_ImageSaved"] = "Imagen guardada como {0}.",
        ["Status_ImageSaveFailed"] = "No se pudo guardar la imagen: {0}",
        ["Status_Recognizing"] = "Reconociendo…",
        ["Status_NoText"] = "{0} no encontró texto en esta imagen.",
        ["Status_Done"] = "Listo ({0}).",
        ["Status_DoneConfidence"] = "Listo ({0}) · confianza media {1} %.",
        ["Status_RecognizeFailed"] = "El reconocimiento falló: {0}",
        ["Status_Scanning"] = "Buscando códigos QR y de barras…",
        ["Status_NoBarcode"] = "No hay ningún código QR ni de barras en esta imagen.",
        ["Status_BarcodeOne"] = "Se encontró un código {0}.",
        ["Status_BarcodeMany"] = "Se encontraron {0} códigos.",
        ["Status_ScanFailed"] = "La búsqueda falló: {0}",
        ["Status_NothingToTranslate"] = "No hay texto que traducir.",
        ["Status_Translating"] = "Traduciendo al {0} en este dispositivo…",
        ["Status_Translated"] = "Traducido al {0}, en este dispositivo y sin acceso a la red.",
        ["Status_TranslateFailed"] = "La traducción falló: {0}",
        ["Status_NothingToCopy"] = "No hay texto que copiar.",
        ["Status_TextCopied"] = "Texto copiado al portapapeles.",
        ["Status_CopyFailed"] = "No se pudo copiar el texto: {0}",
        ["Status_NothingToSpeak"] = "No hay texto que leer.",
        ["Status_SpeakFailed"] = "No se pudo leer el texto: {0}",
        ["Status_HistoryLoaded"] = "Mostrando el resultado de {0}.",
        ["Status_NeedImage"] = "Cargue primero una imagen.",
        ["Status_CaptureFailed"] = "La captura de pantalla falló: {0}",
        ["Status_LanguagePackMissing"] = "Windows no tiene ningún paquete de idioma OCR instalado, así que no hay con qué reconocer. Agregue el idioma que necesite en Hora e idioma y luego Idioma y región.",
        ["Btn_OpenLanguageSettings"] = "Abrir la configuración de idioma",

        ["Source_Clipboard"] = "la imagen del portapapeles",
        ["Source_Dropped"] = "la imagen arrastrada",
        ["Source_FullScreen"] = "Pantalla completa",
        ["Source_Region"] = "Zona de la pantalla",
        ["Source_Codes"] = "{0} (códigos)",

        ["FileType_Image"] = "Imagen {0}",

        ["Region_Hint"] = "Arrastre para seleccionar una zona　·　Esc o clic derecho para cancelar",

        ["Err_NoLanguagePack"] = "Windows no tiene instalado el paquete de idioma OCR para este idioma. Agregue uno en Hora e idioma y luego Idioma y región.",
        ["Err_TextTooLong"] = "El texto es demasiado largo para el modelo local. Traduzca un fragmento más corto.",
        ["Err_ModelDeclined"] = "El modelo local se negó a traducir este texto.",
        ["Err_TranslationFailed"] = "La traducción local no devolvió ningún resultado.",
    };
}
