using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Pt = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR do Windows · sem pacote de idioma",
        ["Engine_OneLanguage"] = "OCR do Windows · 1 idioma",
        ["Engine_ManyLanguages"] = "OCR do Windows · {0} idiomas",
        ["Engine_OnDevice"] = "{0} · no dispositivo",

        ["Preview_Placeholder"] = "Solte uma imagem aqui, ou use Arquivo, Captura ou Área de transferência abaixo",
        ["Btn_CopyImage"] = "Copiar",
        ["Tip_CopyImage"] = "Copiar a imagem para a área de transferência",
        ["Btn_SaveImage"] = "Salvar",
        ["Tip_SaveImage"] = "Salvar a imagem como…",
        ["Btn_FitToWindow"] = "Ajustar",
        ["Tip_FitToWindow"] = "Ajustar o zoom à janela",
        ["Tip_ActualSize"] = "Tamanho real em pixels",

        ["Voice_Placeholder"] = "Voz",
        ["Tip_Voice"] = "Voz usada na leitura em voz alta",
        ["Tip_Speak"] = "Ler o texto em voz alta",
        ["Tip_StopSpeak"] = "Parar a leitura",
        ["Tip_CopyText"] = "Copiar o texto (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Sem quebras",
        ["Tip_RemoveLineBreaks"] = "Juntar as quebras de linha de volta em parágrafos",
        ["Btn_RemoveSpaces"] = "Sem espaços",
        ["Tip_RemoveSpaces"] = "Remover todos os espaços, para chinês, japonês e coreano",
        ["Result_Placeholder"] = "O texto reconhecido aparece aqui e pode ser editado.",

        ["Btn_OpenFile"] = "Arquivo",
        ["Tip_OpenFile"] = "Abrir um arquivo de imagem (Ctrl+O)",
        ["Btn_Capture"] = "Captura",
        ["Tip_Capture"] = "Selecionar uma região da tela e reconhecê-la ({0}). Pressione Ctrl+Shift+R para a tela inteira.",
        ["Hotkey_Unavailable"] = "sem atalho — outro aplicativo ocupou os dois",
        ["Btn_Paste"] = "Área de transferência",
        ["Tip_Paste"] = "Carregar uma imagem ou texto da área de transferência (Ctrl+V)",
        ["Btn_History"] = "Histórico",
        ["Tip_History"] = "Resultados recentes",
        ["History_Empty"] = "Nada reconhecido ainda.",
        ["History_EmptyPreview"] = "(vazio)",
        ["Tip_Settings"] = "Opções",
        ["Settings_Header"] = "Opções",
        ["Setting_UiLanguage"] = "Idioma do aplicativo",
        ["Lang_SystemDefault"] = "Padrão do sistema",
        ["Setting_RepairNumbers"] = "Corrigir l e I dentro de números",
        ["Setting_RepairNumbers_Desc"] = "Os reconhecedores leem v1.6.5 como vl.6.5 com frequência. Com esta opção ativada, um l ou I vira 1 apenas onde há um separador e um dígito ao lado, então html5 e IPv6 ficam intactos. Desativada, a leitura do mecanismo é mantida exatamente como veio.",
        ["Common_On"] = "Ativado",
        ["Common_Off"] = "Desativado",
        ["Lang_Placeholder"] = "Idioma",
        ["Tip_OcrLanguage"] = "Idioma de reconhecimento, entre os pacotes de idioma instalados no Windows",
        ["Btn_Translate"] = "Traduzir",
        ["Tip_Translate"] = "Traduzir neste dispositivo — nada é enviado pela rede",
        ["Btn_Barcode"] = "Códigos",
        ["Tip_Barcode"] = "Ler códigos QR e códigos de barras na imagem",
        ["Btn_Recognize"] = "Reconhecer",
        ["Tip_Recognize"] = "Reconhecer o texto da imagem (F5)",

        ["Option_AutoAi"] = "Automático (Windows AI)",
        ["Option_AutoMulti"] = "Automático (vários idiomas · mais lento)",

        ["Status_Loaded"] = "{0} carregada.",
        ["Status_OpenFailed"] = "Não foi possível abrir a imagem: {0}",
        ["Status_ClipboardText"] = "Texto carregado da área de transferência.",
        ["Status_ClipboardEmpty"] = "A área de transferência não contém imagem nem texto.",
        ["Status_ClipboardFailed"] = "Não foi possível ler a área de transferência: {0}",
        ["Status_DropFailed"] = "Não foi possível usar o que foi solto: {0}",
        ["Status_ImageCopied"] = "Imagem copiada para a área de transferência.",
        ["Status_ImageCopyFailed"] = "Não foi possível copiar a imagem: {0}",
        ["Status_ImageSaved"] = "Imagem salva como {0}.",
        ["Status_ImageSaveFailed"] = "Não foi possível salvar a imagem: {0}",
        ["Status_Recognizing"] = "Reconhecendo…",
        ["Status_NoText"] = "{0} não encontrou texto nesta imagem.",
        ["Status_Done"] = "Concluído ({0}).",
        ["Status_DoneConfidence"] = "Concluído ({0}) · confiança média de {1}%.",
        ["Status_RecognizeFailed"] = "O reconhecimento falhou: {0}",
        ["Status_Scanning"] = "Procurando códigos QR e códigos de barras…",
        ["Status_NoBarcode"] = "Nenhum código QR ou de barras encontrado nesta imagem.",
        ["Status_BarcodeOne"] = "Um código {0} encontrado.",
        ["Status_BarcodeMany"] = "{0} códigos encontrados.",
        ["Status_ScanFailed"] = "A leitura falhou: {0}",
        ["Status_NothingToTranslate"] = "Não há texto para traduzir.",
        ["Status_Translating"] = "Traduzindo para {0} neste dispositivo…",
        ["Status_Translated"] = "Traduzido para {0}, neste dispositivo, sem acesso à rede.",
        ["Status_TranslateFailed"] = "A tradução falhou: {0}",
        ["Status_NothingToCopy"] = "Não há texto para copiar.",
        ["Status_TextCopied"] = "Texto copiado para a área de transferência.",
        ["Status_CopyFailed"] = "Não foi possível copiar o texto: {0}",
        ["Status_NothingToSpeak"] = "Não há texto para ler em voz alta.",
        ["Status_SpeakFailed"] = "Não foi possível ler o texto em voz alta: {0}",
        ["Status_HistoryLoaded"] = "Mostrando o resultado de {0}.",
        ["Status_NeedImage"] = "Carregue uma imagem primeiro.",
        ["Status_CaptureFailed"] = "A captura de tela falhou: {0}",
        ["Status_LanguagePackMissing"] = "O Windows não tem nenhum pacote de idioma de OCR instalado, então não há com o que reconhecer. Adicione o idioma que você precisa em Hora e idioma, depois Idioma e região.",
        ["Btn_OpenLanguageSettings"] = "Abrir as configurações de idioma",

        ["Source_Clipboard"] = "a imagem da área de transferência",
        ["Source_Dropped"] = "a imagem solta",
        ["Source_FullScreen"] = "Tela inteira",
        ["Source_Region"] = "Região da tela",
        ["Source_Codes"] = "{0} (códigos)",

        ["FileType_Image"] = "Imagem {0}",

        ["Region_Hint"] = "Arraste para selecionar uma área　·　Esc ou clique com o botão direito para cancelar",

        ["Err_NoLanguagePack"] = "O Windows não tem pacote de idioma de OCR instalado para este idioma. Adicione um em Hora e idioma, depois Idioma e região.",
        ["Err_TextTooLong"] = "O texto é longo demais para o modelo local. Traduza um trecho menor.",
        ["Err_ModelDeclined"] = "O modelo local recusou-se a traduzir este texto.",
        ["Err_TranslationFailed"] = "A tradução local não produziu resultado.",
    };
}
