using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> He = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "‏OCR של Windows · אין ערכת שפה",
        ["Engine_OneLanguage"] = "‏OCR של Windows · שפה אחת",
        ["Engine_ManyLanguages"] = "‏OCR של Windows · {0} שפות",
        ["Engine_OnDevice"] = "{0} · במכשיר",

        ["Preview_Placeholder"] = "גררו לכאן תמונה, או השתמשו בקובץ, בצילום מסך או בלוח בהמשך",
        ["Btn_CopyImage"] = "העתקה",
        ["Tip_CopyImage"] = "העתקת התמונה ללוח",
        ["Btn_SaveImage"] = "שמירה",
        ["Tip_SaveImage"] = "שמירת התמונה בשם…",
        ["Btn_FitToWindow"] = "התאמה",
        ["Tip_FitToWindow"] = "התאמת מרחק התצוגה לחלון",
        ["Tip_ActualSize"] = "גודל אמיתי בפיקסלים",

        ["Voice_Placeholder"] = "קול",
        ["Tip_Voice"] = "הקול שמשמש להקראה",
        ["Tip_Speak"] = "הקראת הטקסט",
        ["Tip_StopSpeak"] = "עצירת ההקראה",
        ["Tip_CopyText"] = "העתקת הטקסט (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "איחוד שורות",
        ["Tip_RemoveLineBreaks"] = "איחוד מעברי שורה חזרה לפסקאות",
        ["Btn_RemoveSpaces"] = "בלי רווחים",
        ["Tip_RemoveSpaces"] = "הסרת כל הרווחים — לסינית, ליפנית ולקוריאנית",
        ["Result_Placeholder"] = "הטקסט שזוהה יופיע כאן וניתן לערוך אותו.",

        ["Btn_OpenFile"] = "קובץ",
        ["Tip_OpenFile"] = "פתיחת קובץ תמונה (Ctrl+O)",
        ["Btn_Capture"] = "צילום מסך",
        ["Tip_Capture"] = "בחרו אזור במסך וזהו אותו ({0}). הקישו Ctrl+Shift+R למסך המלא.",
        ["Hotkey_Unavailable"] = "אין קיצור — יישום אחר תפס את שניהם",
        ["Btn_Paste"] = "לוח",
        ["Tip_Paste"] = "טעינת תמונה או טקסט מהלוח (Ctrl+V)",
        ["Btn_History"] = "היסטוריה",
        ["Tip_History"] = "תוצאות אחרונות",
        ["History_Empty"] = "עדיין לא זוהה דבר.",
        ["History_EmptyPreview"] = "(ריק)",
        ["Tip_Settings"] = "אפשרויות",
        ["Settings_Header"] = "אפשרויות",
        ["Setting_UiLanguage"] = "שפת היישום",
        ["Lang_SystemDefault"] = "ברירת המחדל של המערכת",
        ["Setting_RepairNumbers"] = "תיקון l ו‑I בתוך מספרים",
        ["Setting_RepairNumbers_Desc"] = "מנועי זיהוי קוראים לא אחת את v1.6.5 כ‑vl.6.5. כשהאפשרות פועלת, האות l או I הופכת ל‑1 רק היכן שיש לצדה מפריד וספרה, כך ש‑html5 ו‑IPv6 נשארים כמות שהם. כשהיא כבויה, קריאת המנוע נשמרת בדיוק כפי שהתקבלה.",
        ["Common_On"] = "פועל",
        ["Common_Off"] = "כבוי",
        ["Lang_Placeholder"] = "שפה",
        ["Tip_OcrLanguage"] = "שפת הזיהוי, מתוך ערכות השפה המותקנות ב‑Windows",
        ["Btn_Translate"] = "תרגום",
        ["Tip_Translate"] = "תרגום במכשיר הזה — דבר אינו נשלח ברשת",
        ["Btn_Barcode"] = "קודים",
        ["Tip_Barcode"] = "קריאת קודי QR וברקודים בתמונה",
        ["Btn_Recognize"] = "זיהוי",
        ["Tip_Recognize"] = "זיהוי הטקסט בתמונה (F5)",

        ["Option_AutoAi"] = "אוטומטי (Windows AI)",
        ["Option_AutoMulti"] = "אוטומטי (כמה שפות · אטי יותר)",

        ["Status_Loaded"] = "{0} נטען.",
        ["Status_OpenFailed"] = "לא ניתן היה לפתוח את התמונה: {0}",
        ["Status_ClipboardText"] = "טקסט נטען מהלוח.",
        ["Status_ClipboardEmpty"] = "בלוח אין תמונה ואין טקסט.",
        ["Status_ClipboardFailed"] = "לא ניתן היה לקרוא את הלוח: {0}",
        ["Status_DropFailed"] = "לא ניתן היה להשתמש במה שנגרר: {0}",
        ["Status_ImageCopied"] = "התמונה הועתקה ללוח.",
        ["Status_ImageCopyFailed"] = "לא ניתן היה להעתיק את התמונה: {0}",
        ["Status_ImageSaved"] = "התמונה נשמרה בשם {0}.",
        ["Status_ImageSaveFailed"] = "לא ניתן היה לשמור את התמונה: {0}",
        ["Status_Recognizing"] = "מזהה…",
        ["Status_NoText"] = "{0} לא מצא טקסט בתמונה הזאת.",
        ["Status_Done"] = "הסתיים ({0}).",
        ["Status_DoneConfidence"] = "הסתיים ({0}) · ביטחון ממוצע {1}%.",
        ["Status_RecognizeFailed"] = "הזיהוי נכשל: {0}",
        ["Status_Scanning"] = "מחפש קודי QR וברקודים…",
        ["Status_NoBarcode"] = "לא נמצאו קוד QR או ברקוד בתמונה הזאת.",
        ["Status_BarcodeOne"] = "נמצא קוד {0} אחד.",
        ["Status_BarcodeMany"] = "נמצאו {0} קודים.",
        ["Status_ScanFailed"] = "החיפוש נכשל: {0}",
        ["Status_NothingToTranslate"] = "אין טקסט לתרגם.",
        ["Status_Translating"] = "מתרגם ל{0} במכשיר הזה…",
        ["Status_Translated"] = "תורגם ל{0}, במכשיר הזה, בלי גישה לרשת.",
        ["Status_TranslateFailed"] = "התרגום נכשל: {0}",
        ["Status_NothingToCopy"] = "אין טקסט להעתיק.",
        ["Status_TextCopied"] = "הטקסט הועתק ללוח.",
        ["Status_CopyFailed"] = "לא ניתן היה להעתיק את הטקסט: {0}",
        ["Status_NothingToSpeak"] = "אין טקסט להקריא.",
        ["Status_SpeakFailed"] = "לא ניתן היה להקריא את הטקסט: {0}",
        ["Status_HistoryLoaded"] = "מציג את התוצאה מ‑{0}.",
        ["Status_NeedImage"] = "טענו תחילה תמונה.",
        ["Status_CaptureFailed"] = "צילום המסך נכשל: {0}",
        ["Status_LanguagePackMissing"] = "ב‑Windows לא מותקנת שום ערכת שפה ל‑OCR, ולכן אין במה לזהות. הוסיפו את השפה הדרושה תחת שעה ושפה, ואז שפה ואזור.",
        ["Btn_OpenLanguageSettings"] = "פתיחת הגדרות השפה",

        ["Source_Clipboard"] = "התמונה מהלוח",
        ["Source_Dropped"] = "התמונה שנגררה",
        ["Source_FullScreen"] = "מסך מלא",
        ["Source_Region"] = "אזור במסך",
        ["Source_Codes"] = "{0} (קודים)",

        ["FileType_Image"] = "תמונת {0}",

        ["Region_Hint"] = "גררו כדי לבחור אזור　·　‏Esc או לחיצה ימנית לביטול",

        ["Err_NoLanguagePack"] = "ב‑Windows לא מותקנת ערכת שפה ל‑OCR עבור השפה הזאת. הוסיפו אחת תחת שעה ושפה, ואז שפה ואזור.",
        ["Err_TextTooLong"] = "הטקסט ארוך מדי עבור המודל שרץ במכשיר. תרגמו קטע קצר יותר.",
        ["Err_ModelDeclined"] = "המודל שרץ במכשיר סירב לתרגם את הטקסט הזה.",
        ["Err_TranslationFailed"] = "התרגום במכשיר לא החזיר תוצאה.",
    };
}
