using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> De = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · kein Sprachpaket",
        ["Engine_OneLanguage"] = "Windows OCR · 1 Sprache",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} Sprachen",
        ["Engine_OnDevice"] = "{0} · lokal auf dem Gerät",

        ["Preview_Placeholder"] = "Bild hier ablegen oder unten Datei, Aufnahme bzw. Zwischenablage verwenden",
        ["Btn_CopyImage"] = "Kopieren",
        ["Tip_CopyImage"] = "Bild in die Zwischenablage kopieren",
        ["Btn_SaveImage"] = "Speichern",
        ["Tip_SaveImage"] = "Bild speichern unter…",
        ["Btn_FitToWindow"] = "Einpassen",
        ["Tip_FitToWindow"] = "Auf Fenstergröße zoomen",
        ["Tip_ActualSize"] = "Tatsächliche Pixelgröße",

        ["Voice_Placeholder"] = "Stimme",
        ["Tip_Voice"] = "Stimme zum Vorlesen",
        ["Tip_Speak"] = "Text vorlesen",
        ["Tip_StopSpeak"] = "Vorlesen beenden",
        ["Tip_CopyText"] = "Text kopieren (Strg+Umschalt+C)",
        ["Btn_RemoveLineBreaks"] = "Umbrüche weg",
        ["Tip_RemoveLineBreaks"] = "Harte Zeilenumbrüche wieder zu Absätzen zusammenführen",
        ["Btn_RemoveSpaces"] = "Leerzeichen weg",
        ["Tip_RemoveSpaces"] = "Alle Leerzeichen entfernen — für Chinesisch, Japanisch und Koreanisch",
        ["Result_Placeholder"] = "Der erkannte Text erscheint hier und kann bearbeitet werden.",

        ["Btn_OpenFile"] = "Datei",
        ["Tip_OpenFile"] = "Bilddatei öffnen (Strg+O)",
        ["Btn_Capture"] = "Aufnahme",
        ["Tip_Capture"] = "Bildschirmbereich auswählen und erkennen ({0}). Strg+Umschalt+R für den ganzen Bildschirm.",
        ["Hotkey_Unavailable"] = "kein Tastenkürzel — beide sind von einer anderen App belegt",
        ["Btn_Paste"] = "Zwischenablage",
        ["Tip_Paste"] = "Bild oder Text aus der Zwischenablage laden (Strg+V)",
        ["Btn_History"] = "Verlauf",
        ["Tip_History"] = "Zuletzt erkannte Ergebnisse",
        ["History_Empty"] = "Es wurde noch nichts erkannt.",
        ["History_EmptyPreview"] = "(leer)",
        ["Tip_Settings"] = "Optionen",
        ["Settings_Header"] = "Optionen",
        ["Setting_UiLanguage"] = "App-Sprache",
        ["Lang_SystemDefault"] = "Systemsprache",
        ["Setting_RepairNumbers"] = "l und I in Zahlen korrigieren",
        ["Setting_RepairNumbers_Desc"] = "Erkennungsmodule lesen v1.6.5 regelmäßig als vl.6.5. Ist die Option aktiv, wird ein l oder I nur dort zu einer 1, wo ein Trennzeichen und eine Ziffer daneben stehen — html5 und IPv6 bleiben also unangetastet. Ist sie aus, bleibt die Lesart des Moduls exakt erhalten.",
        ["Common_On"] = "Ein",
        ["Common_Off"] = "Aus",
        ["Lang_Placeholder"] = "Sprache",
        ["Tip_OcrLanguage"] = "Erkennungssprache, aus den in Windows installierten Sprachpaketen",
        ["Btn_Translate"] = "Übersetzen",
        ["Tip_Translate"] = "Auf diesem Gerät übersetzen — es wird nichts über das Netzwerk gesendet",
        ["Btn_Barcode"] = "Codes",
        ["Tip_Barcode"] = "QR-Codes und Barcodes im Bild lesen",
        ["Btn_Recognize"] = "Erkennen",
        ["Tip_Recognize"] = "Text im Bild erkennen (F5)",

        ["Option_AutoAi"] = "Automatisch (Windows AI)",
        ["Option_AutoMulti"] = "Automatisch (mehrsprachig · langsamer)",

        ["Status_Loaded"] = "{0} geladen.",
        ["Status_OpenFailed"] = "Das Bild konnte nicht geöffnet werden: {0}",
        ["Status_ClipboardText"] = "Text aus der Zwischenablage geladen.",
        ["Status_ClipboardEmpty"] = "In der Zwischenablage liegt weder ein Bild noch Text.",
        ["Status_ClipboardFailed"] = "Die Zwischenablage konnte nicht gelesen werden: {0}",
        ["Status_DropFailed"] = "Das abgelegte Element konnte nicht verwendet werden: {0}",
        ["Status_ImageCopied"] = "Bild in die Zwischenablage kopiert.",
        ["Status_ImageCopyFailed"] = "Das Bild konnte nicht kopiert werden: {0}",
        ["Status_ImageSaved"] = "Bild als {0} gespeichert.",
        ["Status_ImageSaveFailed"] = "Das Bild konnte nicht gespeichert werden: {0}",
        ["Status_Recognizing"] = "Wird erkannt…",
        ["Status_NoText"] = "{0} hat in diesem Bild keinen Text gefunden.",
        ["Status_Done"] = "Fertig ({0}).",
        ["Status_DoneConfidence"] = "Fertig ({0}) · durchschnittliche Konfidenz {1} %.",
        ["Status_RecognizeFailed"] = "Die Erkennung ist fehlgeschlagen: {0}",
        ["Status_Scanning"] = "Es wird nach QR-Codes und Barcodes gesucht…",
        ["Status_NoBarcode"] = "In diesem Bild ist kein QR-Code und kein Barcode zu finden.",
        ["Status_BarcodeOne"] = "Ein {0}-Code gefunden.",
        ["Status_BarcodeMany"] = "{0} Codes gefunden.",
        ["Status_ScanFailed"] = "Die Suche ist fehlgeschlagen: {0}",
        ["Status_NothingToTranslate"] = "Es gibt keinen Text zum Übersetzen.",
        ["Status_Translating"] = "Wird auf diesem Gerät ins {0} übersetzt…",
        ["Status_Translated"] = "Ins {0} übersetzt — auf diesem Gerät, ohne Netzwerkzugriff.",
        ["Status_TranslateFailed"] = "Die Übersetzung ist fehlgeschlagen: {0}",
        ["Status_NothingToCopy"] = "Es gibt keinen Text zum Kopieren.",
        ["Status_TextCopied"] = "Text in die Zwischenablage kopiert.",
        ["Status_CopyFailed"] = "Der Text konnte nicht kopiert werden: {0}",
        ["Status_NothingToSpeak"] = "Es gibt keinen Text zum Vorlesen.",
        ["Status_SpeakFailed"] = "Der Text konnte nicht vorgelesen werden: {0}",
        ["Status_HistoryLoaded"] = "Es wird das Ergebnis von {0} angezeigt.",
        ["Status_NeedImage"] = "Laden Sie zuerst ein Bild.",
        ["Status_CaptureFailed"] = "Die Bildschirmaufnahme ist fehlgeschlagen: {0}",
        ["Status_LanguagePackMissing"] = "In Windows ist kein OCR-Sprachpaket installiert, es gibt also nichts, womit erkannt werden könnte. Fügen Sie die gewünschte Sprache unter Zeit und Sprache, dann Sprache und Region hinzu.",
        ["Btn_OpenLanguageSettings"] = "Spracheinstellungen öffnen",

        ["Source_Clipboard"] = "das Bild aus der Zwischenablage",
        ["Source_Dropped"] = "das abgelegte Bild",
        ["Source_FullScreen"] = "Ganzer Bildschirm",
        ["Source_Region"] = "Bildschirmbereich",
        ["Source_Codes"] = "{0} (Codes)",

        ["FileType_Image"] = "{0}-Bild",

        ["Region_Hint"] = "Zum Auswählen eines Bereichs ziehen　·　Esc oder Rechtsklick bricht ab",

        ["Err_NoLanguagePack"] = "Für diese Sprache ist in Windows kein OCR-Sprachpaket installiert. Fügen Sie eines unter Zeit und Sprache, dann Sprache und Region hinzu.",
        ["Err_TextTooLong"] = "Der Text ist zu lang für das lokale Modell. Übersetzen Sie einen kleineren Ausschnitt.",
        ["Err_ModelDeclined"] = "Das lokale Modell hat die Übersetzung dieses Textes abgelehnt.",
        ["Err_TranslationFailed"] = "Die lokale Übersetzung hat kein Ergebnis geliefert.",
    };
}
