using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Fil = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · walang language pack",
        ["Engine_OneLanguage"] = "Windows OCR · 1 wika",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} wika",
        ["Engine_OnDevice"] = "{0} · sa device",

        ["Preview_Placeholder"] = "Ihulog dito ang isang larawan, o gamitin ang File, Kuha, o Clipboard sa ibaba",
        ["Btn_CopyImage"] = "Kopyahin",
        ["Tip_CopyImage"] = "Kopyahin ang larawan sa clipboard",
        ["Btn_SaveImage"] = "I-save",
        ["Tip_SaveImage"] = "I-save ang larawan bilang…",
        ["Btn_FitToWindow"] = "Ikasya",
        ["Tip_FitToWindow"] = "I-zoom para kumasya sa window",
        ["Tip_ActualSize"] = "Aktuwal na laki sa pixel",

        ["Voice_Placeholder"] = "Boses",
        ["Tip_Voice"] = "Boses na ginagamit sa pagbabasa nang malakas",
        ["Tip_Speak"] = "Basahin nang malakas ang teksto",
        ["Tip_StopSpeak"] = "Itigil ang pagbabasa",
        ["Tip_CopyText"] = "Kopyahin ang teksto (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Pagdugtungin",
        ["Tip_RemoveLineBreaks"] = "Pagdugtungin muli ang mga hating linya bilang talata",
        ["Btn_RemoveSpaces"] = "Walang espasyo",
        ["Tip_RemoveSpaces"] = "Alisin ang lahat ng espasyo — para sa Tsino, Hapon at Koreano",
        ["Result_Placeholder"] = "Lilitaw dito ang nakilalang teksto at maaari itong i-edit.",

        ["Btn_OpenFile"] = "File",
        ["Tip_OpenFile"] = "Magbukas ng file ng larawan (Ctrl+O)",
        ["Btn_Capture"] = "Kuha",
        ["Tip_Capture"] = "Pumili ng bahagi ng screen at kilalanin ito ({0}). Pindutin ang Ctrl+Shift+R para sa buong screen.",
        ["Hotkey_Unavailable"] = "walang shortcut — kapwa nakuha na ng ibang app",
        ["Btn_Paste"] = "Clipboard",
        ["Tip_Paste"] = "Kunin ang larawan o teksto mula sa clipboard (Ctrl+V)",
        ["Btn_History"] = "Kasaysayan",
        ["Tip_History"] = "Mga kamakailang resulta",
        ["History_Empty"] = "Wala pang nakikilala.",
        ["History_EmptyPreview"] = "(walang laman)",
        ["Tip_Settings"] = "Mga opsyon",
        ["Settings_Header"] = "Mga opsyon",
        ["Setting_UiLanguage"] = "Wika ng app",
        ["Lang_SystemDefault"] = "Default ng system",
        ["Setting_RepairNumbers"] = "Ayusin ang l at I sa loob ng mga numero",
        ["Setting_RepairNumbers_Desc"] = "Madalas basahin ng mga recognizer ang v1.6.5 bilang vl.6.5. Kapag naka-on ito, nagiging 1 lamang ang l o I kung may katabing pananda at digit, kaya hindi nagagalaw ang html5 at IPv6. Kapag naka-off, mananatili ang pagbasa ng makina nang eksakto kung paano ito dumating.",
        ["Common_On"] = "On",
        ["Common_Off"] = "Off",
        ["Lang_Placeholder"] = "Wika",
        ["Tip_OcrLanguage"] = "Wika ng pagkilala, mula sa mga language pack na naka-install sa Windows",
        ["Btn_Translate"] = "Isalin",
        ["Tip_Translate"] = "Isalin sa device na ito — walang ipinapadala sa network",
        ["Btn_Barcode"] = "Mga code",
        ["Tip_Barcode"] = "Basahin ang mga QR code at barcode sa larawan",
        ["Btn_Recognize"] = "Kilalanin",
        ["Tip_Recognize"] = "Kilalanin ang teksto sa larawan (F5)",

        ["Option_AutoAi"] = "Awtomatiko (Windows AI)",
        ["Option_AutoMulti"] = "Awtomatiko (maraming wika · mas mabagal)",

        ["Status_Loaded"] = "Na-load ang {0}.",
        ["Status_OpenFailed"] = "Hindi mabuksan ang larawan: {0}",
        ["Status_ClipboardText"] = "Na-load ang teksto mula sa clipboard.",
        ["Status_ClipboardEmpty"] = "Walang larawan ni teksto ang clipboard.",
        ["Status_ClipboardFailed"] = "Hindi mabasa ang clipboard: {0}",
        ["Status_DropFailed"] = "Hindi magamit ang inihulog: {0}",
        ["Status_ImageCopied"] = "Nakopya ang larawan sa clipboard.",
        ["Status_ImageCopyFailed"] = "Hindi makopya ang larawan: {0}",
        ["Status_ImageSaved"] = "Na-save ang larawan bilang {0}.",
        ["Status_ImageSaveFailed"] = "Hindi ma-save ang larawan: {0}",
        ["Status_Recognizing"] = "Kinikilala…",
        ["Status_NoText"] = "Walang natagpuang teksto ang {0} sa larawang ito.",
        ["Status_Done"] = "Tapos na ({0}).",
        ["Status_DoneConfidence"] = "Tapos na ({0}) · katiyakan sa karaniwan {1}%.",
        ["Status_RecognizeFailed"] = "Nabigo ang pagkilala: {0}",
        ["Status_Scanning"] = "Naghahanap ng mga QR code at barcode…",
        ["Status_NoBarcode"] = "Walang natagpuang QR code o barcode sa larawang ito.",
        ["Status_BarcodeOne"] = "May natagpuang isang {0} code.",
        ["Status_BarcodeMany"] = "May natagpuang {0} code.",
        ["Status_ScanFailed"] = "Nabigo ang paghahanap: {0}",
        ["Status_NothingToTranslate"] = "Walang tekstong maisasalin.",
        ["Status_Translating"] = "Isinasalin sa {0} sa device na ito…",
        ["Status_Translated"] = "Naisalin sa {0}, sa device na ito, nang walang koneksyon sa network.",
        ["Status_TranslateFailed"] = "Nabigo ang pagsasalin: {0}",
        ["Status_NothingToCopy"] = "Walang tekstong makokopya.",
        ["Status_TextCopied"] = "Nakopya ang teksto sa clipboard.",
        ["Status_CopyFailed"] = "Hindi makopya ang teksto: {0}",
        ["Status_NothingToSpeak"] = "Walang tekstong mababasa nang malakas.",
        ["Status_SpeakFailed"] = "Hindi mabasa nang malakas ang teksto: {0}",
        ["Status_HistoryLoaded"] = "Ipinapakita ang resulta mula {0}.",
        ["Status_NeedImage"] = "Mag-load muna ng larawan.",
        ["Status_CaptureFailed"] = "Nabigo ang pagkuha ng screen: {0}",
        ["Status_LanguagePackMissing"] = "Walang naka-install na OCR language pack sa Windows, kaya walang magagamit sa pagkilala. Idagdag ang wikang kailangan mo sa Oras at wika, saka Wika at rehiyon.",
        ["Btn_OpenLanguageSettings"] = "Buksan ang mga setting ng wika",

        ["Source_Clipboard"] = "larawan mula sa clipboard",
        ["Source_Dropped"] = "inihulog na larawan",
        ["Source_FullScreen"] = "Buong screen",
        ["Source_Region"] = "Bahagi ng screen",
        ["Source_Codes"] = "{0} (mga code)",

        ["FileType_Image"] = "Larawang {0}",

        ["Region_Hint"] = "Mag-drag para pumili ng bahagi　·　Esc o kanang pag-click para kanselahin",

        ["Err_NoLanguagePack"] = "Walang naka-install na OCR language pack ang Windows para sa wikang ito. Magdagdag ng isa sa Oras at wika, saka Wika at rehiyon.",
        ["Err_TextTooLong"] = "Masyadong mahaba ang teksto para sa modelong nasa device. Magsalin ng mas maikling bahagi.",
        ["Err_ModelDeclined"] = "Tumanggi ang modelong nasa device na isalin ang tekstong ito.",
        ["Err_TranslationFailed"] = "Walang naibigay na resulta ang pagsasalin sa device.",
    };
}
