using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Sv = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · inget språkpaket",
        ["Engine_OneLanguage"] = "Windows OCR · 1 språk",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} språk",
        ["Engine_OnDevice"] = "{0} · på enheten",

        ["Preview_Placeholder"] = "Släpp en bild här, eller använd Fil, Skärmklipp eller Urklipp nedan",
        ["Btn_CopyImage"] = "Kopiera",
        ["Tip_CopyImage"] = "Kopiera bilden till Urklipp",
        ["Btn_SaveImage"] = "Spara",
        ["Tip_SaveImage"] = "Spara bilden som…",
        ["Btn_FitToWindow"] = "Anpassa",
        ["Tip_FitToWindow"] = "Zooma så att bilden fyller fönstret",
        ["Tip_ActualSize"] = "Verklig pixelstorlek",

        ["Voice_Placeholder"] = "Röst",
        ["Tip_Voice"] = "Röst som används vid uppläsning",
        ["Tip_Speak"] = "Läs upp texten",
        ["Tip_StopSpeak"] = "Sluta läsa upp",
        ["Tip_CopyText"] = "Kopiera texten (Ctrl+Skift+C)",
        ["Btn_RemoveLineBreaks"] = "Slå ihop",
        ["Tip_RemoveLineBreaks"] = "Slå ihop hårda radbrytningar till stycken igen",
        ["Btn_RemoveSpaces"] = "Inga blanksteg",
        ["Tip_RemoveSpaces"] = "Ta bort alla blanksteg — för kinesiska, japanska och koreanska",
        ["Result_Placeholder"] = "Den igenkända texten visas här och går att redigera.",

        ["Btn_OpenFile"] = "Fil",
        ["Tip_OpenFile"] = "Öppna en bildfil (Ctrl+O)",
        ["Btn_Capture"] = "Skärmklipp",
        ["Tip_Capture"] = "Markera ett skärmområde och tolka det ({0}). Tryck Ctrl+Skift+R för hela skärmen.",
        ["Hotkey_Unavailable"] = "inget kortkommando — en annan app har tagit båda",
        ["Btn_Paste"] = "Urklipp",
        ["Tip_Paste"] = "Hämta en bild eller text från Urklipp (Ctrl+V)",
        ["Btn_History"] = "Historik",
        ["Tip_History"] = "Senaste resultaten",
        ["History_Empty"] = "Inget har tolkats än.",
        ["History_EmptyPreview"] = "(tomt)",
        ["Tip_Settings"] = "Alternativ",
        ["Settings_Header"] = "Alternativ",
        ["Setting_UiLanguage"] = "Appens språk",
        ["Lang_SystemDefault"] = "Systemets standard",
        ["Setting_RepairNumbers"] = "Rätta l och I inuti tal",
        ["Setting_RepairNumbers_Desc"] = "Tolkningsmotorer läser regelbundet v1.6.5 som vl.6.5. När det här är på blir ett l eller I en 1:a bara där det står en avgränsare och en siffra intill, så html5 och IPv6 lämnas i fred. När det är av behålls motorns läsning precis som den kom.",
        ["Common_On"] = "På",
        ["Common_Off"] = "Av",
        ["Lang_Placeholder"] = "Språk",
        ["Tip_OcrLanguage"] = "Tolkningsspråk, bland de språkpaket Windows har installerat",
        ["Btn_Translate"] = "Översätt",
        ["Tip_Translate"] = "Översätt på den här enheten — inget skickas över nätverket",
        ["Btn_Barcode"] = "Koder",
        ["Tip_Barcode"] = "Läs QR-koder och streckkoder i bilden",
        ["Btn_Recognize"] = "Tolka",
        ["Tip_Recognize"] = "Tolka texten i bilden (F5)",

        ["Option_AutoAi"] = "Automatiskt (Windows AI)",
        ["Option_AutoMulti"] = "Automatiskt (flera språk · långsammare)",

        ["Status_Loaded"] = "{0} inläst.",
        ["Status_OpenFailed"] = "Det gick inte att öppna bilden: {0}",
        ["Status_ClipboardText"] = "Text hämtad från Urklipp.",
        ["Status_ClipboardEmpty"] = "Urklipp innehåller varken bild eller text.",
        ["Status_ClipboardFailed"] = "Det gick inte att läsa Urklipp: {0}",
        ["Status_DropFailed"] = "Det gick inte att använda det som släpptes: {0}",
        ["Status_ImageCopied"] = "Bilden kopierad till Urklipp.",
        ["Status_ImageCopyFailed"] = "Det gick inte att kopiera bilden: {0}",
        ["Status_ImageSaved"] = "Bilden sparad som {0}.",
        ["Status_ImageSaveFailed"] = "Det gick inte att spara bilden: {0}",
        ["Status_Recognizing"] = "Tolkar…",
        ["Status_NoText"] = "{0} hittade ingen text i den här bilden.",
        ["Status_Done"] = "Klart ({0}).",
        ["Status_DoneConfidence"] = "Klart ({0}) · genomsnittlig säkerhet {1} %.",
        ["Status_RecognizeFailed"] = "Tolkningen misslyckades: {0}",
        ["Status_Scanning"] = "Söker efter QR-koder och streckkoder…",
        ["Status_NoBarcode"] = "Ingen QR-kod eller streckkod hittades i den här bilden.",
        ["Status_BarcodeOne"] = "Hittade en {0}-kod.",
        ["Status_BarcodeMany"] = "Hittade {0} koder.",
        ["Status_ScanFailed"] = "Sökningen misslyckades: {0}",
        ["Status_NothingToTranslate"] = "Det finns ingen text att översätta.",
        ["Status_Translating"] = "Översätter till {0} på den här enheten…",
        ["Status_Translated"] = "Översatt till {0}, på den här enheten, utan nätverksåtkomst.",
        ["Status_TranslateFailed"] = "Översättningen misslyckades: {0}",
        ["Status_NothingToCopy"] = "Det finns ingen text att kopiera.",
        ["Status_TextCopied"] = "Texten kopierad till Urklipp.",
        ["Status_CopyFailed"] = "Det gick inte att kopiera texten: {0}",
        ["Status_NothingToSpeak"] = "Det finns ingen text att läsa upp.",
        ["Status_SpeakFailed"] = "Det gick inte att läsa upp texten: {0}",
        ["Status_HistoryLoaded"] = "Visar resultatet från {0}.",
        ["Status_NeedImage"] = "Läs in en bild först.",
        ["Status_CaptureFailed"] = "Skärmbilden misslyckades: {0}",
        ["Status_LanguagePackMissing"] = "Windows har inget OCR-språkpaket installerat, så det finns inget att tolka med. Lägg till språket du behöver under Tid och språk, sedan Språk och region.",
        ["Btn_OpenLanguageSettings"] = "Öppna språkinställningarna",

        ["Source_Clipboard"] = "bilden från Urklipp",
        ["Source_Dropped"] = "den släppta bilden",
        ["Source_FullScreen"] = "Hela skärmen",
        ["Source_Region"] = "Skärmområde",
        ["Source_Codes"] = "{0} (koder)",

        ["FileType_Image"] = "{0}-bild",

        ["Region_Hint"] = "Dra för att markera ett område　·　Esc eller högerklick avbryter",

        ["Err_NoLanguagePack"] = "Windows har inget OCR-språkpaket installerat för det här språket. Lägg till ett under Tid och språk, sedan Språk och region.",
        ["Err_TextTooLong"] = "Texten är för lång för modellen på enheten. Översätt en mindre del.",
        ["Err_ModelDeclined"] = "Modellen på enheten avböjde att översätta den här texten.",
        ["Err_TranslationFailed"] = "Översättningen på enheten gav inget resultat.",
    };
}
