using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Uk = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · немає мовного пакета",
        ["Engine_OneLanguage"] = "Windows OCR · 1 мова",
        ["Engine_ManyLanguages"] = "Windows OCR · мов: {0}",
        ["Engine_OnDevice"] = "{0} · на пристрої",

        ["Preview_Placeholder"] = "Перетягніть зображення сюди або скористайтеся кнопками Файл, Знімок чи Буфер обміну внизу",
        ["Btn_CopyImage"] = "Копіювати",
        ["Tip_CopyImage"] = "Копіювати зображення до буфера обміну",
        ["Btn_SaveImage"] = "Зберегти",
        ["Tip_SaveImage"] = "Зберегти зображення як…",
        ["Btn_FitToWindow"] = "Вписати",
        ["Tip_FitToWindow"] = "Масштабувати за розміром вікна",
        ["Tip_ActualSize"] = "Справжній розмір у пікселях",

        ["Voice_Placeholder"] = "Голос",
        ["Tip_Voice"] = "Голос для читання вголос",
        ["Tip_Speak"] = "Прочитати текст уголос",
        ["Tip_StopSpeak"] = "Зупинити читання",
        ["Tip_CopyText"] = "Копіювати текст (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Без розривів",
        ["Tip_RemoveLineBreaks"] = "Об’єднати жорсткі розриви рядків назад в абзаци",
        ["Btn_RemoveSpaces"] = "Без пробілів",
        ["Tip_RemoveSpaces"] = "Прибрати всі пробіли — для китайської, японської та корейської",
        ["Result_Placeholder"] = "Розпізнаний текст з’явиться тут, його можна редагувати.",

        ["Btn_OpenFile"] = "Файл",
        ["Tip_OpenFile"] = "Відкрити файл зображення (Ctrl+O)",
        ["Btn_Capture"] = "Знімок",
        ["Tip_Capture"] = "Виділити ділянку екрана й розпізнати її ({0}). Натисніть Ctrl+Shift+R для всього екрана.",
        ["Hotkey_Unavailable"] = "немає сполучення клавіш — обидва зайняла інша програма",
        ["Btn_Paste"] = "Буфер обміну",
        ["Tip_Paste"] = "Завантажити зображення або текст із буфера обміну (Ctrl+V)",
        ["Btn_History"] = "Журнал",
        ["Tip_History"] = "Останні результати",
        ["History_Empty"] = "Ще нічого не розпізнано.",
        ["History_EmptyPreview"] = "(порожньо)",
        ["Tip_Settings"] = "Параметри",
        ["Settings_Header"] = "Параметри",
        ["Setting_UiLanguage"] = "Мова програми",
        ["Lang_SystemDefault"] = "Як у системі",
        ["Setting_RepairNumbers"] = "Виправляти l та I всередині чисел",
        ["Setting_RepairNumbers_Desc"] = "Механізми розпізнавання регулярно читають v1.6.5 як vl.6.5. Коли параметр увімкнено, l або I стає одиницею лише там, де поряд стоять роздільник і цифра, тож html5 та IPv6 лишаються недоторканими. Коли вимкнено, прочитане механізмом зберігається точно таким, яким надійшло.",
        ["Common_On"] = "Увімк.",
        ["Common_Off"] = "Вимк.",
        ["Lang_Placeholder"] = "Мова",
        ["Tip_OcrLanguage"] = "Мова розпізнавання — з-поміж мовних пакетів, установлених у Windows",
        ["Btn_Translate"] = "Перекласти",
        ["Tip_Translate"] = "Переклад на цьому пристрої — нічого не надсилається мережею",
        ["Btn_Barcode"] = "Коди",
        ["Tip_Barcode"] = "Зчитати QR-коди та штрихкоди на зображенні",
        ["Btn_Recognize"] = "Розпізнати",
        ["Tip_Recognize"] = "Розпізнати текст на зображенні (F5)",

        ["Option_AutoAi"] = "Автоматично (Windows AI)",
        ["Option_AutoMulti"] = "Автоматично (кілька мов · повільніше)",

        ["Status_Loaded"] = "Завантажено: {0}.",
        ["Status_OpenFailed"] = "Не вдалося відкрити зображення: {0}",
        ["Status_ClipboardText"] = "Текст завантажено з буфера обміну.",
        ["Status_ClipboardEmpty"] = "У буфері обміну немає ні зображення, ні тексту.",
        ["Status_ClipboardFailed"] = "Не вдалося прочитати буфер обміну: {0}",
        ["Status_DropFailed"] = "Не вдалося скористатися перетягнутим елементом: {0}",
        ["Status_ImageCopied"] = "Зображення скопійовано до буфера обміну.",
        ["Status_ImageCopyFailed"] = "Не вдалося скопіювати зображення: {0}",
        ["Status_ImageSaved"] = "Зображення збережено як {0}.",
        ["Status_ImageSaveFailed"] = "Не вдалося зберегти зображення: {0}",
        ["Status_Recognizing"] = "Розпізнавання…",
        ["Status_NoText"] = "{0} не знайшов тексту на цьому зображенні.",
        ["Status_Done"] = "Готово ({0}).",
        ["Status_DoneConfidence"] = "Готово ({0}) · середня впевненість {1}%.",
        ["Status_RecognizeFailed"] = "Розпізнавання не вдалося: {0}",
        ["Status_Scanning"] = "Пошук QR-кодів і штрихкодів…",
        ["Status_NoBarcode"] = "На цьому зображенні немає ні QR-коду, ні штрихкоду.",
        ["Status_BarcodeOne"] = "Знайдено один код {0}.",
        ["Status_BarcodeMany"] = "Знайдено кодів: {0}.",
        ["Status_ScanFailed"] = "Сканування не вдалося: {0}",
        ["Status_NothingToTranslate"] = "Немає тексту для перекладу.",
        ["Status_Translating"] = "Переклад на {0} на цьому пристрої…",
        ["Status_Translated"] = "Перекладено на {0} — на цьому пристрої, без доступу до мережі.",
        ["Status_TranslateFailed"] = "Переклад не вдався: {0}",
        ["Status_NothingToCopy"] = "Немає тексту для копіювання.",
        ["Status_TextCopied"] = "Текст скопійовано до буфера обміну.",
        ["Status_CopyFailed"] = "Не вдалося скопіювати текст: {0}",
        ["Status_NothingToSpeak"] = "Немає тексту для читання вголос.",
        ["Status_SpeakFailed"] = "Не вдалося прочитати текст уголос: {0}",
        ["Status_HistoryLoaded"] = "Показано результат від {0}.",
        ["Status_NeedImage"] = "Спочатку завантажте зображення.",
        ["Status_CaptureFailed"] = "Знімок екрана не вдався: {0}",
        ["Status_LanguagePackMissing"] = "У Windows не встановлено жодного мовного пакета OCR, тож розпізнавати нічим. Додайте потрібну мову в розділі Час і мова, далі Мова та регіон.",
        ["Btn_OpenLanguageSettings"] = "Відкрити параметри мови",

        ["Source_Clipboard"] = "зображення з буфера обміну",
        ["Source_Dropped"] = "перетягнуте зображення",
        ["Source_FullScreen"] = "Весь екран",
        ["Source_Region"] = "Ділянка екрана",
        ["Source_Codes"] = "{0} (коди)",

        ["FileType_Image"] = "Зображення {0}",

        ["Region_Hint"] = "Перетягніть, щоб виділити ділянку　·　Esc або права кнопка — скасувати",

        ["Err_NoLanguagePack"] = "У Windows немає встановленого мовного пакета OCR для цієї мови. Додайте його в розділі Час і мова, далі Мова та регіон.",
        ["Err_TextTooLong"] = "Текст задовгий для моделі на пристрої. Перекладіть меншу частину.",
        ["Err_ModelDeclined"] = "Модель на пристрої відмовилася перекладати цей текст.",
        ["Err_TranslationFailed"] = "Переклад на пристрої не дав результату.",
    };
}
