using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Ja = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · 言語パックなし",
        ["Engine_OneLanguage"] = "Windows OCR · 1 言語",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} 言語",
        ["Engine_OnDevice"] = "{0} · デバイス上で実行",

        ["Preview_Placeholder"] = "ここに画像をドロップするか、下のファイル・キャプチャ・クリップボードを使います",
        ["Btn_CopyImage"] = "コピー",
        ["Tip_CopyImage"] = "画像をクリップボードにコピー",
        ["Btn_SaveImage"] = "保存",
        ["Tip_SaveImage"] = "画像に名前を付けて保存…",
        ["Btn_FitToWindow"] = "全体表示",
        ["Tip_FitToWindow"] = "ウィンドウに合わせて拡大縮小",
        ["Tip_ActualSize"] = "実際のピクセルサイズ",

        ["Voice_Placeholder"] = "音声",
        ["Tip_Voice"] = "読み上げに使う音声",
        ["Tip_Speak"] = "テキストを読み上げる",
        ["Tip_StopSpeak"] = "読み上げを停止",
        ["Tip_CopyText"] = "テキストをコピー（Ctrl+Shift+C）",
        ["Btn_RemoveLineBreaks"] = "改行削除",
        ["Tip_RemoveLineBreaks"] = "強制改行を段落に戻す",
        ["Btn_RemoveSpaces"] = "空白削除",
        ["Tip_RemoveSpaces"] = "すべての空白を削除します。中国語・日本語・韓国語向け",
        ["Result_Placeholder"] = "認識されたテキストがここに表示され、編集できます。",

        ["Btn_OpenFile"] = "ファイル",
        ["Tip_OpenFile"] = "画像ファイルを開く（Ctrl+O）",
        ["Btn_Capture"] = "キャプチャ",
        ["Tip_Capture"] = "画面の範囲を選んで認識します（{0}）。Ctrl+Shift+R で画面全体。",
        ["Hotkey_Unavailable"] = "ショートカットなし。どちらも他のアプリが使用中です",
        ["Btn_Paste"] = "クリップボード",
        ["Tip_Paste"] = "クリップボードから画像またはテキストを読み込む（Ctrl+V）",
        ["Btn_History"] = "履歴",
        ["Tip_History"] = "最近の認識結果",
        ["History_Empty"] = "まだ認識結果がありません。",
        ["History_EmptyPreview"] = "（空）",
        ["Tip_Settings"] = "オプション",
        ["Settings_Header"] = "オプション",
        ["Setting_UiLanguage"] = "アプリの言語",
        ["Lang_SystemDefault"] = "システムに従う",
        ["Setting_RepairNumbers"] = "数字の中の l と I を修正",
        ["Setting_RepairNumbers_Desc"] = "認識エンジンは v1.6.5 を vl.6.5 と読むことがよくあります。オンにすると、l や I の隣に区切り記号と数字の両方がある場合にだけ 1 に変換するため、html5 や IPv6 はそのまま残ります。オフにすると、エンジンが返した読みをそのまま使います。",
        ["Common_On"] = "オン",
        ["Common_Off"] = "オフ",
        ["Lang_Placeholder"] = "言語",
        ["Tip_OcrLanguage"] = "認識言語。Windows にインストール済みの言語パックから選べます",
        ["Btn_Translate"] = "翻訳",
        ["Tip_Translate"] = "このデバイス上で翻訳します。ネットワークには何も送信しません",
        ["Btn_Barcode"] = "コード",
        ["Tip_Barcode"] = "画像の QR コードとバーコードを読み取る",
        ["Btn_Recognize"] = "認識",
        ["Tip_Recognize"] = "画像内のテキストを認識（F5）",

        ["Option_AutoAi"] = "自動判別（Windows AI）",
        ["Option_AutoMulti"] = "自動判別（多言語 · 低速）",

        ["Status_Loaded"] = "{0}を読み込みました。",
        ["Status_OpenFailed"] = "画像を開けませんでした：{0}",
        ["Status_ClipboardText"] = "クリップボードからテキストを読み込みました。",
        ["Status_ClipboardEmpty"] = "クリップボードに画像もテキストもありません。",
        ["Status_ClipboardFailed"] = "クリップボードを読み取れませんでした：{0}",
        ["Status_DropFailed"] = "ドロップされた内容を使えませんでした：{0}",
        ["Status_ImageCopied"] = "画像をクリップボードにコピーしました。",
        ["Status_ImageCopyFailed"] = "画像をコピーできませんでした：{0}",
        ["Status_ImageSaved"] = "画像を {0} として保存しました。",
        ["Status_ImageSaveFailed"] = "画像を保存できませんでした：{0}",
        ["Status_Recognizing"] = "認識しています…",
        ["Status_NoText"] = "{0} はこの画像からテキストを見つけられませんでした。",
        ["Status_Done"] = "完了（{0}）。",
        ["Status_DoneConfidence"] = "完了（{0}）· 平均信頼度 {1}%。",
        ["Status_RecognizeFailed"] = "認識に失敗しました：{0}",
        ["Status_Scanning"] = "QR コードとバーコードを探しています…",
        ["Status_NoBarcode"] = "この画像に QR コードやバーコードは見つかりませんでした。",
        ["Status_BarcodeOne"] = "{0} コードを 1 件見つけました。",
        ["Status_BarcodeMany"] = "コードを {0} 件見つけました。",
        ["Status_ScanFailed"] = "スキャンに失敗しました：{0}",
        ["Status_NothingToTranslate"] = "翻訳するテキストがありません。",
        ["Status_Translating"] = "このデバイス上で{0}に翻訳しています…",
        ["Status_Translated"] = "{0}に翻訳しました。すべてこのデバイス上で行われ、ネットワークは使いません。",
        ["Status_TranslateFailed"] = "翻訳に失敗しました：{0}",
        ["Status_NothingToCopy"] = "コピーするテキストがありません。",
        ["Status_TextCopied"] = "テキストをクリップボードにコピーしました。",
        ["Status_CopyFailed"] = "テキストをコピーできませんでした：{0}",
        ["Status_NothingToSpeak"] = "読み上げるテキストがありません。",
        ["Status_SpeakFailed"] = "読み上げられませんでした：{0}",
        ["Status_HistoryLoaded"] = "{0} の結果を表示しています。",
        ["Status_NeedImage"] = "先に画像を読み込んでください。",
        ["Status_CaptureFailed"] = "画面のキャプチャに失敗しました：{0}",
        ["Status_LanguagePackMissing"] = "Windows に OCR の言語パックが 1 つもインストールされていないため、認識できません。［時刻と言語］→［言語と地域］で必要な言語を追加してください。",
        ["Btn_OpenLanguageSettings"] = "言語設定を開く",

        ["Source_Clipboard"] = "クリップボードの画像",
        ["Source_Dropped"] = "ドロップされた画像",
        ["Source_FullScreen"] = "画面全体",
        ["Source_Region"] = "画面の範囲",
        ["Source_Codes"] = "{0}（コード）",

        ["FileType_Image"] = "{0} 画像",

        ["Region_Hint"] = "ドラッグして範囲を選択　·　Esc または右クリックで取り消し",

        ["Err_NoLanguagePack"] = "この言語の OCR 言語パックが Windows にインストールされていません。［時刻と言語］→［言語と地域］で追加してください。",
        ["Err_TextTooLong"] = "テキストがデバイス上のモデルには長すぎます。分けて翻訳してください。",
        ["Err_ModelDeclined"] = "デバイス上のモデルがこのテキストの翻訳を拒否しました。",
        ["Err_TranslationFailed"] = "デバイス上の翻訳から結果が返りませんでした。",
    };
}
