using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Fr = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · aucun module linguistique",
        ["Engine_OneLanguage"] = "Windows OCR · 1 langue",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} langues",
        ["Engine_OnDevice"] = "{0} · sur l'appareil",

        ["Preview_Placeholder"] = "Déposez une image ici, ou utilisez Fichier, Capture ou Presse-papiers ci-dessous",
        ["Btn_CopyImage"] = "Copier",
        ["Tip_CopyImage"] = "Copier l'image dans le presse-papiers",
        ["Btn_SaveImage"] = "Enregistrer",
        ["Tip_SaveImage"] = "Enregistrer l'image sous…",
        ["Btn_FitToWindow"] = "Ajuster",
        ["Tip_FitToWindow"] = "Ajuster le zoom à la fenêtre",
        ["Tip_ActualSize"] = "Taille réelle en pixels",

        ["Voice_Placeholder"] = "Voix",
        ["Tip_Voice"] = "Voix utilisée pour la lecture",
        ["Tip_Speak"] = "Lire le texte à voix haute",
        ["Tip_StopSpeak"] = "Arrêter la lecture",
        ["Tip_CopyText"] = "Copier le texte (Ctrl+Maj+C)",
        ["Btn_RemoveLineBreaks"] = "Sans retours",
        ["Tip_RemoveLineBreaks"] = "Fusionner les retours à la ligne en paragraphes",
        ["Btn_RemoveSpaces"] = "Sans espaces",
        ["Tip_RemoveSpaces"] = "Supprimer toutes les espaces, pour le chinois, le japonais et le coréen",
        ["Result_Placeholder"] = "Le texte reconnu apparaît ici et peut être modifié.",

        ["Btn_OpenFile"] = "Fichier",
        ["Tip_OpenFile"] = "Ouvrir un fichier image (Ctrl+O)",
        ["Btn_Capture"] = "Capture",
        ["Tip_Capture"] = "Sélectionner une zone de l'écran et la reconnaître ({0}). Ctrl+Maj+R pour tout l'écran.",
        ["Hotkey_Unavailable"] = "aucun raccourci — les deux sont pris par une autre application",
        ["Btn_Paste"] = "Presse-papiers",
        ["Tip_Paste"] = "Charger une image ou du texte depuis le presse-papiers (Ctrl+V)",
        ["Btn_History"] = "Historique",
        ["Tip_History"] = "Résultats récents",
        ["History_Empty"] = "Rien n'a encore été reconnu.",
        ["History_EmptyPreview"] = "(vide)",
        ["Tip_Settings"] = "Options",
        ["Settings_Header"] = "Options",
        ["Setting_UiLanguage"] = "Langue de l'application",
        ["Lang_SystemDefault"] = "Langue du système",
        ["Setting_RepairNumbers"] = "Corriger l et I dans les nombres",
        ["Setting_RepairNumbers_Desc"] = "Les moteurs lisent régulièrement v1.6.5 comme vl.6.5. Activé, un l ou un I ne devient un 1 que lorsqu'un séparateur et un chiffre l'encadrent, ce qui laisse html5 et IPv6 intacts. Désactivé, la lecture du moteur est conservée telle quelle.",
        ["Common_On"] = "Activé",
        ["Common_Off"] = "Désactivé",
        ["Lang_Placeholder"] = "Langue",
        ["Tip_OcrLanguage"] = "Langue de reconnaissance, issue des modules linguistiques installés dans Windows",
        ["Btn_Translate"] = "Traduire",
        ["Tip_Translate"] = "Traduire sur cet appareil — rien n'est envoyé sur le réseau",
        ["Btn_Barcode"] = "Codes",
        ["Tip_Barcode"] = "Lire les QR codes et les codes-barres de l'image",
        ["Btn_Recognize"] = "Reconnaître",
        ["Tip_Recognize"] = "Reconnaître le texte de l'image (F5)",

        ["Option_AutoAi"] = "Automatique (Windows AI)",
        ["Option_AutoMulti"] = "Automatique (multilingue · plus lent)",

        ["Status_Loaded"] = "{0} chargée.",
        ["Status_OpenFailed"] = "Impossible d'ouvrir l'image : {0}",
        ["Status_ClipboardText"] = "Texte chargé depuis le presse-papiers.",
        ["Status_ClipboardEmpty"] = "Le presse-papiers ne contient ni image ni texte.",
        ["Status_ClipboardFailed"] = "Impossible de lire le presse-papiers : {0}",
        ["Status_DropFailed"] = "Impossible d'utiliser l'élément déposé : {0}",
        ["Status_ImageCopied"] = "Image copiée dans le presse-papiers.",
        ["Status_ImageCopyFailed"] = "Impossible de copier l'image : {0}",
        ["Status_ImageSaved"] = "Image enregistrée sous {0}.",
        ["Status_ImageSaveFailed"] = "Impossible d'enregistrer l'image : {0}",
        ["Status_Recognizing"] = "Reconnaissance en cours…",
        ["Status_NoText"] = "{0} n'a trouvé aucun texte dans cette image.",
        ["Status_Done"] = "Terminé ({0}).",
        ["Status_DoneConfidence"] = "Terminé ({0}) · confiance moyenne {1} %.",
        ["Status_RecognizeFailed"] = "La reconnaissance a échoué : {0}",
        ["Status_Scanning"] = "Recherche de QR codes et de codes-barres…",
        ["Status_NoBarcode"] = "Aucun QR code ni code-barres dans cette image.",
        ["Status_BarcodeOne"] = "Un code {0} trouvé.",
        ["Status_BarcodeMany"] = "{0} codes trouvés.",
        ["Status_ScanFailed"] = "La recherche a échoué : {0}",
        ["Status_NothingToTranslate"] = "Il n'y a aucun texte à traduire.",
        ["Status_Translating"] = "Traduction en {0} sur cet appareil…",
        ["Status_Translated"] = "Traduit en {0}, sur cet appareil, sans accès au réseau.",
        ["Status_TranslateFailed"] = "La traduction a échoué : {0}",
        ["Status_NothingToCopy"] = "Il n'y a aucun texte à copier.",
        ["Status_TextCopied"] = "Texte copié dans le presse-papiers.",
        ["Status_CopyFailed"] = "Impossible de copier le texte : {0}",
        ["Status_NothingToSpeak"] = "Il n'y a aucun texte à lire.",
        ["Status_SpeakFailed"] = "Impossible de lire le texte : {0}",
        ["Status_HistoryLoaded"] = "Affichage du résultat de {0}.",
        ["Status_NeedImage"] = "Chargez d'abord une image.",
        ["Status_CaptureFailed"] = "La capture d'écran a échoué : {0}",
        ["Status_LanguagePackMissing"] = "Windows n'a aucun module linguistique OCR installé, il n'y a donc rien avec quoi reconnaître. Ajoutez la langue voulue dans Heure et langue, puis Langue et région.",
        ["Btn_OpenLanguageSettings"] = "Ouvrir les paramètres de langue",

        ["Source_Clipboard"] = "l'image du presse-papiers",
        ["Source_Dropped"] = "l'image déposée",
        ["Source_FullScreen"] = "Écran entier",
        ["Source_Region"] = "Zone de l'écran",
        ["Source_Codes"] = "{0} (codes)",

        ["FileType_Image"] = "Image {0}",

        ["Region_Hint"] = "Faites glisser pour sélectionner une zone　·　Échap ou clic droit pour annuler",

        ["Err_NoLanguagePack"] = "Windows n'a aucun module linguistique OCR installé pour cette langue. Ajoutez-en un dans Heure et langue, puis Langue et région.",
        ["Err_TextTooLong"] = "Le texte est trop long pour le modèle local. Traduisez une portion plus courte.",
        ["Err_ModelDeclined"] = "Le modèle local a refusé de traduire ce texte.",
        ["Err_TranslationFailed"] = "La traduction locale n'a produit aucun résultat.",
    };
}
