using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> It = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR di Windows · nessun language pack",
        ["Engine_OneLanguage"] = "OCR di Windows · 1 lingua",
        ["Engine_ManyLanguages"] = "OCR di Windows · {0} lingue",
        ["Engine_OnDevice"] = "{0} · sul dispositivo",

        ["Preview_Placeholder"] = "Trascina qui un'immagine, oppure usa File, Cattura o Appunti qui sotto",
        ["Btn_CopyImage"] = "Copia",
        ["Tip_CopyImage"] = "Copia l'immagine negli appunti",
        ["Btn_SaveImage"] = "Salva",
        ["Tip_SaveImage"] = "Salva l'immagine con nome…",
        ["Btn_FitToWindow"] = "Adatta",
        ["Tip_FitToWindow"] = "Adatta lo zoom alla finestra",
        ["Tip_ActualSize"] = "Dimensione reale in pixel",

        ["Voice_Placeholder"] = "Voce",
        ["Tip_Voice"] = "Voce usata per la lettura ad alta voce",
        ["Tip_Speak"] = "Leggi il testo ad alta voce",
        ["Tip_StopSpeak"] = "Interrompi la lettura",
        ["Tip_CopyText"] = "Copia il testo (Ctrl+Maiusc+C)",
        ["Btn_RemoveLineBreaks"] = "Unisci righe",
        ["Tip_RemoveLineBreaks"] = "Riunisci le interruzioni di riga in paragrafi",
        ["Btn_RemoveSpaces"] = "Senza spazi",
        ["Tip_RemoveSpaces"] = "Rimuovi tutti gli spazi, per cinese, giapponese e coreano",
        ["Result_Placeholder"] = "Il testo riconosciuto compare qui e può essere modificato.",

        ["Btn_OpenFile"] = "File",
        ["Tip_OpenFile"] = "Apri un file immagine (Ctrl+O)",
        ["Btn_Capture"] = "Cattura",
        ["Tip_Capture"] = "Seleziona un'area dello schermo e riconoscila ({0}). Premi Ctrl+Maiusc+R per l'intero schermo.",
        ["Hotkey_Unavailable"] = "nessuna scorciatoia — un'altra app le occupa entrambe",
        ["Btn_Paste"] = "Appunti",
        ["Tip_Paste"] = "Carica un'immagine o del testo dagli appunti (Ctrl+V)",
        ["Btn_History"] = "Cronologia",
        ["Tip_History"] = "Risultati recenti",
        ["History_Empty"] = "Non è ancora stato riconosciuto nulla.",
        ["History_EmptyPreview"] = "(vuoto)",
        ["Tip_Settings"] = "Opzioni",
        ["Settings_Header"] = "Opzioni",
        ["Setting_UiLanguage"] = "Lingua dell'app",
        ["Lang_SystemDefault"] = "Impostazione di sistema",
        ["Setting_RepairNumbers"] = "Correggi l e I dentro i numeri",
        ["Setting_RepairNumbers_Desc"] = "I motori di riconoscimento leggono spesso v1.6.5 come vl.6.5. Se l'opzione è attiva, una l o una I diventa 1 solo dove accanto si trovano un separatore e una cifra, così html5 e IPv6 restano intatti. Se è disattivata, la lettura del motore viene mantenuta esattamente com'è.",
        ["Common_On"] = "Attivo",
        ["Common_Off"] = "Non attivo",
        ["Lang_Placeholder"] = "Lingua",
        ["Tip_OcrLanguage"] = "Lingua di riconoscimento, tra i language pack installati in Windows",
        ["Btn_Translate"] = "Traduci",
        ["Tip_Translate"] = "Traduci su questo dispositivo — nulla viene inviato in rete",
        ["Btn_Barcode"] = "Codici",
        ["Tip_Barcode"] = "Leggi i codici QR e i codici a barre nell'immagine",
        ["Btn_Recognize"] = "Riconosci",
        ["Tip_Recognize"] = "Riconosci il testo nell'immagine (F5)",

        ["Option_AutoAi"] = "Automatico (Windows AI)",
        ["Option_AutoMulti"] = "Automatico (multilingua · più lento)",

        ["Status_Loaded"] = "{0} caricata.",
        ["Status_OpenFailed"] = "Impossibile aprire l'immagine: {0}",
        ["Status_ClipboardText"] = "Testo caricato dagli appunti.",
        ["Status_ClipboardEmpty"] = "Negli appunti non ci sono né immagini né testo.",
        ["Status_ClipboardFailed"] = "Impossibile leggere gli appunti: {0}",
        ["Status_DropFailed"] = "Impossibile usare l'elemento trascinato: {0}",
        ["Status_ImageCopied"] = "Immagine copiata negli appunti.",
        ["Status_ImageCopyFailed"] = "Impossibile copiare l'immagine: {0}",
        ["Status_ImageSaved"] = "Immagine salvata come {0}.",
        ["Status_ImageSaveFailed"] = "Impossibile salvare l'immagine: {0}",
        ["Status_Recognizing"] = "Riconoscimento in corso…",
        ["Status_NoText"] = "{0} non ha trovato testo in questa immagine.",
        ["Status_Done"] = "Fatto ({0}).",
        ["Status_DoneConfidence"] = "Fatto ({0}) · attendibilità media {1}%.",
        ["Status_RecognizeFailed"] = "Riconoscimento non riuscito: {0}",
        ["Status_Scanning"] = "Ricerca di codici QR e codici a barre…",
        ["Status_NoBarcode"] = "Nessun codice QR o a barre trovato in questa immagine.",
        ["Status_BarcodeOne"] = "Trovato un codice {0}.",
        ["Status_BarcodeMany"] = "Trovati {0} codici.",
        ["Status_ScanFailed"] = "Scansione non riuscita: {0}",
        ["Status_NothingToTranslate"] = "Non c'è testo da tradurre.",
        ["Status_Translating"] = "Traduzione in {0} su questo dispositivo…",
        ["Status_Translated"] = "Tradotto in {0}, su questo dispositivo, senza accesso alla rete.",
        ["Status_TranslateFailed"] = "Traduzione non riuscita: {0}",
        ["Status_NothingToCopy"] = "Non c'è testo da copiare.",
        ["Status_TextCopied"] = "Testo copiato negli appunti.",
        ["Status_CopyFailed"] = "Impossibile copiare il testo: {0}",
        ["Status_NothingToSpeak"] = "Non c'è testo da leggere ad alta voce.",
        ["Status_SpeakFailed"] = "Impossibile leggere il testo ad alta voce: {0}",
        ["Status_HistoryLoaded"] = "Viene mostrato il risultato di {0}.",
        ["Status_NeedImage"] = "Carica prima un'immagine.",
        ["Status_CaptureFailed"] = "Cattura dello schermo non riuscita: {0}",
        ["Status_LanguagePackMissing"] = "In Windows non è installato alcun language pack per l'OCR, quindi non c'è nulla con cui riconoscere. Aggiungi la lingua che ti serve in Data/ora e lingua, poi Lingua e area geografica.",
        ["Btn_OpenLanguageSettings"] = "Apri le impostazioni della lingua",

        ["Source_Clipboard"] = "l'immagine dagli appunti",
        ["Source_Dropped"] = "l'immagine trascinata",
        ["Source_FullScreen"] = "Schermo intero",
        ["Source_Region"] = "Area dello schermo",
        ["Source_Codes"] = "{0} (codici)",

        ["FileType_Image"] = "Immagine {0}",

        ["Region_Hint"] = "Trascina per selezionare un'area　·　Esc o clic destro per annullare",

        ["Err_NoLanguagePack"] = "In Windows non è installato alcun language pack per l'OCR di questa lingua. Aggiungine uno in Data/ora e lingua, poi Lingua e area geografica.",
        ["Err_TextTooLong"] = "Il testo è troppo lungo per il modello locale. Traducine una parte più breve.",
        ["Err_ModelDeclined"] = "Il modello locale ha rifiutato di tradurre questo testo.",
        ["Err_TranslationFailed"] = "La traduzione locale non ha prodotto alcun risultato.",
    };
}
