using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Id = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR Windows · tanpa paket bahasa",
        ["Engine_OneLanguage"] = "OCR Windows · 1 bahasa",
        ["Engine_ManyLanguages"] = "OCR Windows · {0} bahasa",
        ["Engine_OnDevice"] = "{0} · di perangkat",

        ["Preview_Placeholder"] = "Jatuhkan gambar di sini, atau gunakan Berkas, Tangkapan, atau Papan klip di bawah",
        ["Btn_CopyImage"] = "Salin",
        ["Tip_CopyImage"] = "Salin gambar ke papan klip",
        ["Btn_SaveImage"] = "Simpan",
        ["Tip_SaveImage"] = "Simpan gambar sebagai…",
        ["Btn_FitToWindow"] = "Paskan",
        ["Tip_FitToWindow"] = "Perbesar agar pas dengan jendela",
        ["Tip_ActualSize"] = "Ukuran piksel sebenarnya",

        ["Voice_Placeholder"] = "Suara",
        ["Tip_Voice"] = "Suara yang dipakai untuk membacakan",
        ["Tip_Speak"] = "Bacakan teksnya",
        ["Tip_StopSpeak"] = "Hentikan pembacaan",
        ["Tip_CopyText"] = "Salin teks (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Gabung baris",
        ["Tip_RemoveLineBreaks"] = "Gabungkan kembali pemutus baris menjadi paragraf",
        ["Btn_RemoveSpaces"] = "Tanpa spasi",
        ["Tip_RemoveSpaces"] = "Hapus semua spasi — untuk bahasa Tionghoa, Jepang, dan Korea",
        ["Result_Placeholder"] = "Teks hasil pengenalan muncul di sini dan dapat disunting.",

        ["Btn_OpenFile"] = "Berkas",
        ["Tip_OpenFile"] = "Buka berkas gambar (Ctrl+O)",
        ["Btn_Capture"] = "Tangkapan",
        ["Tip_Capture"] = "Pilih sebagian layar lalu kenali ({0}). Tekan Ctrl+Shift+R untuk seluruh layar.",
        ["Hotkey_Unavailable"] = "tanpa pintasan — keduanya sudah dipakai aplikasi lain",
        ["Btn_Paste"] = "Papan klip",
        ["Tip_Paste"] = "Muat gambar atau teks dari papan klip (Ctrl+V)",
        ["Btn_History"] = "Riwayat",
        ["Tip_History"] = "Hasil terbaru",
        ["History_Empty"] = "Belum ada yang dikenali.",
        ["History_EmptyPreview"] = "(kosong)",
        ["Tip_Settings"] = "Opsi",
        ["Settings_Header"] = "Opsi",
        ["Setting_UiLanguage"] = "Bahasa aplikasi",
        ["Lang_SystemDefault"] = "Bawaan sistem",
        ["Setting_RepairNumbers"] = "Perbaiki l dan I di dalam angka",
        ["Setting_RepairNumbers_Desc"] = "Mesin pengenal kerap membaca v1.6.5 sebagai vl.6.5. Jika opsi ini aktif, huruf l atau I hanya menjadi angka 1 di tempat yang bersebelahan dengan pemisah dan angka, sehingga html5 dan IPv6 tetap utuh. Jika nonaktif, bacaan mesin dipertahankan persis seperti aslinya.",
        ["Common_On"] = "Aktif",
        ["Common_Off"] = "Nonaktif",
        ["Lang_Placeholder"] = "Bahasa",
        ["Tip_OcrLanguage"] = "Bahasa pengenalan, dari paket bahasa yang terpasang di Windows",
        ["Btn_Translate"] = "Terjemahkan",
        ["Tip_Translate"] = "Terjemahkan di perangkat ini — tidak ada yang dikirim lewat jaringan",
        ["Btn_Barcode"] = "Kode",
        ["Tip_Barcode"] = "Baca kode QR dan kode batang dalam gambar",
        ["Btn_Recognize"] = "Kenali",
        ["Tip_Recognize"] = "Kenali teks dalam gambar (F5)",

        ["Option_AutoAi"] = "Otomatis (Windows AI)",
        ["Option_AutoMulti"] = "Otomatis (banyak bahasa · lebih lambat)",

        ["Status_Loaded"] = "{0} dimuat.",
        ["Status_OpenFailed"] = "Gambar tidak dapat dibuka: {0}",
        ["Status_ClipboardText"] = "Teks dimuat dari papan klip.",
        ["Status_ClipboardEmpty"] = "Papan klip tidak berisi gambar maupun teks.",
        ["Status_ClipboardFailed"] = "Papan klip tidak dapat dibaca: {0}",
        ["Status_DropFailed"] = "Isi yang dijatuhkan tidak dapat dipakai: {0}",
        ["Status_ImageCopied"] = "Gambar disalin ke papan klip.",
        ["Status_ImageCopyFailed"] = "Gambar tidak dapat disalin: {0}",
        ["Status_ImageSaved"] = "Gambar disimpan sebagai {0}.",
        ["Status_ImageSaveFailed"] = "Gambar tidak dapat disimpan: {0}",
        ["Status_Recognizing"] = "Mengenali…",
        ["Status_NoText"] = "{0} tidak menemukan teks pada gambar ini.",
        ["Status_Done"] = "Selesai ({0}).",
        ["Status_DoneConfidence"] = "Selesai ({0}) · keyakinan rata-rata {1}%.",
        ["Status_RecognizeFailed"] = "Pengenalan gagal: {0}",
        ["Status_Scanning"] = "Mencari kode QR dan kode batang…",
        ["Status_NoBarcode"] = "Tidak ada kode QR atau kode batang pada gambar ini.",
        ["Status_BarcodeOne"] = "Menemukan satu kode {0}.",
        ["Status_BarcodeMany"] = "Menemukan {0} kode.",
        ["Status_ScanFailed"] = "Pemindaian gagal: {0}",
        ["Status_NothingToTranslate"] = "Tidak ada teks untuk diterjemahkan.",
        ["Status_Translating"] = "Menerjemahkan ke bahasa {0} di perangkat ini…",
        ["Status_Translated"] = "Diterjemahkan ke bahasa {0}, di perangkat ini, tanpa akses jaringan.",
        ["Status_TranslateFailed"] = "Penerjemahan gagal: {0}",
        ["Status_NothingToCopy"] = "Tidak ada teks untuk disalin.",
        ["Status_TextCopied"] = "Teks disalin ke papan klip.",
        ["Status_CopyFailed"] = "Teks tidak dapat disalin: {0}",
        ["Status_NothingToSpeak"] = "Tidak ada teks untuk dibacakan.",
        ["Status_SpeakFailed"] = "Teks tidak dapat dibacakan: {0}",
        ["Status_HistoryLoaded"] = "Menampilkan hasil dari {0}.",
        ["Status_NeedImage"] = "Muat gambar terlebih dahulu.",
        ["Status_CaptureFailed"] = "Penangkapan layar gagal: {0}",
        ["Status_LanguagePackMissing"] = "Windows tidak memiliki paket bahasa OCR yang terpasang, jadi tidak ada yang bisa dipakai untuk mengenali. Tambahkan bahasa yang Anda perlukan di Waktu & bahasa, lalu Bahasa & wilayah.",
        ["Btn_OpenLanguageSettings"] = "Buka pengaturan bahasa",

        ["Source_Clipboard"] = "gambar dari papan klip",
        ["Source_Dropped"] = "gambar yang dijatuhkan",
        ["Source_FullScreen"] = "Layar penuh",
        ["Source_Region"] = "Bagian layar",
        ["Source_Codes"] = "{0} (kode)",

        ["FileType_Image"] = "Gambar {0}",

        ["Region_Hint"] = "Seret untuk memilih area　·　Esc atau klik kanan untuk membatalkan",

        ["Err_NoLanguagePack"] = "Windows tidak memiliki paket bahasa OCR untuk bahasa ini. Tambahkan satu di Waktu & bahasa, lalu Bahasa & wilayah.",
        ["Err_TextTooLong"] = "Teksnya terlalu panjang untuk model di perangkat. Terjemahkan bagian yang lebih pendek.",
        ["Err_ModelDeclined"] = "Model di perangkat menolak menerjemahkan teks ini.",
        ["Err_TranslationFailed"] = "Penerjemahan di perangkat tidak menghasilkan apa pun.",
    };
}
