using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Da = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · ingen sprogpakke",
        ["Engine_OneLanguage"] = "Windows OCR · 1 sprog",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} sprog",
        ["Engine_OnDevice"] = "{0} · på enheden",

        ["Preview_Placeholder"] = "Slip et billede her, eller brug Fil, Skærmklip eller Udklipsholder nedenfor",
        ["Btn_CopyImage"] = "Kopiér",
        ["Tip_CopyImage"] = "Kopiér billedet til udklipsholderen",
        ["Btn_SaveImage"] = "Gem",
        ["Tip_SaveImage"] = "Gem billedet som…",
        ["Btn_FitToWindow"] = "Tilpas",
        ["Tip_FitToWindow"] = "Zoom, så billedet passer i vinduet",
        ["Tip_ActualSize"] = "Faktisk pixelstørrelse",

        ["Voice_Placeholder"] = "Stemme",
        ["Tip_Voice"] = "Stemme, der bruges til oplæsning",
        ["Tip_Speak"] = "Læs teksten højt",
        ["Tip_StopSpeak"] = "Stop oplæsningen",
        ["Tip_CopyText"] = "Kopiér teksten (Ctrl+Skift+C)",
        ["Btn_RemoveLineBreaks"] = "Saml linjer",
        ["Tip_RemoveLineBreaks"] = "Saml hårde linjeskift til afsnit igen",
        ["Btn_RemoveSpaces"] = "Ingen mellemrum",
        ["Tip_RemoveSpaces"] = "Fjern alle mellemrum — til kinesisk, japansk og koreansk",
        ["Result_Placeholder"] = "Den genkendte tekst vises her og kan redigeres.",

        ["Btn_OpenFile"] = "Fil",
        ["Tip_OpenFile"] = "Åbn en billedfil (Ctrl+O)",
        ["Btn_Capture"] = "Skærmklip",
        ["Tip_Capture"] = "Markér et skærmområde, og genkend det ({0}). Tryk på Ctrl+Skift+R for hele skærmen.",
        ["Hotkey_Unavailable"] = "ingen genvej — en anden app har taget dem begge",
        ["Btn_Paste"] = "Udklipsholder",
        ["Tip_Paste"] = "Hent et billede eller tekst fra udklipsholderen (Ctrl+V)",
        ["Btn_History"] = "Historik",
        ["Tip_History"] = "Seneste resultater",
        ["History_Empty"] = "Der er ikke genkendt noget endnu.",
        ["History_EmptyPreview"] = "(tom)",
        ["Tip_Settings"] = "Indstillinger",
        ["Settings_Header"] = "Indstillinger",
        ["Setting_UiLanguage"] = "Appens sprog",
        ["Lang_SystemDefault"] = "Systemets standard",
        ["Setting_RepairNumbers"] = "Ret l og I inde i tal",
        ["Setting_RepairNumbers_Desc"] = "Genkendere læser jævnligt v1.6.5 som vl.6.5. Når dette er slået til, bliver et l eller I kun til et 1-tal, hvor der står et skilletegn og et ciffer ved siden af, så html5 og IPv6 får lov at være. Når det er slået fra, bevares motorens læsning præcis, som den kom.",
        ["Common_On"] = "Til",
        ["Common_Off"] = "Fra",
        ["Lang_Placeholder"] = "Sprog",
        ["Tip_OcrLanguage"] = "Genkendelsessprog blandt de sprogpakker, Windows har installeret",
        ["Btn_Translate"] = "Oversæt",
        ["Tip_Translate"] = "Oversæt på denne enhed — der sendes intet over netværket",
        ["Btn_Barcode"] = "Koder",
        ["Tip_Barcode"] = "Læs QR-koder og stregkoder i billedet",
        ["Btn_Recognize"] = "Genkend",
        ["Tip_Recognize"] = "Genkend teksten i billedet (F5)",

        ["Option_AutoAi"] = "Automatisk (Windows AI)",
        ["Option_AutoMulti"] = "Automatisk (flere sprog · langsommere)",

        ["Status_Loaded"] = "{0} indlæst.",
        ["Status_OpenFailed"] = "Billedet kunne ikke åbnes: {0}",
        ["Status_ClipboardText"] = "Tekst hentet fra udklipsholderen.",
        ["Status_ClipboardEmpty"] = "Udklipsholderen indeholder hverken billede eller tekst.",
        ["Status_ClipboardFailed"] = "Udklipsholderen kunne ikke læses: {0}",
        ["Status_DropFailed"] = "Det, der blev sluppet, kunne ikke bruges: {0}",
        ["Status_ImageCopied"] = "Billedet er kopieret til udklipsholderen.",
        ["Status_ImageCopyFailed"] = "Billedet kunne ikke kopieres: {0}",
        ["Status_ImageSaved"] = "Billedet er gemt som {0}.",
        ["Status_ImageSaveFailed"] = "Billedet kunne ikke gemmes: {0}",
        ["Status_Recognizing"] = "Genkender…",
        ["Status_NoText"] = "{0} fandt ingen tekst i dette billede.",
        ["Status_Done"] = "Færdig ({0}).",
        ["Status_DoneConfidence"] = "Færdig ({0}) · gennemsnitlig sikkerhed {1} %.",
        ["Status_RecognizeFailed"] = "Genkendelsen mislykkedes: {0}",
        ["Status_Scanning"] = "Søger efter QR-koder og stregkoder…",
        ["Status_NoBarcode"] = "Der blev ikke fundet nogen QR-kode eller stregkode i dette billede.",
        ["Status_BarcodeOne"] = "Fandt én {0}-kode.",
        ["Status_BarcodeMany"] = "Fandt {0} koder.",
        ["Status_ScanFailed"] = "Søgningen mislykkedes: {0}",
        ["Status_NothingToTranslate"] = "Der er ingen tekst at oversætte.",
        ["Status_Translating"] = "Oversætter til {0} på denne enhed…",
        ["Status_Translated"] = "Oversat til {0}, på denne enhed, uden netværksadgang.",
        ["Status_TranslateFailed"] = "Oversættelsen mislykkedes: {0}",
        ["Status_NothingToCopy"] = "Der er ingen tekst at kopiere.",
        ["Status_TextCopied"] = "Teksten er kopieret til udklipsholderen.",
        ["Status_CopyFailed"] = "Teksten kunne ikke kopieres: {0}",
        ["Status_NothingToSpeak"] = "Der er ingen tekst at læse højt.",
        ["Status_SpeakFailed"] = "Teksten kunne ikke læses højt: {0}",
        ["Status_HistoryLoaded"] = "Viser resultatet fra {0}.",
        ["Status_NeedImage"] = "Indlæs et billede først.",
        ["Status_CaptureFailed"] = "Skærmbilledet mislykkedes: {0}",
        ["Status_LanguagePackMissing"] = "Windows har ingen OCR-sprogpakke installeret, så der er intet at genkende med. Tilføj det sprog, du har brug for, under Klokkeslæt og sprog og derefter Sprog og område.",
        ["Btn_OpenLanguageSettings"] = "Åbn sprogindstillingerne",

        ["Source_Clipboard"] = "billedet fra udklipsholderen",
        ["Source_Dropped"] = "det slupne billede",
        ["Source_FullScreen"] = "Hele skærmen",
        ["Source_Region"] = "Skærmområde",
        ["Source_Codes"] = "{0} (koder)",

        ["FileType_Image"] = "{0}-billede",

        ["Region_Hint"] = "Træk for at markere et område　·　Esc eller højreklik annullerer",

        ["Err_NoLanguagePack"] = "Windows har ingen OCR-sprogpakke installeret til dette sprog. Tilføj en under Klokkeslæt og sprog og derefter Sprog og område.",
        ["Err_TextTooLong"] = "Teksten er for lang til modellen på enheden. Oversæt et mindre stykke.",
        ["Err_ModelDeclined"] = "Modellen på enheden afviste at oversætte denne tekst.",
        ["Err_TranslationFailed"] = "Oversættelsen på enheden gav intet resultat.",
    };
}
