using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Vi = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "OCR của Windows · chưa có gói ngôn ngữ",
        ["Engine_OneLanguage"] = "OCR của Windows · 1 ngôn ngữ",
        ["Engine_ManyLanguages"] = "OCR của Windows · {0} ngôn ngữ",
        ["Engine_OnDevice"] = "{0} · trên thiết bị",

        ["Preview_Placeholder"] = "Thả một ảnh vào đây, hoặc dùng Tệp, Chụp màn hình hay Bảng nhớ tạm ở bên dưới",
        ["Btn_CopyImage"] = "Sao chép",
        ["Tip_CopyImage"] = "Sao chép ảnh vào bảng nhớ tạm",
        ["Btn_SaveImage"] = "Lưu",
        ["Tip_SaveImage"] = "Lưu ảnh thành…",
        ["Btn_FitToWindow"] = "Vừa khung",
        ["Tip_FitToWindow"] = "Thu phóng cho vừa cửa sổ",
        ["Tip_ActualSize"] = "Kích thước điểm ảnh thật",

        ["Voice_Placeholder"] = "Giọng đọc",
        ["Tip_Voice"] = "Giọng dùng để đọc thành tiếng",
        ["Tip_Speak"] = "Đọc to văn bản",
        ["Tip_StopSpeak"] = "Dừng đọc",
        ["Tip_CopyText"] = "Sao chép văn bản (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Nối dòng",
        ["Tip_RemoveLineBreaks"] = "Nối các dấu xuống dòng cứng trở lại thành đoạn văn",
        ["Btn_RemoveSpaces"] = "Bỏ khoảng trắng",
        ["Tip_RemoveSpaces"] = "Xóa toàn bộ khoảng trắng — dành cho tiếng Trung, Nhật và Hàn",
        ["Result_Placeholder"] = "Văn bản nhận dạng được sẽ hiện ở đây và có thể chỉnh sửa.",

        ["Btn_OpenFile"] = "Tệp",
        ["Tip_OpenFile"] = "Mở một tệp ảnh (Ctrl+O)",
        ["Btn_Capture"] = "Chụp màn hình",
        ["Tip_Capture"] = "Chọn một vùng màn hình rồi nhận dạng ({0}). Nhấn Ctrl+Shift+R để lấy toàn màn hình.",
        ["Hotkey_Unavailable"] = "không có phím tắt — một ứng dụng khác đã chiếm cả hai",
        ["Btn_Paste"] = "Bảng nhớ tạm",
        ["Tip_Paste"] = "Nạp ảnh hoặc văn bản từ bảng nhớ tạm (Ctrl+V)",
        ["Btn_History"] = "Lịch sử",
        ["Tip_History"] = "Kết quả gần đây",
        ["History_Empty"] = "Chưa nhận dạng gì cả.",
        ["History_EmptyPreview"] = "(trống)",
        ["Tip_Settings"] = "Tùy chọn",
        ["Settings_Header"] = "Tùy chọn",
        ["Setting_UiLanguage"] = "Ngôn ngữ ứng dụng",
        ["Lang_SystemDefault"] = "Mặc định của hệ thống",
        ["Setting_RepairNumbers"] = "Sửa l và I nằm trong số",
        ["Setting_RepairNumbers_Desc"] = "Các bộ nhận dạng thường đọc v1.6.5 thành vl.6.5. Khi bật tùy chọn này, chữ l hoặc I chỉ đổi thành số 1 ở nơi có dấu phân cách và chữ số nằm kề bên, nên html5 và IPv6 vẫn nguyên vẹn. Khi tắt, kết quả đọc của bộ máy được giữ đúng như nó vốn có.",
        ["Common_On"] = "Bật",
        ["Common_Off"] = "Tắt",
        ["Lang_Placeholder"] = "Ngôn ngữ",
        ["Tip_OcrLanguage"] = "Ngôn ngữ nhận dạng, lấy từ các gói ngôn ngữ đã cài trong Windows",
        ["Btn_Translate"] = "Dịch",
        ["Tip_Translate"] = "Dịch ngay trên thiết bị này — không có gì được gửi qua mạng",
        ["Btn_Barcode"] = "Mã",
        ["Tip_Barcode"] = "Đọc mã QR và mã vạch trong ảnh",
        ["Btn_Recognize"] = "Nhận dạng",
        ["Tip_Recognize"] = "Nhận dạng văn bản trong ảnh (F5)",

        ["Option_AutoAi"] = "Tự động (Windows AI)",
        ["Option_AutoMulti"] = "Tự động (nhiều ngôn ngữ · chậm hơn)",

        ["Status_Loaded"] = "Đã nạp {0}.",
        ["Status_OpenFailed"] = "Không mở được ảnh: {0}",
        ["Status_ClipboardText"] = "Đã nạp văn bản từ bảng nhớ tạm.",
        ["Status_ClipboardEmpty"] = "Bảng nhớ tạm không chứa ảnh lẫn văn bản.",
        ["Status_ClipboardFailed"] = "Không đọc được bảng nhớ tạm: {0}",
        ["Status_DropFailed"] = "Không dùng được nội dung vừa thả: {0}",
        ["Status_ImageCopied"] = "Đã sao chép ảnh vào bảng nhớ tạm.",
        ["Status_ImageCopyFailed"] = "Không sao chép được ảnh: {0}",
        ["Status_ImageSaved"] = "Đã lưu ảnh thành {0}.",
        ["Status_ImageSaveFailed"] = "Không lưu được ảnh: {0}",
        ["Status_Recognizing"] = "Đang nhận dạng…",
        ["Status_NoText"] = "{0} không tìm thấy văn bản nào trong ảnh này.",
        ["Status_Done"] = "Xong ({0}).",
        ["Status_DoneConfidence"] = "Xong ({0}) · độ tin cậy trung bình {1}%.",
        ["Status_RecognizeFailed"] = "Nhận dạng thất bại: {0}",
        ["Status_Scanning"] = "Đang tìm mã QR và mã vạch…",
        ["Status_NoBarcode"] = "Không tìm thấy mã QR hay mã vạch nào trong ảnh này.",
        ["Status_BarcodeOne"] = "Tìm thấy một mã {0}.",
        ["Status_BarcodeMany"] = "Tìm thấy {0} mã.",
        ["Status_ScanFailed"] = "Quét thất bại: {0}",
        ["Status_NothingToTranslate"] = "Không có văn bản để dịch.",
        ["Status_Translating"] = "Đang dịch sang {0} trên thiết bị này…",
        ["Status_Translated"] = "Đã dịch sang {0}, ngay trên thiết bị này, không cần mạng.",
        ["Status_TranslateFailed"] = "Dịch thất bại: {0}",
        ["Status_NothingToCopy"] = "Không có văn bản để sao chép.",
        ["Status_TextCopied"] = "Đã sao chép văn bản vào bảng nhớ tạm.",
        ["Status_CopyFailed"] = "Không sao chép được văn bản: {0}",
        ["Status_NothingToSpeak"] = "Không có văn bản để đọc.",
        ["Status_SpeakFailed"] = "Không đọc được văn bản: {0}",
        ["Status_HistoryLoaded"] = "Đang hiển thị kết quả lúc {0}.",
        ["Status_NeedImage"] = "Hãy nạp một ảnh trước đã.",
        ["Status_CaptureFailed"] = "Chụp màn hình thất bại: {0}",
        ["Status_LanguagePackMissing"] = "Windows chưa cài gói ngôn ngữ OCR nào nên không có gì để nhận dạng. Hãy thêm ngôn ngữ bạn cần trong Thời gian và ngôn ngữ, rồi Ngôn ngữ và khu vực.",
        ["Btn_OpenLanguageSettings"] = "Mở cài đặt ngôn ngữ",

        ["Source_Clipboard"] = "ảnh từ bảng nhớ tạm",
        ["Source_Dropped"] = "ảnh vừa thả vào",
        ["Source_FullScreen"] = "Toàn màn hình",
        ["Source_Region"] = "Vùng màn hình",
        ["Source_Codes"] = "{0} (mã)",

        ["FileType_Image"] = "Ảnh {0}",

        ["Region_Hint"] = "Kéo để chọn một vùng　·　Esc hoặc bấm chuột phải để hủy",

        ["Err_NoLanguagePack"] = "Windows chưa cài gói ngôn ngữ OCR cho ngôn ngữ này. Hãy thêm một gói trong Thời gian và ngôn ngữ, rồi Ngôn ngữ và khu vực.",
        ["Err_TextTooLong"] = "Văn bản quá dài đối với mô hình trên thiết bị. Hãy dịch một phần ngắn hơn.",
        ["Err_ModelDeclined"] = "Mô hình trên thiết bị đã từ chối dịch văn bản này.",
        ["Err_TranslationFailed"] = "Bản dịch trên thiết bị không trả về kết quả nào.",
    };
}
