using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Hu = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · nincs nyelvi csomag",
        ["Engine_OneLanguage"] = "Windows OCR · 1 nyelv",
        ["Engine_ManyLanguages"] = "Windows OCR · {0} nyelv",
        ["Engine_OnDevice"] = "{0} · az eszközön",

        ["Preview_Placeholder"] = "Húzzon ide egy képet, vagy használja lent a Fájl, a Felvétel vagy a Vágólap gombot",
        ["Btn_CopyImage"] = "Másolás",
        ["Tip_CopyImage"] = "A kép másolása a vágólapra",
        ["Btn_SaveImage"] = "Mentés",
        ["Tip_SaveImage"] = "Kép mentése másként…",
        ["Btn_FitToWindow"] = "Illesztés",
        ["Tip_FitToWindow"] = "Nagyítás az ablakhoz igazítva",
        ["Tip_ActualSize"] = "Valódi képpontméret",

        ["Voice_Placeholder"] = "Hang",
        ["Tip_Voice"] = "A felolvasáshoz használt hang",
        ["Tip_Speak"] = "A szöveg felolvasása",
        ["Tip_StopSpeak"] = "A felolvasás leállítása",
        ["Tip_CopyText"] = "A szöveg másolása (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Sorok egyben",
        ["Tip_RemoveLineBreaks"] = "A kemény sortörések visszaolvasztása bekezdésekké",
        ["Btn_RemoveSpaces"] = "Szóköz nélkül",
        ["Tip_RemoveSpaces"] = "Az összes szóköz eltávolítása — kínai, japán és koreai szöveghez",
        ["Result_Placeholder"] = "A felismert szöveg itt jelenik meg, és szerkeszthető.",

        ["Btn_OpenFile"] = "Fájl",
        ["Tip_OpenFile"] = "Képfájl megnyitása (Ctrl+O)",
        ["Btn_Capture"] = "Felvétel",
        ["Tip_Capture"] = "Képernyőterület kijelölése és felismerése ({0}). A teljes képernyőhöz nyomja meg a Ctrl+Shift+R billentyűt.",
        ["Hotkey_Unavailable"] = "nincs gyorsbillentyű — mindkettőt lefoglalta egy másik alkalmazás",
        ["Btn_Paste"] = "Vágólap",
        ["Tip_Paste"] = "Kép vagy szöveg betöltése a vágólapról (Ctrl+V)",
        ["Btn_History"] = "Előzmények",
        ["Tip_History"] = "Legutóbbi eredmények",
        ["History_Empty"] = "Még nincs felismert eredmény.",
        ["History_EmptyPreview"] = "(üres)",
        ["Tip_Settings"] = "Beállítások",
        ["Settings_Header"] = "Beállítások",
        ["Setting_UiLanguage"] = "Az alkalmazás nyelve",
        ["Lang_SystemDefault"] = "Rendszer szerint",
        ["Setting_RepairNumbers"] = "Az l és I javítása számokon belül",
        ["Setting_RepairNumbers_Desc"] = "A felismerők rendszeresen vl.6.5 alakban olvassák a v1.6.5 karakterláncot. Bekapcsolt állapotban egy l vagy I csak ott lesz 1-es, ahol mellette elválasztó és számjegy áll, így a html5 és az IPv6 érintetlen marad. Kikapcsolva a motor olvasata pontosan úgy marad, ahogy érkezett.",
        ["Common_On"] = "Be",
        ["Common_Off"] = "Ki",
        ["Lang_Placeholder"] = "Nyelv",
        ["Tip_OcrLanguage"] = "A felismerés nyelve a Windowsban telepített nyelvi csomagok közül",
        ["Btn_Translate"] = "Fordítás",
        ["Tip_Translate"] = "Fordítás ezen az eszközön — semmi sem megy ki a hálózatra",
        ["Btn_Barcode"] = "Kódok",
        ["Tip_Barcode"] = "QR-kódok és vonalkódok beolvasása a képről",
        ["Btn_Recognize"] = "Felismerés",
        ["Tip_Recognize"] = "A képen lévő szöveg felismerése (F5)",

        ["Option_AutoAi"] = "Automatikus (Windows AI)",
        ["Option_AutoMulti"] = "Automatikus (több nyelv · lassabb)",

        ["Status_Loaded"] = "{0} betöltve.",
        ["Status_OpenFailed"] = "A kép nem nyitható meg: {0}",
        ["Status_ClipboardText"] = "Szöveg betöltve a vágólapról.",
        ["Status_ClipboardEmpty"] = "A vágólapon nincs sem kép, sem szöveg.",
        ["Status_ClipboardFailed"] = "A vágólap nem olvasható: {0}",
        ["Status_DropFailed"] = "Az idehúzott elem nem használható: {0}",
        ["Status_ImageCopied"] = "A kép a vágólapra másolva.",
        ["Status_ImageCopyFailed"] = "A kép nem másolható: {0}",
        ["Status_ImageSaved"] = "A kép mentve {0} néven.",
        ["Status_ImageSaveFailed"] = "A kép nem menthető: {0}",
        ["Status_Recognizing"] = "Felismerés folyamatban…",
        ["Status_NoText"] = "A(z) {0} nem talált szöveget ezen a képen.",
        ["Status_Done"] = "Kész ({0}).",
        ["Status_DoneConfidence"] = "Kész ({0}) · átlagos megbízhatóság {1}%.",
        ["Status_RecognizeFailed"] = "A felismerés nem sikerült: {0}",
        ["Status_Scanning"] = "QR-kódok és vonalkódok keresése…",
        ["Status_NoBarcode"] = "Ezen a képen nincs QR-kód és vonalkód sem.",
        ["Status_BarcodeOne"] = "Egy {0} kód található.",
        ["Status_BarcodeMany"] = "{0} kód található.",
        ["Status_ScanFailed"] = "A keresés nem sikerült: {0}",
        ["Status_NothingToTranslate"] = "Nincs lefordítandó szöveg.",
        ["Status_Translating"] = "Fordítás {0} nyelvre ezen az eszközön…",
        ["Status_Translated"] = "Lefordítva {0} nyelvre — ezen az eszközön, hálózati hozzáférés nélkül.",
        ["Status_TranslateFailed"] = "A fordítás nem sikerült: {0}",
        ["Status_NothingToCopy"] = "Nincs másolandó szöveg.",
        ["Status_TextCopied"] = "A szöveg a vágólapra másolva.",
        ["Status_CopyFailed"] = "A szöveg nem másolható: {0}",
        ["Status_NothingToSpeak"] = "Nincs felolvasandó szöveg.",
        ["Status_SpeakFailed"] = "A szöveg nem olvasható fel: {0}",
        ["Status_HistoryLoaded"] = "A(z) {0} időpontú eredmény látható.",
        ["Status_NeedImage"] = "Először töltsön be egy képet.",
        ["Status_CaptureFailed"] = "A képernyőfelvétel nem sikerült: {0}",
        ["Status_LanguagePackMissing"] = "A Windowsban nincs telepítve OCR nyelvi csomag, így nincs mivel felismerni. Vegye fel a szükséges nyelvet az Idő és nyelv, majd a Nyelv és régió alatt.",
        ["Btn_OpenLanguageSettings"] = "Nyelvi beállítások megnyitása",

        ["Source_Clipboard"] = "a vágólapon lévő kép",
        ["Source_Dropped"] = "az idehúzott kép",
        ["Source_FullScreen"] = "Teljes képernyő",
        ["Source_Region"] = "Képernyőterület",
        ["Source_Codes"] = "{0} (kódok)",

        ["FileType_Image"] = "{0} kép",

        ["Region_Hint"] = "Húzással jelöljön ki egy területet　·　Esc vagy jobb gomb: mégse",

        ["Err_NoLanguagePack"] = "A Windowsban nincs telepítve OCR nyelvi csomag ehhez a nyelvhez. Vegyen fel egyet az Idő és nyelv, majd a Nyelv és régió alatt.",
        ["Err_TextTooLong"] = "A szöveg túl hosszú az eszközön futó modellnek. Fordítson le egy rövidebb részt.",
        ["Err_ModelDeclined"] = "Az eszközön futó modell elutasította ennek a szövegnek a fordítását.",
        ["Err_TranslationFailed"] = "Az eszközön futó fordítás nem adott eredményt.",
    };
}
