using System;
using System.Collections.Generic;

namespace InstaOCR.Services;

internal static partial class Strings
{
    internal static readonly Dictionary<string, string> Cs = new(StringComparer.Ordinal)
    {
        ["Engine_NoLanguagePack"] = "Windows OCR · žádný jazykový balíček",
        ["Engine_OneLanguage"] = "Windows OCR · 1 jazyk",
        ["Engine_ManyLanguages"] = "Windows OCR · jazyků: {0}",
        ["Engine_OnDevice"] = "{0} · v zařízení",

        ["Preview_Placeholder"] = "Přetáhněte sem obrázek nebo použijte tlačítka Soubor, Snímek či Schránka níže",
        ["Btn_CopyImage"] = "Kopírovat",
        ["Tip_CopyImage"] = "Zkopírovat obrázek do schránky",
        ["Btn_SaveImage"] = "Uložit",
        ["Tip_SaveImage"] = "Uložit obrázek jako…",
        ["Btn_FitToWindow"] = "Přizpůsobit",
        ["Tip_FitToWindow"] = "Přiblížit na velikost okna",
        ["Tip_ActualSize"] = "Skutečná velikost v pixelech",

        ["Voice_Placeholder"] = "Hlas",
        ["Tip_Voice"] = "Hlas použitý pro předčítání",
        ["Tip_Speak"] = "Přečíst text nahlas",
        ["Tip_StopSpeak"] = "Zastavit čtení",
        ["Tip_CopyText"] = "Zkopírovat text (Ctrl+Shift+C)",
        ["Btn_RemoveLineBreaks"] = "Spojit řádky",
        ["Tip_RemoveLineBreaks"] = "Spojit pevné konce řádků zpět do odstavců",
        ["Btn_RemoveSpaces"] = "Bez mezer",
        ["Tip_RemoveSpaces"] = "Odstranit všechny mezery — pro čínštinu, japonštinu a korejštinu",
        ["Result_Placeholder"] = "Rozpoznaný text se objeví zde a lze jej upravit.",

        ["Btn_OpenFile"] = "Soubor",
        ["Tip_OpenFile"] = "Otevřít soubor s obrázkem (Ctrl+O)",
        ["Btn_Capture"] = "Snímek",
        ["Tip_Capture"] = "Vybrat oblast obrazovky a rozpoznat ji ({0}). Pro celou obrazovku stiskněte Ctrl+Shift+R.",
        ["Hotkey_Unavailable"] = "žádná zkratka — obě zabrala jiná aplikace",
        ["Btn_Paste"] = "Schránka",
        ["Tip_Paste"] = "Načíst obrázek nebo text ze schránky (Ctrl+V)",
        ["Btn_History"] = "Historie",
        ["Tip_History"] = "Nedávné výsledky",
        ["History_Empty"] = "Zatím nebylo nic rozpoznáno.",
        ["History_EmptyPreview"] = "(prázdné)",
        ["Tip_Settings"] = "Možnosti",
        ["Settings_Header"] = "Možnosti",
        ["Setting_UiLanguage"] = "Jazyk aplikace",
        ["Lang_SystemDefault"] = "Podle systému",
        ["Setting_RepairNumbers"] = "Opravovat l a I uvnitř čísel",
        ["Setting_RepairNumbers_Desc"] = "Rozpoznávací moduly běžně čtou v1.6.5 jako vl.6.5. Je-li volba zapnutá, změní se l nebo I na 1 jen tam, kde vedle stojí oddělovač a číslice, takže html5 a IPv6 zůstanou nedotčené. Je-li vypnutá, zůstane čtení modulu přesně takové, jaké přišlo.",
        ["Common_On"] = "Zapnuto",
        ["Common_Off"] = "Vypnuto",
        ["Lang_Placeholder"] = "Jazyk",
        ["Tip_OcrLanguage"] = "Jazyk rozpoznávání — z jazykových balíčků nainstalovaných ve Windows",
        ["Btn_Translate"] = "Přeložit",
        ["Tip_Translate"] = "Přeložit v tomto zařízení — po síti se nic neodesílá",
        ["Btn_Barcode"] = "Kódy",
        ["Tip_Barcode"] = "Přečíst QR kódy a čárové kódy v obrázku",
        ["Btn_Recognize"] = "Rozpoznat",
        ["Tip_Recognize"] = "Rozpoznat text v obrázku (F5)",

        ["Option_AutoAi"] = "Automaticky (Windows AI)",
        ["Option_AutoMulti"] = "Automaticky (více jazyků · pomalejší)",

        ["Status_Loaded"] = "Načteno: {0}.",
        ["Status_OpenFailed"] = "Obrázek se nepodařilo otevřít: {0}",
        ["Status_ClipboardText"] = "Text načten ze schránky.",
        ["Status_ClipboardEmpty"] = "Ve schránce není ani obrázek, ani text.",
        ["Status_ClipboardFailed"] = "Schránku se nepodařilo přečíst: {0}",
        ["Status_DropFailed"] = "Přetažený obsah nelze použít: {0}",
        ["Status_ImageCopied"] = "Obrázek zkopírován do schránky.",
        ["Status_ImageCopyFailed"] = "Obrázek se nepodařilo zkopírovat: {0}",
        ["Status_ImageSaved"] = "Obrázek uložen jako {0}.",
        ["Status_ImageSaveFailed"] = "Obrázek se nepodařilo uložit: {0}",
        ["Status_Recognizing"] = "Probíhá rozpoznávání…",
        ["Status_NoText"] = "{0} v tomto obrázku nenašel žádný text.",
        ["Status_Done"] = "Hotovo ({0}).",
        ["Status_DoneConfidence"] = "Hotovo ({0}) · průměrná spolehlivost {1} %.",
        ["Status_RecognizeFailed"] = "Rozpoznávání selhalo: {0}",
        ["Status_Scanning"] = "Hledají se QR kódy a čárové kódy…",
        ["Status_NoBarcode"] = "V tomto obrázku není žádný QR kód ani čárový kód.",
        ["Status_BarcodeOne"] = "Nalezen jeden kód {0}.",
        ["Status_BarcodeMany"] = "Nalezeno kódů: {0}.",
        ["Status_ScanFailed"] = "Hledání selhalo: {0}",
        ["Status_NothingToTranslate"] = "Není co překládat.",
        ["Status_Translating"] = "Překládá se do jazyka {0} v tomto zařízení…",
        ["Status_Translated"] = "Přeloženo do jazyka {0} — v tomto zařízení, bez přístupu k síti.",
        ["Status_TranslateFailed"] = "Překlad selhal: {0}",
        ["Status_NothingToCopy"] = "Není co kopírovat.",
        ["Status_TextCopied"] = "Text zkopírován do schránky.",
        ["Status_CopyFailed"] = "Text se nepodařilo zkopírovat: {0}",
        ["Status_NothingToSpeak"] = "Není co číst nahlas.",
        ["Status_SpeakFailed"] = "Text se nepodařilo přečíst nahlas: {0}",
        ["Status_HistoryLoaded"] = "Zobrazuje se výsledek z {0}.",
        ["Status_NeedImage"] = "Nejprve načtěte obrázek.",
        ["Status_CaptureFailed"] = "Snímek obrazovky selhal: {0}",
        ["Status_LanguagePackMissing"] = "Ve Windows není nainstalovaný žádný jazykový balíček pro OCR, takže není čím rozpoznávat. Přidejte potřebný jazyk v části Čas a jazyk, pak Jazyk a oblast.",
        ["Btn_OpenLanguageSettings"] = "Otevřít nastavení jazyka",

        ["Source_Clipboard"] = "obrázek ze schránky",
        ["Source_Dropped"] = "přetažený obrázek",
        ["Source_FullScreen"] = "Celá obrazovka",
        ["Source_Region"] = "Oblast obrazovky",
        ["Source_Codes"] = "{0} (kódy)",

        ["FileType_Image"] = "Obrázek {0}",

        ["Region_Hint"] = "Tažením vyberte oblast　·　Esc nebo pravé tlačítko zruší",

        ["Err_NoLanguagePack"] = "Ve Windows není pro tento jazyk nainstalovaný žádný jazykový balíček pro OCR. Přidejte jej v části Čas a jazyk, pak Jazyk a oblast.",
        ["Err_TextTooLong"] = "Text je pro model v zařízení příliš dlouhý. Přeložte menší část.",
        ["Err_ModelDeclined"] = "Model v zařízení tento text odmítl přeložit.",
        ["Err_TranslationFailed"] = "Překlad v zařízení nevrátil žádný výsledek.",
    };
}
